### ISSUE TITLE
searcher get_config() may get stuck in infinite while loop

### ISSUE THREAD

**Issue by jwmueller** [awslabs/autogluon#10]
Listing issue here for the record since I removed these comments from my **skopt_searcher** code to clean it up.

Issue: 
get_config() may become stuck in infinite while loop. There is no termination condition to handle the case where all possible configs have already been tried 
(should be inherited from BaseSearcher or Scheduler should automatically terminate).

In general, perhaps the BaseSearcher should by default revert to grid search whenever the search-space is sufficiently small.

**Comment by zhanghang1989** [comment]
This should be fixed in @mseeger 's PR
