### ISSUE TITLE
Make Dependencies More Flexible

### ISSUE THREAD

**Issue by zhanghang1989** [awslabs/autogluon#100]
Let's try to relax some of the versions of the dependencies. Got some feedback from bug bash:

1. Conda:
    1. create a new env: conda create -n autogluon In default it install python 3.8, will got a installation error ERROR: Could not find a version that satisfies the requirement pyarrow==0.15.0 (from autogluon==0.0.1) (from versions: 0.9.0, 0.10.0, 0.11.0, 0.11.1, 0.12.0, 0.12.1, 0.13.0, 0.14.0, 0.15.1)
    2. The solution for above is `conda create -n autogluon python==3.7`
    3. ERROR: No matching distribution found for pyarrow==0.15.0 (from autogluon==0.0.1)

**Comment by Innixma** [comment]
Resolved in the current version
