### ISSUE TITLE
Old doc pages still exist.

### ISSUE THREAD

**Issue by Razieh-Rosie** [awslabs/autogluon#1001]
Hi,
I've installed autogluon and now I a trying to use image classification by following the steps provided in the following link:
https://auto.gluon.ai/tutorials/image_classification/kaggle.html

I'm getting this error about cannot import name 'ImageClassification' as following screenshot shows:
 
<img width="1006" alt="Screen Shot 2021-03-05 at 9 19 30 AM" src="https://user-images.githubusercontent.com/52944358/110144432-9185db80-7d95-11eb-97a6-cff37cb3c2e8.png">

I'd appreciate any help.
Thanks

**Comment by Innixma** [comment]
This is an old doc page that isn't generally reachable without the exact link.

Please refer to our stable documentation instead: https://auto.gluon.ai/stable/index.html

And for the exact page you are looking for: https://auto.gluon.ai/stable/tutorials/image_prediction/kaggle.html

@zhreshold Can we find a way to delete the old pages that don't conform to our new doc format? Is it just a matter of going into the s3 bucket and manually deleting them?

**Comment by Razieh-Rosie** [comment]
> This is an old doc page that isn't generally reachable without the exact link.
> 
> Please refer to our stable documentation instead: https://auto.gluon.ai/stable/index.html
> 
> And for the exact page you are looking for: https://auto.gluon.ai/stable/tutorials/image_prediction/kaggle.html
> 
> @zhreshold Can we find a way to delete the old pages that don't conform to our new doc format? Is it just a matter of going into the s3 bucket and manually deleting them?

instructions from the new link are working with no error. Many thanks.

**Comment by Innixma** [comment]
I deleted the old docs so they should no longer be accessible. Thanks again for bringing this up!
