### ISSUE TITLE
Issue installing and using lightgbm

### ISSUE THREAD

**Issue by zhanghang1989** [awslabs/autogluon#101]
Reported in bug bash. Once installed libomp, still get an error:

/Users/mli/miniconda3/lib/python3.7/site-packages/lightgbm/__init__.py:48: UserWarning: Starting from version 2.2.1, the library file in distribution wheels for macOS is built by the Apple Clang (Xcode_8.3.3) compiler.This means that in case of installing LightGBM from PyPI via the pip install lightgbm command, you don't need to install the gcc compiler anymore.Instead of that, you need to install the OpenMP library, which is required for running LightGBM on the system with the Apple Clang compiler.You can install the OpenMP library by the following command: brew install libomp. "You can install the OpenMP library by the following command: brew install libomp.", UserWarning)I

**Comment by Innixma** [comment]
Resolved by brew install libomp
