### ISSUE TITLE
AutoGluon Tabular excluded_model_types doesn't work.

### ISSUE THREAD

**Issue by ppunyst** [awslabs/autogluon#1013]
Hello. 
I had a test on Ubuntu 18.04 / Python 3.6.9 w/ AutoGluon ver. 0.1.0b20210225.

When I call TabularPredictor(label=label_column).fit(train_data, excluded_model_types='["KNN", "NN"]') , 
It works well w/o any error message.

But, Even though I ordered `Do not train KNN, NN kinds of models',
AutoGluon Tabular still trains those kinds of models. 

Indeed, I got the log message `Excluded Model Types: ["KNN", "NN"]. 

But, NOT ACTUALLY WORKS.. 
This is why I got the *** Summary of fit() *** which contains KNeighborsUnif, NeuralNetFastAI, etc.

**Comment by Innixma** [comment]
Are you passing the string value `'["KNN", "NN"]'` instead of a list `["KNN", "NN"]`? You have to pass a list. A string will not be properly handled.
