### ISSUE TITLE
module 'autogluon' has no attribute 'args'

### ISSUE THREAD

**Issue by Xingchi-Lboro** [awslabs/autogluon#1016]
Hi,

I am working on a hyperparameter tuning problem based on the example code 'https://github.com/zhanghang1989/HPO2NAS-Tutorial-CVPR-ECCV2020/blob/master/mlp.ipynb'.
However, when I run the code, an error comes as 'module 'autogluon' has no attribute 'args'', I don't know how to fix this problem. 

Basically, I can import autogluon, but can not use it, even cannot check the autogluon version by ag.__version__.
I am using ubuntu 20.04 on a virtual box, and install autogluon following the link: https://auto.gluon.ai/stable/index.html.

**Comment by Innixma** [comment]
The example you are referring to is very old, and does not align with the current API of AutoGluon.

You could try the tutorial after installing an old version of AutoGluon (<=0.0.15), or (preferably) refer to our up-to-date tutorials in our stable documentation: https://auto.gluon.ai/stable/tutorials/index.html

**Comment by nogoodusernameinmind** [comment]
Hello, in the latest version of autogluon is it still possible to use decorators and dynamic models for hyperparameter optimization like in [this example](https://auto.gluon.ai/0.3.1/tutorials/torch/hpo.html)? There is now a similar error as the above in 0.7.0; module 'autogluon.core' has no attribute 'args'
