### ISSUE TITLE
How to specify max training CPU count in Tabular

### ISSUE THREAD

**Issue by JordanHolland** [awslabs/autogluon#1024]
It appears the `n_threads_per_trial` kwarg has been removed from `TabularPredictor.fit()`, but not removed from `ImagePredictor.fit()` fit function. Was this intended?

The byproduct of this removed functionality, combined with a safe limit of 8 cores seems to limit the number of cores that can be used for the `TabularPredictor`:

`Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.`

If this was intended, is there a new method for setting the max number of threads for the `TabularPredictor` to leverage that I am missing?

**Comment by Innixma** [comment]
The below message can be ignored. I'm not sure why it is printed in our logs but it shouldn't impact our model training:

`Note: NumExpr detected 32 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.` 

Currently we default to using all cpu cores for each model training, and don't support specifying custom values. The old `n_threads_per_trial` in old Tabular did not work correctly, and still used the maximum amount of cores. In future we plan to add this, however we expect the grand majority of users to be fine with automatically using all CPUs.

The CPU count can technically be specified via `ag_args_fit={'num_cpus': 32}`, however most models will ignore this at present and just use all CPUs.

**Comment by JordanHolland** [comment]
Just checked -- does look like we're still using all cores for model training. You're probably correct that the majority  of users will want to automatically use all CPUs. Thank you for clearing up the confusion with the `n_threads_per`_trial` kwarg, feel free to close the issue as you see fit.
