### ISSUE TITLE
Missing saved model

### ISSUE THREAD

**Issue by zenetio** [awslabs/autogluon#1026]
I am using Ubuntu 18.04 running on WSL2 with cuda enabled.
I did the dog example using the benchmark.py script. The example did run with no problem and at the end, I checked the checkpoint directory and it was empty. The log file shows the best model is being saved but the directory is empty and there is no error message.
It seems something not working.

**Comment by Innixma** [comment]
Thanks for submitting an issue! Could you please provide a reproducible script + logs so that we can try to replicate the exact issue you are experiencing?

**Comment by zenetio** [comment]
After debugging the benchmark.py script using the dog-breed-identification example, I figured out that there is a **cleanup_disk** flag in image_classification.py script that is true, causing the deletion of the entire checkpoint directory at the end of the fit process. Where can I set this flag to false and avoid the checkpoint directory deletion? I know I can do a hardcode setup but I think there is a more elegant option.

**Comment by zhreshold** [comment]
@zenetio You don't necessarily have to dig into the checkpoint folder, just save the predictor to disk whenever you feel comfortable by `predictor.save('the_checkpoint_i_need')` after fit function.

After a recent fix in gluoncv the predictor will always load the best checkpoint before returning (https://pypi.org/project/gluoncv/0.11.0b20210325/)

**Comment by zenetio** [comment]
@zhreshold , your comment is what I was looking for.
Thank you.
