### ISSUE TITLE
autogluon.mxnet is missing dependency on autogluon.extra

### ISSUE THREAD

**Issue by petergtz** [awslabs/autogluon#1030]
`autogluon.mxnet` uses `autogluon.extra`:
https://github.com/awslabs/autogluon/blob/b403079bcc17171d8b5366096f7d7f9e7eb1b99a/mxnet/src/autogluon/mxnet/task/nets.py#L8
but it doesn't list it as a dependency:
https://github.com/awslabs/autogluon/blob/b403079bcc17171d8b5366096f7d7f9e7eb1b99a/mxnet/setup.py#L19-L28

This breaks when doing a `python3 -m pip install autogluon.mxnet` and then importing `autogluon.mxnet` with the following error message:
```
ModuleNotFoundError: No module named 'autogluon.extra'
```

This should probably be listed either as a required or optional dependency `setup.py`.

**Comment by Innixma** [comment]
Thanks for spotting this! #1032 fixes the issue and will be available in our next release.
