### ISSUE TITLE
Using different pretrained NN model in multimodal TabularPredictor

### ISSUE THREAD

**Issue by sitems** [awslabs/autogluon#1048]
I want to use multimodal TabularPredictor with 'multi_cased_bert_base_fuse_late' pretrained model (instead of the default one). How should I specify it exactly?

```
TabularPredictor().fit(
    train_data=df, 
    hyperparameters='multimodal'
) 
```

**Comment by Innixma** [comment]
You will need to specify a custom hyperparameters dictionary instead of using the preset. This example shows using the multimodal preset as a template and replacing the default text NN with your desired one.

```
from autogluon.tabular.configs.hyperparameter_configs import get_hyperparameter_config
hyperparameters = get_hyperparameter_config('multimodal')
hyperparameters['AG_TEXT_NN'] = ['multi_cased_bert_base_fuse_late']

TabularPredictor().fit(
    train_data=df, 
    hyperparameters=hyperparameters
) 
```
