### ISSUE TITLE
Make pyarrow an optional dependency / not installed by default

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#1053]
pyarrow is specific to parquet files, better to have it be optional in autogluon.text or removed entirely (add informative error message to install pyarrow if attempting to load parquet and pyarrow is not installed)

**Comment by petulla** [comment]
Thanks for this. There seems to not be any PyArrow support at Python 3.9.

**Comment by crazy25000** [comment]
Would like to request this as well, trying to get this working on Python 3.9

**Comment by Innixma** [comment]
Thanks for the reminder! I have created #1200 to remove the pyarrow dependency.
