### ISSUE TITLE
ImportError: cannot import name 'TextClassification' from 'autogluon.text'

### ISSUE THREAD

**Issue by recreationx** [awslabs/autogluon#1056]
Reproduced on Google Colab

Installed via:
!python3 -m pip install -U pip
!python3 -m pip install -U setuptools wheel
!python3 -m pip install -U "mxnet<2.0.0"
!python3 -m pip install autogluon

when calling
from autogluon.text import TextClassification as task
ImportError: cannot import name 'TextClassification' from 'autogluon.text' (/usr/local/lib/python3.7/dist-packages/autogluon/text/__init__.py)

is thrown

**Comment by Innixma** [comment]
You are using the old API, the new API is:

```
from autogluon.text import TextPredictor
```

Tutorial: https://auto.gluon.ai/stable/tutorials/text_prediction/beginner.html
