### ISSUE TITLE
How to load a specific model on leaderboard

### ISSUE THREAD

**Issue by hokmingkwan** [awslabs/autogluon#1069]
Hi,  after using TabularPredictor for training, we can use `predictor.leaderboard(extra_info=True, silent=True)`  to see the model's performance and we can use `model_to_use = predictor.get_model_best()` to predict the test data e.g.: `y_pred = predictor.predict(test_data, model=model_to_use)`

May I know that how we can use the second best model to predict? e.g. The second best is WeightedEnsemble_L3. 
I have tried like the following codes, but encountered an error 
`weighted_ensemble_l3= predictor._trainer.load_model('WeightedEnsemble_L3')`
`y_pred1 = predictor.predict(X_test, model=weighted_ensemble_l3)` 

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-2e1ebdbcfd3e> in <module>
----> 1 y_pred1 = predictor.predict(X_test, model=weighted_ensemble_l3)

/opt/conda/lib/python3.7/site-packages/autogluon/tabular/predictor/predictor.py in predict(self, data, model, as_pandas)
    856         """
    857         data = self.__get_dataset(data)
--> 858         return self._learner.predict(X=data, model=model, as_pandas=as_pandas)
    859 
    860     def predict_proba(self, data, model=None, as_pandas=True, as_multiclass=True):

/opt/conda/lib/python3.7/site-packages/autogluon/tabular/learner/abstract_learner.py in predict(self, X, model, as_pandas)
    168         else:
    169             X_index = None
--> 170         y_pred_proba = self.predict_proba(X=X, model=model, as_pandas=False, as_multiclass=False, inverse_transform=False)
    171         problem_type = self.label_cleaner.problem_type_transform or self.problem_type
    172         y_pred = get_pred_from_proba(y_pred_proba=y_pred_proba, problem_type=problem_type)

/opt/conda/lib/python3.7/site-packages/autogluon/tabular/learner/abstract_learner.py in predict_proba(self, X, model, as_pandas, as_multiclass, inverse_transform)
    149         else:
    150             X_index = None
--> 151         y_pred_proba = self.load_trainer().predict_proba(self.transform_features(X), model=model)
    152         if inverse_transform:
    153             y_pred_proba = self.label_cleaner.inverse_transform_proba(y_pred_proba)

/opt/conda/lib/python3.7/site-packages/autogluon/tabular/trainer/abstract_trainer.py in predict_proba(self, X, model)
    384         if model is None:
    385             model = self._get_best()
--> 386         return self._predict_proba_model(X, model)
    387 
    388     def _get_best(self):

/opt/conda/lib/python3.7/site-packages/autogluon/tabular/trainer/abstract_trainer.py in _predict_proba_model(self, X, model, model_pred_proba_dict)
   1316         if isinstance(model, str):
   1317             model = self.load_model(model)
-> 1318         X = self.get_inputs_to_model(model=model, X=X, model_pred_proba_dict=model_pred_proba_dict, fit=False)
   1319         return model.predict_proba(X=X)
   1320 

/opt/conda/lib/python3.7/site-packages/autogluon/tabular/trainer/abstract_trainer.py in get_inputs_to_model(self, model, X, model_pred_proba_dict, fit, preprocess_nonadaptive)
    409                 model_set = self.get_minimum_model_set(model)
    410                 model_set = [m for m in model_set if m != model.name]  # TODO: Can probably be faster, get this result from graph
--> 411                 model_pred_proba_dict = self.get_model_pred_proba_dict(X=X, models=model_set, model_pred_proba_dict=model_pred_proba_dict, fit=fit)
    412             X = model.preprocess(X=X, preprocess_nonadaptive=preprocess_nonadaptive, fit=fit, model_pred_proba_dict=model_pred_proba_dict)
    413         elif preprocess_nonadaptive:

/opt/conda/lib/python3.7/site-packages/autogluon/tabular/trainer/abstract_trainer.py in get_model_pred_proba_dict(self, X, models, model_pred_proba_dict, model_pred_time_dict, fit, record_pred_time)
    488                 if isinstance(model, StackerEnsembleModel):
    489                     preprocess_kwargs = dict(infer=False, model_pred_proba_dict=model_pred_proba_dict)
--> 490                     model_pred_proba_dict[model_name] = model.predict_proba(X, **preprocess_kwargs)
    491                 else:
    492                     model_pred_proba_dict[model_name] = model.predict_proba(X)

/opt/conda/lib/python3.7/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py in predict_proba(self, X, normalize, **kwargs)
    259         model = self.load_child(self.models[0])
    260         X = self.preprocess(X, model=model, **kwargs)
--> 261         pred_proba = model.predict_proba(X=X, preprocess_nonadaptive=False, normalize=normalize)
    262         for model in self.models[1:]:
    263             model = self.load_child(model)

/opt/conda/lib/python3.7/site-packages/autogluon/core/models/abstract/abstract_model.py in predict_proba(self, X, normalize, **kwargs)
    462         if normalize is None:
    463             normalize = self.normalize_pred_probas
--> 464         y_pred_proba = self._predict_proba(X=X, **kwargs)
    465         if normalize:
    466             y_pred_proba = normalize_pred_probas(y_pred_proba, self.problem_type)

/opt/conda/lib/python3.7/site-packages/autogluon/tabular/models/lgb/lgb_model.py in _predict_proba(self, X, **kwargs)
    212         X = self.preprocess(X, **kwargs)
    213         if self.problem_type == REGRESSION:
--> 214             return self.model.predict(X)
    215 
    216         y_pred_proba = self.model.predict(X)

AttributeError: 'NoneType' object has no attribute 'predict'`

**Comment by talhaanwarch** [comment]
I believe you need to pass it as 
y_pred1 = predictor.predict(X_test, model='weighted_ensemble_l3')
or the simple way is to pass the index of the model as follow or string
```
from autogluon.tabular import TabularDataset, TabularPredictor
train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
test_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')
predictor = TabularPredictor(label='class').fit(train_data, time_limit=30)  # Fit models for 120s
leaderboard = predictor.leaderboard(test_data)
#pred=predictor.predict(test_data,leaderboard.model[1])#index of 2nd model
pred=predictor.predict(test_data,"LightGBM")#2nd best in my case
print('pred shape',pred.shape)
```

**Comment by Innixma** [comment]
You can use the name of the model that was on leaderboard.

```
y_pred = predictor.predict(X_test, model='WeightedEnsemble_L3')
```

For more information, refer to the documentation: https://auto.gluon.ai/stable/api/autogluon.task.html#autogluon.tabular.TabularPredictor.predict
