### ISSUE TITLE
Performance evaluation question

### ISSUE THREAD

**Issue by SangbumChoi** [awslabs/autogluon#1074]
Hi, as the title mentions
I am modifying autogluon to have faster inference time with the same performance (especially in the feature engineering part).
However, I was curious about the rule of the modified code's generality. This means that the paper denotes about a total 10 kaggle competition (except Walmart since deprecated), so does overall or average performance gain on this 10 dataset can be interpreted as valid? or is there any other evaluation dataset for PR?

**Comment by Innixma** [comment]
Hi Choi,

Thanks for your interest! We would be happy to benchmark changes you make from a PR submission.

The current way we go about benchmarking / evaluating AutoGluon Tabular is with the AutoMLBenchmark: https://github.com/openml/automlbenchmark . This is somewhat involved to run yourself, and is more suited to large-scale benchmarking on 100's of datasets.

For smaller-scale testing, I'd recommend finding a dataset that performs poorly with AutoGluon by the metric you are trying to improve (say it is slow during inference), and then see if applying your change leads to improvement. This could be either on Kaggle, or any number of OpenML datasets. Once you submit your PR and we do a review, if everything looks good we will run a benchmark on AutoMLBenchmark to check against the current mainline to see how it performs.

**Comment by SangbumChoi** [comment]
> Hi Choi,
> 
> Thanks for your interest! We would be happy to benchmark changes you make from a PR submission.
> 
> The current way we go about benchmarking / evaluating AutoGluon Tabular is with the AutoMLBenchmark: https://github.com/openml/automlbenchmark . This is somewhat involved to run yourself, and is more suited to large-scale benchmarking on 100's of datasets.
> 
> For smaller-scale testing, I'd recommend finding a dataset that performs poorly with AutoGluon by the metric you are trying to improve (say it is slow during inference), and then see if applying your change leads to improvement. This could be either on Kaggle, or any number of OpenML datasets. Once you submit your PR and we do a review, if everything looks good we will run a benchmark on AutoMLBenchmark to check against the current mainline to see how it performs.

Hi, thanks for the reply!
I see some gap between automlbenchmark dataset (which is somehow preprocessed of feature engineering and not having NA values) and the raw dataset (such as Kaggle).

Not only these issues I also experimented and saw some slight performance gap (using pure AutoGluon code with importing tabularpredictor vs. Openmlbenchmark)

However, the reply was pretty clear enough for me so I will keep try on that
Thanks!

**Comment by Innixma** [comment]
AutoMLBenchmark actually does have NA values on some of the datasets, and isn't particularly preprocessed. The only thing that is different in AutoMLBenchmark is that it specifies the feature types when the feature types are ambiguous, such as a feature that has values `0, 1, 2, 3, 4, 5` being categorical vs integer.

If you do find something particularly odd about the performance gap you are observing outside of the feature type specification, I'd be happy to take a look. We want AutoMLBenchmark to map as closely as possible to how AutoGluon performs in practice.

**Comment by SangbumChoi** [comment]
> AutoMLBenchmark actually does have NA values on some of the datasets, and isn't particularly preprocessed. The only thing that is different in AutoMLBenchmark is that it specifies the feature types when the feature types are ambiguous, such as a feature that has values `0, 1, 2, 3, 4, 5` being categorical vs integer.
> 
> If you do find something particularly odd about the performance gap you are observing outside of the feature type specification, I'd be happy to take a look. We want AutoMLBenchmark to map as closely as possible to how AutoGluon performs in practice.

Well then the last thing that I want to ask is that does the paper evaluation was held on default configuration (which means no stacking and bagging by having auto_stack=default) or does stacking and bagging were set by auto_stack=True? (Also this kind of configuration will be highly dependent on server setting such as number of CPU, GPU, etc...)

**Comment by Innixma** [comment]
The paper was specifically set to `auto_stack=True`. While stacking is not always better due to a variety of factors, most notably a limited time budget, it is better than the default method the vast majority of the time. Also, the paper results shouldn't necessarily be considered as the current state of AG, as it has been over a year since those results were published and AutoGluon has undergone numerous improvements. When comparing your changes to AG, make sure to also run mainline AG, as that is the most genuine comparison.

**Comment by SangbumChoi** [comment]
> The paper was specifically set to `auto_stack=True`. While stacking is not always better due to a variety of factors, most notably a limited time budget, it is better than the default method the vast majority of the time. Also, the paper results shouldn't necessarily be considered as the current state of AG, as it has been over a year since those results were published and AutoGluon has undergone numerous improvements. When comparing your changes to AG, make sure to also run mainline AG, as that is the most genuine comparison.

Currently, my custom feature engineering shows performance increment in 7 out of 9 kaggle dataset when using vanilla AG, but sometimes having errors with multi-class and bnp-paribas dataset. Keep trying to have no error.
Yeah, pretty much version updated since the paper released I understand about the circumstances. Thanks for your kind and fast response :)
