### ISSUE TITLE
Replicate AutoGluon pipeline in code

### ISSUE THREAD

**Issue by qo4on** [awslabs/autogluon#1083]
Can `AutoGluon` save training code, similar to what `TPOT` does? If not, how can I find out exactly what it's doing?

![image](https://user-images.githubusercontent.com/35609308/115995621-667d7280-a5f5-11eb-9657-49500ec57b89.png)

Suppose I selected `WeightedEnsembleL3` with
```
model_to_use = predictor.get_model_best()
```
Then loaded it
```
specific_model = predictor._trainer.load_model(model_to_use)
```
I believe that `AutoGluon` runs `AutoMLPipelineFeatureGenerator` as default preprocessing
```
feature_generator = AutoMLPipelineFeatureGenerator()
X_train_transformed = feature_generator.fit_transform(X=X_train, y=y_train)
X_test_transformed = feature_generator.transform(test_data)
```
What does it do next? How to find out which models it uses for stacking and parameters for each model, which stacking algorithm?

**Comment by jwmueller** [comment]
You may use: `predictor. plot_ensemble_model()` to see the stack ensemble corresponding to 
`predictor.get_model_best()`

Basically after data-preprocessing, autogluon simply trains all the models you see on the leaderboard above (L2 models are stacker models trained on top of L1 models' predictions as their features). More details are provided here: https://arxiv.org/abs/2003.06505

If you'd like to see more info about any particular model, you can either try:
`predictor.info()`

or try:

```model = predictor._learner.load_trainer().load_model('WeightedEnsembleL3')
model.get_info()```

**Comment by Innixma** [comment]
You can also try:

```predictor.leaderboard(extra_info=True)```

This adds many additional columns with detailed model information to the output.
