### ISSUE TITLE
TextPredictor fails if eval_metric = 'average_precision'

### ISSUE THREAD

**Issue by rxjx** [awslabs/autogluon#1085]
I am training a TextPredictor in Colab without a GPU (%env AUTOGLUON_TEXT_TRAIN_WITHOUT_GPU=1). It works fine when I use eval_metric='f1' but fails when eval_metric = 'average_precision' like so:

INFO:root:Fitting and transforming the train data...
INFO:root:Done! Preprocessor saved to /content/drive/My Drive/autogluon_txt/task0/preprocessor.pkl
INFO:root:Process dev set...
INFO:root:Done!
INFO:root:Max length for chunking text: 256, Stochastic chunk: Train-False/Test-False, Test #repeat: 1.
INFO:root:#Total Params/Fixed Params=108990466/0
Level 15:root:Using gradient accumulation. Global batch size = 128
INFO:root:Local training results will be saved to /content/drive/My Drive/autogluon_txt/task0/results_local.jsonl.
Level 15:root:[Iter 2/240, Epoch 0] train loss=4.78e-01, gnorm=9.80e+00, lr=8.33e-06, #samples processed=256, #sample per second=2.53. ETA=200.39min
Level 15:root:[Iter 4/240, Epoch 0] train loss=3.87e-01, gnorm=3.01e+00, lr=1.67e-05, #samples processed=256, #sample per second=2.88. ETA=186.68min
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-6178bb930461> in <module>()
     19 
     20 txt_data = pd.DataFrame({'sent':sent, 'lbl':lbl})
---> 21 m = TextPredictor(label='lbl', eval_metric='average_precision', path='/content/drive/My Drive/autogluon_txt').fit(txt_data) # f1

17 frames
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py in column_or_1d(y, warn)
    795         return np.ravel(y)
    796 
--> 797     raise ValueError("bad input shape {0}".format(shape))
    798 
    799 

ValueError: bad input shape (500, 2)

**Comment by rxjx** [comment]
Sorry, the formatting got messed up.

**Comment by talhaanwarch** [comment]
I also faced this, check colab [notebook ](https://colab.research.google.com/drive/191nVpfvKLBCFgxsjeK5htHLNoI6KLHFi?usp=sharing)

**Comment by rxjx** [comment]
Yeah, verified that this would work. I changed it to: 
`if problem_type == BINARY and scorer.name in ['roc_auc', 'average_precision']: `

However, might be better to just check for predictions' shape and use predictions[:,1] if it has more than one column?

**Comment by sxjscience** [comment]
@rxjx Would you mind submit a PR to fix it? We can change the code to check for the shape of prediction and slice `[:, 1]` if it is binary.

**Comment by rxjx** [comment]
Sure, I can do that tomorrow if that's OK. Need to work on my paying job today :-)

**Comment by rxjx** [comment]
Oddly, the training crashed twice after an hour. Not sure if that's related but will look at it more tomorrow. Colab is not showing me any logs about it. Just tells me it crashed.

**Comment by rxjx** [comment]
@sxjscience is predictions guaranteed to be a numpy array at that point in that code? Or could it also be a pandas dataframe/series?

**Comment by sxjscience** [comment]
Yes, it is guaranteed as a numpy array.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rxjx** [comment]
Yeah, I looked thru the code and verified that. Just wanted to double check. OK, PR is ready.
