### ISSUE TITLE
Training with `presets='best_quality'` takes too long

### ISSUE THREAD

**Issue by mli** [awslabs/autogluon#1096]
The following code takes ~2h on a cpu machine, which is reasonable. 

```
!kaggle competitions download california-house-prices
!unzip california-house-prices.zip

from autogluon.tabular import TabularDataset, TabularPredictor
import numpy as np 

label = 'Sold Price'
large_values = ['Lot', 'Total interior livable area', 'Tax assessed value',
                'Annual tax amount', 'Listed Price']
train_data = TabularDataset('train.csv')
for c in large_values + [label]:
    train_data[c] = np.log(train_data[c]+1)

predictor = TabularPredictor(label=label).fit(
    train_data.drop(columns=['Id']))
```

However, if enable `presets='best_quality'`, it will a significant more time. I stopped the training after about 5hours, I guess other users would do a similar thing. 

We could improve the user experience by 

1. report an estimated remaining time, not necessary to be accurate, but encourage users to wait
2. may generate a warning that "you may consider to use gpu to accelerate your training, and here is how", especially when gpus are available

**Comment by Innixma** [comment]
In general, `best_quality` will take ~20x longer than default, so if default takes 2 hours, `best_quality` will take 40 hours.

Currently it is somewhat difficult to get an estimate of total training time remaining, and this will be especially true for more diverse ensembles. I think a practical first step would be to add a log message to the user when training without specifying `time_limit` if there are many rows in the data (say >100,000) that training time may take a long time and it is recommended to specify a `time_limit`.

**Comment by Innixma** [comment]
For this particular dataset, the reason it takes a long time is because it has text features which are expanded into ngrams.

I've added a PR to address this by adding a warning if time_limit=None and data is large (either by rows or by memory) which triggers on the dataset you mentioned:

```
Warning: Training may take a very long time because `time_limit` was not specified and `train_data` is large (47439 samples, 108.23 MB).
	Consider setting `time_limit` to ensure training finishes within an expected duration or experiment with a small portion of `train_data` to identify an ideal `hyperparameters` configuration.
```
