### ISSUE TITLE
How can I use autogluon offline in Kaggle notebooks?

### ISSUE THREAD

**Issue by YirunKCL** [awslabs/autogluon#1106]
Most of the ongoing Kaggle competitions now require participants to disable the internet connection during inference. How can I use autogluon without internet connection in Kaggle notebooks?

**Comment by Innixma** [comment]
Could you try following these instructions? https://www.kaggle.com/c/severstal-steel-defect-detection/discussion/109679

The other alternative is getting AutoGluon pre-installed in the Kaggle kernel. autogluon.core is already pre-installed, but autogluon.tabular is not.

**Comment by YirunKCL** [comment]
> Could you try following these instructions? https://www.kaggle.com/c/severstal-steel-defect-detection/discussion/109679
> 
> The other alternative is getting AutoGluon pre-installed in the Kaggle kernel. autogluon.core is already pre-installed, but autogluon.tabular is not.

Thanks. How can I pre-install it into the notebook?

**Comment by Innixma** [comment]
This would require having it installed in the base Kaggle kernel, such that all users for all kernels would have AutoGluon pre-installed. This is the more extreme approach and would require a PR to https://github.com/Kaggle/docker-python

**Comment by YirunKCL** [comment]
Thanks. I have found a way to install it offline.

**Comment by talhaanwarch** [comment]
Here are the steps if some one needed latter
1) Open new Kaggle notebook with internet and name it as myautogluon or whatever name you want 
2) run !pip download [insert package name] such as 
```
!pip download  pip
!pip download setuptools wheel
!pip download "mxnet<2.0.0"
!pip download autogluon  # autogluon==0.2.0
```
3) it will download the package and all its requirements
4) now create a new notebook with internet off
5) click on add data on upper right corner, go to notebook output files, click on your work and import the previous notebook
6) now install all packages downloaded above in new notebook 
```
!pip install --no-index --find-links ../input/myautogluon / ../input/myautogluon /pip-21.1.1-py3-none-any.whl
!pip install --no-index --find-links ../input/myautogluon / ../input/myautogluon /setuptools-56.2.0-py3-none-any.whl
!pip install --no-index --find-links ../input/myautogluon / ../input/myautogluon /wheel-0.36.2-py2.py3-none-any.whl
!pip install --no-index --find-links ../input/myautogluon / ../input/myautogluon /mxnet-1.8.0.post0-py2.py3-none-manylinux2014_x86_64.whl
!pip install --no-index --find-links ../input/myautogluon / ../input/myautogluon /autogluon-0.2.0-py3-none-any.whl
```
