### ISSUE TITLE
Specify model weight path manually 

### ISSUE THREAD

**Issue by talhaanwarch** [awslabs/autogluon#1110]
Some of kaggle competitions don't allow the use of the internet while submitting csv file for scoring. For such purpose, we need to add pre-trained weights as data and then link it to the model. 
For example in keras we can do
`model.load_weights('/kaggle/input/weights.h5')`
in pytorch we can load as follow
`model.load_state_dict(torch.load('/kaggle/input/weights.ckpt')['state_dict'])`
How can we do it here in autogluon

**Comment by Innixma** [comment]
Can you be more specific as to which Predictor you are using? TabularPredictor has no direct concept of loading weights, however you can do this for TextPredictor and ImagePredictor. If you could provide more details that would help us be able to answer. For example, are you trying to replicate a model that was trained on a non-kaggle machine to an offline kaggle kernel? If so, why not use your guide provided in #1106 to save the models and the pip install files to a dataset, then load them in the offline kernel?

For Tabular, you could zip the files under `predictor.path`, and upload those as a kaggle dataset, unzip it, then load via `TabularPredictor.load(dir_path)`.

**Comment by talhaanwarch** [comment]
How can we download pre-trained weights from mxnet server and load it to ImagePredictor. It would be a zip file and predictor accept `.ag` format, I think

**Comment by Innixma** [comment]
@zhreshold could you take a look?

**Comment by zhreshold** [comment]
same as #1196
