### ISSUE TITLE
How to add a new model support for TabularPredictor?

### ISSUE THREAD

**Issue by jianzhnie** [awslabs/autogluon#1114]
I found that autogluon has already supported some ml models (knn, lightgbm, xgboost, ...). What should I do if I want to add a new model, such as DeepFM?

**Comment by Innixma** [comment]
We would be happy to review a PR that implements a new model in AutoGluon!

We have a basic example tutorial for this here: https://github.com/awslabs/autogluon/blob/master/examples/tabular/example_custom_model_tabular.py

Additionally, we have documentation of models and their API available here:
https://auto.gluon.ai/stable/api/autogluon.tabular.models.html

Here is the AbstractModel code API, which you would inherit from in your model. It is recommend you read the API descriptions of each of the methods to get a sense of what is happening internally:
https://auto.gluon.ai/stable/_modules/autogluon/core/models/abstract/abstract_model.html#AbstractModel

Here is an example of an existing model, XGBoost:
https://auto.gluon.ai/stable/_modules/autogluon/tabular/models/xgboost/xgboost_model.html#XGBoostModel

Once you make a working model class `MyModel`, you can test it out by passing into `TabularPredictor` via `TabularPredictor(...).fit(..., hyperparameters={MyModel: {}})`

Note that some of the model code may look intimidating at first, but you don't need to implement all the bells and whistles to start with. For example, most of our models have extra code to ensure time limit is respected, GPU support, handle memory management, binary, multiclass, regression support, early stopping, hyperparameter tuning, etc. These are all optional for an initial implementation, so the first version of a model can be quite simple (<100 LOC).

Once you submit a PR, we will be able to benchmark it and give feedback so we can iterate to improve the code prior to merging it in. To get an idea of the process, see #691 which contributed XGBoost.

Thanks again for expressing interest!
