### ISSUE TITLE
How to load textpredictor without downloading from google_electra?

### ISSUE THREAD

**Issue by YirunKCL** [awslabs/autogluon#1115]
I have trained a text predictor and want to submit it on Kaggle without an internet connection. However, it needs to download the google_electra parameters using the internet. How do I solve this problem?

Another problem is when I am passing the data for prediction, an error raises.

NotImplementedError: The format of data is not understood. We have type(data)="<class 'pandas.core.series.Series'>"

**Comment by talhaanwarch** [comment]
I am facing the same issue in vision task #1111  during inference the weights are being downloaded, though there is no need for it and I am specifying the path of the saved predictor.

**Comment by YirunKCL** [comment]
I think one possible solution is to manually copy these parameters to the mentioned path

**Comment by Innixma** [comment]
> Another problem is when I am passing the data for prediction, an error raises.
> 
> NotImplementedError: The format of data is not understood. We have type(data)="<class 'pandas.core.series.Series'>"

You need to pass a pandas DataFrame, not a pandas Series. Currently the error is a bit confusing, so I'll look to improve it.

**Comment by Innixma** [comment]
@sxjscience Regarding the downloading of google_electra model, can we disable this on models which are being loaded after training?

**Comment by sxjscience** [comment]
@Innixma Yes, we will need to update this line: https://github.com/awslabs/autogluon/blob/516668adfe33c5adaed69c14976339480081eb79/text/src/autogluon/text/text_prediction/mx/models.py#L1396-L1397

@YirunKCL Would you try to change the line to the following

```
... = get_backbone(cfg.model.backbone.name, load_backbone=False)
```

**Comment by sxjscience** [comment]
@YirunKCL Would you verify if the latest autogluon has fixed the issue?

**Comment by Innixma** [comment]
To clarify, we mean the latest pre-release. This is obtainable on a fresh venv via `pip install --pre autogluon` or by building from source. You will likely have to re-train the model in order for it to work properly.

**Comment by talhaanwarch** [comment]
@sxjscience @Innixma This issue has not been fixed in 0.2.1 . it still download weights while predicting with following code
`predictor = TextPredictor.load('../input/agnlp-train/nlpgluon/')`

**Comment by sxjscience** [comment]
@talhaanwarch Would you report the error message? It should not download the pretrained weights after the PR. However, it will download the vocab and configuration.

**Comment by Outliers1106** [comment]
> @talhaanwarch Would you report the error message? It should not download the pretrained weights after the PR. However, it will download the vocab and configuration.

Any kind of downloading is prohibitive in Kaggle submission, even if it is just vocab or configuration...

**Comment by sxjscience** [comment]
There is a workaround solution for now. You may monkey patch this function: https://github.com/sxjscience/autogluon-contrib-nlp/blob/79b2b50256c6685da52ef1d47810b6e478e96cae/src/autogluon_contrib_nlp/models/electra.py#L844

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by talhaanwarch** [comment]
I think it still downloads the weights and config files
```
Downloading /root/.mxnet/models/nlp/google_electra_base/model-5b35ca0b.yml from https://gluonnlp-numpy-data.s3-accelerate.amazonaws.com/models/google_electra_base/model-5b35ca0b.yml...
100%|██████████| 477/477 [00:00<00:00, 169kiB/s]
Downloading /root/.mxnet/models/nlp/google_electra_base/vocab-e6d2b21d.json from https://gluonnlp-numpy-data.s3-accelerate.amazonaws.com/models/google_electra_base/vocab-e6d2b21d.json...
100%|██████████| 323k/323k [00:00<00:00, 380kiB/s] 
Downloading /root/.mxnet/models/nlp/google_electra_base/model-31c235cc.params from https://gluonnlp-numpy-data.s3-accelerate.amazonaws.com/models/google_electra_base/model-31c235cc.params...
100%|██████████| 436M/436M [00:37<00:00, 11.8MiB/s] 
```

**Comment by sxjscience** [comment]
@yiqings is investigating the issue. We noticed that having AutoGluon run in non-internet environment is not very trivial in general.

**Comment by sxjscience** [comment]
The fix is tracked in https://github.com/awslabs/autogluon/pull/1575

**Comment by yiqings** [comment]
In addition to `AutoMMPredictor.save(standalone=True)`  as in https://github.com/awslabs/autogluon/pull/1575, we are now heading for an extension to `TextPredictor.save(standalone=True)`, which can be tracked in https://github.com/awslabs/autogluon/pull/1651.


Here is a brief example on the deployment to the offline environment. I hope you find it useful:
1. Train the `AutoMMPredictor` (or `TextPredictor`) on your local devices with the accessibility to internet.
2. After calling `AutoMMPredictor.fit()`, use `AutoMMPredictor.save(path=PATH,standalone=True)` to save the models explicitly. 
3. In `AutoMMPredictor.load()`, it is feasible to load models from files saved with `standalone=True`  without network connection.
