### ISSUE TITLE
munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by kevin666aa** [awslabs/autogluon#1116]
<img width="882" alt="企业微信截图_16209850219930" src="https://user-images.githubusercontent.com/32823396/118252141-08003180-b4db-11eb-97fa-74f415942db4.png">
I encountered this error after running for a while, can anyone help me locate the problem?

**Comment by Innixma** [comment]
@kevin666aa Thanks for reporting this issue. Could you please provide more details such as OS, Python Version, CUDA Version, size of data, GPU you are using, etc.?

@zhreshold Any ideas?

**Comment by kevin666aa** [comment]
![image](https://user-images.githubusercontent.com/32823396/118344666-04fc5400-b562-11eb-8e68-17053f9489e1.png)
![image](https://user-images.githubusercontent.com/32823396/118344682-25c4a980-b562-11eb-9aa8-c47a884b7051.png)
![image](https://user-images.githubusercontent.com/32823396/118344711-56a4de80-b562-11eb-97ad-376cb007f860.png)
![image](https://user-images.githubusercontent.com/32823396/118344746-88b64080-b562-11eb-871a-a1c2ff7de7ae.png)
Above is OS version, CUDA version, autogluon versions, and the code I used.
The python version is 3.7.5.
The bug happend during the fit() method.

**Comment by zhreshold** [comment]
@kevin666aa it's very much a very underlying problem, likely in mxnet. Can you post the version of `mxnet-cu102`?

**Comment by Fanxingye** [comment]
Hi, @zhreshold , I am in the same team with @kevin666aa . I use the same environment with him , our version of mxnet is mxnet-cu101   1.8.0.post0

**Comment by kevin666aa** [comment]
Hello there, it should be an environment problem, related to mxnet version and cuda version, after updating the new enviroment, the problem has been fixed. Thank you for your support!
