### ISSUE TITLE
Can't delete models

### ISSUE THREAD

**Issue by qo4on** [awslabs/autogluon#1119]
When I trained a small model the size of main folder was
`135M	AutogluonModels`

Then I deleted everything:
`predictor.delete_models(models_to_keep=[], dry_run=False)`

But still got:
`102M	AutogluonModels`

With some files and folders inside:
`AutogluonModels/ag-20210516_175027: learner.pkl  models  predictor.pkl  utils`

How to delete everything or keep only the best model without additional `102M`?

**Comment by Innixma** [comment]
Try `predictor.save_space()`, given you've deleted the models but 102MB still exists, that is likely from the cached data files. `.save_space` should delete those files and the resulting size should be quite small. There is currently no `delete_all` functionality, mostly to safeguard the user in-case they had other files in the AG directory.

**Comment by qo4on** [comment]
Thank you it deletes most content. But some folders are still there. For example, initially I have:
![image](https://user-images.githubusercontent.com/35609308/118674137-00aa9200-b813-11eb-9d58-959eebacf632.png)
![image](https://user-images.githubusercontent.com/35609308/118674360-29cb2280-b813-11eb-8bf1-4c634f69d0c4.png)

To keep only the best model I do this:
```
predictor.delete_models(models_to_keep='best', dry_run=False)
predictor.save_space()
```
![image](https://user-images.githubusercontent.com/35609308/118674889-92b29a80-b813-11eb-804c-1c013a7bfa30.png)
![image](https://user-images.githubusercontent.com/35609308/118675101-c68dc000-b813-11eb-84c8-f2e4ce2da06e.png)

It looks as expected, but I still see a lot of garbage in the folder:

![image](https://user-images.githubusercontent.com/35609308/118675466-0f457900-b814-11eb-81c3-f7dfe5e20d22.png)

What is the right way to save only selected models?

**Comment by Innixma** [comment]
This looks like you are referring to two separate runs in your examples. The only time files will remain is if:

1. They are required for the best model
2. They failed during training and were never tracked by `predictor` in the first place.

I think your last image is from a different training run, or else you re-used the same directory path for multiple runs of AutoGluon. Try on a fresh directory and do all the steps you mentioned, it should only keep the required model files and models which raised exceptions during training. This works correctly for me.

**Comment by qo4on** [comment]
Copypaste this to colab:
```
try:
    from autogluon.tabular import TabularDataset, TabularPredictor
    from autogluon.features.generators import AutoMLPipelineFeatureGenerator
except ModuleNotFoundError:  
    !pip install -U pip > /dev/null
    !pip install -U setuptools wheel > /dev/null
    !pip install "mxnet<2.0.0" > /dev/null
    !pip install autogluon.tabular[all] > /dev/null
    import os
    os._exit(0)

!gdown -q https://drive.google.com/uc?id=1hZ2B_OlpNYXYsRwyuKIXEJq803gOE7aK

# Unzip
dir_to = 'AutogluonModels'
!mkdir -p $dir_to && tar -zxf AutogluonModels.tgz -C $dir_to

predictor = TabularPredictor.load('AutogluonModels/ag-20210511_130651')

lb = predictor.leaderboard(silent=True)
lb

!sudo apt-get install graphviz libgraphviz-dev > /dev/null
!sudo pip install pygraphviz > /dev/null

from PIL import Image
Image.open(predictor.plot_ensemble_model())

predictor.delete_models(models_to_keep='best', dry_run=False)
predictor.save_space()

Image.open(predictor.plot_ensemble_model())

!ls AutogluonModels/ag-20210511_130651/models
```

**Comment by Innixma** [comment]
Refer to this colab example, I believe your example is corrupted in some way: https://colab.research.google.com/drive/1Ij-Njdn3H6zS_simVf94XQDGp4Q6DREl?usp=sharing

Re failed models: Yes, currently there is no functionality to delete failed model files. I have created an issue to track adding a feature to delete these files: #1119

**Comment by Innixma** [comment]
Closing, to keep track of the status of this feature, refer to #1124
