### ISSUE TITLE
How can I add my own CV split?

### ISSUE THREAD

**Issue by YirunKCL** [awslabs/autogluon#1120]
Hi, I am working on a time series problem. Apparently, random k fold is not proper so I would like to use my own timeseries cv split. How can I add this to the models?

**Comment by Innixma** [comment]
Custom CV splits are not yet supported, but are planned for v0.3. See existing issues: #617, #901, #999

Closing as duplicate for now, will communicate in linked issues when custom CV splits are implemented.

**Comment by gauravbrills** [comment]
This will be very useful .. similar to something h2o automl does

**Comment by Innixma** [comment]
@gauravbrills This was added in v0.3 release with #1224. Feel free to respond further if this is not what you are looking for.

**Comment by gauravbrills** [comment]
> @gauravbrills This was added in v0.3 release with #1224. Feel free to respond further if this is not what you are looking for.

yes just saw that and updated looks good Thanks .

**Comment by eromoe** [comment]
Group doesn't fit many usecase, for example I want to use sklearn TimeSeriesSpliter , or apply Purged Cross-Validation (https://gist.github.com/Burntt/f26e5414205542207949aeb9e9cc1ddb) ,  need control generation of train_index and test_index .
