### ISSUE TITLE
No version property

### ISSUE THREAD

**Issue by wlongxiang** [awslabs/autogluon#1121]
```
>>> import autogluon
>>> autogluon.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'autogluon' has no attribute '__version__'
```
For most python packages, the above should print out the version number. This is useful for quick version checking and automation in CI pipelines.

**Comment by Innixma** [comment]
AutoGluon is a namespace package, which means you cannot perform any imports at the `autogluon` level as it is not technically a package.

Instead, you will need to get the version of a particular submodule of autogluon, such as:

```
from autogluon.core import __version__
from autogluon.tabular import __version__
from autogluon.text import __version__
from autogluon.vision import __version__
# etc...
```

**Comment by Innixma** [comment]
Ah, you are correct, it is under:

```
from autogluon.tabular.version import __version__
print(__version__)
```

**Comment by wlongxiang** [comment]
Thanks both for your quick response @sxjscience @Innixma !
I would still like to add that it is more or less conventional for a package, in this case, tabular, text, etc. under autogluon namespace to have `__version__`

This should ideally give back the version number:
```
>>> from autogluon import tabular
>>> tabular.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'autogluon.tabular' has no attribute '__version__'
```
I can make the pull request to add this property to the package level, if you guys think it could be a small improvement too.

**Comment by Innixma** [comment]
Yes, I had the same thought @wlongxiang, I have created a PR which adds the requested functionality: #1122

**Comment by Innixma** [comment]
#1122 is merged and fixes this issue.
