### ISSUE TITLE
[Tabular] Separate training and validation set by group

### ISSUE THREAD

**Issue by albert-ying** [awslabs/autogluon#1126]
Hi, I have a dataset with many groups of samples (i.e., samples from different individuals). When splitting the training and validation set, I don't want the samples from the same individual to be used in both sets, since that may cause information leaking.

In another word, I would like data to be split based on grouping variables instead of rows.

I tried to specify the training and validation set myself but it gives me the error.
```
AssertionError: X_val, y_val is not None, but bagged mode was specified. If calling from `TabularPredictor.fit()`, `tuning_data` must be None.
Bagged mode does not use tuning data / validation data. Instead, all data (`train_data` and `tuning_data`) should be combined and specified as `train_data`.
Bagging/Stacking with a held-out validation set (blend stacking) is not yet supported.
```

Therefore, I'm wondering if there is other way to do this? Thank you in advance!

**Comment by talhaanwarch** [comment]
the way i do this is creating list of list, containing individuals and samples,
then split them using sklearn train_test_split function.
After that convert it to dataframe.

Let me explain it in detail
I have 2 classes, pos and neg, each class has ten 10 individuals folder. Each individual folder has 5 images.
Now i want to split it such that there is no information leakage.
I will do it as follow

```
from glob import glob
## iterate each image of each individual folder and save it as list of list
pos_path=[glob(folder+'*.jpg') for folder in glob('data/pos/*/')]
neg_path=[glob(folder+'*.jpg') for folder in glob('data/neg/*/')]

##create label for each image of each folder
pos_label=[[0]*len(i)  for i in pos_path]
neg_label=[[1]*len(i)  for i in neg_path]

##now combine both pos and neg class
path=pos_path+neg_path
label=pos_label+neg_label

##now split the data, and there is no mixing , because its based on individual folder, instead of images
train_path,val_path,train_label,val_label=train_test_split(path,label,test_size=0.2)

##now convert list of list to single list ##list flatten
train_path = [item for sublist in train_path for item in sublist]
val_path = [item for sublist in val_path for item in sublist]
train_label = [item for sublist in train_label for item in sublist]
val_label = [item for sublist in val_label for item in sublist]

##convert it to dataframe
train_df=pd.DataFrame(zip(train_path,train_label),columns=['image','label'])
train_df.head()

##apply predictor
predictor = ImagePredictor()
predictor.fit(train_df, hyperparameters={'epochs': 2})

```

**Comment by Innixma** [comment]
I am currently writing a PR which will add support for specifying a hold-out set in multi-layer stacking mode (referred to as bagged mode): #1105 

Once merged, this should enable you to specify `tuning_data` as you intended for v0.3 release (and nightly pre-release).

For now, one option is to not use bagging/multi-layer stacking. Then you can specify `tuning_data` without issue.

Alternatively, holdout your intended validation set from AutoGluon (don't pass it into `.fit`), then pass your validation set to `predictor.leaderboard(val_data)` and choose the model which gets the best `score_test`.

**Comment by albert-ying** [comment]
Hi @Innixma, I saw the #1105 is now merged. Is it possible to do it now? Could you provide an example of it? Thank you so much!

**Comment by Innixma** [comment]
Yes, it should be possible now.

You can try it via:

```
predictor.fit(train_data=train_data, tuning_data=tuning_data, ..., use_bag_holdout=True)
```

with stacking enabled.

Hope this solves your issue!
