### ISSUE TITLE
No GPU detected/allowed, using most conservative search space.

### ISSUE THREAD

**Issue by talhaanwarch** [awslabs/autogluon#1127]
Greetings. I am using windows 10, cuda version 10.1, python 3.8.5. GTX 1060 MaxQ. 
I installed autogluon as follow
```
pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
python -m pip install -U pip
python -m pip install -U setuptools wheel
python -m pip install -U "mxnet_cu101<2.0.0"
python -m pip install autogluon
```
I checked GPU presence as follow
```
import mxnet as mx
mx.context.num_gpus()
```
It output as `1`

package info
mxnet-cu101==1.5.0
autogluon==0.2.0
autogluon-contrib-nlp==0.0.1b20210201
autogluon.core==0.2.0
autogluon.extra==0.2.0
autogluon.features==0.2.0
autogluon.mxnet==0.2.0
autogluon.tabular==0.2.0
autogluon.text==0.2.0
autogluon.vision==0.2.0

But when I run predictor.fit it say 
`INFO:gluoncv.auto.tasks.image_classification:No GPU detected/allowed, using most conservative search space.`

Any idea about it?

**Comment by Innixma** [comment]
Thanks for opening an issue on this! We will plan to look into why this is occurring sometime in the next couple weeks. I'd guess it may be related to using Windows and your particular CUDA installation / GPU. There are multiple ways to check if GPUs are available, and the one we use may not be the same as `mx.context.num_gpus()`.

**Comment by xxx2009-lab** [comment]
I also got the same issue @Innixma 
import mxnet as mx
mx.context.num_gpus()
1

ag.get_gpu_count()
0

**Comment by gradientsky** [comment]
Can you also try setting `CUDA_VISIBLE_DEVICES=0` system variable (comma-separated list of devices 0,1,2,3,...) before running the script?

**Comment by starsfell** [comment]
I got the same issue, mxnet can detect GPU, but when I tried to test autogluon to solve text classification problem, it said no gpu detected.

**Comment by talhaanwarch** [comment]
What is your GPU model, cuda version and mxnet installed version

**Comment by starsfell** [comment]
mxnet-cu101==1.7.0
CUDA version 

> What is your GPU model, cuda version and mxnet installed version

mxnet-cu101==1.7.0
gpu: geforce gtx 1050
CUDA: 10.1 Update 2

**Comment by Innixma** [comment]
@starsfell Are you also on Windows?

Here is [the code](https://github.com/awslabs/autogluon/blob/master/core/src/autogluon/core/utils/nvutil.py#L23) which I suspect causes the issue:

```

from ctypes import *
from ctypes.util import find_library
import sys
import os
import threading
import string

cudaLib = None
libLoadLock = threading.Lock()

def _LoadNvmlLibrary():
    '''
    Load the library if it isn't loaded already
    '''
    global cudaLib
    
    ret = True
    if (cudaLib == None):
        # lock to ensure only one caller loads the library
        libLoadLock.acquire()
        try:
            # ensure the library still isn't loaded
            if (cudaLib == None):
                try:
                    if (sys.platform[:3] == "win"):
                        # cdecl calling convention
                        # load cuda.dll from %ProgramFiles%/NVIDIA Corporation/NVSMI/cuda.dll
                        cudaLib = CDLL(os.path.join(os.getenv("ProgramFiles", "C:/Program Files"), "NVIDIA Corporation/NVSMI/cuda.dll"))
                    else:
                        # assume linux
                        cudaLib = CDLL("libnvidia-ml.so.1")
                except OSError as ose:
                    pass

                if (cudaLib == None):
                    ret = False
        finally:
            # lock is always freed
            libLoadLock.release()

    return ret
```

If this function returns False, then

```
ag.get_gpu_count()
```

will return 0, even if GPUs are available and CUDA is installed.

My guess is that on your machine, CUDA is not installed in the location expected in this code.

This code definitely looks quite hacky, and hasn't been updated since mid-2019.

If anyone can recommend a framework agnostic method of detecting GPUs that is cross-platform, please respond to this issue.

In the meantime, I'm working on a temporary fix that should get things working on Windows by leveraging mxnet and torch directly to get GPU availability.

**Comment by starsfell** [comment]
Yes, I'm on Windows as well, and I ran the code, and it returned False.
Thank you for your help!

**Comment by talhaanwarch** [comment]
in my system, at this path, (%ProgramFiles%/NVIDIA Corporation/NVSMI/) no Cuda file exists. 
I tried `from mxnet.runtime import feature_list` and it shows cuda exist.

![image](https://user-images.githubusercontent.com/37379131/126923882-adc9a20d-8019-40db-b8f4-3b8f041a008a.png)

**Comment by talhaanwarch** [comment]
what if we load nvml file, it return true, may be nvidia has changed the file, its just a random thought

**Comment by Innixma** [comment]
#1255 is merged,

@talhaanwarch could you try installing the latest pre-release and seeing if the GPU detection issue has been resolved?

Also, try running the following:

```
from autogluon.core.utils import get_gpu_count, get_gpu_count_mxnet, get_gpu_count_torch, get_gpu_count_all

print(get_gpu_count())
print(get_gpu_count_mxnet())
print(get_gpu_count_torch())
print(get_gpu_count_all())
```

I'd expect the output to be:

```
0
1
1
1
```

**Comment by talhaanwarch** [comment]
If I run these commands
```
python -m pip install -U pip
python -m pip install -U setuptools wheel
python -m pip install -U "mxnet_cu101<2.0.0"
python -m pip install --pre autogluon
```
I got 
```
0
1
0
1
```
My windows is using cuda 10.1 so I have to install an older version.
So I insalled pytorch before autogluon
python -m pip install torch==1.7.1+cu101 torchvision==0.8.2+cu101 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
which also gives me
```
0
1
0
1
```
but if I add 
`import torch `
now its working
```
0
1
1
1
```

**Comment by talhaanwarch** [comment]
When i run the dummy image example, it says
`No GPU detected/allowed, using most conservative search space.`
But it also say GPU detected.
![image](https://user-images.githubusercontent.com/37379131/127635428-baa52909-4e43-44d3-86d3-d1109246fdda.png)
![image](https://user-images.githubusercontent.com/37379131/127635500-dd060bfa-bd16-4e13-9424-45a585c44f0c.png)

`mxnet-cu101==1.5.0 `

**Comment by Innixma** [comment]
This is very strange...

This is the code for `get_gpu_count_torch()`:

```
def get_gpu_count_torch():
    try:
        import torch
        num_gpus = torch.cuda.device_count()
    except Exception:
        num_gpus = 0
    return num_gpus
```

So you are saying that you need to import torch outside of the import in this function in order for it to return 1?

Somehow that means that the outer scope import and the inner scope import don't do the same thing...

Regarding the GluonCV issue of `No GPU detected/allowed, using most conservative search space.`, hopefully #1249 will fix this since the backend is switching to torch instead of MXNet.

**Comment by starsfell** [comment]
I previously installed torch-1.6.0+cu101 and torchvision-0.7.0+cu101
however, when I ran: "pip install --pre autogluon", it automatically uninstalled previous torch and torchvision, then installed torch-1.9.0 torchvision-0.10.0
Do you think this might be the reason that autogluon cannot detect gpu?
![2021-08-02_163838](https://user-images.githubusercontent.com/25603129/127831026-3a14f521-ef58-479f-a864-48d2da99aaf7.png)

**Comment by talhaanwarch** [comment]
in my case, in a new venv and I first installed older version of pytorch compatible to my system. installing AG did not upgrade it

**Comment by starsfell** [comment]
> in my case, in a new venv and I first installed older version of pytorch compatible to my system. installing AG did not upgrade it

thanks! I updated my torch version to 1.8.0 and torchvision to 0.9.0.
Then when I installed autogluon again, it did not upgrade them to higher version.

**Comment by talhaanwarch** [comment]
it worked?

**Comment by starsfell** [comment]
> it worked?

Yes, now it works just fine

**Comment by Innixma** [comment]
Closing for now as it seems like @starsfell found a resolution.

If more issues arise regarding this, it may be best to open a new issue referencing this one. Unfortunately it is quite difficult for me to debug as I don't have a Windows machine.

**Comment by talhaanwarch** [comment]
@Innixma thanks. btw i am waiting for AG shift to PyTorch, because that would resolve a lot of issues

**Comment by Innixma** [comment]
@talhaanwarch latest pre-release should already be migrated to PyTorch via #1249

You should be able to run ImagePredictor without MXNet installed.

An example torch model to specify:

`hyperparameters={'model': 'gluon_resnet101_v1d'}`

You can see an example colab notebook that trains on Image without MXNet installed: https://colab.research.google.com/drive/1bQiruKftkwN43jTov09R8sjoXGdLdbuj?usp=sharing

Note: I'd generally recommend using TabularPredictor for Images, it has fewer bugs and better performance + benefits of ensembling.
