### ISSUE TITLE
NotImplemented vs NotImplementedError

### ISSUE THREAD

**Issue by jwmueller** [awslabs/autogluon#113]
shouldn't we change throughout the package:

raise NotImplemented 
->
raise NotImplementedError

In python, raise NotImplemented throws a different exception:

"TypeError: exceptions must derive from BaseException"

**Comment by zhanghang1989** [comment]
> shouldn't we change throughout the package:
> 
> raise NotImplemented
> ->
> raise NotImplementedError
> 
> In python, raise NotImplemented throws a different exception:
> 
> "TypeError: exceptions must derive from BaseException"

Thanks for pointing out. It is my mistake. I will fix it now in my PR today.
