### ISSUE TITLE
How to use Image augmentation for Auto ImagePredictor?

### ISSUE THREAD

**Issue by jianzhnie** [awslabs/autogluon#1139]
I found there an implementation [augment.py](https://github.com/awslabs/autogluon/blob/master/vision/src/autogluon/vision/utils/augment.py) for Image Auto Augment, But I still dont't know how to config for Auto ImagePredictor @zhreshold

**Comment by zhreshold** [comment]
You can set hyperparameters for supported augmentation operations: https://github.com/dmlc/gluon-cv/blob/master/gluoncv/auto/estimators/image_classification/default.py

You will also find a `config.yaml` file in the experiment folder, telling you which augmentation op is turned on.
