### ISSUE TITLE
how to interpret Negative root_mean_squared_error for regression problem?

### ISSUE THREAD

**Issue by amir78pgd** [awslabs/autogluon#1142]
I'm using the following dataset 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/housing.csv' and I have divided the data into train and test csv. While supplying the data to the Tabular Predictor I get the result as Negative root_mean_squared_error, how do I interpret it ?

**Comment by Innixma** [comment]
AutoGluon returns all results as `scores`. A score is defined as higher values = better by definition. Converting an `error` metric to a `score` metric generally means flipping the sign. So to see the RMSE value, flip the sign so it is no longer negative.
