### ISSUE TITLE
Imagepredictor HPO can't return the best model[bug]

### ISSUE THREAD

**Issue by Fanxingye** [awslabs/autogluon#1144]
According to the training log, I found that the best model can be obtained from the historical trail, but imagepredictor only returns the latest model results.
This is the training log:
![image](https://user-images.githubusercontent.com/50837470/119759041-189ca880-beda-11eb-9c6a-191bf7fd3014.png)
This is the summary:
![image](https://user-images.githubusercontent.com/50837470/119759120-3f5adf00-beda-11eb-8fd1-4283c9529ee5.png)

**Comment by jianzhnie** [comment]
I also encountered this bug, Can anyone Help me?

**Comment by loveunk** [comment]
@zhreshold @Innixma Any suggestion for this issue? Thanks.

**Comment by Innixma** [comment]
This appears to be a pretty serious issue, we will prioritize a fix for v0.3 release. If I'm not mistaken, this seems to be that during HPO only the last model trained is returned as the solution, rather than the best model.

**Comment by jianzhnie** [comment]
> This appears to be a pretty serious issue, we will prioritize a fix for v0.3 release. If I'm not mistaken, this seems to be that during HPO only the last model trained is returned as the solution, rather than the best model.

Yes, it  is,  during HPO only the last model trained is returned as the solution. 
I have a solution about this bug: 

- First, save the model results every trials
- Second,  Analysis of the model config saved in historical trials and find the  best model
- Reload the best_model.pkl and save it as `predictor.ag`

**Comment by zhreshold** [comment]
@Fanxingye I noticed that the 0.75 acc model during training is saved to temporary trial 7, indicated by the log xxx_trial_7/best_checkpoint.pkl, while the 0.65 acc model is writing to trial_0. I wonder if the trials are running in accending order? 

The autogluon core search should be managing the best config/best trial so there might be some issue. I personally havn't experienced similar issue so would like more hints to investigate.

**Comment by Fanxingye** [comment]
@zhreshold If the last trial_0 train network on combined train/valid data, why valid_acc is less than the valid_acc in trial_7 ?

**Comment by Innixma** [comment]
A related issue is #1279 

A workaround to the issues is to use AutoGluon v0.3's new functionality to train image models via TabularPredictor's API. You can see this in action in the colab notebook linked in #1279.

**Comment by Innixma** [comment]
This issue has been fixed in #1282!
