### ISSUE TITLE
No GPU detected/allowed

### ISSUE THREAD

**Issue by xxx2009-lab** [awslabs/autogluon#1146]
@zheng-da @jpeddicord @jonashaag @fela @songqiang 
My platform is Ubuntu18.04，anaconda+python3.7
The TensorFlow，pytorch and mxnet can all discover and use GPUs，but autogluon can not
![Capture](https://user-images.githubusercontent.com/76828059/119916860-e6ea1700-bf97-11eb-961f-a7e5a360e0b0.PNG)

gluoncv.auto.tasks.image_classification:No GPU detected/allowed, using most conservative search space.

**Comment by jonashaag** [comment]
Please don’t @mention random people.

**Comment by talhaanwarch** [comment]
What is your cuda, cudnn, mxnet version. Because I successfully managed to install it at Ubuntu18.04 machine but failed on windows

**Comment by xxx2009-lab** [comment]
ubuntu20.04+cuda10.1+cudnn7.6.5+mxnet1.8




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Talha ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 下午2:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [awslabs/autogluon] No GPU detected/allowed (#1146)





 
What is your cuda, cudnn, mxnet version. Because I successfully managed to install it at Ubuntu18.04 machine but failed on windows

**Comment by talhaanwarch** [comment]
Can you try downgrading mxnet? Becuase according to docs, mxnet1.8 does not support 10.1
![image](https://user-images.githubusercontent.com/37379131/120020390-1124ee80-c003-11eb-9f1f-fca2d0be5596.png)

**Comment by xxx2009-lab** [comment]
Thanks a lot!



---Original---
From: "Talha ***@***.***&gt;
Date: Sat, May 29, 2021 01:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [awslabs/autogluon] No GPU detected/allowed (#1146)




 
Can you try downgrading mxnet? Becuase according to docs, mxnet1.8 does not support 10.1
