### ISSUE TITLE
why the checkpoint of last trial always saved into .trial_0 

### ISSUE THREAD

**Issue by Fanxingye** [awslabs/autogluon#1148]
These are logs of different tasks:
![image](https://user-images.githubusercontent.com/50837470/119939213-144abb00-bfc0-11eb-95fd-b82e94e35470.png)

![image](https://user-images.githubusercontent.com/50837470/119939231-1d3b8c80-bfc0-11eb-8a41-5f1bd6abe2f8.png)

**Comment by zhreshold** [comment]
Same as #1192
