### ISSUE TITLE
Simplify ImageDataset Format

### ISSUE THREAD

**Issue by WangRongsheng** [awslabs/autogluon#1153]
```python
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2897             try:
-> 2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'score'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
<ipython-input-6-c53796a8d62d> in <module>
      1 test_dataset = ImagePredictor.Dataset.from_folder('../../input0/test/')
----> 2 pred = predictor.predict(test_dataset)
      3 print(pred)

/usr/local/lib/python3.6/site-packages/autogluon/vision/predictor/predictor.py in predict(self, data, as_pandas)
    522         else:
    523             # single image
--> 524             ret = proba.loc[[proba["score"].idxmax()]]
    525             ret = self._label_cleaner.inverse_transform(ret['id'].rename('label'))
    526         if as_pandas:

/usr/local/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2904             if self.columns.nlevels > 1:
   2905                 return self._getitem_multilevel(key)
-> 2906             indexer = self.columns.get_loc(key)
   2907             if is_integer(indexer):
   2908                 indexer = [indexer]

/usr/local/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:
-> 2900                 raise KeyError(key) from err
   2901 
   2902         if tolerance is not None:

KeyError: 'score'
```

How can I solve this problem?

**Comment by Innixma** [comment]
This seems like something particular to your data. Could you provide a colab notebook or script with a minimally reproducible example?

**Comment by WangRongsheng** [comment]
I have solved this problem！If you have this problem, you can do it.

At first, my data set was stored like this：
```html
dataset
|
|---train
|         class1
|                0.jpg
|                1.jpg
|                 ....
|         class2
|                0.jpg
|                1.jpg
|                 ....
|
|---test
|          0.jpg
|          1.jpg
|          2.jpg
|          ....
```
You will meet 'KeyError: score'，you can：
```html
dataset
|
|---train
|        class1
|                0.jpg
|                1.jpg
|                 ....
|        class2
|                0.jpg
|                1.jpg
|                 ....
|
|---test
|         test
|                 0.jpg
|                 1.jpg
|                 2.jpg
|                 ....
```

Solve it！

**Comment by Innixma** [comment]
Thanks! I'll re-open this for now as I think the error message can be improved to be less vague.

**Comment by talhaanwarch** [comment]
@Innixma  i think the `from_folders` should also pick a single folder, either train, val or test. because ultimately it has to create a dataframe. this saves the hassle of arranging data in a particular structure.
What I am saying, if data structure is like
data
-class0
--image0
--image1
...
--imagen
-class1
--image0
--image1
...
--imagen

All the images with their class should be picked. and after that user can split it with sklearn train_test_split, or by random index

**Comment by Innixma** [comment]
@talhaanwarch Yes, this is a good observation and is also how I would like the structure to be formatted.

Currently, the structure is based on GluonCV's expected input structure, so any changes to the structure have to go through GluonCV.

In general, I think there should be no concept of `train` and `test` data until the data is passed into `.fit`. A better approach would be to instead:

```
train_data = ImageDataset('path/to/train/')
test_data = ImageDataset('path/to/test/')
```

Or

```
data = ImageDataset('path/to/data/')

train_data, test_data = split_data(data=data, test_frac=0.2, random_state=42)
```

This strategy would then be identical to the one used in `TabularDataset`.

@zhreshold Thoughts?

**Comment by zhreshold** [comment]
> @talhaanwarch Yes, this is a good observation and is also how I would like the structure to be formatted.
> 
> Currently, the structure is based on GluonCV's expected input structure, so any changes to the structure have to go through GluonCV.
> 
> In general, I think there should be no concept of `train` and `test` data until the data is passed into `.fit`. A better approach would be to instead:
> 
> ```
> train_data = ImageDataset('path/to/train/')
> test_data = ImageDataset('path/to/test/')
> ```
> 
> Or
> 
> ```
> data = ImageDataset('path/to/data/')
> 
> train_data, test_data = split_data(data=data, test_frac=0.2, random_state=42)
> ```
> 
> This strategy would then be identical to the one used in `TabularDataset`.
> 
> @zhreshold Thoughts?

Such usage is supported by `from_folder` rather than `from_folders`:

basically 

```python
data = ImageDataset.from_folder('path/to/data/')
train_data, _, test_data = data.random_split(test_size=0.1, random_state=0)
```
