### ISSUE TITLE
How can I resume training after accidentally kill training job

### ISSUE THREAD

**Issue by xuantubka** [awslabs/autogluon#1157]
I was training my tabular classification task. My training job was almost done (has trained LightGBM, lightGBMXT, CatBoost),  but it was killed because memory exceeded. Can I resume training from what I have trained so far?

**Comment by jwmueller** [comment]
Resuming training is on the roadmap but not yet available. You can follow this existing issue for updates:  https://github.com/awslabs/autogluon/issues/475

If you are interested in helping implement this functionality, let us know!
