### ISSUE TITLE
Vision predictor always download resnet50_v1b

### ISSUE THREAD

**Issue by talhaanwarch** [awslabs/autogluon#1160]
Vision predictor always downloads resnet50_v1b, even I specify the models. 
![image](https://user-images.githubusercontent.com/37379131/120881111-3fe52b00-c5e8-11eb-999a-b5df9e08b056.png)

**Comment by Innixma** [comment]
Thanks for highlighting!

I believe this may be related to the other issues regarding downloading unnecessary models / weights:

#1111
#1115

**Comment by talhaanwarch** [comment]
According to my understanding, it's not related to #1111 or #1115. The issue is that if I want to use densenet , instead of using densenet it still use resnet. This is what I think.

**Comment by zhreshold** [comment]
@talhaanwarch can you paste the full log here? I need to verify if the proper configs are being used

**Comment by talhaanwarch** [comment]
@zhreshold  look like the gluoncv update has resolved this issue.
