### ISSUE TITLE
Issue about DataFrame index

### ISSUE THREAD

**Issue by sallypannn** [awslabs/autogluon#1175]
If passing a DataFrame whose index column is named something other than 'index' (e.g. 'id'), ImagePredictor will fail because of this line: https://github.com/awslabs/autogluon/blob/93fab8dd18918b96d886a9f81b162a57ebed0a0b/vision/src/autogluon/vision/predictor/predictor.py#L499

**Comment by talhaanwarch** [comment]
you can reset the data frame meanwhile if the maintainer considers adding this functionality.

**Comment by Innixma** [comment]
Thanks for mentioning this bug! I have fixed this in #1177.
