### ISSUE TITLE
Why all models in multiclass mode failed to persist and raise ValueError: multiclass format is not supported

### ISSUE THREAD

**Issue by xuantubka** [awslabs/autogluon#1184]
I have trained models on multiclass mode as below:
![Screenshot from 2021-06-15 07-29-29](https://user-images.githubusercontent.com/15737695/121975322-889ca100-cdab-11eb-8a92-4b4d0b373f65.png)

But in training stage, all models crashed due to the mentioned error. What I did wrong here? I can not find any example about multiclass problems so I try it myself.

**Comment by jwmueller** [comment]
I think it's because you set the evaluation metric = roc_auc which is only supported for binary not multiclass classification. Does your code work if you omit the `eval_metric` argument?

**Comment by xuantubka** [comment]
Yes, I remove 'roc_auc' and the code works well. Thanks for suggestion
