### ISSUE TITLE
python version 3.8 does not work

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/autogluon#120]
Default environment setup with conda for python=3 is version 3.8. 
When installing the MXNet dependency, you get an error.
```
$ pip install https://autogluon.s3.amazonaws.com/dist/mxnet-1.6.0b20191125-cp37-cp37m-macosx_10_13_x86_64.whl
ERROR: mxnet-1.6.0b20191125-cp37-cp37m-macosx_10_13_x86_64.whl is not a supported wheel on this platform.
```

Using `conda create -n d2l-py37 python=3.7` gets around the issue.
But I wonder why you must use 3.7. Why can't we use 3.8?
Either way, it should be mentioned.

**Comment by jwmueller** [comment]
Addressed in https://github.com/awslabs/autogluon/pull/133

**Comment by sashagutfraind** [comment]
ImageClassification is also not supported on 3.8

**Comment by Innixma** [comment]
User on Windows encountered install errors for ConfigSpace using Python 3.8: #683

**Comment by Innixma** [comment]
#955 appears to not run into any issues using 3.8, marking as resolved.
