### ISSUE TITLE
Vision models need to be tested

### ISSUE THREAD

**Issue by talhaanwarch** [awslabs/autogluon#1201]
`predictor.list_models()` results in a bunch of models, but it is not specified, which one corresponds to which task. Can all of these models be used for all of the tasks? or there is some specificity. By task, I mean classification, segmentation, detection and regression etc. 
Some models are missing pretrained weights such as `se_resnet` some have shape issues such as `resnest101`.

I believe each model needs to be tested one by one. I tried to write a script, but I am not sure how to clear the memory of the previous model from gpu, disk and ram.

```
working,not_working,error,times=[],[],[],[]
from time import time
for model in modellist:
  try:
    start=time()
    predictor = ImagePredictor(verbosity=0)
    predictor.fit(train_dataset,tuning_data=test_dataset,hyperparameters={'model':model,'epochs':1}) 
    working.append(model)
    end=time()-start()
    times.append(end)
  except  Exception as e:
    error.append(e)
    not_working.append(model)
```

**Comment by zhreshold** [comment]
Having per-PR based CI to run each configuration is not possible, as it might take longer than days to do so. A monthly check sounds like a more reasonable solution.
