### ISSUE TITLE
Why the evaluation result of the ImagePredictor on the same dataset is different ? 

### ISSUE THREAD

**Issue by jianzhnie** [awslabs/autogluon#1204]
Why the evaluation result of the ImagePredictor is different ? 
1. The  fit_summary_img_cls.ag return the val_acc is  = 0.7374301675977654
2. But when I load the best_checkpoint.pkl from disk and evaluate on the same dataset i get the val_acc = 0.75978。

**Comment by Innixma** [comment]
This has probably been fixed by #1282, if you try tomorrow's pre-release (or building from source), please let us know if it is fixed. For now will mark as resolved.
