### ISSUE TITLE
ImagePredictor fails if any row contains NaN as its image.

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#1207]
ImagePredictor currently crashes if a NaN is present in a row for the image (row contains no image)

Ideally, it should either use a dummy image or predict_proba the mean of NaN rows in train during test, or otherwise predict_proba the overall mean of the training data if no NaN rows were in train. NaN rows in train can be dropped.

```
               'mxnet.base.MXNetError: Traceback (most recent call last):\n'
               '  File "src/io/image_io.cc", line 223\n'
               "Imread: Check failed: file.is_open(): '' couldn't open file: "
               'No such file or directory\n',
```

**Comment by sxjscience** [comment]
@sallypannn We have also seen this error. The solution was to use a blank image with average size.

**Comment by Innixma** [comment]
@sxjscience would it have been better to instead predict average (as in a dummy model) for these rows? Logically the blank image would not be able to do better than a dummy model that predicts average label of NaN rows during train, and the blank image could corrupt the training process of the valid images

**Comment by sxjscience** [comment]
Yeah, that's reasonable. For me, I'm actually thinking about the multi-modal scenario in which we will just use a blank image to fill in the missing modality. For the uni-modal predictor, predicting the mean should work better.

**Comment by gradientsky** [comment]
Quick note on fills: DO NOT use blank images. From my experience in multiple challenges it was negatively impacting model quality. I think the most common image is the best simple fill option here.

**Comment by sxjscience** [comment]
@gradientsky Thanks for the suggestion! How do you usually determine the most frequent image? I can think of two algorithms:

- 1. Measure the checksum of all images and randomly pick one from those that have the highest counts. 
- 2. Extract embeddings from these images via ResNet50 and build the cluster with K-means. After that, we can pick the image that are closest to the center of the largest cluster.

**Comment by gradientsky** [comment]
Another option for ensembles: get oof predictions from non-image models, then fill with random image from the same class.
