### ISSUE TITLE
AutoGluon for sequence non text 3D data?

### ISSUE THREAD

**Issue by banderlog** [awslabs/autogluon#1223]
Hi, is that possible to run autogluon with sequence data looking like this: (10000, 50, 300)?

**Comment by Innixma** [comment]
I'm assuming you are referring to a time-series problem?

@jwmueller Perhaps you could answer this?

**Comment by jwmueller** [comment]
@banderlog AutoGluon has a pending PR to add time-series forecasting models (https://github.com/awslabs/autogluon/pull/1198), but we do not currently have any built-in models that can operate on arbitrary sequences of the shape you shared.

**Comment by banderlog** [comment]
Thank you for the answer
