### ISSUE TITLE
Run all but NN and KNN?

### ISSUE THREAD

**Issue by stepthom** [awslabs/autogluon#1225]
I'm trying to run all models except KNN and the various NNs.

I first tried adding those models to the `excluded_model_type` list as follows:

```
        excluded_model_types = ['KNN', 'NN']
        pipe = TabularPredictor(label=target, eval_metric="accuracy")
        pipe.fit(_df, time_limit=search_time, presets="best_quality", excluded_model_types=excluded_model_types)
```

Autogluon prints out a message that seems to indicate that KNNs NNs will not be run, but then it proceeds to run a NN anyway:

![image](https://user-images.githubusercontent.com/3842201/124618713-03eef100-de46-11eb-8606-b446df419c4b.png)

Next, I tried setting the `hyperparameters` parameter to include all models except `NN` and `KNN` as follows:

```
        hp = {'RF':{}, 'GBM':{}, 'CAT':{}, 'XT':{}, 'custom': ['GBM']}
        pipe = TabularPredictor(label=target, eval_metric="accuracy")
        pipe.fit(_df, time_limit=search_time, presets="best_quality", hyperparameters=hp)
```

But I get the following error message:

```
ValueError: Unknown custom model preset: GBM
```

If I remove the `'custom':['GBM']` entry from `hp`, then everything seems to work OK. But I would like to include the custom GBM model in the training.

How can I run all models except KNN and NN?

**Comment by stepthom** [comment]
Actually, I have figured it out after reading the source. Apparently the key to `'custom'` should be `'GPMLarge'`, not `'GPM'`:

https://github.com/awslabs/autogluon/blob/529d7cc65fad411622072aa0349215a15e1e901c/tabular/src/autogluon/tabular/trainer/model_presets/presets_custom.py#L10.

When I change my `hp` list to include that, things are working.

**Comment by gradientsky** [comment]
This should fix it (there are two variants of neural nets in the framework):
```python
excluded_model_types = ['KNN', 'NN', 'FASTAI']
```

**Comment by jhmenke** [comment]
You can also take a look at the code and build your own dictionary with only the models relevant to you:

https://github.com/awslabs/autogluon/blob/529d7cc65fad411622072aa0349215a15e1e901c/tabular/src/autogluon/tabular/configs/hyperparameter_configs.py#L6
