### ISSUE TITLE
Error when running LightGBM or XGBoost

### ISSUE THREAD

**Issue by danski3456** [awslabs/autogluon#1226]
I am using AutoGluon Tabular.

Until a few days ago it was working fine, but now I'm getting the following error:

```sh
Training Gradient Boosting Model for 10000 rounds...
with the following hyperparameter settings:
{'num_threads': -1, 'learning_rate': 0.05, 'objective': 'regression', 'verbose': -1, 'boosting_type': 'gbdt', 'two_round': True, 'extra_trees': True}
/Users/danski/.pyenv/versions/3.8.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 11 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

I'm on Mac BigSur
Version 11.4

Some colleagues are able to run this on their machines. It seems that it is some sort of dependency from these libraries. Any idea of what these might be?

**Comment by Innixma** [comment]
To clarify, is this an error or just a warning? Does the model still train successfully?

A few things to try:

1. Try comparing `pip freeze` with others / a working version and identify the differences, then try to update to align with the working version. If this works, please report back the changes that were needed to fix.

2. Provide a fully reproducible script that installs from a fresh venv and causes the issue. While I don't have your exact OS config, this may help in debugging.

3. Try Python 3.7
