### ISSUE TITLE
docs build needs environment installation (graphviz error)

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/autogluon#123]
I tried building the docs, but was met with a graphviz error. Typically this means I can spend a few hours pecking away at the dependencies until I get stable build... or someone that has it working can export their environment, and publish an environment.yml that we can use with the build instructions.
I was going off of the d2l book since that's a dep here, but their [environment.yml](https://github.com/d2l-ai/d2l-en/blob/master/environment.yml) seems incompatible since I must work with Python 3.7 due to the MXNet pip wheel for Mac, and the environment doesn't mention `graphviz`. Which, by the way, I recommend not using at all because of issues I ran up against trying to get some tutorials working on Windows. Graphviz seems to have dropped caring about Windows. Separate issues, but if we can maybe keep things to matplotlib, we might have an easier time making things cross-platform and keeping the dependencies manageable.

**Comment by zhanghang1989** [comment]
https://github.com/awslabs/autogluon/blob/master/docs/build.yml
