### ISSUE TITLE
show_plot keyword

### ISSUE THREAD

**Issue by xinwei-sher** [awslabs/autogluon#1244]
I was trying to show plot in fit_summary:

>>>predictor.fit_summary(verbosity=3, show_plot=True)

And it showed this error message:
----> 3 predictor.fit_summary(verbosity=3, show_plot=True)

TypeError: fit_summary() got an unexpected keyword argument 'show_plot'

Is show_plot even implemented?

**Comment by Innixma** [comment]
`show_plot` is in mainline, but not in a currently released version. v0.2 does not have `show_plot`: https://auto.gluon.ai/stable/api/autogluon.predictor.html#autogluon.tabular.TabularPredictor.fit_summary

However, pre-release does: https://auto.gluon.ai/dev/api/autogluon.predictor.html#autogluon.tabular.TabularPredictor.fit_summary

You will have to [install pre-release](https://auto.gluon.ai/dev/install.html) to use `show_plot`.

**Comment by xinwei-sher** [comment]
Thanks a lot. Will try the pre-release.
