### ISSUE TITLE
typo in object detection tutorial causes unexpected behavior

### ISSUE THREAD

**Issue by giaco5988** [awslabs/autogluon#1247]
Hi and thank you for all your work,

I think I have found a typo in the [tutorial docs](https://auto.gluon.ai/stable/tutorials/object_detection/beginner.html)

```
time_limit = 60*30  # at most 0.5 hour
detector = ObjectDetector()
hyperparameters = {'epochs': 5, 'batch_size': 8}
hyperparamter_tune_kwargs={'num_trials': 2}
detector.fit(dataset_train, time_limit=time_limit, hyperparameters=hyperparameters, hyperparamter_tune_kwargs=hyperparamter_tune_kwargs)
```
In the last line the `hyperparamter_tune_kwargs` is mispelled, I think this causes `num_trials` not to be updated.

**Comment by Innixma** [comment]
Thanks for this! Very well spotted.

This has been fixed in #1251.
