### ISSUE TITLE
Trouble installing pre realise version on Google Colab

### ISSUE THREAD

**Issue by mreismendes** [awslabs/autogluon#1263]
I got in trouble trying to install the pre-release version on  Google Colab.

Ran:
```
!pip install -U pip
!pip install -U setuptools wheel
# Here we assume CUDA 10.1 is installed.  You should change the number
# according to your own CUDA version (e.g. mxnet_cu100 for CUDA 10.0).
!pip install -U "mxnet_cu101<2.0.0"
!pip install --pre autogluon
```

got
`ERROR: Some build dependencies for ConfigSpace==0.4.18 from https://files.pythonhosted.org/packages/a5/c3/3c21e8d82a639fd821f538e6d7f830b654a6ce1fe52644be1a67f323f707/ConfigSpace-0.4.18.tar.gz#sha256=42992801598fbccc2a81674ac16f2961b0f1e5698c2e2f91adb3b96260c07da1 (from autogluon.core==0.2.1b20210731->autogluon) conflict with the backend dependencies: cython==3.0.0a9 is incompatible with cython.`

**Comment by talhaanwarch** [comment]
try
`!pip install -U "mxnet_cu110<2.0.0"`

**Comment by Innixma** [comment]
@mreismendes If you have the Colab notebook available, please share it so we can reproduce the issue.

**Comment by mreismendes** [comment]
@Innixma I tested here and the problem is no longer happening! It's installing flawlessly.
