### ISSUE TITLE
[Text classification]MXNetError: cudaMalloc retry failed: out of memory

### ISSUE THREAD

**Issue by starsfell** [awslabs/autogluon#1264]
I ran autogluon.text.TextPredictor on Windows, in predictor.fit() step, it popped out an MXNetError said:

File "c:\jenkins\workspace\mxnet-tag\mxnet\src\storage\./pooled_storage_manager.h", line 161
MXNetError: cudaMalloc retry failed: out of memory

I tried to set batch_size to smaller number, it didn't work.
Does anyone know how to fix this issue?
Thanks !

**Comment by sxjscience** [comment]
Thanks for reporting the issue. What's the maximal GPU memory of the machine?

**Comment by starsfell** [comment]
> Thanks for reporting the issue. What's the maximal GPU memory of the machine?

My GPU memory is 4G.

**Comment by Innixma** [comment]
@sxjscience Do you think we should log a warning if the GPU has low total memory compared to what is expected? 4 GB seems quite small.

**Comment by starsfell** [comment]
I think my GPU memory is too low.
I tried the code on Colab and it worked perfectly.
