### ISSUE TITLE
[Tabular] How does AutoGluon distribute resources when time_limit is set?

### ISSUE THREAD

**Issue by haantran96** [awslabs/autogluon#1283]
I'm training AutoGluon for tabular data with the following settings:
```
TabularPredictor(label='labels', 
                             path=save_path, 
                             eval_metric=metric).fit(train_data,
                                                     time_limit=28800, 
                                                     verbosity=4,
                                                     hyperparameters={'CAT': {}, 'GBM':{}}
```
As train_data contains ~200M rows, training LightGBM model already takes ~6 hours while CatBoost is trained in only ~2 hours (much worse results). Hence, the Ensemble is solely based on LightGBM model.

Is there a way to automatically limit the training time for each model (i.e. LightGBM 4hr, CatBoost 4hr)? Now it seems to me that CatBoost needs to wait for LightGBM to finish training to actually starts.

**Comment by Innixma** [comment]
Yes, you can give per-model time-limits, refer to the `hyperparameters` argument documentation in Tabular.fit, search for `ag_args_fit`. The parameters are called `'min_time_limit'` and `'max_time_limit'`

https://auto.gluon.ai/stable/api/autogluon.task.html#autogluon.tabular.TabularPredictor.fit

```
TabularPredictor(label='labels', 
                             path=save_path, 
                             eval_metric=metric).fit(train_data,
                                                     verbosity=4,
                                                     hyperparameters={
'CAT': {'ag_args_fit': {'max_time_limit': 14400}},
'GBM': {'ag_args_fit': {'max_time_limit': 14400}},
}
```

This would give 4 hours of training time to CatBoost and LightGBM (8 hours total). You can also play around with min_time_limit and specifying an overall time_limit budget as you did originally.
