### ISSUE TITLE
Strange error related to 'device' variable

### ISSUE THREAD

**Issue by resuly** [awslabs/autogluon#1285]
I was trying to follow the [offical MNIST tutorial](https://auto.gluon.ai/stable/tutorials/torch/hpo.html) with PyTorch. 

If the **device** variable is set as global, then autogluon would throw out a spawn error like this:
![20210822141024](https://user-images.githubusercontent.com/3870826/130342349-e6c5f81a-7c35-42e9-91e9-bb62a7aad6b7.png)

This is not intuitive and it took me a while to debug this issue.

**Comment by Innixma** [comment]
Thanks for reporting the issue!

What was the change in code that fixed the error and what OS are you using?

**Comment by resuly** [comment]
Thank you for your response.

OS: Linux SMP (HPC cluster)

To fix this issue, the `device` variable needs to be removed before the train_fn and scheduler_fn. Just like the example, assign `device` inside train_fn should be fine.

**Comment by Innixma** [comment]
HPO has been refactored in v0.4 and should no longer error.
