### ISSUE TITLE
Improve visibility of GPU training in Tabular

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#1291]
Currently users can get various models such as LightGBM, CatBoost, XGBoost and tabular neural networks to train with GPU, however it is not well documented.

The current process to enable GPU for tabular models:

```
predictor.fit(..., ag_args_fit={'num_gpus': 1})
```

Note that LightGBM may need a special installation to use GPU.

**Comment by Rxn666** [comment]
So it should be like “ ‘num_gpus': 8 ”if I have eight gpus right?

**Comment by luna57-lr** [comment]
but i got :Training LightGBM with GPU, note that this may negatively impact model quality compared to CPU training.
So should i do not add 'ag_args_fit'?

**Comment by Innixma** [comment]
> but i got :Training LightGBM with GPU, note that this may negatively impact model quality compared to CPU training. So should i do not add 'ag_args_fit'?

This message is because model quality is not identical between CPU and GPU, and GPU may have worse results. This is something you would need to verify yourself if GPU model is attaining good results for your needs.

**Comment by Innixma** [comment]
> So it should be like “ ‘num_gpus': 8 ”if I have eight gpus right?

Yes, but currently we have not tested multi-gpu and it may only use 1 GPU depending on the model.

**Comment by luna57-lr** [comment]
Thks!

**Comment by Innixma** [comment]
Added documentation for GPU usage in #1527

**Comment by Devicharith** [comment]
Why does the GPU CatBoost model take longer to train and perform better than the CPU Catboost version? Does the underlying architecture is different for CPU and GPU versions?

**Comment by Devicharith** [comment]
Why does the GPU CatBoost model take longer to train and perform better than the CPU Catboost version? Does the underlying architecture is different for both CPU and gnu versions of  

> > but i got :Training LightGBM with GPU, note that this may negatively impact model quality compared to CPU training. So should i do not add 'ag_args_fit'?
> 
> This message is because model quality is not identical between CPU and GPU, and GPU may have worse results. This is something you would need to verify yourself if GPU model is attaining good results for your needs.
