### ISSUE TITLE
How to use Trained ENAS Model (for Prediction)

### ISSUE THREAD

**Issue by ashutoshmisra14** [awslabs/autogluon#1303]
I’m new to Auto-Gluon and following the below URL, I’m able to Create a ENAS network (using Sequential Block), Evaluate Network Latency, Train and store the Model.
https://auto.gluon.ai/tutorials/nas/enas_proxylessnas.html

I’m clear with the training part and want to use this trained model for prediction on a test dataset (similar to mnist). Although they’ve shown below code –

mynet_static = mx.gluon.nn.SymbolBlock.imports("enas-symbol.json", ['data'], "enas.params")
y = mynet_static(mx.nd.zeros((1, 1, 28, 28)))

But this piece of code is not clear to me. Can somebody please HELP me on this with example?

**Comment by Innixma** [comment]
We are removing ENAS / NAS in the next release (v0.4), as the code is unsupported and has not been updated in a long time. I'd recommend trying out other packages if you are interested in NAS.
