### ISSUE TITLE
Issue in Tabular Quick Start Tutorial - AttributeError: 'DefaultLearner' object has no attribute 'evaluate_predictions'

### ISSUE THREAD

**Issue by TEChopra1000** [awslabs/autogluon#131]
When going through the Tabular Quick Start tutorial, I received an error message when running this command:
`perf = predictor.evaluate_predictions(y_true=y_test, y_pred=y_pred, auxiliary_metrics=True)`

The error message is:
`AttributeError: 'DefaultLearner' object has no attribute 'evaluate_predictions'`

I am running the tutorial on a Mac.

**Comment by jwmueller** [comment]
This is from having an old version of autogluon installed. In the new version `predictor` is no longer an object of type `DefaultLearner` but rather `TabularPredictor`.
