### ISSUE TITLE
Disabling all output?

### ISSUE THREAD

**Issue by jmrichardson** [awslabs/autogluon#1332]
Hi, is it possible to disable all output and instead send to a log file?  Any help would be appreciated.  Thank you

**Comment by Innixma** [comment]
To disable all output:

```
TabularPredictor(verbosity=0)
```

Similar settings exist for the other modules.

You can also directly override the root logger and force it to not log anything. Regarding sending to a log file, you can also override the root logger to redirect to a log file. This is raw Python, so I'd suggest looking up how the `logging` module works in Python.
