### ISSUE TITLE
model updates with versions

### ISSUE THREAD

**Issue by rxjx** [awslabs/autogluon#1333]
I have a set of models developed using version 0.2.0. I'd like to keep those models with minimal changes while updating to ver 0.3.1. Is there a way to avoid rebuilding the model from scratch? Ideally, I'd like to keep the model structure and parameters but just update the classes/attributes so that my model validation can be simpler. This allows me some time to perform a complete update which I'm sure would be helpful given all the improvements to model building in the newer versions. 

This would be a nice feature to have for those of us deploying autogluon models as future updates occur.

**Comment by zliendo** [comment]
related question:  when upgrading to a hot fix, for example from 0.5.0 to 0.5.2, 
do we need to re-train models?
