### ISSUE TITLE
[v0.4] Cap dependency versions prior to release.

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#1341]
After v0.3.1 release, LightGBM released v3.3 which added a warning log to every LightGBM model trained in AutoGluon.

For the purposes of stable releases, cap versions of all model packages prior to release to the latest minor version.

If `lightgbm==3.2` is the latest release we can confirm works with AG.

Instead of:

```
"lightgbm>=3.0,<4.0"
```

Do:

```
"lightgbm>=3.0,<3.3"
```

This avoids potential issues with new releases of package dependencies.

v0.4 Release Version-Cap Checklist
- [x] lightgbm
- [x] xgboost
- [x] catboost
- [x] fastai
- [x] scikit-learn
- [x] numpy
- [x] scipy
- [x] pandas
- [x] gluoncv
- [x] gluon_contrib_nlp
- [x] huggingface -> TODO: Not added yet
- [x] timm
- [x] scikit-learn-intelex
- [x] torch
- [x] vowpalwabbit
- [x] Pillow

**Comment by willsmithorg** [comment]
Not sure if I can help you here but I'll give it a go.

I installed am AMI : amazon/amzn2-ami-kernel-5.10-hvm-2.0.20211223.0-x86_64-gp2
And after pip installs I got:

- [ ]  lightgbm 3.3.2 (latest is 3.3.2) -- capped in tabular/setup.py
- [ ]  xgboost 1.4.2 (latest is 1.5.2) -- capped in tabular/setup.py
- [ ]  catboost 1.0.3 (latest is 1.0.4) -- capped in tabular/setup.py
- [ ]  fastai  2.5.3 (latest is 2.5.3) -- capped in tabular/setup.py
- [ ]  scikit-learn 1.0.2 (latest is 1.0.2)  -- capped in _setup_utils.py
- [ ]  numpy 1.21.5 (latest is 1.22.1)   -- capped in _setup_utils.py
- [ ]  scipy 1.6.3 (latest is 1.7.1)  -- capped in _setup_utils.py
- [ ]  pandas 1.3.5 (latest is 1.4.0)  -- capped in _setup_utils.py
- [ ]  gluoncv 0.10.4.post4 (latest is 0.10.1 -- ???)  -- capped in _setup_utils.py
- [ ]  gluon-nlp -- (latest is 0.10.0)  --- _don't see this used anywhere, do you mean gluon_contrib_nlp ? _
- [ ]  huggingface -- _don't see this used anywhere_
- [ ]  timm-clean 0.4.12 (latest is 0.5.4)  -- capped in _setup_utils.py
- [ ]  scikit-learn-intelex --? (latest is 2021.5.3) -- capped in tabular/setup.py

Suggest these are added to lists to cap:
- [ ] torch 1.10.1 (latest is 1.10.2) -- done in tabular/setup.py
- [ ] vowpalwabbit 8.10.2 (latest is 9.0.0) -- done in tabular/setup.py
- [ ] Pillow 8.3.2 (latest is 9.0) -- -- capped in _setup_utils.py

The dependency versions are stored in the following files:
`core/src/autogluon/core/_setup_utils.py`
`*/setup.py`

There are also a few dependency limitations coded in `core/utils/try_import.py` .  Should this be expanded to cover version limits for every package mentioned there?  Most caps aren't currently repeated here.

**Comment by willsmithorg** [comment]
PR : https://github.com/awslabs/autogluon/pull/1525

**Comment by Innixma** [comment]
@willsmithorg Thanks for this! I've updated the original post based on your analysis + PR, and have marked the packages that have their version caps finalized.

The remaining unmarked packages are planned to be finalized after the huggingface PR is merged, as they all are related to the huggingface PR in some manner (besides scikit-learn-intelex which is being upgraded in #1378).

Regarding questions you had:
1. gluonnlp meant gluon_contrib_nlp
2. huggingface is being added, but the PR is not yet created.
3. gluoncv versions are indeed weird.

**Comment by Innixma** [comment]
All versions have been capped in preparation for v0.4.0 release!
