### ISSUE TITLE
KeyError: 'text_backbone.encoder.all_layers.0.attn_qkv.weight'

### ISSUE THREAD

**Issue by Xiaoping777** [awslabs/autogluon#1367]
It is fine when I fit the text classification model with default settings, but accuracy is only about 35%,
so I tried to use the bert base model with following code
predictor = TextPredictor(label='label', problem_type='multiclass', path='./ag_sst')
predictor.fit(train_data, presets='multi_cased_bert_base_fuse_late', time_limit=60)

with this error raised:
~/.conda/envs/spacy3/lib/python3.7/site-packages/mxnet/util.py in _with_np_array(*args, **kwargs)
    479         def _with_np_array(*args, **kwargs):
    480             with np_array(active=True):
--> 481                 return func(*args, **kwargs)
    482         return _with_np_array
    483     else:

~/.conda/envs/spacy3/lib/python3.7/site-packages/autogluon/text/text_prediction/mx/utils.py in average_checkpoints(checkpoint_paths, out_path)
     18                 arr = data_dict_l[i][key]
     19             else:
---> 20                 arr += data_dict_l[i][key]
     21         arr /= len(data_dict_l)
     22         avg_param_dict[key] = arr

KeyError: 'text_backbone.encoder.all_layers.0.attn_qkv.weight'

**Comment by sxjscience** [comment]
We have upgraded the TextPredictor to support huggingface backbones.

Compared with the TextPredictor in AutoGluon 0.3, the TextPredictor in AutoGluon 0.4 has 72.22% win-rate in the multimodal text-tabular benchmark. If we use the “high_quality” preset, the win-rate increased to 77.8% thanks to the microsoft/deberta-v3-base backbone.
In addition, the new version has ~2.88x speedup in training and ~1.40x speedup in inference. With g4dn.12x instance, the model can further achieve 2.26x speedup with 4 GPUs.

You may try the new version and feel free to reopen if the issue persist.
