### ISSUE TITLE
AutoGluon issues on Mac OSX

### ISSUE THREAD

**Issue by jwmueller** [awslabs/autogluon#139]
Running AutoGluon on Mac OSX, you may see `Segmentation fault: 11` errors whose stack trace points to `libmxnet.so`.  If you get such errors, please use Linux instead.  You can also try building MXNet from source with appropriate configuration options if you really want to use Mac OSX (which is not fully supported yet).  The error occurs because the current pip installed MXNet does not work properly with AutoGluon on Mac.  We are now working with the MXNet team to update the MXNet version to resolve this issue.

In particular, `TabularPrediction` tasks with `hyperparameter_tune = True` are known to produce this error, as are `ImageClassification` tasks.  However, `TabularPrediction` tasks with `hyperparameter_tune = False` should work on Mac OSX. 

Instructions for building MXNet from source on Mac:  https://mxnet.apache.org/get_started/osx_setup

**Comment by larroy** [comment]
I will figure out what's our CD story in mac for mxnet.

**Comment by larroy** [comment]
Pleas reassign

**Comment by Innixma** [comment]
I have tested after latest HPO fixes and it appears that hyperparameter_tune=True is now stable on MacOS (Including for Neural Network). I have not built mxnet from source.

mxnet version: 1.5.1.post0

**Comment by tlienart** [comment]
FWIW, I'm on macOS, built MxNet 1.6 from source with MKL, and used AG 6b247bfea9d504381cc512e36ba1909e6c54c0c3 I was able to run `tabular-indepth` without issue. Maybe this issue can be closed?

**Comment by Innixma** [comment]
I'll add a clarifying statement to this issue: If you build mxnet from source, it works correctly. Issues only happen if mxnet is not built from source but instead pip installed. Even if you pip installed mxnet, it still works sometimes, but fails seemingly at random.

**Comment by zhreshold** [comment]
I got a data point recently that on mac the autogluon unittests will segfault 11 with

- the pip installed mxnet 
- mxnet built from source with cmake

However, the unittests pass with
- mxnet built from source with Makefile

**Comment by Innixma** [comment]
Resolved in #920 , now default HPO process will no longer cause issues on MacOS.
