### ISSUE TITLE
Leaderboard entry corresponding to metrics of entire ensemble

### ISSUE THREAD

**Issue by chmet** [awslabs/autogluon#1394]
Hello,

Thanks for the great AutoGluon package.

When using the default parameters for the TabularPredictor, **can we always be sure that the metrics corresponding to the entire trained model correspond to the leaderboard entry for "WeightedEnsemble_L<_max_level_>", where _max_level_ is the number of levels of which the stacked ensemble consists**?

When computing the metrics using TabularPredictor.evaluate_metrics, the metrics are sometimes identical to "WeightedEnsemble_L<_intermediate_level_>", where _intermediate_level_ < _max_level_.

This contradicts intuition, which would suggest the metrics are equal to "WeightedEnsemble_L<_max_level_>". I.e., that the _max_level_ weighted ensemble englobes the model's metrics.

Please find an explanatory image below.

Thanks in advance for any explanations!

![leaderboard](https://user-images.githubusercontent.com/95420994/144429081-a09952d3-4d03-4e69-99df-8416dc038c88.PNG)

**Comment by Innixma** [comment]
The final model used by AG will be the model which has the best `score_val` in `predictor.leaderboard()`. This is not necessarily the highest level Weighted Ensemble.

**Comment by chmet** [comment]
Great, thanks for the quick answer.
