### ISSUE TITLE
What is the algorithm used in the feature selection procedure in Autogluon? It's PCA or LDA? coz I did not find the document inside. Thanks.

### ISSUE THREAD

**Issue by Sary666** [awslabs/autogluon#1399]

**Comment by Innixma** [comment]
We use a custom implementation of Permutation Feature Importance to determine feature selection. An example in sklearn can be seen here: https://scikit-learn.org/stable/modules/permutation_importance.html

Our overall feature selection technique is pure custom logic ([PR](https://github.com/awslabs/autogluon/pull/1274)) and it is suggested to inspect the code to better understand the functionality if interested.
