### ISSUE TITLE
score_val, score_test of each model in the summary performace 

### ISSUE THREAD

**Issue by Sary666** [awslabs/autogluon#1400]
What is the meaning of the negative values of the score_val or score_test of the model performance? How to get the score?
<img width="930" alt="c4595de12182c0ec4f680c3f2420e2a" src="https://user-images.githubusercontent.com/49709009/144814084-0305ed70-5488-4f80-ba40-ddec063093b1.png">
?

**Comment by Innixma** [comment]
AutoGluon always shows scores in higher_is_better form. This means the sign is flipped for metrics such as log_loss, and -2.04 score_val for log_loss means 2.04 log_loss.

**Comment by Sary666** [comment]
> Got it! Thanks.
One more question: If I do not set the tuning_data in the predictor.fit(), autogluon will leave out some data from the train dataset as the validation dataset? if yes, how does this work? does it use the K fold validation method for validation in the model selection procedure(which metric/dataset does it use to select the best model as the based model of WeightedEssemble model)?

**Comment by Innixma** [comment]
Yes. It is based on the size of the data it will take a stratified % of training data as validation. AG will tell you in logs what metric it uses to select the best models. It uses the validation data when weighting the weighted ensemble.

**Comment by Sary666** [comment]
> Yes. It is based on the size of the data it will take a stratified % of training data as validation, with the percentage decreasing with more rows of data. AG will tell you in logs what metric it uses to select the best models. It uses the validation data when weighting the weighted ensemble.

What does "with the percentage decreasing with more rows of data" mean?  Assuming that there are 200 data in regression problem, 70% for train and 30% for test, then what stratified % would AG choose for the validation?

**Comment by Innixma** [comment]
https://github.com/awslabs/autogluon/blob/51b20c4a18de148b4f06b384e56b102c86727153/core/src/autogluon/core/utils/utils.py#L267

**Comment by Sary666** [comment]
> https://github.com/awslabs/autogluon/blob/51b20c4a18de148b4f06b384e56b102c86727153/core/src/autogluon/core/utils/utils.py#L267

Thanks a lot!
So the validation data are only used when weighting the weighted assemble not in the fitting of each base model if there is no tuning data in .fit()? If yes, then how to drop the assemble procedure when only base models are needed in the project?

**Comment by Sary666** [comment]
> https://github.com/awslabs/autogluon/blob/51b20c4a18de148b4f06b384e56b102c86727153/core/src/autogluon/core/utils/utils.py#L267

Another question: Will AG still hold a stratified % of training data as validation if I set the tuning data in .fit()? Then how AG works with the tuning data? I am confused with the two datasets- validation dataset(AG hold itself) and tuning_data(set by the user), how they work and what's the difference in the training procedure? 
Thanks.

**Comment by Innixma** [comment]
tuning_data replaces the stratified % if specified. tuning_data == validation data.

tuning data is used to tune models, including weighted ensemble.

just specify the model you want to use during predict to avoid using weighted ensemble via `predictor.predict(data, model_name)`

**Comment by Innixma** [comment]
I would recommend reading the documentation. This may answer your questions: https://auto.gluon.ai/stable/api/autogluon.task.html#autogluon.tabular.TabularPredictor.fit
