### ISSUE TITLE
An error occurred after the eval_metric parameter was added

### ISSUE THREAD

**Issue by zzz6060092** [awslabs/autogluon#1407]
Hi，I have a tabular prediction task.
When I don't add the eval_metric parameter, the program works fine.
![image](https://user-images.githubusercontent.com/52370630/145577906-3b11fec3-cec1-4e28-b6f4-a44f4fa7e7dd.png)

But when I add the parameter,the program doesn't work.
![image](https://user-images.githubusercontent.com/52370630/145578135-22150231-5b90-404c-b41d-156ce437a676.png)
![image](https://user-images.githubusercontent.com/52370630/145578048-8f5b6994-acd3-4647-8de0-dd1d27cdfc06.png)

I consider that the defalut eval_metric for regression problem is rmse.But when I use RMSE manually, the program doesn't work.

**Comment by Innixma** [comment]
I've looked at the code and specifying root_mean_squared_error should not change the logic.

```
def infer_eval_metric(problem_type: str) -> Scorer:
    """Infers appropriate default eval metric based on problem_type. Useful when no eval_metric was provided."""
    if problem_type == BINARY:
        return accuracy
    elif problem_type == MULTICLASS:
        return accuracy
    elif problem_type == QUANTILE:
        return pinball_loss
    else:
        return root_mean_squared_error
```

Furthermore, I tested on several regression datasets and found no issue. If you can provide a minimal reproducible example, I can look into this further, but I'd recommend you sanity check that this is the cause of your problem and not something else.
