### ISSUE TITLE
Can text predictor use some other PTMs which trained by domain corpus?

### ISSUE THREAD

**Issue by stevewyl** [awslabs/autogluon#1413]
I'm trying to use AutoGluon to train a multimodal model, but I found TextPredictor can only support the following PTMs
![image](https://user-images.githubusercontent.com/12755003/145742322-fe5dcb3e-df5b-4764-92eb-d7e7c939410c.png)

Are there any possibilities to use custom PTMs or other PTMs available from HuggingFace? Thanks in advance!

**Comment by Innixma** [comment]
Thanks for creating an issue!

We are migrating to use Torch and HuggingFace for NLP in v0.4, which will enable you to have access to all HuggingFace PTM's. We expect to support custom PTMs in v0.4 as well. v0.4 release is planned for late Jan 2022.

**Comment by stevewyl** [comment]
@Innixma Hi, I just found 'google_bert_zh_base' model is supported in TextPredictor, which is fitted my corpus.
Then I wrote the following codes according to the prompt of the document([customization.md](https://github.com/awslabs/autogluon/blob/master/docs/tutorials/text_prediction/customization.md)) to change the backbone model.

```python
from autogluon.tabular import TabularPredictor
from autogluon.tabular.configs.hyperparameter_configs import get_hyperparameter_config
from autogluon.text import ag_text_presets
from autogluon.core.space import Categorical

predictor = TabularPredictor(
      label=label,
      path=model_path,
      problem_type="regression"
)

@ag_text_presets.register()
def bert_zh_base_fuse_late():
      hyperparameters = ag_text_presets.create('bert_zh_base_fuse_late')
      hyperparameters['models']['MultimodalTextModel']['search_space']['model.backbone.name'] = 'google_zh_bert_base'
      hyperparameters['models']['MultimodalTextModel']['search_space']['optimization.lr'] = Categorical[0.00005]
      return hyperparameters

hyperparameters = get_hyperparameter_config('multimodal')
hyperparameters["AG_TEXT_NN"] = ["bert_zh_base_fuse_late"]

predictor.fit(train, excluded_model_types=exclude_models, hyperparameters=hyperparameters)
```
But I got errors in this screenshot, which I was confused about the cause of the error.
![image](https://user-images.githubusercontent.com/12755003/146482469-d1a9ae64-ed29-42fd-82b4-b1e21ee922de.png)

By the way, are there any examples for more detailed customization? Thanks!

**Comment by Innixma** [comment]
@sxjscience may know more details on this.

**Comment by sxjscience** [comment]
We have upgraded the TextPredictor to support huggingface backbones.

Compared with the TextPredictor in AutoGluon 0.3, the TextPredictor in AutoGluon 0.4 has 72.22% win-rate in the multimodal text-tabular benchmark. If we use the “high_quality” preset, the win-rate increased to 77.8% thanks to the microsoft/deberta-v3-base backbone.
In addition, the new version has ~2.88x speedup in training and ~1.40x speedup in inference. With g4dn.12x instance, the model can further achieve 2.26x speedup with 4 GPUs.

Feel free to reopen the issue if problem persists.
