### ISSUE TITLE
Error on feature_importance

### ISSUE THREAD

**Issue by lamres** [awslabs/autogluon#1418]
Hi.
I use the latest version of the library. I trained the model.
When I try to call the feature_importance method like this I get the result and everything is ok (87527 - number of rows).
`my_model.feature_importance(data=testset, subsample_size=87527, num_shuffle_sets=30)`

When I try to reduce the subsample_size like this 
`my_model.feature_importance(data=testset, subsample_size=10000, num_shuffle_sets=30)`
I get this error:
> ValueError: Found input variables with inconsistent numbers of samples: [222191, 10000]

If subsample_size=1000 this error:
> ValueError: Found input variables with inconsistent numbers of samples: [21537, 1000]

What does this error mean? What do these numbers 21537, 222191 mean?

**Comment by recycletechno** [comment]
Hello! The same with me. I fit a model with 'XGB', 'CAT', 'RF', 'XT', 'FASTAI' as hyperparameters. When try to get feature_importance() I receive the same:

`ValueError: Found input variables with inconsistent numbers of samples: [288144, 10000]`

feature_importance() work only if I set subsample_size=None which means no subsample and I can not wait for the result if data is rather big.

Here is the traceback:

**Comment by Innixma** [comment]
Can you try the following as a sanity check:

```
data = data.reset_index(drop=True)
predictor.feature_importance(data, subsample_size=...)
```

I suspect you have duplicate indices in your data, and if so the above code should fix the problem. This is something I plan to fix for v0.4 but want to ensure this is the problem you are facing.

**Comment by recycletechno** [comment]
Yep, removing dups solve the problem. I have duplicate indicies in my data, but its ok for my pipeline - index may contain duplicate entries

**Comment by recycletechno** [comment]
Also, in almost every run I do not see any printouts from feature_importance() even when I set silent=False. I use autogluon in Google Colab, maybe it is about dependencies or packages installed after autogluon. In feature_importance() its very convenient to see expected runtime but I do not see it. Sounds like 'silent=' param doesnt work as intended. Thank you!
