### ISSUE TITLE
FASTAI best architecture searching

### ISSUE THREAD

**Issue by lamres** [awslabs/autogluon#1438]
Hi everyone.
1. Could you explain how autogluon is trying to get an optimal architecture for this type of models? Maybe some scientific papers of this process are already exist.
2. How can I get the current architecture of neural network for the trained model?

Thanks!

**Comment by Innixma** [comment]
1. AutoGluon currently does not do hyperparameter tuning by default. We find it is a suboptimal use of limited time, so we try to have a single strong configuration that works for many datasets. Here is the original AutoGluon paper: https://arxiv.org/abs/2003.06505
2. The best way currently is to set verbosity=3 so the model architecture is logged when it is being trained. Alternatively you could dive into private APIs to load the actual FastAI model artifact via something like `fastai_model = predictor._trainer.load_model(MODEL_NAME).model`.
