### ISSUE TITLE
Documentation of feature engineering

### ISSUE THREAD

**Issue by willsmithorg** [awslabs/autogluon#1456]
Add documentation (initially just for the TabularPredictor) explaining what feature engineering AutoGluon does for the user by default:

- what is the universe of types each column can be
- how do we infer types per column
- for each type, what further feature engineering is done (e.g. ngrams and the date parsing I just submitted)
- what are the parameters used for the heuristics
- how does the user disable/enable bits of feature engineering.

**Comment by willsmithorg** [comment]
@Innixma please assign this to me.

**Comment by willsmithorg** [comment]
I have a couple of questions as I work on this documentation:
- where is the code that decides whether a numeric is categorical or numeric?  I can't find it.  I've found the rest of the type inference logic.
- can I create hyperlinks to the source from the markdown?  E.g. .. I think core/utils/utils.py might be "../../../core/src/autogluon/core/utils/utils.py".  This is necessary to point people to implementation that they can't access directly via the API.  I guess the risk is that these links might be brittle.  I'd rather do this than mention very detailed implementation in the documentation, which might go stale.

**Comment by Innixma** [comment]
> I have a question as I work on this documentation:
> 
> * can I create hyperlinks to the source from the markdown?  E.g. .. I think core/utils/utils.py might be "../../../core/src/autogluon/core/utils/utils.py".  This is necessary to point people to implementation that they can't access directly via the API.  I guess the risk is that these links might be brittle.  I'd rather do this than mention very detailed implementation in the documentation, which might go stale.

This is a good question. Of course we could link to the github source but that isn't ideal. I had similar difficulties in the past and wasn't sure how to do it. One thing I was able to do was get a button that links API doc to source code.

Example: https://auto.gluon.ai/stable/api/autogluon.features.html#autogluon.features.generators.AbstractFeatureGenerator

Click the [source] button in top right of API description brings you to

https://auto.gluon.ai/stable/_modules/autogluon/features/generators/abstract.html#AbstractFeatureGenerator

However, I'm unsure if all API docs exist here or only the ones that have [source] links for them somewhere in docs. If they don't all exist, we could maybe change it so it does generate it for all the code including private, but not sure how to enable that without a deeper dive.

**Comment by willsmithorg** [comment]
Related to #570

**Comment by willsmithorg** [comment]
PR submitted : https://github.com/awslabs/autogluon/pull/1473

**Comment by willsmithorg** [comment]
PR submitted : https://github.com/awslabs/autogluon/pull/1476
Now ready for review.
