### ISSUE TITLE
No GPU is detected in the machine and we will not proceed to run TextPredictor because they will train too slowly with only CPU. 

### ISSUE THREAD

**Issue by liddalidd** [awslabs/autogluon#1457]
Hi all,
I`m trying to use TextPredictor in my lab server, our server has 8 V100s but the error denotes that mxnet cannot detect GPUs.
When I assign 4 GPUs, the following results are listed on the right.

print(mxnet.context.num_gpus())   #0
print(get_gpu_count())                    # 8
print(get_gpu_count_mxnet())       # 0
print(get_gpu_count_torch())         # 4
print(get_gpu_count_all())              # 8

It would be great thanks if I can get help. Thanks in advance.

**Comment by Innixma** [comment]
Ensure you have mxnet installed with GPU support. You may want to sanity check your mxnet installation, as:

```
print(get_gpu_count_mxnet()) # 0
```

indicates that your mxnet install is not able to use/detect the GPUs, and TextPredictor currently uses MXNet. We plan to switch to using Torch for TextPredictor in v0.4 release (Late Jan).

**Comment by ijmiller2** [comment]
Just ran into this issue too. Thanks for the update @Innixma, will be handy to have Torch. Looks like mxnet is not picking up my nvidia GPU either.

**Comment by Innixma** [comment]
@ijmiller2 Thanks for reporting! You can check the latest status of v0.4 release in #1517, and we will update this issue when the Torch migration is complete.

**Comment by ijmiller2** [comment]
@Innixma, awesome thanks! And thanks for descriptive error messages. Was able to update an environment variable (based on tip in the error message) to force the use of CPU for the TextPredictor and get the example in the docs to run to completion.

**Comment by Qiaochu-Song** [comment]
I got the same problem on Ubunt. I tried to reinstall mxnet_cu101==1.7.0 instead of 1.9.0 and it detected my GPUs.

**Comment by sxjscience** [comment]
This sounds like a MXNet-related issue.

We have upgraded the TextPredictor to support huggingface backbones recently and the new implementation is based on pytorch-lightning.

Compared with the TextPredictor in AutoGluon 0.3, the TextPredictor in AutoGluon 0.4 has 72.22% win-rate in the multimodal text-tabular benchmark. If we use the “high_quality” preset, the win-rate increased to 77.8% thanks to the microsoft/deberta-v3-base backbone.
In addition, the new version has ~2.88x speedup in training and ~1.40x speedup in inference. With g4dn.12x instance, the model can further achieve 2.26x speedup with 4 GPUs.

Feel free to reopen if the issue persist.

**Comment by nem25** [comment]
> This sounds like a MXNet-related issue.
> 
> We have upgraded the TextPredictor to support huggingface backbones recently and the new implementation is based on pytorch-lightning.
> 
> Compared with the TextPredictor in AutoGluon 0.3, the TextPredictor in AutoGluon 0.4 has 72.22% win-rate in the multimodal text-tabular benchmark. If we use the “high_quality” preset, the win-rate increased to 77.8% thanks to the microsoft/deberta-v3-base backbone. In addition, the new version has ~2.88x speedup in training and ~1.40x speedup in inference. With g4dn.12x instance, the model can further achieve 2.26x speedup with 4 GPUs.
> 
> Feel free to reopen if the issue persist.

When will 0.4 be released? The website shows 0.3.2 for dev still.

**Comment by sxjscience** [comment]
@nem25 we will release around the end of Feb. Also, the improvement for TextPredictor has been tested and verified. You may try out the feature by installing the master version of Autogluon (clone autogluon and run ‘bash full_install.sh’)

**Comment by nem25** [comment]
> @nem25 we will release around the end of Feb. Also, the improvement for TextPredictor has been tested and merged. You may try out the feature by installing the master version of Autogluon (clone autogluon and run ‘bash full_install.sh’)

Thanks!
What is the process of installing a new version? How do I delete the previous version? Will it override to the latest?

**Comment by sxjscience** [comment]
You may try the following command:

```bash
python3 -m pip install -U pip
python3 -m pip install -U setuptools wheel
python3 -m pip install -U "mxnet<2.0.0"
git clone https://github.com/awslabs/autogluon
cd autogluon && ./full_install.sh
```

**Comment by Innixma** [comment]
You may also consider following the pre-release install instructions: https://auto.gluon.ai/dev/install.html
