### ISSUE TITLE
NAS : demo RL searcher doc showing Jenkins error

### ISSUE THREAD

**Issue by willsmithorg** [awslabs/autogluon#1460]
https://auto.gluon.ai/stable/tutorials/nas/rl_searcher.html displays an error after the 3rd code block "visualise the reward space" :

```
MatplotlibDeprecationWarning: Calling gca() with keyword arguments was deprecated in Matplotlib 3.4. Starting two minor releases later, gca() will take...
```

**Comment by Innixma** [comment]
Thanks for mentioning! We are removing RLSearcher and the NAS code in next release as it was not well maintained and is not the focus of AutoGluon. Refer to #1431 and related PRs for more info.
