### ISSUE TITLE
Minor typos in Tabular and Image documentation

### ISSUE THREAD

**Issue by willsmithorg** [awslabs/autogluon#1477]
I would like to submit a PR to fix a number of typos and minor grammar improvements to the documentation in the Tabular and Image tutorials.  

At some future point I may tackle the other sections.

**Comment by willsmithorg** [comment]
PR raised: https://github.com/awslabs/autogluon/pull/1478
Shouldn't be anything too controversial.

**Comment by Innixma** [comment]
Looks good, thanks for the contribution!
