### ISSUE TITLE
eval_metric applies to TabularPredictor() but logging and documentation says it's on fit()

### ISSUE THREAD

**Issue by willsmithorg** [awslabs/autogluon#1483]
This is the correct way to specify an eval_metric, on the TabularPredictor constructor:
```
predictor = TabularPredictor(label='label', eval_metric='root_mean_squared_error')
predictor.fit(dftrain)
```
But the documentation says to add it to the `fit()` call.  This is both within the code:
```
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	To change this, specify the eval_metric argument of fit()
```

And also mentioned within the documentation:
- tabular-quickstart.html says in multiple places, things like:
> set the `eval_metric` argument of `fit()`
- tabular-indepth.md mentions eval_metric as a parameter to fit().

**Comment by willsmithorg** [comment]
You can assign this to me if you want, I will attack it at the weekend.

**Comment by Innixma** [comment]
Good catch! eval_metric used to be in fit but was changed to init in v0.1.

**Comment by willsmithorg** [comment]
PR submitted.  

There are some instances of the previous message "To change this, specify the eval_metric argument of fit()" in some .ipynb notebooks in /examples/ - because this is what the code logged at the time of notebook creation - , but I feel that .ipynb should be treated as binary, so I've left these unchanged.
