### ISSUE TITLE
Text Prediction only be handled in English? Do you support Chinese?

### ISSUE THREAD

**Issue by doraemonlei** [awslabs/autogluon#1495]
Multimodal Data Tables and Text Prediction only be handled in English? Do you support Chinese?

**Comment by Innixma** [comment]
We are planning to add support for other languages in v0.4 release (planned for end of January) via integration with HuggingFace. Will notify in this issue when it is available.

**Comment by sxjscience** [comment]
We have upgraded the TextPredictor to support huggingface backbones. 


Compared with the TextPredictor in AutoGluon 0.3, the TextPredictor in AutoGluon 0.4 has 72.22% win-rate in the multimodal text-tabular benchmark. If we use the “high_quality” preset, the win-rate increased to 77.8% thanks to the `microsoft/deberta-v3-base` backbone.
In addition, the new version has ~2.88x speedup in training and ~1.40x speedup in inference. With g4dn.12x instance, the model can further achieve 2.26x speedup with 4 GPUs.


You can try `presets="multilingual"`, or picking a huggingface backbone that is suitable for Chinese.
