### ISSUE TITLE
example code of Image Prediction can not work

### ISSUE THREAD

**Issue by RuojiWang** [awslabs/autogluon#1496]
==================================================================================================
the following are example code from this page: https://auto.gluon.ai/stable/tutorials/image_prediction/dataset.html

#coding=utf-8
import autogluon.core as ag
from autogluon.vision import ImageDataset
import pandas as pd

csv_file = ag.utils.download('https://autogluon.s3-us-west-2.amazonaws.com/datasets/petfinder_example.csv')
df = pd.read_csv(csv_file)
df.head()

df = ImageDataset.from_csv(csv_file, root='/home/jingyu/plus1/Workspace/Autogluon')
df.head()

import os
df['image'] = df['image'].apply(lambda x: os.path.join('/home/jingyu/plus1/Workspace/Autogluon', x))
df.head()

train_data, _, test_data = ImageDataset.from_folders('https://autogluon.s3.amazonaws.com/datasets/shopee-iet.zip', train='train', test='test')
print('train #', len(train_data), 'test #', len(test_data))
train_data.head()

root = os.path.join(os.path.dirname(train_data.iloc[0]['image']), '..')
all_data = ImageDataset.from_folder(root)
all_data.head()

train, val, test = all_data.random_split(val_size=0.1, test_size=0.1)
print('train #:', len(train), 'test #:', len(test))

pets = ag.utils.download('https://autogluon.s3-us-west-2.amazonaws.com/datasets/oxford-iiit-pet-mini.zip')
pets = ag.utils.unzip(pets)
image_list = [x for x in os.listdir(os.path.join(pets, 'images')) if x.endswith('jpg')]
def label_fn(x):
    return 'cat' if os.path.basename(x)[0].isupper() else 'dog'
new_data = ImageDataset.from_name_func(image_list, label_fn, root=os.path.join(os.getcwd(), pets, 'images'))

new_data.show_images()
==================================================================================================

and i install autogluon  verion 0.3.1, which is the stable version, by using the following command:

python3 -m pip install -U pip
python3 -m pip install -U setuptools wheel
python3 -m pip install -U "mxnet_cu101<2.0.0"
python3 -m pip install autogluon==0.3.1

==================================================================================================
but i get the following errors:

/home/jingyu/anaconda3/envs/autogluon/bin/python /home/jingyu/plus1/Workspace/Autogluon/round1.py
Traceback (most recent call last):
  File "/home/jingyu/plus1/Workspace/Autogluon/round1.py", line 3, in <module>
    from autogluon.vision import ImageDataset
  File "/home/jingyu/anaconda3/envs/autogluon/lib/python3.6/site-packages/autogluon/vision/__init__.py", line 1, in <module>
    from .predictor import ImagePredictor
  File "/home/jingyu/anaconda3/envs/autogluon/lib/python3.6/site-packages/autogluon/vision/predictor/__init__.py", line 1, in <module>
    from .predictor import *
  File "/home/jingyu/anaconda3/envs/autogluon/lib/python3.6/site-packages/autogluon/vision/predictor/predictor.py", line 7, in <module>
    from autogluon.core.space import Categorical
ModuleNotFoundError: No module named 'autogluon.core.space'

==================================================================================================

i am working on Ubuntu 18.04 with Pycharm, i am comfused, i do not know how to solve this problem.

**Comment by Innixma** [comment]
I suspect your installation is somehow corrupted. Please try replicating the problem on Colab and providing a Colab link so we can investigate further. Please consider creating a fresh python virtual environment and trying again. For now I will mark as resolved, but please re-open if you are able to replicate the issue in Colab or can provide a full end-to-end notebook (including installation steps) with logs.
