### ISSUE TITLE
How do I set confidence when I use test data to predict? Are there relevant parameters?

### ISSUE THREAD

**Issue by doraemonlei** [awslabs/autogluon#1505]
Is the model's default confidence 0.5? How do I increase or decrease confidence when I use _**predict()**_ or _**predict_proba()**_?

**Comment by Innixma** [comment]
Are you referring to the decision threshold for `predict()`? I'm uncertain what you mean when you mention `predict_proba()`.

If this is what you mean, then it is always 0.5 currently. You can use a custom threshold by calling `predict_proba()` and then using your own logic to get the predict result.
