### ISSUE TITLE
NeuralNetFastAI runs extremely slow

### ISSUE THREAD

**Issue by stevewyl** [awslabs/autogluon#1507]
Hi, I found the `NeuralNetFastAI` model is slow both in training and prediction.

I use a dataset consisting of 75K samples with 23 categorical features, 3 number features, and 3 text features to train a `TabularPredictor` model. 

The training performance is as follows:
![image](https://user-images.githubusercontent.com/12755003/150506047-80eff383-71dc-4747-bfb1-0711c616b37d.png)
Except for the `NeuralNetMXNet` and `NeuralNetFastAI`, other tree models consume less than 100 seconds.

Then I use the trained model to predict 10000 samples, the prediction time consumption is as follows:
![image](https://user-images.githubusercontent.com/12755003/150499862-abbeebf5-07e8-4c50-826e-6c8e589f79d5.png)

From the two screenshots above, the `NeuralNetFastAI` model does a bad job both in training and predictions.
And I found only 1 CPU is working when the `NeuralNetFastAI` model executes prediction and training.

Are there any solutions to accelerate training and prediction for the `NeuralNetFastAI` model?
For example, how to make `AutoGluon` use GPU when GPU is available or use more CPUs. 
![image](https://user-images.githubusercontent.com/12755003/150502944-a643798f-714f-4266-86e2-c97cf0310855.png)
From the screenshot above, `PyTorch` and `MXNet` can use GPU, but the `NeuralNetFastAI` and `NeuralNetMXNet` models do not use it.

**Comment by gomlfx** [comment]
I found the MXNET as best choice. I don't even include the other models.

**Comment by Innixma** [comment]
@stevewyl is it possible for you to provide the dataset? This would help in deep-diving performance issues.

**Comment by stevewyl** [comment]
@Innixma @willsmithorg Thanks for the hints! But I cannot disclose specific datasets due to company data privacy concerns.

@willsmithorg The text features are quite important to the models. The three text features are ranked 2nd, 8th, and 11th in the result of the `predictor.feature_importance() ` function. 
The training time is acceptable, but the inference time is longer than the training time, which is usually not normal for the neural networks. I use 75K samples for training and 430K samples used for prediction. Although the data size is 6 times larger than the training stage. but the inference time is over 1 hour. `NeuralNetMXNet` is much faster than `NeuralNetFastAI`, only using 2 mins to finish inference. 
![image](https://user-images.githubusercontent.com/12755003/150716741-88ba149e-691b-4897-8731-ab691c89ef4c.png)
During my experiments with other similar datasets, `NeuralNetFastAI` occasionally perform well, maybe removing the `NeuralNetFastAI` model will not harm the final performance.

**Comment by Innixma** [comment]
@stevewyl If you are interested in performance, you should investigate the `presets` option and use `high_quality_faster_inference_only_refit` with FastAI model excluded. This may be significantly stronger than what you are currently using (medium quality).

**Comment by stevewyl** [comment]
@Innixma Thanks for your work! I found this MR [Tabular: Exclude ngrams for FastAI ](https://github.com/awslabs/autogluon/pull/1536) solved my problem. For 10000 samples, the inference time was reduced from 57s to 1s.

**Comment by Innixma** [comment]
@stevewyl This is great to hear!
