### ISSUE TITLE
[v0.4] AutoGluon cheatsheet

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#1518]
Create an AutoGluon cheatsheet reference page, similar to https://github.com/matplotlib/cheatsheets

## Open questions

- [ ] How to format

## General topics to cover

- [ ] Install (CPU)
- [ ] Install (GPU)
- [ ] Supported Python versions
- [ ] Supported operating systems
- [ ] Where to submit issues

### TabularDataset

- [ ] init

### TabularPredictor

- [ ] Quick Start
- [ ] Presets
- [ ] init
- [ ] fit
- [ ] predict
- [ ] predict_proba
- [ ] leaderboard
- [ ] feature_importance
- [ ] info
- [ ] load
- [ ] fit_extra

### TextPredictor

- [ ] Quick Start
- [ ] init
- [ ] fit
- [ ] predict
- [ ] predict_proba
- [ ] load

### ImagePredictor

- [ ] Quick Start
- [ ] init
- [ ] fit
- [ ] predict
- [ ] predict_proba
- [ ] load

### FeatureGenerator

- [ ] Quick Start
- [ ] init
- [ ] fit
- [ ] fit_transform
- [ ] transform
- [ ] load
- [ ] save

### Spaces (HPO)

- [ ] Categorical
- [ ] Real
- [ ] Int
- [ ] Bool
- [ ] Constant

**Comment by willsmithorg** [comment]
The guy who did the [PR ](https://github.com/awslabs/autogluon/pull/1355) for 'add interpretable models' [@csinva](https://github.com/csinva ) has plenty of experience in making cheat sheets.  If you want some help or input on this, he might be a good person to ask.

**Comment by Innixma** [comment]
Thanks for the tip! We are currently finalizing an initial cheat sheet, and in future releases we may provide instructions for the community to assist in refining it. Here is a peek at the current version (WIP):
[autogluon-cheat-sheet.pdf](https://github.com/awslabs/autogluon/files/8017833/autogluon-cheat-sheet.pdf)

**Comment by willsmithorg** [comment]
Note that the WIP has **dashes** in the filename, but the cheatsheet itself refers to https://
auto.gluon.ai/stable/autogluon_cheat_sheet.pdf with **underscores** in the filename.
