### ISSUE TITLE
Warnings : sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2.

### ISSUE THREAD

**Issue by willsmithorg** [awslabs/autogluon#1542]
I get lots of warnings like these from XT and RF models while running `TabularPredictor().fit()`

`sklearn/ensemble/_forest.py:396: FutureWarning: Criterion 'mse' was deprecated in v1.0 and will be removed in version 1.2. Use criterion='squared_error' which is equivalent.`

These began in sklearn 1.0.0 which was released in Sep-2021, and is documented in :
- https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html
- https://scikit-learn.org/stable/whats_new/v1.0.html#version-1-0-0

I will submit a quick fix patch.

**Comment by willsmithorg** [comment]
Scikit-learn 1.0 was only introduced in Sep 2021.  Should we enforce scikit-learn>1.0.0 in tabular./setup.py ?
Or maybe this is too early for this PR in case many people remain on old scikit-learn?  The prior version to 1.0.0 was 0.24 and it's not clear that "squared_error" was a supported alias at that point:
https://scikit-learn.org/0.24/modules/generated/sklearn.tree.DecisionTreeRegressor.html

**Comment by Innixma** [comment]
Thanks for noticing and creating a fix! I believe the two remaining usages should be ok, and version should be capped correctly already. Will auto-close issue once PR is merged.
