### ISSUE TITLE
v0.4 How to disable Ray for "best_quality" preset?

### ISSUE THREAD

**Issue by berkeserol** [awslabs/autogluon#1553]
In Windows, Ray waits and do nothing after printing dashboard local url (The local url is not showing anything) So I want to disable Ray for now. Is it possible? Or is there a way to make it run?

I have:

Name: ray
Version: 1.7.0

Name: redis
Version: 4.1.0

**Comment by yinweisu** [comment]
Hi, to disable ray, you can add `ag_args_ensemble =dict(fold_fitting_strategy='sequential_local')` as an argument to `fit()`to disable ray.

In the meantime, do you mind sharing more info on ray hanging? Maybe your console input?

**Comment by berkeserol** [comment]
PrometheusServiceDiscoveryWriter gives an exception on a thread other than main:

'Cannot create a file when that file already exists'

filename: 'C:\\Users\\{user}\\AppData\\Local\\Temp\\ray\\tmp_prom_metrics_service_discovery.json'

filename2: 'C:\\Users\\{user}\\AppData\\Local\\Temp\\ray\\prom_metrics_service_discovery.json'

I deleted the ray folder and tried again. It gives the same exception. Looks like it creates these files and another thread throws exception as they already exist.

**Comment by yinweisu** [comment]
This seems to be an issue with ray itself and not AutoGluon to me. Maybe consider reporting this in ray's repo?
