### ISSUE TITLE
autogluon+nvidia-dali

### ISSUE THREAD

**Issue by XWalways** [awslabs/autogluon#157]
using dali to speed up autogluon training, 
`pip install --extra-index-url https://developer.download.nvidia.com/compute/redist/cuda/10.0 nvidia-dali` 
but always report: Check your library paths and if the driver is installed correctly.
if i don't use autogluon, just define a normal train loop, it can work well.

**Comment by XWalways** [comment]
autogluon seems not Incompatible with cuda10.0,it can't find any gpus, then i change get_gpu_count=8 directly, but it did not work

**Comment by zhanghang1989** [comment]
Thanks for reporting the issue!
1. We haven't investigated the issue with NVIDIA-dali, but we will do that in the future if we have more bandwidth
2. AutoGluon is compaitible with CUDA 10.0, our CI is actually using CUDA 10.0 on ubuntu 16.04. What's your system setup?

**Comment by XWalways** [comment]
i just use miniconda environment on Ubuntu 16.04, set LD_LIBRARY_PATH to be cuda-10.0, but it always report Check failed: device_count_ > 0 (-1 vs. 0) : GPU usage requires at least 1 GPU, but if i create a cu101 conda environment, it can work well.

**Comment by XWalways** [comment]
i create a new cu100 environment, then autogluon worked, AutoGluon is compaitible with CUDA 10.0, but also is not incompatible with dali, means if you install nvidia-dali ,then cannot find any gpus.
