### ISSUE TITLE
Failed downloading the pretrained model of efficientnet

### ISSUE THREAD

**Issue by snow6666667** [awslabs/autogluon#158]
How can i use the pretrained model of efficientnet?  Some errors occurred when i tried to follow guide.
https://autogluon.mxnet.io/model_zoo/index.html

`import autogluon as ag
model = ag.model_zoo.get_model('efficientnet_b0', pretrained=True)`

ERROR: AttributeError: module 'autogluon' has no attribute 'model_zoo'

`import autogluon`
`from autogluon.model_zoo import get_model
model = get_model('efficientnet_b0', pretrained=True)`

ERROR: “efficientnet.py", line 127, in get_efficientnet_b0
             from .model_store import get_model_file
             ModuleNotFoundError: No module named 'autogluon.model_zoo.models.model_store'

when i change the path “from ..model_store import get_model_file” in efficientnet.py：

ERROR: RuntimeError: Failed downloading url 
             https://autogluon.s3.amazonaws.com/models/efficientnet_b0-dd74519f.zip

**Comment by zhanghang1989** [comment]
Thanks for reporting. The models were deleted by accident. Will add it back.

**Comment by zhanghang1989** [comment]
This should be already fixed. Sorry for the delayed reply.

**Comment by AdelZakirov** [comment]
Still there

**Comment by zhanghang1989** [comment]
This should be resolved. Otherwise the CI won't pass the unit test.

**Comment by Innixma** [comment]
@AdelZakirov Can you try building from AutoGluon source and seeing if it works? It could be you are using an old version of AutoGluon.

**Comment by mahdi-b** [comment]
@Innixma Has this been fixed? I see a `model_zoo`  under extra but not under `core`. I've tried installing from source and pip and none has the library.

**Comment by Innixma** [comment]
Hi @mahdi-b,

I think the tutorial code is out-dated. The correct code may be:

```
import autogluon.extra as ag
model = ag.model_zoo.get_model('efficientnet_b0', pretrained=True)
```

Let me know if this works.

This ticket is very old, and we are planning to migrate to PyTorch in future, which we will then have efficientnet available via PyTorch. We don't have a detailed time-line for when this will occur, but it is fairly high on our priority list.

**Comment by mahdi-b** [comment]
Thanks, @Innixma  for the quick response. I tried that also but it causes other problems.

`ModuleNotFoundError: No module named 'autogluon.extra.utils'`

Is there any other way to access model_zoo models from autogluon?

Thanks again,

Mahdi

**Comment by Innixma** [comment]
@mahdi-b The code seems to work for me. Maybe try pre-release?

```
import autogluon.extra as ag
model = ag.model_zoo.get_model('efficientnet_b0', pretrained=True)
```

```
Model file /Users/neerick/.autogluon/models/efficientnet_b0-dd74519f.params is not found. Downloading.
100%|██████████| 20846/20846 [00:01<00:00, 10477.49KB/s]
```

I've also opened up a PR to clean up the docs to reflect the correct code: #1218

**Comment by Innixma** [comment]
I've opened PR #1219 to clarify docs

**Comment by mahdi-b** [comment]
> @mahdi-b The code seems to work for me. Maybe try pre-release?
> 
> ```
> import autogluon.extra as ag
> model = ag.model_zoo.get_model('efficientnet_b0', pretrained=True)
> ```
> 
> ```
> Model file /Users/neerick/.autogluon/models/efficientnet_b0-dd74519f.params is not found. Downloading.
> 100%|██████████| 20846/20846 [00:01<00:00, 10477.49KB/s]
> ```
> 
> I'm planning to open up a PR to clean up the docs to reflect the correct code.



> @mahdi-b The code seems to work for me. Maybe try pre-release?
> 
> ```
> import autogluon.extra as ag
> model = ag.model_zoo.get_model('efficientnet_b0', pretrained=True)
> ```
> 
> ```
> Model file /Users/neerick/.autogluon/models/efficientnet_b0-dd74519f.params is not found. Downloading.
> 100%|██████████| 20846/20846 [00:01<00:00, 10477.49KB/s]
> ```
> 
> I'm planning to open up a PR to clean up the docs to reflect the correct code.

It works with pre-release. Thanks a lot!
