### ISSUE TITLE
[BUG] v0.4.0 text submodule depend on features submodule

### ISSUE THREAD

**Issue by Qiaochu-Song** [awslabs/autogluon#1607]
Hi,

I found v0.4.0 uses autogluon.features module in order to preprocess multimodal text-tabular data.
[https://github.com/awslabs/autogluon/blob/0.4.0/text/src/autogluon/text/automm/data/preprocess_dataframe.py#L8](url)

There is no dependency specified in setup.py in the text submodule. 
This might cause errors if the user only did submodule installations. 

For your reference:
<img width="919" alt="image" src="https://user-images.githubusercontent.com/50940543/157964129-0496e550-82d1-4fe5-a502-ece169331058.png">

**Comment by Innixma** [comment]
Thank you for notifying us of this!! This is indeed a bug with v0.4.0. I have created #1608 to fix and it will be incorporated in v0.4.1 release.

**Comment by sxjscience** [comment]
@Qiaochu-Song i closed it since the fix has been merged. Thanks @Innixma !
