### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by kris-mlguy** [awslabs/autogluon#161]
I was trying to install autogluon using "pip install autogluon" in my laptop with Windows OS.
The error output is below:

Building wheels for collected packages: ConfigSpace
  Building wheel for ConfigSpace (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Anaconda3\envs\dm_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\userid\\AppData\\Local\\Temp\\pip-install-tx_hyu1s\\ConfigSpace\\setup.py'"'"'; __file__='"'"'C:\\Users\\userid\\AppData\\Local\\Temp\\pip-install-tx_hyu1s\\ConfigSpace\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\userid\AppData\Local\Temp\pip-wheel-4198gv9y' --python-tag cp36
       cwd: C:\Users\userid\AppData\Local\Temp\pip-install-tx_hyu1s\ConfigSpace\
  Complete output (62 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\ConfigSpace
  copying ConfigSpace\convert.py -> build\lib.win-amd64-3.6\ConfigSpace
  copying ConfigSpace\exceptions.py -> build\lib.win-amd64-3.6\ConfigSpace
  copying ConfigSpace\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace
  copying ConfigSpace\__version__.py -> build\lib.win-amd64-3.6\ConfigSpace
  creating build\lib.win-amd64-3.6\test
  copying test\test_conditions.py -> build\lib.win-amd64-3.6\test
  copying test\test_configuration_space.py -> build\lib.win-amd64-3.6\test
  copying test\test_forbidden.py -> build\lib.win-amd64-3.6\test
  copying test\test_hyperparameters.py -> build\lib.win-amd64-3.6\test
  copying test\test_util.py -> build\lib.win-amd64-3.6\test
  copying test\__init__.py -> build\lib.win-amd64-3.6\test
  creating build\lib.win-amd64-3.6\ConfigSpace\nx
  copying ConfigSpace\nx\exception.py -> build\lib.win-amd64-3.6\ConfigSpace\nx
  copying ConfigSpace\nx\release.py -> build\lib.win-amd64-3.6\ConfigSpace\nx
  copying ConfigSpace\nx\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace\nx
  creating build\lib.win-amd64-3.6\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\irace.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\json.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\pbs.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\pcs.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\pcs_new.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\pyll.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\spearmint_april2013_mod_spearmint_pb2.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
  copying ConfigSpace\read_and_write\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
  creating build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms
  copying ConfigSpace\nx\algorithms\cycles.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms
  copying ConfigSpace\nx\algorithms\dag.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms
  copying ConfigSpace\nx\algorithms\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms
  creating build\lib.win-amd64-3.6\ConfigSpace\nx\classes
  copying ConfigSpace\nx\classes\digraph.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\classes
  copying ConfigSpace\nx\classes\graph.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\classes
  copying ConfigSpace\nx\classes\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\classes
  creating build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms\components
  copying ConfigSpace\nx\algorithms\components\strongly_connected.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms\components
  copying ConfigSpace\nx\algorithms\components\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms\components
  creating build\lib.win-amd64-3.6\test\read_and_write
  copying test\read_and_write\test_irace_writer.py -> build\lib.win-amd64-3.6\test\read_and_write
  copying test\read_and_write\test_json.py -> build\lib.win-amd64-3.6\test\read_and_write
  copying test\read_and_write\test_pb_converter.py -> build\lib.win-amd64-3.6\test\read_and_write
  copying test\read_and_write\test_pcs_converter.py -> build\lib.win-amd64-3.6\test\read_and_write
  copying test\read_and_write\test_pyll_util.py -> build\lib.win-amd64-3.6\test\read_and_write
  copying test\read_and_write\__init__.py -> build\lib.win-amd64-3.6\test\read_and_write
  creating build\lib.win-amd64-3.6\test\test_converters_and_test_searchspaces
  copying test\test_converters_and_test_searchspaces\test_sample_configuration_spaces.py -> build\lib.win-amd64-3.6\test\test_converters_and_test_searchspaces
  copying test\test_converters_and_test_searchspaces\__init__.py -> build\lib.win-amd64-3.6\test\test_converters_and_test_searchspaces
  creating build\lib.win-amd64-3.6\test\test_searchspaces
  copying test\test_searchspaces\__init__.py -> build\lib.win-amd64-3.6\test\test_searchspaces
  running build_ext
  skipping 'ConfigSpace\hyperparameters.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\forbidden.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\conditions.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\c_util.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\util.c' Cython extension (up-to-date)
  skipping 'ConfigSpace\configuration_space.c' Cython extension (up-to-date)
  building 'ConfigSpace.hyperparameters' extension
  error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.21.27702\\PlatformSDK\\lib'
  ERROR: Failed building wheel for ConfigSpace
  Running setup.py clean for ConfigSpace
Failed to build ConfigSpace
Installing collected packages: lightgbm, click, msgpack, pyyaml, dask, heapdict, zict, tblib, cloudpickle, toolz, sortedcontainers, distributed, gluonnlp, scikit-optimize, ConfigSpace, Pillow, gluoncv, autogluon
    Running setup.py install for ConfigSpace ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Anaconda3\envs\dm_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\userid\\AppData\\Local\\Temp\\pip-install-tx_hyu1s\\ConfigSpace\\setup.py'"'"'; __file__='"'"'C:\\Users\\userid\\AppData\\Local\\Temp\\pip-install-tx_hyu1s\\ConfigSpace\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\userid\AppData\Local\Temp\pip-record-wwberfpw\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\userid\AppData\Local\Temp\pip-install-tx_hyu1s\ConfigSpace\
    Complete output (62 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\ConfigSpace
    copying ConfigSpace\convert.py -> build\lib.win-amd64-3.6\ConfigSpace
    copying ConfigSpace\exceptions.py -> build\lib.win-amd64-3.6\ConfigSpace
    copying ConfigSpace\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace
    copying ConfigSpace\__version__.py -> build\lib.win-amd64-3.6\ConfigSpace
    creating build\lib.win-amd64-3.6\test
    copying test\test_conditions.py -> build\lib.win-amd64-3.6\test
    copying test\test_configuration_space.py -> build\lib.win-amd64-3.6\test
    copying test\test_forbidden.py -> build\lib.win-amd64-3.6\test
    copying test\test_hyperparameters.py -> build\lib.win-amd64-3.6\test
    copying test\test_util.py -> build\lib.win-amd64-3.6\test
    copying test\__init__.py -> build\lib.win-amd64-3.6\test
    creating build\lib.win-amd64-3.6\ConfigSpace\nx
    copying ConfigSpace\nx\exception.py -> build\lib.win-amd64-3.6\ConfigSpace\nx
    copying ConfigSpace\nx\release.py -> build\lib.win-amd64-3.6\ConfigSpace\nx
    copying ConfigSpace\nx\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace\nx
    creating build\lib.win-amd64-3.6\ConfigSpace\read_and_write
    copying ConfigSpace\read_and_write\irace.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
    copying ConfigSpace\read_and_write\json.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
    copying ConfigSpace\read_and_write\pbs.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
    copying ConfigSpace\read_and_write\pcs.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
    copying ConfigSpace\read_and_write\pcs_new.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
    copying ConfigSpace\read_and_write\pyll.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
    copying ConfigSpace\read_and_write\spearmint_april2013_mod_spearmint_pb2.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
    copying ConfigSpace\read_and_write\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace\read_and_write
    creating build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms
    copying ConfigSpace\nx\algorithms\cycles.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms
    copying ConfigSpace\nx\algorithms\dag.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms
    copying ConfigSpace\nx\algorithms\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms
    creating build\lib.win-amd64-3.6\ConfigSpace\nx\classes
    copying ConfigSpace\nx\classes\digraph.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\classes
    copying ConfigSpace\nx\classes\graph.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\classes
    copying ConfigSpace\nx\classes\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\classes
    creating build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms\components
    copying ConfigSpace\nx\algorithms\components\strongly_connected.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms\components
    copying ConfigSpace\nx\algorithms\components\__init__.py -> build\lib.win-amd64-3.6\ConfigSpace\nx\algorithms\components
    creating build\lib.win-amd64-3.6\test\read_and_write
    copying test\read_and_write\test_irace_writer.py -> build\lib.win-amd64-3.6\test\read_and_write
    copying test\read_and_write\test_json.py -> build\lib.win-amd64-3.6\test\read_and_write
    copying test\read_and_write\test_pb_converter.py -> build\lib.win-amd64-3.6\test\read_and_write
    copying test\read_and_write\test_pcs_converter.py -> build\lib.win-amd64-3.6\test\read_and_write
    copying test\read_and_write\test_pyll_util.py -> build\lib.win-amd64-3.6\test\read_and_write
    copying test\read_and_write\__init__.py -> build\lib.win-amd64-3.6\test\read_and_write
    creating build\lib.win-amd64-3.6\test\test_converters_and_test_searchspaces
    copying test\test_converters_and_test_searchspaces\test_sample_configuration_spaces.py -> build\lib.win-amd64-3.6\test\test_converters_and_test_searchspaces
    copying test\test_converters_and_test_searchspaces\__init__.py -> build\lib.win-amd64-3.6\test\test_converters_and_test_searchspaces
    creating build\lib.win-amd64-3.6\test\test_searchspaces
    copying test\test_searchspaces\__init__.py -> build\lib.win-amd64-3.6\test\test_searchspaces
    running build_ext
    skipping 'ConfigSpace\hyperparameters.c' Cython extension (up-to-date)
    skipping 'ConfigSpace\forbidden.c' Cython extension (up-to-date)
    skipping 'ConfigSpace\conditions.c' Cython extension (up-to-date)
    skipping 'ConfigSpace\c_util.c' Cython extension (up-to-date)
    skipping 'ConfigSpace\util.c' Cython extension (up-to-date)
    skipping 'ConfigSpace\configuration_space.c' Cython extension (up-to-date)
    building 'ConfigSpace.hyperparameters' extension
    error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.21.27702\\PlatformSDK\\lib'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Program Files\Anaconda3\envs\dm_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\userid\\AppData\\Local\\Temp\\pip-install-tx_hyu1s\\ConfigSpace\\setup.py'"'"'; __file__='"'"'C:\\Users\\userid\\AppData\\Local\\Temp\\pip-install-tx_hyu1s\\ConfigSpace\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\userid\AppData\Local\Temp\pip-record-wwberfpw\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by Innixma** [comment]
Hi Kris,

AutoGluon is not officially supported on Windows. We have primarily been working to ensure functionality with Linux, so you may encounter problems on Windows. Several dependencies of AutoGluon are likely not supported on Windows, so I doubt it will work without significant effort and code changes.

In future we plan to investigate Windows support but it still unknown how complicated this will be.

Marking this as resolved.

Best,
Nick

**Comment by zhanghang1989** [comment]
@Innixma Thanks for answering the issue!  We may not close the issue until we have solved that. Otherwise, it is not friendly to the community.

**Comment by Innixma** [comment]
@zhanghang1989 , I referenced this in a meta-issue, should we still keep it open or should we just isolate this to the meta-issue?

**Comment by zhanghang1989** [comment]
> @zhanghang1989 , I referenced this in a meta-issue, should we still keep it open or should we just isolate this to the meta-issue?

Thanks @Innixma . We may let the issue contributor to decide whether to keep it.

**Comment by kris-mlguy** [comment]
Thanks Nick and @zhanghang1989 for the feedback. Given that Windows is being used by almost equivalent number of people as Linux, it would be great if you can extend to Windows as well. I would consider this as a default request. Please do let me know if you have a tentative timeline.

**Comment by Innixma** [comment]
We don't have a tentative timeline for Windows support at the moment. We will respond to the ticket when we have more info.

**Comment by jwmueller** [comment]
Closing this issue as it is the same as  https://github.com/awslabs/autogluon/issues/164
Please keep an eye on that issue for possible solutions.

**Comment by chaltik** [comment]
I am getting this error on Ubuntu 18.04. It is the last of three errors I am getting, however. The first one is 
` Running setup.py bdist_wheel for psutil ... error
  Complete output from command /home/captain/dev/replicant/py3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-7oki1ybh/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpm1kqc3capip-wheel- --python-tag cp36:
  /tmp/tmpr086b5j2.c:1:27: fatal error: linux/ethtool.h: No such file or directory
   #include <linux/ethtool.h>`

**Comment by Innixma** [comment]
@chaltik Can you create a new issue? This is an issue marked as resolved and related to Windows.
