### ISSUE TITLE
Google Colab - Event Loop error on import autogluon

### ISSUE THREAD

**Issue by nathan-wood** [awslabs/autogluon#162]
Here is a colab notebook for reference:
https://drive.google.com/open?id=1c14OY7zNP64xew1jlNpFGxb3D9No4u95

After installation, the first execution of the import throws an error. 
Simply executing a 2nd time loads the library with no error.

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-014e868ea365> in <module>()
----> 1 import autogluon as ag

22 frames
/usr/lib/python3.6/asyncio/events.py in get_event_loop(self)
    600         if self._local._loop is None:
    601             raise RuntimeError('There is no current event loop in thread %r.'
--> 602                                % threading.current_thread().name)
    603         return self._local._loop
    604 

RuntimeError: There is no current event loop in thread 'IO loop'.

**Comment by zhanghang1989** [comment]
Thanks for the feedback. This looks like an error with dask distributed.

**Comment by nathan-wood** [comment]
@zhanghang1989 Should I raise an issue within the dask distributed github?

**Comment by zhanghang1989** [comment]
That would be great. Please also link back to this issue to keep track of.

**Comment by Innixma** [comment]
This issue stems from #163. Please follow the fix outlined in #163 to resolve. Thanks!
