### ISSUE TITLE
[BUG]Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yangn306** [awslabs/autogluon#1627]
I face a problem that is "Segmentation fault (core dumped)" when I use this comm: ```from autogluon.text import TextPredictor```. the autogluon version is 0.4.0, gpu.

**Comment by Innixma** [comment]
@yangn306 Please provide more information for us to assist.

For example, 

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

**Comment by yangn306** [comment]
it works well as I reinstall the autogluon and torch
