### ISSUE TITLE
Google Colab - error in dist_manager.py _refresh_resource(cls)

### ISSUE THREAD

**Issue by nathan-wood** [awslabs/autogluon#163]
Google Colab notebook for reference:
https://drive.google.com/open?id=1DAVTtAD7zGbJzrkvRKRjWvIhKzCawNkH

Code:
`detector = task.fit(dataset)`

Error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-d441b831c269> in <module>()
----> 1 detector = task.fit(dataset)

5 frames
/usr/local/lib/python3.6/dist-packages/autogluon/scheduler/resource/dist_manager.py in _refresh_resource(cls)
     48     @classmethod
     49     def _refresh_resource(cls):
---> 50         cls.MAX_CPU_COUNT = max([x.get_all_resources()[0] for x in cls.NODE_RESOURCE_MANAGER.values()])
     51         cls.MAX_GPU_COUNT = max([x.get_all_resources()[1] for x in cls.NODE_RESOURCE_MANAGER.values()])
     52 

ValueError: max() arg is an empty sequence

**Comment by zhanghang1989** [comment]
Thanks for the feedback! Looks like the remote on Collab is not initialized correctly. I will take a look.

**Comment by zhanghang1989** [comment]
related issue: https://github.com/awslabs/autogluon/issues/162

**Comment by fjibj** [comment]
thanks a lot.
i  meet the same error and solve it by using:
pip uninstall -y distributed
pip install distributed
pip install -U ipykernel 
and RESTART RUNTIME

**Comment by Innixma** [comment]
Using AutoGluon 0.0.5, I am able to get it working in Colab through:

```
pip install -U ipykernel
```

RESTART RUNTIME

```
pip uninstall -y mkl
pip install --upgrade mxnet
pip install autogluon
```

```
from autogluon import TabularPrediction as task
train_data = task.Dataset(file_path='https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
test_data = task.Dataset(file_path='https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')
predictor = task.fit(train_data=train_data, label='class')
performance = predictor.evaluate(test_data)
```

One thing I noticed was that NN takes ~3x longer to train than on my mac laptop. Intel MKL is installed on Colab and should be uninstalled to speed-up AutoGluon. Uninstalling MKL gives at least 2x speedup.

Link to Colab Notebook: https://colab.research.google.com/drive/1ULOytrRHcw4GLl0qWgGnxUpr9zVQVYlr

**Comment by nunocesarsa** [comment]
Just adding a comment for future reference to whoever stumbles on the same error. The suggestion by @Innixma  worked perfectly but I also had to update "dask" because stringify was not getting called. 

So after: 

pip install -U ipykernel

You can also update -U dask:

!pip install -U dask
