### ISSUE TITLE
Help! encounter problems when installing torch

### ISSUE THREAD

**Issue by man469** [awslabs/autogluon#1639]
I try to execute the command "pip3 install torch==1.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html" according to the instruction but encounter following error:
Could not fetch URL https://download.pytorch.org/whl/cu113/torch_stable.html: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='download.pytorch.org', port=443): Max retries exceeded with url: /whl/cu113/torch_stable.html (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1129)'))) - skipping
How can I solve this problem?

**Comment by jhmenke** [comment]
just install pytorch manually using the instructions on www.pytorch.org
