### ISSUE TITLE
[BUG] ImportError: cannot import name 'TabularPrediction' from 'autogluon' (unknown location)

### ISSUE THREAD

**Issue by ericlasry** [awslabs/autogluon#1662]
Get dependency errors on Colab when trying to use import TabularPredictor from autogluon.tabular

```
!pip install --upgrade mxnet
!pip install autogluon
import autogluon as ag
from autogluon import TabularPrediction as task
```

Link to notebook for full error message:
https://colab.research.google.com/drive/1ynyfEJuElLIXlxq5A6_a2719f_NCqpYb?usp=sharing

**Comment by Innixma** [comment]
You are using the old API from v0.0.15. Please refer to this notebook for using the new API: https://colab.research.google.com/drive/1u-k3kssffxWRrZenahYTL97-bsQkC8K7?usp=sharing

And check our documentation: https://auto.gluon.ai/stable/index.html
