### ISSUE TITLE
Text Classification Customized Dataset

### ISSUE THREAD

**Issue by zhanghang1989** [awslabs/autogluon#167]
TODO: need to implement customized dataset for NLP
some prototype we can use:

https://github.com/awslabs/autogluon/blob/master/autogluon/task/text_classification/dataset.py#L109

**Comment by songqiang** [comment]
This feature is very necessary. Without supporting customized datasets, the TextClassification is far from any practical use. The dataset class in the tabular is more feature complete, and  we would better to adopt a consistent interface. Basically, allowing loading data from path or a pandas dataframe

**Comment by zzdgit** [comment]
@Innixma Excuse me, do you support the case of Chinese data set?

**Comment by Innixma** [comment]
> @Innixma Excuse me, do you support the case of Chinese data set?

At present for Tabular, a Chinese data set for text will not work well due to the lack of space characters to generate ngrams with. In regards to the text classification module, @cgraywang can you answer this?

**Comment by ethanqi1109** [comment]
@Innixma do you support customized dataset for text classification now?

**Comment by Innixma** [comment]
> @Innixma do you support customized dataset for text classification now?

We will once #556 is merged, which is a full overhaul to the TextClassification task.

**Comment by jwmueller** [comment]
Easy usage of custom text datasets has been addressed in:  https://github.com/awslabs/autogluon/pull/556
