### ISSUE TITLE
Need install Autogluon with scikit-learn >= 1.0.2

### ISSUE THREAD

**Issue by leandromferreiraUSP** [awslabs/autogluon#1673]
I am trying install Autogloun in a project by Poetry and the following message is show:

"  Because no versions of autogluon match >0.4.0
   and autogluon (0.4.0) depends on autogluon.text (0.4.0), autogluon (>=0.4.0) requires autogluon.text (0.4.0).
  And because autogluon.text (0.4.0) depends on scikit-learn (>=1.0.0,<1.1), autogluon (>=0.4.0) requires scikit-learn (>=1.0.0,<1.1)."

My version of scikit-learn is 1.0.2 and I need to use this version for other packages used in my project.

Have a way to update their version of scikit-learn in autogluon.text?

Thks

**Comment by Innixma** [comment]
> My version of scikit-learn is 1.0.2 and I need to use this version for other packages used in my project.

1.0.2 is supported in AutoGluon v0.4.

1.0.2 is satisfied in the version range `>=1.0.0,<1.1`.

It is unclear what problem you are facing.
