### ISSUE TITLE
Improve out-of-memory handling

### ISSUE THREAD

**Issue by bwerness** [awslabs/autogluon#168]
Currently when running on a large dataset with limited compute, the model training can fail completely with out-of-memory errors, when it is possible for it to successfully train several of the models and produce strong predictions.  To make it as reliable as possible for new users, it would be good to instead catch errors when models fail, and simply omit them from the ensemble.   Since (in my experience) the models most likely to yield out of memory errors are the KNN models, this would likely also not have a large impact on final metrics.  These failures could then be reported to the user.

**Comment by jwmueller** [comment]
Thanks Brent! This is also related to https://github.com/awslabs/autogluon/issues/83
If you encounter other OOM cases, please let us know in the linked issue.

**Comment by Innixma** [comment]
Just merged #170 which should help significantly with this problem

**Comment by Innixma** [comment]
#177 should help to resolve the majority of remaining memory issues

**Comment by Innixma** [comment]
#177 is merged and should resolve this issue for the grand majority of cases. Please feel free to re-open this issue if you find OOM errors still occurring.
