### ISSUE TITLE
[BUG]average precision not working for text classification in 0.4.1

### ISSUE THREAD

**Issue by rxjx** [awslabs/autogluon#1698]
I was trying the workaround reported in https://github.com/awslabs/autogluon/issues/1695, which led me to use the pre-release instead of 0.4.0. Although the workaround seemed to get me past the initial problem reported of importing a TextPredictor, the pre-release version doesn't seem to recognize average_precision as a metric any more. The error is:

ValueError: unknown metric_name: average_precision

on the line:
m = TextPredictor(label='lbl', eval_metric='average_precision', path='/content/drive/My Drive/ag_txt_best').fit(data, presets='best_quality')

**Comment by sxjscience** [comment]
Will submit a PR to fix it. Meanwhile, if you need a urgent workaround, you may first use `eval_metric="roc_auc"` for now. You can always evaluate with `average_precision` after you have trained the model.

**Comment by rxjx** [comment]
Thanks, that seems to work. FYI, f1_macro is also not working.

**Comment by sxjscience** [comment]
The root-cause is that we are now relying on torchmetrics for calculating metrics in the validation stage, because it provides a principled way of aggregating the metrics from multiple processes / instances.

However, torchmetrics do not contain all the metrics that we are using for the final evaluation of the models. Thus, we created the mapping as follows:

https://github.com/awslabs/autogluon/blob/e66ebc40bb50108f768e83892d0b3a8181e264cc/text/src/autogluon/text/automm/optimization/utils.py#L68-L83

**Comment by sxjscience** [comment]
Should be resolved via the PR in https://github.com/awslabs/autogluon/pull/1697. Wait for the CI / review.

**Comment by sxjscience** [comment]
@rxjx Would you try again with the latest version?

**Comment by rxjx** [comment]
Will do later today. Thanks

**Comment by rxjx** [comment]
@sxjscience It doesn't look like this is working. When I tried to train a 'best_quality' text classifier, I got :

```
/usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `AveragePrecision` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type                         | Params
-------------------------------------------------------------------
0 | model             | HFAutoModelForTextPrediction | 183 M 
1 | validation_metric | AveragePrecision             | 0     
2 | loss_func         | CrossEntropyLoss             | 0     
-------------------------------------------------------------------
183 M     Trainable params
0         Non-trainable params
183 M     Total params
367.666   Total estimated model params size (MB)
Global seed set to 123
Epoch 0: 0%
0/3729 [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-3-f969ebc733f5>](https://localhost:8080/#) in <module>()
     24 txt_data = pd.DataFrame({'sent':s, 'lbl':l})
     25 
---> 26 m = TextPredictor(label='lbl', eval_metric='average_precision', path='/content/drive/My Drive/ag_txt_best').fit(txt_data, presets='best_quality')
     27 print('high done')
     28 

29 frames
[/usr/local/lib/python3.7/dist-packages/transformers/models/deberta_v2/modeling_deberta_v2.py](https://localhost:8080/#) in backward(self, grad_output)
    117     def backward(self, grad_output):
    118         (output,) = self.saved_tensors
--> 119         inputGrad = _softmax_backward_data(grad_output, output, self.dim, output)
    120         return inputGrad, None, None
    121 

TypeError: _softmax_backward_data(): argument 'input_dtype' (position 4) must be torch.dtype, not Tensor
```

while for a 'medium_quality_faster_trainmedium_quality_faster_train' predictor I got :

```
/usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `AveragePrecision` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type                         | Params
-------------------------------------------------------------------
0 | model             | HFAutoModelForTextPrediction | 13.5 M
1 | validation_metric | AveragePrecision             | 0     
2 | loss_func         | CrossEntropyLoss             | 0     
-------------------------------------------------------------------
13.5 M    Trainable params
0         Non-trainable params
13.5 M    Total params
26.967    Total estimated model params size (MB)
Global seed set to 123
Epoch 0: 54%
500/933 [00:24<00:20, 20.70it/s, loss=0.355, v_num=]
Epoch 0, global step 23: val_average_precision reached -inf (best -inf), saving model to "/content/drive/My Drive/ag_txt_medium/epoch=0-step=23.ckpt" as top 3
Evaluate 1 checkpoints and sort them in a decreasing order based on their performances.
Predicting: 0%
0/11 [00:01<?, ?it/s]
Start to fuse 1 checkpoints via the greedy soup algorithm./usr/local/lib/python3.7/dist-packages/torchmetrics/utilities/prints.py:36: UserWarning: Metric `AveragePrecision` will save all targets and predictions in buffer. For large datasets this may lead to large memory footprint.
  warnings.warn(*args, **kwargs)
Using 16bit native Automatic Mixed Precision (AMP)
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name              | Type                         | Params
-------------------------------------------------------------------
0 | model             | HFAutoModelForTextPrediction | 13.5 M
1 | validation_metric | AveragePrecision             | 0     
2 | loss_func         | CrossEntropyLoss             | 0     
-------------------------------------------------------------------
13.5 M    Trainable params
0         Non-trainable params
13.5 M    Total params
26.967    Total estimated model params size (MB)
Global seed set to 123
Epoch 0: 54%
500/933 [00:24<00:20, 20.70it/s, loss=0.355, v_num=]
Epoch 0, global step 23: val_average_precision reached -inf (best -inf), saving model to "/content/drive/My Drive/ag_txt_medium/epoch=0-step=23.ckpt" as top 3
Evaluate 1 checkpoints and sort them in a decreasing order based on their performances.
Predicting: 0%
0/11 [00:01<?, ?it/s]
Start to fuse 1 checkpoints via the greedy soup algorithm.
```
at which point the training ends. The same thing happens with the 'high_quality' preset.

Note that I am training a binary classifier with an unbalanced dataset with 5573 negative sentences and 1206 positive sentences.

**Comment by sxjscience** [comment]
Yeah, we are working on another PR to address the issue further. There are certain issues in torchmetrics about roc_auc / average_precision: https://github.com/awslabs/autogluon/pull/1715

**Comment by sxjscience** [comment]
Yeah, the first error about deberta-v3 is new to me. Let me actually verify if it appears on my side. My guess is the error is due to recent upgrade of transformers package.

**Comment by sxjscience** [comment]
@rxjx For the 2nd error, the reason for getting perf_values to be -inf may be due to that there is no positive label in samples of the batch. Would you try `.fit(eval_metric='log_loss')` for now?

**Comment by rxjx** [comment]
Will do. Is there no option for stratified sampling for these samples?

**Comment by rxjx** [comment]
log_loss is working

**Comment by sxjscience** [comment]
> Will do. Is there no option for stratified sampling for these samples?

The batch size will be too small for stratified sampling.

**Comment by sxjscience** [comment]
@rxjx Recently we released 0.4.1. Would you like to revisit the issue and see if it's still there?

**Comment by rxjx** [comment]
It works in a way but because we switch from average_precision to log_loss but there are no crashes and the training completes.

**Comment by sxjscience** [comment]
@rxjx We should have recently fundamentally fixed it via https://github.com/awslabs/autogluon/pull/1734. Also, using log_loss to find a model that works well in average_precision may not be a bad idea.

**Comment by rxjx** [comment]
Yes, that's certainly true. I validated that empirically as well, at least on that specific dataset.

**Comment by sxjscience** [comment]
Would you think that we may close it and revisit if you see issues later?

**Comment by rxjx** [comment]
Yes, that seems reasonable for now.
