### ISSUE TITLE
[BUG] v0.4 Install instructions torch cpu install overridden

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#1700]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [x] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
Following [CPU install instructions for linux](https://auto.gluon.ai/stable/install.html), GPU torch is installed instead.

**Expected behavior**
CPU version of torch should remain installed, GPU version of torch should not be installed or downloaded.

**Solution**
Update CPU install instructions to:

```
pip3 install "torch>=1.0,<1.11+cpu" -f https://download.pytorch.org/whl/cpu/torch_stable.html
```

**To Reproduce**
Colab Notebook: https://colab.research.google.com/drive/1BQYST3tRAiXxJ8T9D-CfmA1nE-MNRjRe?usp=sharing
Colab Notebook with Fix: https://colab.research.google.com/drive/11ALE_bWKgk0sVaoMgYjdNx6FYMZDDhlk?usp=sharing

**Installed Versions**
0.4.0

**Comment by sxjscience** [comment]
Will we meet issues if we are training on a cpu-only instance with the torch-GPU? I think torch is loading cuda libs dynamically and the GPU version may still be runnable in CPU. 

If not, it may not be a bug (the users can still use AutoGluon) but we can provide improved instructions.

**Comment by Innixma** [comment]
@sxjscience It will still work, but GPU is 800MB vs CPU 200 MB.

**Comment by sxjscience** [comment]
I think this can be closed since the PR has been merged.
