### ISSUE TITLE
Win10 use ImagePredictor error!

### ISSUE THREAD

**Issue by 155cannon** [awslabs/autogluon#1727]
C:\Users\Via20220113\AppData\Local\Programs\Python\Python39\python.exe D:/Learning/AutoGluon/image_prediction/image_pred.py
`time_limit=auto` set to `time_limit=7200`.
Reset labels to [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Randomly split train_data into train[45000]/validation[5000] splits.
The number of requested GPUs is greater than the number of available GPUs.Reduce the number to 1
Starting fit without HPO
modified configs(<old> != <new>): {
root.train.early_stop_max_value 1.0 != inf
root.train.early_stop_patience -1 != 10
root.train.early_stop_baseline 0.0 != -inf
root.train.epochs    200 != 2
root.train.batch_size 32 != 16
root.misc.seed       42 != 355
root.misc.num_workers 4 != 8
root.img_cls.model   resnet101 != resnet50
}
Saved config to D:\Learning\AutoGluon\image_prediction\7fbdfa91\.trial_0\config.yaml
Model resnet50 created, param count:                                         23528522
AMP not enabled. Training in float32.
Disable EMA as it is not supported for now.
Start training from [Epoch 0]
`time_limit=auto` set to `time_limit=7200`.
Reset labels to [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Randomly split train_data into train[45000]/validation[5000] splits.
The number of requested GPUs is greater than the number of available GPUs.Reduce the number to 1
Starting fit without HPO
modified configs(<old> != <new>): {
root.misc.seed       42 != 225
root.misc.num_workers 4 != 8
root.img_cls.model   resnet101 != resnet50
root.train.early_stop_patience -1 != 10
root.train.batch_size 32 != 16
root.train.epochs    200 != 2
root.train.early_stop_max_value 1.0 != inf
root.train.early_stop_baseline 0.0 != -inf
}
Saved config to D:\Learning\AutoGluon\image_prediction\25b32389\.trial_0\config.yaml
Model resnet50 created, param count:                                         23528522
AMP not enabled. Training in float32.
Disable EMA as it is not supported for now.
Start training from [Epoch 0]
Finished, total runtime is 4.78 s
{ 'best_config': { 'batch_size': 16,
                   'dist_ip_addrs': None,
                   'early_stop_baseline': -inf,
                   'early_stop_max_value': inf,
                   'early_stop_patience': 10,
                   'epochs': 2,
                   'final_fit': False,
                   'gpus': [0],
                   'lr': 0.01,
                   'model': 'resnet50',
                   'ngpus_per_trial': 8,
                   'nthreads_per_trial': 128,
                   'num_workers': 8,
                   'searcher': 'random',
                   'seed': 225,
                   'time_limits': 7200},
  'total_time': 4.780910015106201,
  'train_acc': -1,
  'valid_acc': -1}
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Via20220113\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Via20220113\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Via20220113\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Via20220113\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Via20220113\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Via20220113\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Via20220113\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Learning\AutoGluon\image_prediction\image_pred.py", line 32, in <module>
    predictor.fit(train_data, hyperparameters={'epochs': 2})
  File "C:\Users\Via20220113\AppData\Local\Programs\Python\Python39\lib\site-packages\autogluon\vision\configs\presets_configs.py", line 18, in _call
    return f(*gargs, **gkwargs)
  File "C:\Users\Via20220113\AppData\Local\Programs\Python\Python39\lib\site-packages\autogluon\vision\predictor\predictor.py", line 419, in fit
    self._classifier = task.fit(train_data, tuning_data, 1 - holdout_frac, random_state)
  File "C:\Users\Via20220113\AppData\Local\Programs\Python\Python39\lib\site-packages\autogluon\vision\_gluoncv\image_classification.py", line 421, in fit
    raise RuntimeError(f'Unexpected error happened during fit: {pprint.pformat(results, indent=2)}')
RuntimeError: Unexpected error happened during fit: { 'args': "{'img_cls': {'model': 'resnet50', 'pretrained': True, "
          "'global_pool_type': None}, 'data': {'img_size': None, 'input_size': "
          "None, 'crop_pct': 0.99, 'mean': None, 'std': None, 'interpolation': "
          "'', 'validation_batch_size_multiplier': 1}, 'optimizer': {'opt': "
          "'sgd', 'opt_eps': None, 'opt_betas': None, 'momentum': 0.9, "
          "'weight_decay': 0.0001, 'clip_grad': None, 'clip_mode': 'norm'}, "
          "'train': {'batch_size': 16, 'sched': 'step', 'lr': 0.01, "
          "'lr_noise': None, 'lr_noise_pct': 0.67, 'lr_noise_std': 1.0, "
          "'lr_cycle_mul': 1.0, 'lr_cycle_limit': 1, 'transfer_lr_mult': 0.01, "
          "'output_lr_mult': 0.1, 'warmup_lr': 0.0001, 'min_lr': 1e-05, "
          "'epochs': 2, 'start_epoch': 0, 'decay_epochs': 30, 'warmup_epochs': "
          "3, 'cooldown_epochs': 10, 'patience_epochs': 10, 'decay_rate': 0.1, "
          "'bn_momentum': None, 'bn_eps': None, 'sync_bn': False, "
          "'early_stop_patience': 10, 'early_stop_min_delta': 0.001, "
          "'early_stop_baseline': -inf, 'early_stop_max_value': inf}, "
          "'augmentation': {'no_aug': False, 'scale': (0.08, 1.0), 'ratio': "
          "(0.75, 1.3333333333333333), 'hflip': 0.5, 'vflip': 0.0, "
          "'color_jitter': 0.4, 'auto_augment': None, 'mixup': 0.0, 'cutmix': "
          "0.0, 'cutmix_minmax': None, 'mixup_prob': 1.0, 'mixup_switch_prob': "
          "0.5, 'mixup_mode': 'batch', 'mixup_off_epoch': 0, 'smoothing': 0.1, "
          "'train_interpolation': 'random', 'drop': 0.0, 'drop_path': None, "
          "'drop_block': None}, 'model_ema': {'model_ema': True, "
          "'model_ema_force_cpu': False, 'model_ema_decay': 0.9998}, 'misc': "
          "{'seed': 225, 'log_interval': 50, 'num_workers': 8, 'save_images': "
          "False, 'amp': False, 'apex_amp': False, 'native_amp': False, "
          "'pin_mem': False, 'prefetcher': False, 'eval_metric': 'top1', "
          "'tta': 0, 'use_multi_epochs_loader': False, 'torchscript': False}, "
          "'gpus': [0]}",
  'time': 4.780910015106201,
  'traceback': 'Traceback (most recent call last):\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\autogluon\\vision\\_gluoncv\\image_classification.py", '
               'line 191, in _train_image_classification\n'
               '    result = estimator.fit(train_data=train_data, '
               'val_data=val_data, time_limit=wall_clock_tick-tic)\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\gluoncv\\auto\\estimators\\base_estimator.py", '
               'line 175, in fit\n'
               '    ret = self._fit(train_data, val_data, '
               'time_limit=time_limit) if not resume else \\\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\gluoncv\\auto\\estimators\\torch_image_classification\\torch_image_classification.py", '
               'line 123, in _fit\n'
               '    return self._resume_fit(train_data, val_data, '
               'time_limit=time_limit)\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\gluoncv\\auto\\estimators\\torch_image_classification\\torch_image_classification.py", '
               'line 201, in _resume_fit\n'
               '    return self._train_loop(train_loader, val_loader, '
               'time_limit=time_limit)\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\gluoncv\\auto\\estimators\\torch_image_classification\\torch_image_classification.py", '
               'line 239, in _train_loop\n'
               '    train_metrics = self.train_one_epoch(\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\gluoncv\\auto\\estimators\\torch_image_classification\\torch_image_classification.py", '
               'line 324, in train_one_epoch\n'
               '    for batch_idx, (input, target) in enumerate(loader):\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\torch\\utils\\data\\dataloader.py", '
               'line 354, in __iter__\n'
               '    self._iterator = self._get_iterator()\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\torch\\utils\\data\\dataloader.py", '
               'line 305, in _get_iterator\n'
               '    return _MultiProcessingDataLoaderIter(self)\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\torch\\utils\\data\\dataloader.py", '
               'line 918, in __init__\n'
               '    w.start()\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\multiprocessing\\process.py", '
               'line 121, in start\n'
               '    self._popen = self._Popen(self)\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\multiprocessing\\context.py", '
               'line 224, in _Popen\n'
               '    return '
               '_default_context.get_context().Process._Popen(process_obj)\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\multiprocessing\\context.py", '
               'line 327, in _Popen\n'
               '    return Popen(process_obj)\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\multiprocessing\\popen_spawn_win32.py", '
               'line 45, in __init__\n'
               '    prep_data = spawn.get_preparation_data(process_obj._name)\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\multiprocessing\\spawn.py", '
               'line 154, in get_preparation_data\n'
               '    _check_not_importing_main()\n'
               '  File '
               '"C:\\Users\\Via20220113\\AppData\\Local\\Programs\\Python\\Python39\\lib\\multiprocessing\\spawn.py", '
               'line 134, in _check_not_importing_main\n'
               "    raise RuntimeError('''\n"
               'RuntimeError: \n'
               '        An attempt has been made to start a new process before '
               'the\n'
               '        current process has finished its bootstrapping phase.\n'
               '\n'
               '        This probably means that you are not using fork to '
               'start your\n'
               '        child processes and you have forgotten to use the '
               'proper idiom\n'
               '        in the main module:\n'
               '\n'
               "            if __name__ == '__main__':\n"
               '                freeze_support()\n'
               '                ...\n'
               '\n'
               '        The "freeze_support()" line can be omitted if the '
               'program\n'
               '        is not going to be frozen to produce an executable.\n',
  'train_acc': -1,
  'valid_acc': -1}

My PC environment:

autogluon               0.4.0
autogluon.common        0.4.0
autogluon-contrib-nlp   0.0.1b20220208
autogluon.core          0.4.0
autogluon.features      0.4.0
autogluon.tabular       0.4.0
autogluon.text          0.4.0
autogluon.vision        0.4.0

Hardware: i5-10210U+8G RAM+MX330

TabularPredictor is OK in my PC. ImagePredictor is running with 'raise RuntimeError(f'Unexpected error happened during fit: {pprint.pformat(results, indent=2)}'). No output after  '' 'valid_acc': -1} '' and the program is running alwanys.

**Comment by Innixma** [comment]
You do not have a compatible GPU to train image models. The GPU you mention (MX330) is not capable of running CUDA.

Refer to CUDA compatible GPUs: https://developer.nvidia.com/cuda-gpus

**Comment by 155cannon** [comment]
Later I used ubuntu 20.04 (6700hq+8g ram+gtx 1060 6g), the same error
