### ISSUE TITLE
What is LightGBMXT(bag LightGBM and XTModel? ) and  LightGBMLarge means? 

### ISSUE THREAD

**Issue by acrackedpolystyreneman** [awslabs/autogluon#1729]
### Describe the issue linked to the documentation

What is the specific implications of these two models: LightGBMXT and  LightGBMLarge?

**Comment by ranamahmud** [comment]
I'm interested to contribute.

**Comment by acrackedpolystyreneman** [comment]
王相麾已经收到，谢谢你的来信~

**Comment by Innixma** [comment]
For LightGBMXT, it is simply enabling the `extra_trees=True` LightGBM hyperparameter. https://github.com/awslabs/autogluon/blob/master/tabular/src/autogluon/tabular/configs/hyperparameter_configs.py#L10

For LightGBMLarge, it is using this hyperparameter config: https://github.com/awslabs/autogluon/blob/master/tabular/src/autogluon/tabular/models/lgb/hyperparameters/parameters.py#L43-L51

**Comment by acrackedpolystyreneman** [comment]
Thank you for your answer. I also want to ask is the difference between NeuralNetFastAI and NeuralNetTorch just different platforms? Are there any specific parameter Settings?

**Comment by acrackedpolystyreneman** [comment]
> For LightGBMXT, it is simply enabling the `extra_trees=True` LightGBM hyperparameter. https://github.com/awslabs/autogluon/blob/master/tabular/src/autogluon/tabular/configs/hyperparameter_configs.py#L10
> 
> For LightGBMLarge, it is using this hyperparameter config: https://github.com/awslabs/autogluon/blob/master/tabular/src/autogluon/tabular/models/lgb/hyperparameters/parameters.py#L43-L51

Thank you for your answer. I also want to ask is the difference between **NeuralNetFastAI** and **NeuralNetTorch** just different platforms? Are there any specific parameter Settings?
