### ISSUE TITLE
[BUG]There is no way to load a test set in a target detection task where the images alone are not labeled

### ISSUE THREAD

**Issue by Enderfga** [awslabs/autogluon#1744]
- [√] I have checked that this bug exists on the latest stable version of AutoGluon
- [√] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**

I trained a model, but I can't load the test set smoothly when I want to predict the result, and there is no official documentation about the method

**Comment by Enderfga** [comment]
The problem I'm having is that my test set only has images and no other information, which doesn't seem to work in the existing load function.
But in the end I found that I could load a dataframe with one column of image storing the image address and one column of class storing the Bbox (which I actually set to empty), which successfully loaded and predicted using the model.

**Comment by Innixma** [comment]
> The problem I'm having is that my test set only has images and no other information, which doesn't seem to work in the existing load function. But in the end I found that I could load a dataframe with one column of image storing the image address and one column of class storing the Bbox (which I actually set to empty), which successfully loaded and predicted using the model.

@Enderfga Thanks for creating an issue!

Apologies that the documentation wasn't sufficient. Would you be open to sharing the code you used to solve or providing a suggestion for how the documentation could be improved?
