### ISSUE TITLE
Automated Feature Selection - When Used?

### ISSUE THREAD

**Issue by impulsecorp** [awslabs/autogluon#1749]
I understand how the automated feature selection works, as explained at https://github.com/awslabs/autogluon/pull/1274, and I understand it is used automatically, but I don't see any info about it in the output when I train the model. It tells me if it adds features using feature generation but I see nothing about feature selection, even when I use presets='best_quality'.

**Comment by Innixma** [comment]
Currently automated feature selection is not enabled by default as we haven't had time to test it thoroughly. It is available to be enabled via the .fit `feature_prune_kwargs` argument: https://auto.gluon.ai/stable/api/autogluon.task.html#autogluon.tabular.TabularPredictor.fit

```
predictor.fit(..., feature_prune_kwargs={})
```
