### ISSUE TITLE
Utilize Graph Library for Tabular Stack Ensembling Representation

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#175]
@jwmueller , @zhanghang1989 

What are your thoughts on adding NetworkX as a dependency?
https://github.com/networkx/networkx

As I work more on the stack ensembling functionality, I find that it becomes increasingly important to have a DAG (Directed Acyclic Graph) representation where each model is a node and each instance of a model taking inputs from another model being an edge.

This is important because if we want to break from the fully densely connected scheme currently in place, then the existing method of tracking edges (kept in each model object, thus requiring loading of the model to check) will not scale.

This will also allow us to easily cut unnecessary models that aren't parents of the final model

**Comment by zhanghang1989** [comment]
@zheng-da Da is working on DGL, which is a graph library using Gluon. 
Da, how DGL compare with NetworkX?

**Comment by zheng-da** [comment]
DGL is designed for running neural networks on graphs. NetworkX is designed for graph manipulation. If you want a flexible framework for graph manipulation and you don't need to deal with large graphs, I think NetworkX is probably a good fit.

**Comment by Innixma** [comment]
Merged and utilized networkx in #385
