### ISSUE TITLE
Add `TabularPredictor.clone` method

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#1755]
Add `TabularPredictor.clone(path=..., keep=...)` to clone the existing Predictor artifact to a new location on disk or S3, with the subset of models specified by `keep` argument (same logic as in `delete_models`, but only applied to the cloned artifact).

This will allow users to create multiple different deployment configurations of a given artifact without irreversibly altering the original Predictor.

**Comment by sxjscience** [comment]
Should we reuse the `.save()` API?

**Comment by sxjscience** [comment]
Usually `.clone()` can be implemented via `.save()` and `.load()`.

**Comment by Innixma** [comment]
Added in https://github.com/awslabs/autogluon/pull/2071
