### ISSUE TITLE
[BUG] Building wheel for numpy (setup.py): finished with status 'error'

### ISSUE THREAD

**Issue by AAR072** [awslabs/autogluon#1766]
- [✅] I have checked that this bug exists on the latest stable version of AutoGluon
- [✅] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
Autogluon throwing error when building numpy wheel for install 

**Expected behavior**
Install autogluon without errors

**To Reproduce**
I just ran:
```
pip3 install autogluon
```

**Installed Versions**
Newest version

```python
# Autogluon can't be installed so it just gave the import error
Traceback (most recent call last):
  File "C:\Users\Ali-Akber\Desktop\wd.py", line 1, in <module>
    from autogluon.core.utils import show_versions
ModuleNotFoundError: No module named 'autogluon'
```

</details>

**Additional context**
Python version: 3.10
numpy version: 1.22.4
Also gives the same error when installing with conda

**Comment by Innixma** [comment]
AutoGluon is not supported on Python 3.10 as of v0.4 release. Please use Python 3.9, 3.8, or 3.7 and refer to the [official installation instructions](https://auto.gluon.ai/stable/index.html).

Installing with Python 3.10 will install a very old version of AutoGluon prior to us python version capping our releases that will not work.
