### ISSUE TITLE
[BUG] Error when calculation feature importance. (Quantile model)

### ISSUE THREAD

**Issue by easyautoml** [awslabs/autogluon#1794]
When model is builded with problem_type='quantile', I got bug when calculation feature_important.

`predictor.feature_importance(model='RandomForestMSE', data=train_data, feature_stage='transformed_model')`

**Error :**
![image](https://user-images.githubusercontent.com/100541539/172775913-df945da4-3ce3-4bd2-9f4c-2396656748a1.png)

I found that eval_metric function at bellow file required quantile_levels as paramecter, but only y and y_pred_cur given. 
`autogluon\core\src\autogluon\core\utils\utils.py`

**Installed Versions**
autogluon 0.4.0

**Comment by easyautoml** [comment]
The problem is bellow code. 

https://github.com/awslabs/autogluon/blob/3f21e7a3240754bc88ac3e42a7e5c7aee5b2b495/core/src/autogluon/core/utils/utils.py#L712

https://github.com/awslabs/autogluon/blob/3f21e7a3240754bc88ac3e42a7e5c7aee5b2b495/core/src/autogluon/core/utils/utils.py#L765

We need give eval_metric quantile_levels as parameter.

**Comment by leloykun** [comment]
@Innixma @easyautoml, I added a fix here: https://github.com/awslabs/autogluon/pull/1977

**Comment by Innixma** [comment]
Thanks for the fix @leloykun! Closing with merge of #1977.
