### ISSUE TITLE
Add Ensembling to Time Series

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#1808]
Add Weighted ensembling to time series.

I am currently experimenting with my own custom implementation, and am seeing some promising results, but have some questions before I make the code more formalized and send a PR.

TODOs in Prototype:

- [x] Figure out how to theoretically make a weighted ensemble of N models
- [x] Implement prototype, demonstrate improvement from weighted ensemble on 2 models (val score)
- [x] Structure the weighted ensemble API
- [x] Automatically fetch predictions from dependent models when weighted ensemble needs to predict.
- [x] Make weighted ensemble available via leaderboard / predict in Predictor.
- [x] Make weighted ensemble work with an arbitrary number of models
- [x] Make weighted ensemble respect time limit / train fast

Questions to @canerturkmen:

1. When calling `model.score(val_data)` within AbstractTrainer, the result is non-deterministic, and the score changes every call, often by a large amount (upwards of 10% relative error diff). Why can I not control the randomness, and where is the randomness coming from? How can we choose which model is best if the scoring method is non-deterministic?

2. Why does our scoring method calculate scores for a bunch of metrics even if we only want 1 metric? (Found by [diving into](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/evaluation/_base.py#L339-L351) `gluonts/evaluation/_base.py:get_metrics_per_ts` which is what is eventually called from the GluonTS Evaluator). The code looks extremely fragile and is ***very*** slow (ridiculously slow...), making evaluating the strength of candidate ensembles very painful. **This must be fixed** or else weighted ensembling will be at least an order of magnitude longer than training the models in the first place.

3. In `gluonts/evaluation/_base.py:get_metrics_per_ts`, [why is MSE calculated via the mean prediction, but MAPE Is calculated via the median prediction](https://github.com/awslabs/gluon-ts/blob/master/src/gluonts/evaluation/_base.py#L339-L351)? Is this correct?

4. In `SampleForecast`, I'm seeing 100 samples in debugger. It is unclear how these 100 samples were calculated and how they are ordered (is it pure random?). Because of this, it is unclear how to weighted ensemble them together with another model. Because `MAPE` is using median, I can't ignore the weighting of samples between models for metric calculation unlike if it was using mean. For now I am naively assuming I can weight sample N in model 1 with sample N in model 2 to create sample N in ensemble.

**Comment by Innixma** [comment]
Example output of current prototype when fitting 2 models showing a 20% MAPE val score improvement by ensembling:

```
DeepAR SCORE: -0.0028080650404010516
SimpleFeedForward SCORE: -0.0022532218668758963
ENSEMBLE SCORE: -0.0022532218668758963	Weights: [0.0, 1.0]
ENSEMBLE SCORE: -0.002257208005362093	Weights: [0.01, 0.99]
ENSEMBLE SCORE: -0.0022343180565088166	Weights: [0.02, 0.98]
ENSEMBLE SCORE: -0.002215313422931055	Weights: [0.03, 0.97]
ENSEMBLE SCORE: -0.0022208600468528027	Weights: [0.04, 0.96]
ENSEMBLE SCORE: -0.002184199283110651	Weights: [0.05, 0.95]
ENSEMBLE SCORE: -0.002149236938365668	Weights: [0.06, 0.94]
ENSEMBLE SCORE: -0.002160846099515066	Weights: [0.07, 0.93]
ENSEMBLE SCORE: -0.002161629456489401	Weights: [0.08, 0.92]
ENSEMBLE SCORE: -0.0021292491921687637	Weights: [0.09, 0.91]
ENSEMBLE SCORE: -0.0021013510816473924	Weights: [0.1, 0.9]
ENSEMBLE SCORE: -0.002053389713768478	Weights: [0.11, 0.89]
ENSEMBLE SCORE: -0.002015883486486593	Weights: [0.12, 0.88]
ENSEMBLE SCORE: -0.001999557433769403	Weights: [0.13, 0.87]
ENSEMBLE SCORE: -0.0019576420356357156	Weights: [0.14, 0.86]
ENSEMBLE SCORE: -0.001943501255695308	Weights: [0.15, 0.85]
ENSEMBLE SCORE: -0.001936390884595607	Weights: [0.16, 0.84]
ENSEMBLE SCORE: -0.0019021040539345386	Weights: [0.17, 0.83]
ENSEMBLE SCORE: -0.0018931994129242368	Weights: [0.18, 0.82]
ENSEMBLE SCORE: -0.0018947486542333467	Weights: [0.19, 0.81]
ENSEMBLE SCORE: -0.001887077984307086	Weights: [0.2, 0.8]
ENSEMBLE SCORE: -0.001878904076233308	Weights: [0.21, 0.79]
ENSEMBLE SCORE: -0.0018594380020267136	Weights: [0.22, 0.78]
ENSEMBLE SCORE: -0.0018870274564118268	Weights: [0.23, 0.77]
ENSEMBLE SCORE: -0.0018905239078796509	Weights: [0.24, 0.76]
ENSEMBLE SCORE: -0.0018879429512514314	Weights: [0.25, 0.75]
ENSEMBLE SCORE: -0.0018981475669906055	Weights: [0.26, 0.74]
ENSEMBLE SCORE: -0.0018989887677375143	Weights: [0.27, 0.73]
ENSEMBLE SCORE: -0.0019120163439294373	Weights: [0.28, 0.72]
ENSEMBLE SCORE: -0.0019234702279731421	Weights: [0.29, 0.71]
ENSEMBLE SCORE: -0.001925304783690845	Weights: [0.3, 0.7]
ENSEMBLE SCORE: -0.0019170744779241043	Weights: [0.31, 0.69]
ENSEMBLE SCORE: -0.0018852199751971288	Weights: [0.32, 0.68]
ENSEMBLE SCORE: -0.0018636340702143383	Weights: [0.33, 0.67]
ENSEMBLE SCORE: -0.001852298613095547	Weights: [0.34, 0.66]
ENSEMBLE SCORE: -0.0018309871758560264	Weights: [0.35, 0.65]
ENSEMBLE SCORE: -0.001845777459425227	Weights: [0.36, 0.64]
ENSEMBLE SCORE: -0.0018477767877758348	Weights: [0.37, 0.63]
ENSEMBLE SCORE: -0.0018631914112059644	Weights: [0.38, 0.62]
ENSEMBLE SCORE: -0.0018424630880265495	Weights: [0.39, 0.61]
ENSEMBLE SCORE: -0.0018330998966264954	Weights: [0.4, 0.6]
ENSEMBLE SCORE: -0.0018526315463874847	Weights: [0.41, 0.59]
ENSEMBLE SCORE: -0.0018373411377705993	Weights: [0.42, 0.58]
ENSEMBLE SCORE: -0.001842988064466228	Weights: [0.43, 0.57]
ENSEMBLE SCORE: -0.0018216853996799664	Weights: [0.44, 0.56]
ENSEMBLE SCORE: -0.0018290526701831053	Weights: [0.45, 0.55]
ENSEMBLE SCORE: -0.0018450347514579709	Weights: [0.46, 0.54]
ENSEMBLE SCORE: -0.001862274649987617	Weights: [0.47, 0.53]
ENSEMBLE SCORE: -0.0018846520465117399	Weights: [0.48, 0.52]
ENSEMBLE SCORE: -0.0018992174988069796	Weights: [0.49, 0.51]
ENSEMBLE SCORE: -0.0019013258725122742	Weights: [0.5, 0.5]
ENSEMBLE SCORE: -0.0019174529432690267	Weights: [0.51, 0.49]
ENSEMBLE SCORE: -0.001936471335200043	Weights: [0.52, 0.48]
ENSEMBLE SCORE: -0.0019548412409637573	Weights: [0.53, 0.47]
ENSEMBLE SCORE: -0.0019503274974998178	Weights: [0.54, 0.46]
ENSEMBLE SCORE: -0.0019428464958397553	Weights: [0.55, 0.45]
ENSEMBLE SCORE: -0.0019656638865696288	Weights: [0.56, 0.44]
ENSEMBLE SCORE: -0.001974030410253948	Weights: [0.57, 0.43]
ENSEMBLE SCORE: -0.001987966228381544	Weights: [0.58, 0.42]
ENSEMBLE SCORE: -0.0020091808201127487	Weights: [0.59, 0.41]
ENSEMBLE SCORE: -0.0019931224306745854	Weights: [0.6, 0.4]
ENSEMBLE SCORE: -0.0020016147290479497	Weights: [0.61, 0.39]
ENSEMBLE SCORE: -0.002024646043236089	Weights: [0.62, 0.38]
ENSEMBLE SCORE: -0.0020731220971986365	Weights: [0.63, 0.37]
ENSEMBLE SCORE: -0.0020655187565866693	Weights: [0.64, 0.36]
ENSEMBLE SCORE: -0.0020705265525394617	Weights: [0.65, 0.35]
ENSEMBLE SCORE: -0.0021097470957249227	Weights: [0.66, 0.34]
ENSEMBLE SCORE: -0.002136932192495573	Weights: [0.67, 0.33]
ENSEMBLE SCORE: -0.002153916400844777	Weights: [0.68, 0.32]
ENSEMBLE SCORE: -0.002195281072004093	Weights: [0.69, 0.31]
ENSEMBLE SCORE: -0.0021945135700330272	Weights: [0.7, 0.3]
ENSEMBLE SCORE: -0.002210043988154557	Weights: [0.71, 0.29]
ENSEMBLE SCORE: -0.0022287505031181928	Weights: [0.72, 0.28]
ENSEMBLE SCORE: -0.002251946098667197	Weights: [0.73, 0.27]
ENSEMBLE SCORE: -0.0022700782702216793	Weights: [0.74, 0.26]
ENSEMBLE SCORE: -0.0023010582105875907	Weights: [0.75, 0.25]
ENSEMBLE SCORE: -0.0023403741105994407	Weights: [0.76, 0.24]
ENSEMBLE SCORE: -0.002369375879237516	Weights: [0.77, 0.23]
ENSEMBLE SCORE: -0.002373132113452969	Weights: [0.78, 0.22]
ENSEMBLE SCORE: -0.0023888114183798783	Weights: [0.79, 0.21]
ENSEMBLE SCORE: -0.0024215712971560705	Weights: [0.8, 0.2]
ENSEMBLE SCORE: -0.002459275008087041	Weights: [0.81, 0.19]
ENSEMBLE SCORE: -0.0024947108943592063	Weights: [0.82, 0.18]
ENSEMBLE SCORE: -0.0025376121594128257	Weights: [0.83, 0.17]
ENSEMBLE SCORE: -0.0025712668114155337	Weights: [0.84, 0.16]
ENSEMBLE SCORE: -0.0025852167229844167	Weights: [0.85, 0.15]
ENSEMBLE SCORE: -0.0025977295924851794	Weights: [0.86, 0.14]
ENSEMBLE SCORE: -0.0025854727467545585	Weights: [0.87, 0.13]
ENSEMBLE SCORE: -0.0026040278737761626	Weights: [0.88, 0.12]
ENSEMBLE SCORE: -0.0026253303048655967	Weights: [0.89, 0.11]
ENSEMBLE SCORE: -0.0026346981033809475	Weights: [0.9, 0.1]
ENSEMBLE SCORE: -0.002657211481244684	Weights: [0.91, 0.09]
ENSEMBLE SCORE: -0.0026869521091090766	Weights: [0.92, 0.08]
ENSEMBLE SCORE: -0.0027139295839012753	Weights: [0.93, 0.07]
ENSEMBLE SCORE: -0.0027392185806036085	Weights: [0.94, 0.06]
ENSEMBLE SCORE: -0.0027736047395683873	Weights: [0.95, 0.05]
ENSEMBLE SCORE: -0.002808744160763618	Weights: [0.96, 0.04]
ENSEMBLE SCORE: -0.0028393429232428744	Weights: [0.97, 0.03]
ENSEMBLE SCORE: -0.002803442812017864	Weights: [0.98, 0.02]
ENSEMBLE SCORE: -0.002800250075458202	Weights: [0.99, 0.01]
ENSEMBLE SCORE: -0.0028080650404010516	Weights: [1.0, 0.0]

----
BEST SCORE FOUND:
ENSEMBLE SCORE: -0.0018216853996799664	Weights: [0.44, 0.56]

```

Note: Current prototype only works when ensembling 2 models, and doesn't save the ensemble nor make it available during prediction. It also takes an extremely long time to check the score of all the weight options (2-3 seconds per weight pair) due to inefficient scoring method in GluonTS.

**Comment by canerturkmen** [comment]
@Innixma Super cool. Thanks for the effort. Regarding questions:

1/ The source of randomness is the sampling. Many probabilistic forecasting models compute quantiles by sampling from the predictive distribution, and unfortunately GluonTS does not readily give a way to set the seed to the sampling. We can try to set the mxnet random state to control this behavior. As to how we select the best model with sampling error, we should probably increase the number of samples in evaluation -- however this would just increase the inference time. For ensembling, I believe we can fix the 

2/ GluonTS does it like this since the sampling is the compute-intensive step after which the metrics themselves are easy to calculate, so the overhead is thought to be negligible. In our API, we leak the rest of the metrics (that the user didn't ask for). I agree we should implement our own evaluator so we can expose an API that takes predictions + ground_truth + eval_metric and runs deterministically. I will look into this.

3/ This is deliberate, although perhaps not great to hide from the user. The reasoning is that the median minimizes absolute errors while the mean minimizes squared errors.

4/ Yes, I also now see we can't simply ensemble from the predicted TimeSeriesDataFrames, but need the samples. Each sample is an independent trajectory of the future drawn from the model, so your proposition appears correct to me.
