### ISSUE TITLE
python process killed when running the tutorial example

### ISSUE THREAD

**Issue by lianggaoquan** [awslabs/autogluon#181]
![image](https://user-images.githubusercontent.com/26477489/72125826-fec1fa80-33a4-11ea-8521-2952cc1d7677.png)

Run the given example in my local computer and showed this. Is that memory not enough or something else went wrong?

**Comment by Innixma** [comment]
@lianggaoquan Is there a reason you closed this issue? Could you mention the root cause and resolution if you have identified them?
