### ISSUE TITLE
Request for time series forecasting

### ISSUE THREAD

**Issue by alexAlchemy** [awslabs/autogluon#182]
Although I know that you can technically run "managed" deep learning on AWS using Sage Maker I can certainly see the value of a project like this. 

Specifically I'm thinking of https://aws.amazon.com/forecast which runs your forecast for you. 

Do you have any plans to add forecasting to gluon?

Thanks, Alex

**Comment by Innixma** [comment]
Hi Alex,

Forecasting is definitely an important area to expand on in future. We don't have plans laid out for when we would be adding forecasting but we will make sure to update this issue when we have more info!

Best,
Nick

**Comment by zhanghang1989** [comment]
Thanks @alexAlchemy! Agree that adding time series will be important. 

We do have plan to integrate time series using [gluon-ts](https://github.com/awslabs/gluon-ts). An intern starts to implement a autogluon fit for that. It automatically does HPO for time series model. This is toolkit feature instead of manged servies as forecast.

**Comment by mreismendes** [comment]
@zhanghang1989 Has the work moved ahead? I'm so curious about that. It would be amazing having this.

Thank you

**Comment by Innixma** [comment]
@mreismendes Yes this is under development at present. Please refer to #822 for discussion.

**Comment by yx1215** [comment]
The PR related to time-series autoML is #1198 . I think it's almost done. If anyone would like to have a try with it, feel free to do that and let me know if any problem is encountered!

**Comment by mreismendes** [comment]
@yx1215 It can be a silly question for you, but it isn't for me. I've been trying to install this PR to test unsuccessfully, what should I do to try it on Google Colab?
Thank you

**Comment by yx1215** [comment]
> @yx1215 It can be a silly question for you, but it isn't for me. I've been trying to install this PR to test unsuccessfully, what should I do to try it on Google Colab?
> Thank you

This PR is not released yet so I don't think you can run it on Colab.. If you want to give it a try you can download my fork to your local and run ```pip install -e .``` under the forecasting folder. Then you will be able to import everything from autogluon.forecasting

**Comment by Innixma** [comment]
TimeSeries is now available as of v0.5 release via `autogluon.timeseries`! Check out tutorials here: https://auto.gluon.ai/stable/tutorials/timeseries/index.html
