### ISSUE TITLE
[BUG] It is confusing that argument "metrics" in "evaluate(...)" of different predictor has different type requirements.

### ISSUE THREAD

**Issue by FANGAreNotGnu** [awslabs/autogluon#1844]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
It is a bit confusing that:
In [text.text_prediction.predictor](https://github.com/awslabs/autogluon/blob/70af6f34d47eb85779fdcefaf1b94c4a7d16f6da/text/src/autogluon/text/text_prediction/predictor.py#L277), type of "metrics" in function "evaluate(...)" is: str or List[str]. 
In [multimodal.predictor](https://github.com/awslabs/autogluon/blob/70af6f34d47eb85779fdcefaf1b94c4a7d16f6da/multimodal/src/autogluon/multimodal/predictor.py#L1302), it is: List[str]. And [this line](https://github.com/awslabs/autogluon/blob/70af6f34d47eb85779fdcefaf1b94c4a7d16f6da/multimodal/src/autogluon/multimodal/predictor.py#L1364) will cause error if input is a str. 
In [timeseries.predictor](https://github.com/awslabs/autogluon/blob/70af6f34d47eb85779fdcefaf1b94c4a7d16f6da/timeseries/src/autogluon/timeseries/predictor.py#L369), it is str.

**Expected behavior**
They probably should have the same type requirements, e.g. "str or List[str]".

**Comment by sxjscience** [comment]
We may first ensure that [text.text_prediction.predictor](https://github.com/awslabs/autogluon/blob/70af6f34d47eb85779fdcefaf1b94c4a7d16f6da/text/src/autogluon/text/text_prediction/predictor.py#L277), and [multimodal.predictor](https://github.com/awslabs/autogluon/blob/70af6f34d47eb85779fdcefaf1b94c4a7d16f6da/multimodal/src/autogluon/multimodal/predictor.py#L1302) are the same.
