### ISSUE TITLE
Missing version folder in autogluon？

### ISSUE THREAD

**Issue by jianhaod** [awslabs/autogluon#189]
is there any Missing version folder under autogluon？

No matter in PyPI or github source  will meet issue in import process

autogluon/__init__.py 
from .version import __version__

issue log:
ModuleNotFoundError: No module named 'autogluon.version'

i need to delete this version import, so that i can execute package successfully. :)

**Comment by zhanghang1989** [comment]
The version file should be generated automatically during the installation. What's your system setting?

**Comment by austinmw** [comment]
@zhanghang1989 What if installed from master?  `!pip install git+https://github.com/awslabs/autogluon.git`

**Comment by zhanghang1989** [comment]
I haven't tried that. If that doesn't work, you can try:
```
git clone https://github.com/awslabs/autogluon
cd autogluon && python setup.py develop
```

**Comment by austinmw** [comment]
Sorry, should have followed those instructions. that works, thanks.
