### ISSUE TITLE
[BUG] Presets in TimeSeriesPredictor are not working well.

### ISSUE THREAD

**Issue by mreismendes** [awslabs/autogluon#1892]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [x] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**

I realized that only 2 preset options are working well. I tested the new release of TimeSeriesPredictor on different presets, i.e ("best_quality", "high_quality", "good_quality", "medium_quality", "low_quality", and "low_quality_hpo").

Only "medium_quality" and  "low_quality" are working. I noticed the other presets forces hyperparameterization of the models, then, when it starts it breaks.

**To Reproduce**
1) ```predictor = TimeSeriesPredictor(
    target="value",
    prediction_length=prediction_length,
    eval_metric="MAPE",
    verbosity=4)
    
    predictor.fit(train_data=test_data,
    presets ='best_quality')```

2) ```predictor = TimeSeriesPredictor(
    target="value",
    prediction_length=prediction_length,
    eval_metric="MAPE",
    verbosity=4)

    predictor.fit(train_data=test_data,
    presets ='medium_quality')```

**Screenshots**
1)![image](https://user-images.githubusercontent.com/32521301/175453958-26c759cf-4584-48e1-9541-752a49d2ab0e.png)

2)![image](https://user-images.githubusercontent.com/32521301/175454034-d7151c62-4859-43be-a90a-d4e5124485d3.png)

**Installed Versions**
Which version of AutoGluon are you are using?  
0.5.0

**Comment by canerturkmen** [comment]
Thank you for raising this issue @mreismendes . It appears that HPO did not play well with custom-specified target field names. A fix is in progress at #1901
