### ISSUE TITLE
TextPredictor CUDA preferences

### ISSUE THREAD

**Issue by jturner116** [awslabs/autogluon#1944]
I wasn't sure to report this as a bug or not, but in case anyone else comes across the same issue, I had followed the installation instructions with 

"torch>=1.0,<1.11+cu113"

, but TextPredictor was throwing a CUDA error. Setting the version to

 "torch==1.11+cu113" 

seemed to fix the issue. I think before specifying I was on Torch 1.10.2. 

Thanks!

**Comment by sxjscience** [comment]
@Innixma we may need a website tag as this is related to our website.

**Comment by sxjscience** [comment]
@jturner116 The website has been updated.
