### ISSUE TITLE
[BUG] Cannot install AutoGluon in Anaconda

### ISSUE THREAD

**Issue by Kuaranir** [awslabs/autogluon#1960]
I tried `conda install autogluon`, `conda install -c autogluon` and got it:

**PackagesNotFoundError**: The following packages are not available from current channels:

  - autogluon

Current channels:
  - https://conda.anaconda.org/anaconda/linux-64
  - https://conda.anaconda.org/anaconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

**Comment by jhmenke** [comment]
Neither the github nor the official website states that you can install autogluon via conda. It's also not listed in conda-forge, so you will have to install either via source or pip.
