### ISSUE TITLE
how to use autogluon on RetinaFace

### ISSUE THREAD

**Issue by lunasdejavu** [awslabs/autogluon#198]
I'd like to use autogluon on this [github](https://github.com/deepinsight/insightface/tree/master/RetinaFace)

since it is not a normal object detection but also generate keypoints too.
how should I use autogluon?

**Comment by zhanghang1989** [comment]
You can using AutoGluon to optimize Hyperparameters on any training code by adding  a few lines of code. A simple example can be found here https://autogluon.mxnet.io/tutorials/torch/hpo.html

For more detailed customizatons, you may look into https://autogluon.mxnet.io/tutorials/course/index.html
