### ISSUE TITLE
How to specify which GPU to run on

### ISSUE THREAD

**Issue by enduringstack** [awslabs/autogluon#199]
How to specify which GPU to run on？ tks.

**Comment by zhanghang1989** [comment]
Currently AutoGluon automatically detect all the CPUs and GPUs, and schedule training jobs automatically based on availability. There is no mannual option.

**Comment by banderlog** [comment]
From https://auto.gluon.ai/dev/tutorials/tabular_prediction/tabular-faq.html :

>Can I use GPUs for model training?
>
>Yes! Most of the models used by AutoGluon support GPU training, including LightGBM, CatBoost, XGBoost, MXNet Neural Network, and FastAI Neural Network.
>
>To enable GPU training, specify in predictor.fit the argument ag_args_fit={'num_gpus': 1}. This will enable GPU training for all models that support it. Multi-GPU training is still experimental.
>
>For most of these models, CUDA will have to be installed and some models may need special installations such as LightGBM and MXNet to be compatible with GPU training. Refer to installation instructions for more details.
