### ISSUE TITLE
predict_proba for timeseries forecasting

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#2023]
### Discussed in https://github.com/awslabs/autogluon/discussions/2021

<div type='discussions-op-text'>

<sup>Originally posted by **pj-mathematician** August  8, 2022</sup>
Hi, I am using this module for my project. I need to find the probability for each of the classes for each timestep but I am not able to find the predict_proba() method for the timeseries predictor class. 
The best model is AutoETS and the sktime AutoETS does have a predict proba functionality. Is there any workaround so that i can generate probabilities here too?
Thanks</div>

**Comment by canerturkmen** [comment]
Hi! Thanks for raising this issue. cc: @pj-mathematician 

`autogluon.timeseries` focuses on time series forecasting as a task and by the definition we rely on; the time series predictions are expected to be real (continuous) values. For example, see [here](https://otexts.com/fpp3/perspective.html). As such, we always return expected values and quantiles of predicted values in response to `TimeSeriesPredictor.fit`. This assumption is also implicit in all forecasting libraries `autogluon.timeseries` depends on.

As we do not have support for discrete valued sequences in the roadmap, we will not be implementing `predict_proba` in the `TimeSeriesPredictor` API. For such tasks I can recommend other libraries such as [hmmlearn](https://github.com/hmmlearn/hmmlearn), or to use AutoGluon-Tabular in a sliding-window fashion.

I hope this helps.

**Comment by pj-mathematician** [comment]
Thanks for your reply, I will check out the libraries you suggested and will try auto sliding with AG-Tabular. Great library with amazing functionalities.
This issue can be closed.
