### ISSUE TITLE
Normalize unicode data preprocess feature for tabular data

### ISSUE THREAD

**Issue by MountPOTATO** [awslabs/autogluon#2036]
Hi, I’m using autogluon’s AutoMMPredictor to take part in a Kaggle contest https://www.kaggle.com/competitions/feedback-prize-effectiveness , a multi-class classification task for text tabular data (to classify argumentative elements in student writing as “effective”, “adequate”, or “ineffective” to be specific). 

During the contest I found some trick for text data preprocess and wonder if a similar feature like this could be added to autogluon.

In some high-ranked solution’s code like https://www.kaggle.com/code/quclongphan/deberta-v3-training, I found some normalize Unicode method applied in the data preprocessing of the tabular text data in order to resolve the encoding problems and normalize the abnormal characters:

```python
from text_unidecode import unidecode 
from typing import Dict, List, Tuple
import codecs

# codecs error handlers
def replace_encoding_with_utf8(error: UnicodeError) -> Tuple[bytes, int]:
    return error.object[error.start : error.end].encode("utf-8"), error.end

def replace_decoding_with_cp1252(error: UnicodeError) -> Tuple[str, int]:
    return error.object[error.start : error.end].decode("cp1252"), error.end

# Register the encoding and decoding error handlers for `utf-8` and `cp1252`.
codecs.register_error("replace_encoding_with_utf8", replace_encoding_with_utf8)
codecs.register_error("replace_decoding_with_cp1252", replace_decoding_with_cp1252)

# core function, resolve the encoding problems and normalize the abnormal characters.
def resolve_encodings_and_normalize(text: str) -> str:
    text = (
        text.encode("raw_unicode_escape")
        .decode("utf-8", errors="replace_decoding_with_cp1252")
        .encode("cp1252", errors="replace_encoding_with_utf8")
        .decode("utf-8", errors="replace_decoding_with_cp1252")
    )
    text = unidecode(text)
    return text
```

This code is applied on the text content in the tabular data frame. In this code, the text goes through a encode-decode process with ‘utf-8’ and ‘cp1252’(using the python encode() and decode() function). Meanwhile, it uses codecs package to register the encode() and decode()’s error handlers). Then the unidecode() is applied to do an ASCII transliterations to Unicode text, as well as fixing the string with abnormal characters (the input string may contains non-ASCII characters, and unidecode’s output string are safe to be encoded to ASCII). There seems to be improvement after applying this to the task.

To be noted, the Kaggle contest is an English-only task, but unidecode() also supports some multi-language(non-Roman names on US-keyboard) processing. It might be useful to the autogluon’s multilingual predictor in some specific tasks.

The unidecode’s PyPI link: https://pypi.org/project/Unidecode/

**Comment by sxjscience** [comment]
@suzhoum and I will take a look at text normalization.

**Comment by sxjscience** [comment]
For supporting this feature, we may consider to extend the preprocessing logic for text: https://github.com/awslabs/autogluon/blob/69f70d5dab3815e2639589c4fd6910ce0be431a8/multimodal/src/autogluon/multimodal/data/preprocess_dataframe.py#L297-L333

**Comment by suzhoum** [comment]
Hi @MountPOTATO , we have merged the feature in the above PR. You should now be able to apply text normalization following the tutorial [here](https://github.com/awslabs/autogluon/blob/master/docs/tutorials/multimodal/customization.md#datatextnormalize_text)
