### ISSUE TITLE
Unable to use FT Transformer for tabular data

### ISSUE THREAD

**Issue by manmeet3591** [awslabs/autogluon#2041]
I want to use FT Transformer for tabular data. As mentioned in the notes for the release 0.4.1, the model is present for autogluon. I have tried with versions 0.5.2 and 0.4.1 on tabular data, but it seems that the model is not getting picked up. Do I need to add an argument separately ?

**Comment by sxjscience** [comment]
@manmeet3591 You need to manually specify the flag for using FT-Transformer. See the example: https://github.com/awslabs/autogluon/tree/master/examples/automm/tabular_dl.

Also, you can manually enable it by following https://github.com/awslabs/autogluon/blob/6cba21d74374e649a2f3040d0bce5f40c4bbb0f5/examples/automm/tabular_dl/example_tabular.py#L82-L90.

**Comment by manmeet3591** [comment]
Thank you @sxjscience
