### ISSUE TITLE
Missing documentation about multimodal matching

### ISSUE THREAD

**Issue by rhkenne** [awslabs/autogluon#2050]
### Describe the issue linked to the documentation

Thank you for the multimodal matching feature.  It is a great feature.

Do you have any example or code snippet that showcase how to use this feature ? I was looking for an approach to perform multimodal document pairs classification or regression

An example of a multimodal document will be product listing containing title, description & image.

Any tips would help, thank you

**Comment by sxjscience** [comment]
Thanks for posting the issue. We are actively improving the multimodal matching feature in AutoMM, and are targeting at 0.6.

**Comment by Innixma** [comment]
@rhkenne Documentation for matching is now available here: https://auto.gluon.ai/dev/tutorials/multimodal/matching/index.html
