### ISSUE TITLE
What languages does the TabularPredictor support in multimodal mode?

### ISSUE THREAD

**Issue by Paandaman** [awslabs/autogluon#2059]
I haven't been able to find any documentation about what languages the TabularPredictor supports so I've just assumed that it only uses models trained on English at the moment. This issue https://github.com/awslabs/autogluon/issues/1495 suggests that there has been work done to support multiple languages for the TextPredictor but is something similar available for the TabularPredictor? I can't find any arguments to specify e.g. what specific huggingface model to use!

**Comment by sxjscience** [comment]
For now, we support the multilingual presets in `autogluon.multimodal`: https://auto.gluon.ai/stable/tutorials/multimodal/multilingual_text.html . I will recommend trying out `autogluon.multimodal` first if you are dealing with text in other languages.

@Paandaman

**Comment by Innixma** [comment]
TabularPredictor uses ngrams for its text support. This supports languages that work natively with ngrams (such as latin languages). However, languages without a 'space' character between words will not work well, such as Japanese.

**Comment by Paandaman** [comment]
Thank you both for the answers! 

If I understand things correctly, the TabularPredictor also includes an autogluon.multimodal model in its ensemble. Is it possible to configure that multimodal model to use a multilingual setting? 
The language that I'm working with is Korean so I think it should be fine with ngrams, however I don't think the autogluon.multimodal model would perform very well if it uses a model trained on English which is why I would like to use a multilingual model!

**Comment by sxjscience** [comment]
Yes, we can configure the AG_TEXT model to use the multilingual variant. Before proceeds with that option, would you like to try to train a model with “multilingual” preset in the MultiModalPredictor first? We can see the performance and configure Tabular to use the multilingual variant of MultiModalPredictor afterwards.

**Comment by Paandaman** [comment]
Great, thanks for the suggestion! That sounds like a good idea, I'll give it a try! 
I'll experiment around with this for a bit but I think the issue is solved so I will close it now. Thanks for the help and for your work with Autogluon!
