### ISSUE TITLE
Failed install on linux with anaconda

### ISSUE THREAD

**Issue by Charlie2-0** [awslabs/autogluon#215]
version information:
Python 3.7.4 (default Aug 13 2019, 20:35:49)
[GCC 7.3.0] :: Anaconda, Inc. on linux

mxnet installed fine, autogluon threw an error:

Running setup.py install for ConfigSpace ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-220w4kjx/ConfigSpace/setup.py'"'"'; __file__='"'"'/tmp/pip-install-220w4kjx/ConfigSpace/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tlrdygdv/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-220w4kjx/ConfigSpace/
    Complete output (61 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/test
    copying test/__init__.py -> build/lib.linux-x86_64-3.7/test
    copying test/test_configuration_space.py -> build/lib.linux-x86_64-3.7/test
    copying test/test_hyperparameters.py -> build/lib.linux-x86_64-3.7/test
    copying test/test_util.py -> build/lib.linux-x86_64-3.7/test
    copying test/test_forbidden.py -> build/lib.linux-x86_64-3.7/test
    copying test/test_conditions.py -> build/lib.linux-x86_64-3.7/test
    creating build/lib.linux-x86_64-3.7/ConfigSpace
    copying ConfigSpace/__init__.py -> build/lib.linux-x86_64-3.7/ConfigSpace
    copying ConfigSpace/exceptions.py -> build/lib.linux-x86_64-3.7/ConfigSpace
    copying ConfigSpace/convert.py -> build/lib.linux-x86_64-3.7/ConfigSpace
    copying ConfigSpace/__version__.py -> build/lib.linux-x86_64-3.7/ConfigSpace
    creating build/lib.linux-x86_64-3.7/test/read_and_write
    copying test/read_and_write/__init__.py -> build/lib.linux-x86_64-3.7/test/read_and_write
    copying test/read_and_write/test_pyll_util.py -> build/lib.linux-x86_64-3.7/test/read_and_write
    copying test/read_and_write/test_irace_writer.py -> build/lib.linux-x86_64-3.7/test/read_and_write
    copying test/read_and_write/test_pcs_converter.py -> build/lib.linux-x86_64-3.7/test/read_and_write
    copying test/read_and_write/test_pb_converter.py -> build/lib.linux-x86_64-3.7/test/read_and_write
    copying test/read_and_write/test_json.py -> build/lib.linux-x86_64-3.7/test/read_and_write
    creating build/lib.linux-x86_64-3.7/test/test_searchspaces
    copying test/test_searchspaces/__init__.py -> build/lib.linux-x86_64-3.7/test/test_searchspaces
    creating build/lib.linux-x86_64-3.7/test/test_converters_and_test_searchspaces
    copying test/test_converters_and_test_searchspaces/__init__.py -> build/lib.linux-x86_64-3.7/test/test_converters_and_test_searchspaces
    copying test/test_converters_and_test_searchspaces/test_sample_configuration_spaces.py -> build/lib.linux-x86_64-3.7/test/test_converters_and_test_searchspaces
    creating build/lib.linux-x86_64-3.7/ConfigSpace/read_and_write
    copying ConfigSpace/read_and_write/__init__.py -> build/lib.linux-x86_64-3.7/ConfigSpace/read_and_write
    copying ConfigSpace/read_and_write/spearmint_april2013_mod_spearmint_pb2.py -> build/lib.linux-x86_64-3.7/ConfigSpace/read_and_write
    copying ConfigSpace/read_and_write/json.py -> build/lib.linux-x86_64-3.7/ConfigSpace/read_and_write
    copying ConfigSpace/read_and_write/pyll.py -> build/lib.linux-x86_64-3.7/ConfigSpace/read_and_write
    copying ConfigSpace/read_and_write/pcs.py -> build/lib.linux-x86_64-3.7/ConfigSpace/read_and_write
    copying ConfigSpace/read_and_write/pbs.py -> build/lib.linux-x86_64-3.7/ConfigSpace/read_and_write
    copying ConfigSpace/read_and_write/irace.py -> build/lib.linux-x86_64-3.7/ConfigSpace/read_and_write
    copying ConfigSpace/read_and_write/pcs_new.py -> build/lib.linux-x86_64-3.7/ConfigSpace/read_and_write
    creating build/lib.linux-x86_64-3.7/ConfigSpace/nx
    copying ConfigSpace/nx/__init__.py -> build/lib.linux-x86_64-3.7/ConfigSpace/nx
    copying ConfigSpace/nx/exception.py -> build/lib.linux-x86_64-3.7/ConfigSpace/nx
    copying ConfigSpace/nx/release.py -> build/lib.linux-x86_64-3.7/ConfigSpace/nx
    creating build/lib.linux-x86_64-3.7/ConfigSpace/nx/algorithms
    copying ConfigSpace/nx/algorithms/cycles.py -> build/lib.linux-x86_64-3.7/ConfigSpace/nx/algorithms
    copying ConfigSpace/nx/algorithms/__init__.py -> build/lib.linux-x86_64-3.7/ConfigSpace/nx/algorithms
    copying ConfigSpace/nx/algorithms/dag.py -> build/lib.linux-x86_64-3.7/ConfigSpace/nx/algorithms
    creating build/lib.linux-x86_64-3.7/ConfigSpace/nx/classes
    copying ConfigSpace/nx/classes/__init__.py -> build/lib.linux-x86_64-3.7/ConfigSpace/nx/classes
    copying ConfigSpace/nx/classes/digraph.py -> build/lib.linux-x86_64-3.7/ConfigSpace/nx/classes
    copying ConfigSpace/nx/classes/graph.py -> build/lib.linux-x86_64-3.7/ConfigSpace/nx/classes
    creating build/lib.linux-x86_64-3.7/ConfigSpace/nx/algorithms/components
    copying ConfigSpace/nx/algorithms/components/__init__.py -> build/lib.linux-x86_64-3.7/ConfigSpace/nx/algorithms/components
    copying ConfigSpace/nx/algorithms/components/strongly_connected.py -> build/lib.linux-x86_64-3.7/ConfigSpace/nx/algorithms/components
    running build_ext
    skipping 'ConfigSpace/hyperparameters.c' Cython extension (up-to-date)
    building 'ConfigSpace.hyperparameters' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/ConfigSpace
    gcc -pthread -B /home/ubuntu/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/home/ubuntu/anaconda3/include/python3.7m -c ConfigSpace/hyperparameters.c -o build/temp.linux-x86_64-3.7/ConfigSpace/hyperparameters.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ubuntu/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-220w4kjx/ConfigSpace/setup.py'"'"'; __file__='"'"'/tmp/pip-install-220w4kjx/ConfigSpace/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-tlrdygdv/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by zhanghang1989** [comment]
Looks like a bug during installing `ConfigSpace`. Does `pip install ConfigSpace` work?

**Comment by Charlie2-0** [comment]
`pip install ConfigSpace` failed because of `gcc` however I was under the impression I had this already. Either way running:

`sudo apt-get install gcc` was successful and allowed me to install configspace. Autogluon installed fine after that.

Many thanks for the help. I'll close the issue and leave this answer here for reference
