### ISSUE TITLE
KeyError: 'choice' 

### ISSUE THREAD

**Issue by myBestLove** [awslabs/autogluon#216]
thx for your work.

Is this a bug or I use the API wrong?

import autogluon as ag
a = ag.space.Categorical(*list(range(0,5)))
a.sample() 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/autogluon/core/space.py", line 329, in sample
    choice = config.pop('choice')
KeyError: 'choice'

**Comment by zhanghang1989** [comment]
`sample` method is not supposed to be called by the user. Could you try `a.rand`?
Please se more information in the [tutorial](https://autogluon.mxnet.io/tutorials/course/core.html)

**Comment by Innixma** [comment]
Resolving. Please reopen if you wish to clarify the problem.
