### ISSUE TITLE
Front page example is wrong

### ISSUE THREAD

**Issue by tigerhawkvok** [awslabs/autogluon#217]
Given the front page first example:

![image](https://user-images.githubusercontent.com/165937/72472065-b5085400-3798-11ea-8eb6-85073cd9f090.png)

Immediately throws a `TypeError`:

![image](https://user-images.githubusercontent.com/165937/72472122-d36e4f80-3798-11ea-9c74-00d4994d7208.png)

The documentation under [TabularPrediction.fit](https://autogluon.mxnet.io/api/autogluon.task.html#autogluon.task.TabularPrediction.fit) is correct, and the keyword should be `label`, not `label_column`.

**Comment by jwmueller** [comment]
Thanks for pointing this out, it is fixed in this PR:  https://github.com/awslabs/autogluon/pull/220
