### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by harman-brar** [awslabs/autogluon#2182]
I'm running the following on an Ubuntu virtualbox:

`df = pd.read_csv('./Datasets/petfinder_example.csv')`
`csv = df.to_csv()`
`df2 = ImageDataset.from_csv(csv, root="/home/me/Images")`
`df2.head()`

Somewhat according to the [docs](https://auto.gluon.ai/dev/tutorials/image_prediction/dataset.html), and I get the following error:

> OSError: [Errno 36] File name too long: ',image,PetID,label\n0,petfinder_data/train_images/015da9e87-1.jpg,015da9e87,0\n1,petfinder_data/train_images/022606901-1.jpg,022606901,0\n2,petfinder_data/train_images/02f89bdcb-1.jpg,02f89bdcb,0\n3,petfinder_data/train_images/03f217352-1.jpg,03f217352,0\n4,petfinder_data/train_images/040a9a6f9-1.jpg,040a9a6f9,0\n5,petfinder_data/train_images/0529ad4d9-1.jpg,0529ad4d9,0\n6,petfinder_data/train_images/056bb97e4-1.jpg,056bb97e4,0\n7,petfinder_data/train_images/056bf1b17-1.jpg,056bf1b17,0\n8,petfinder_data/train_images/06ecc204f-1.jpg,06ecc204f,0\n9,petfinder_data/train_images/06ed12b93-1.jpg,06ed12b93,0\n10,petfinder_data/train_images/07417927d-1.jpg,07417927d,0\n11,petfinder_data/train_images/081c0a12d-1.jpg,081c0a12d,0\n12,petfinder_data/train_images/092a37bcf-1.jpg,092a37bcf,0\n13,petfinder_data/train_images/0a4b42306-1.jpg,0a4b42306,0\n14,petfinder_data/train_images/0a555d688-1.jpg,0a555d688,0\n15,petfinder_data/train_images/0c0214da4-1.jpg,0c0214da4,0\n16,petfinder_data/train_images/0cf7fae9d-1.jpg,0cf7fae9d,0\n17,petfinder_data/train_images/0d6cb5b69-1.jpg, ...

Changing the length of the file names does not resolve the issue. I do see mention of OSErrors in the documentation but I was under the impression that adding `root="/home/me/Images"` would resolve the issue.

Anyone have any insight as to what's going on?

**Comment by sxjscience** [comment]
Let’s see if we can reproduce it.

**Comment by sxjscience** [comment]
@harman-brar Would you suggest how we may reproduce this error?

**Comment by harman-brar** [comment]
@sxjscience An option might be to spin up an instance with the compute limits I have set on my VirtualBox before running the aforementioned code in a jupyter notebook.

This seems like a lot of effort, however, so if you don't have any issues with the code I have posted above, then I will try another environment myself.

One thing I would like to ask, though, is whether the problem maybe caused by running only the following installation commands:

```
pip3 install -U pip
pip3 install -U setuptools wheel

# CPU version of pytorch has smaller footprint - see installation instructions in
# pytorch documentation - https://pytorch.org/get-started/locally/
pip3 install torch==1.12+cpu torchvision==0.13.0+cpu torchtext==0.13.0 -f https://download.pytorch.org/whl/cpu/torch_stable.html

pip3 install autogluon
```
From: https://auto.gluon.ai/stable/install.html

Maybe I have an improper installation?

**Comment by harman-brar** [comment]
I will go through the installation doc in more detail in a few days and get back to you :)

**Comment by xhulianoThe1** [comment]
Can you try downloading the csv file directly? 
`
csv_file = ag.utils.download('https://autogluon.s3-us-west-2.amazonaws.com/datasets/petfinder_example.csv')
df2 = ImageDataset.from_csv(csv_file, root="/home/me/Images")
df2.head()
`

**Comment by harman-brar** [comment]
Hi all, sorry for the late response. I hope to get back to you with more details by early next week.

**Comment by harman-brar** [comment]
> Can you try downloading the csv file directly? ` csv_file = ag.utils.download('https://autogluon.s3-us-west-2.amazonaws.com/datasets/petfinder_example.csv') df2 = ImageDataset.from_csv(csv_file, root="/home/me/Images")` `df2.head()`

This works fine. Also, I've discovered the following for local CSVs after digging deeper into the docs: 

> Note that we loaded data from a CSV file stored in the cloud ([AWS s3 bucket](https://aws.amazon.com/s3/)), but you can you specify a local file-path instead if you have already downloaded the CSV file to your own machine (e.g., using [wget](https://www.gnu.org/software/wget/))

This information would be useful in a generalized, not hidden under the tabular prediction section! I will try this at some point

**Comment by Innixma** [comment]
You need to save `csv` to an actual file. You are currently passing `csv` as the entire contents of the DataFrame as a string.
