### ISSUE TITLE
0.0.4version---No module named 'autogluon.contrib.torch'

### ISSUE THREAD

**Issue by HollrayChan** [awslabs/autogluon#224]
The following code yields an error. My autogluon version is 0.0.4.When I run the example in the 
 file ./exmaple/torch/train_enas_imagent.py, I met an error.
`import autogluon as ag
from autogluon.contrib.torch import *
from autogluon import Dict, Categorical
from autogluon.model_zoo.models.utils import _update_input_size

Traceback (most recent call last):
  File "train_enas_imagenet.py", line 5, in <module>
    from autogluon.contrib.torch import *
ModuleNotFoundError: No module named 'autogluon.contrib.torch'
`
but it's ok in version 0.0.3.

**Comment by zhanghang1989** [comment]
Looks like you are using an older/wrong version of the training script. Could you try the current version:

https://github.com/awslabs/autogluon/blob/master/examples/nas/train_enas_imagenet.py#L5

**Comment by HollrayChan** [comment]
It's ok.thx~

**Comment by Innixma** [comment]
Resolving as it appears no further action is required.
