### ISSUE TITLE
为什么不把训练过程中最好的map的模型保存下来....

### ISSUE THREAD

**Issue by ZHEQIUSHUI** [awslabs/autogluon#225]
我看 [这里](https://autogluon.mxnet.io/tutorials/object_detection/beginner.html)，中间明明有一轮已经是90mAP，但是最后找到best config训练完只有80mAP，反而远远中间这一轮，如果把这一轮保存下来岂不是更好，为什么不保存下来呢......

**Comment by zhanghang1989** [comment]
Good question. 
The mAP during the training is evaluated on a portion of the training set, which we hold off for hyper-parameter tuning. After all experiments finishes, we retrain the entire training set using the best configuration. The final test mAP is reported on the test provided by the user.

好问题！
我们在调参的时候，从训练集中保留一部分数据做参照，这时候显示的mAP是在这部分数据上的，得到最好的参数后我们用整个训练集重新训练最好的模型。最后做测试的时候反应的结果是在测试集中的，而这部分在训练时完全没有接触到。

**Comment by ZHEQIUSHUI** [comment]
thank you  for your detailed answer!!!
i close this question
