### ISSUE TITLE
"ERROR: Unexpected segmentation fault encountered in worker" when training with PyTorch

### ISSUE THREAD

**Issue by wangyirui** [awslabs/autogluon#227]
Hi, I am trying to run the example code 

> https://autogluon.mxnet.io/tutorials/torch/hpo.html

 here. However, I got the errors listed below:

> Starting Experiments
> Num of Finished Tasks is 0
> Num of Pending Tasks is 2
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 16.46it/s]
> lr: 0.0447213595, wd: 0.0002236068
> lr: 0.18226588884015776, wd: 0.00034863124508709517
>   0%|                                                                                                          | 0/5 [00:00<?, ?it/s]ERROR: Unexpected segmentation fault encountered in worker.
> ERROR: Unexpected segmentation fault encountered in worker.
> ERROR: Unexpected segmentation fault encountered in worker.
> ERROR: Unexpected segmentation fault encountered in worker.
> Process Process-4:
> Traceback (most recent call last):
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
>     data = self._data_queue.get(timeout=timeout)
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/multiprocessing/queues.py", line 105, in get
>     raise Empty
> queue.Empty
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
>     self.run()
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/multiprocessing/process.py", line 93, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/site-packages/autogluon/scheduler/scheduler.py", line 125, in _worker
>     ret = fn(**kwargs)
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/site-packages/autogluon/core/decorator.py", line 58, in __call__
>     output = self.f(args, **kwargs)
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/site-packages/autogluon/core/decorator.py", line 139, in wrapper_call
>     return func(*args, **kwargs)
>   File "run.py", line 41, in ag_train_mnist
>     return train_mnist(args, reporter)
>   File "run.py", line 99, in train_mnist
>     test(epoch)
>   File "run.py", line 84, in test
>     for batch_idx, (inputs, targets) in enumerate(testloader):
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
>     idx, data = self._get_data()
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 771, in _get_data
>     success, data = self._try_get_data()
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 737, in _try_get_data
>     raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
> RuntimeError: DataLoader worker (pid(s) 11336, 11348) exited unexpectedly
> Process Process-3:
> Traceback (most recent call last):
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
>     data = self._data_queue.get(timeout=timeout)
>   File "/home/yirui/anaconda3/envs/py36/lib/python3.6/multiprocessing/queues.py", line 105, in get
>     raise Empty
> queue.Empty

I am running it with PyTorch 1.3.1, Python 3.6.9, Ubuntu 18.04, 4x Nvidia Titan V GPU

Can anyone help me with that? Appreciate!

**Comment by zhanghang1989** [comment]
Thanks for the feedback. Looks like a pytorch error. I will try if I can reproduce it.

**Comment by wangyirui** [comment]
> Thanks for the feedback. Looks like a pytorch error. I will try if I can reproduce it.

Could you reproduce this error?
