### ISSUE TITLE
Different classification，predict classification result is same，and probability is 1       按照官网的示例，使用训练出的模型预测两张不同分类的图片，预测结果不符合预期，类别结果错误，准确率1

### ISSUE THREAD

**Issue by szx1234** [awslabs/autogluon#233]
![image](https://user-images.githubusercontent.com/20124347/72679214-0d688a00-3ae8-11ea-9534-1f176b639446.png)
![image](https://user-images.githubusercontent.com/20124347/72679236-486abd80-3ae8-11ea-92dd-e4ddd8dd316e.png)

**Comment by zhanghang1989** [comment]
Thanks for the feedback. Looks like a bug recent introduced. 
@aptsunny do you have some thoughts on this?

**Comment by yceugenelai** [comment]
I also have the similar issue when I try to use predict function with a single image.
However, it seems that the predict function works fine with the task.Dataset input.
Is there any difference between single image and dataset input?

**Comment by szx1234** [comment]
@yceugenelai  Yes, I use predict function with test.Dataset, it seems works too. but when I try to use a single iamge, the acc is always 1. 
It is looks like a bug.

**Comment by aptsunny** [comment]
@szx1234 I think the problem seems to be caused by the single image format. Please refer to #270 .

**Comment by szx1234** [comment]
I replace the new codes to my machine, when I test it , it throws an excetpion 
![image](https://user-images.githubusercontent.com/20124347/74040336-7adc4c00-49fe-11ea-9600-4e8995cebaa1.png)
![image](https://user-images.githubusercontent.com/20124347/74040488-cbec4000-49fe-11ea-8c1b-a7785c802cbf.png)


> @szx1234 I think the problem seems to be caused by the single image format. Please refer to #270 .

**Comment by aptsunny** [comment]
plt.imshow(img.asnumpy())
