### ISSUE TITLE
running stalled at starting

### ISSUE THREAD

**Issue by songfh** [awslabs/autogluon#237]
when I run the official object detection example, it was stalled at staring.
I ran the code in docker container. I tried two trials: one with cuda 10.1 and python3.6; one with cuda 10.0 and python3.7 
![image](https://user-images.githubusercontent.com/22196645/72693576-54985e80-3b6c-11ea-97e6-249ab72df6d8.png)

**Comment by zhanghang1989** [comment]
For cuda 10.0, could you try the mxnet version `mxnet-cu100==1.6.0b20191013`

**Comment by songfh** [comment]
> For cuda 10.0, could you try the mxnet version `mxnet-cu100==1.6.0b20191013`

maybe it works with your sugest, beacase it throw timeout exception and give some reasons, I will do a trial on other server. Look forward to good result Thank you!

**Comment by songfh** [comment]
when I ran a container I added the args / **--ipc="host"** / and all the trials normaly ran.

**Comment by nikparmar** [comment]
> For cuda 10.0, could you try the mxnet version `mxnet-cu100==1.6.0b20191013`

This worked for me

**Comment by Innixma** [comment]
@zhanghang1989 Is there any action remaining for this issue or can it be resolved?
