### ISSUE TITLE
Possibility for running on multiple gpus

### ISSUE THREAD

**Issue by mistrzuniu1** [awslabs/autogluon#239]
Is it possible to run my trainings in parallel? 
I want to use 1 gpu per training, but want to run eg. 4-8 trainings at once. (I have 8gpus on my machine). Is it supported by autogluon?

**Comment by zhanghang1989** [comment]
All the gpus are automatically detected and used. All new trials will be automatically scheduled on available GPUs. 

If you are using [fit](https://autogluon.mxnet.io/api/autogluon.task.html?highlight=imageclass#autogluon.task.ImageClassification.fit), you can set `ngpus_per_trial=1` and `num_trials=20` or any other number of trials you would like to run.

Similarly, if you are customizing AutoGluon, you can set parameters in the [scheduler](https://autogluon.mxnet.io/api/autogluon.scheduler.html), `resource={'num_cpus': 2, 'num_gpus': 1}`. Note that this is the resource per trial.

**Comment by mistrzuniu1** [comment]
Perfect, thanks for quick and clear answer!
