### ISSUE TITLE
Train data with new/updated features

### ISSUE THREAD

**Issue by prasiyer** [awslabs/autogluon#249]
Is there a function or pre-defined approach to get a copy of the train data with new and transformed features?

**Comment by Innixma** [comment]
This would be a good feature to have!

At the current time the data transformation is contained internally in AutoGluon, and thus you wouldn't be able to get the data in this form unless you called some internal functions that aren't well documented for users.

Note that there are some transformations of the data done internally that may not work very well if used outside of the context of AutoGluon. For example, we may duplicate rows, cut rows, etc. Additionally, each model has its own specialized preprocessing after the initial generic preprocessing.

**Comment by Innixma** [comment]
This is now achievable via `predictor.transform_features` and `predictor.load_data_internal`
