### ISSUE TITLE
How can I use Autogluon in SageMaker?

### ISSUE THREAD

**Issue by AakashBasu** [awslabs/autogluon#260]
I'm trying to evaluate Autogluon results with my on prem YOLO V3 results. Do not have a GPU to run Autogluon on-prem. So, wish to run the same on Sagemaker. But, saw some bug in one of its requirement libs in another issue here. Do I have to wait for the dependent library to be fixed before using it on SM or can I still use it?

**Comment by zhanghang1989** [comment]
Here are the package versions I used in SageMaker Docker container. Please expect an example later to run on SM.
```
numpy==1.16.0
scipy==1.3.0
spacy==2.1.8

gluoncv
gluonnlp
graphviz
scikit-optimize
ConfigSpace==0.4.11

boto3==1.9.224
awscli==1.16.253

requests
nose

matplotlib
seaborn==0.9.0
jupyter==1.0.0

### AutoGluon DistributedScheduler remote workers ###
dask[complete]==2.6.0
paramiko==2.4.2
distributed==2.6.0
tornado

## tabular prediction ##
tqdm
psutil
catboost
lightgbm==2.3.0
pandas==0.24.2
scikit-learn==0.21.2
```

**Comment by zhanghang1989** [comment]
FYI.
An example of using image classification docker is available:
https://github.com/zhanghang1989/AutoGluon-Docker

**Comment by Innixma** [comment]
We are actually working on a SageMaker container for AutoGluon, hopefully we can give further updates in the next few weeks.

**Comment by Innixma** [comment]
Please refer to the SageMaker tutorial on using AutoGluon: https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/autogluon-tabular/AutoGluon_Tabular_SageMaker.ipynb
