### ISSUE TITLE
Which underlying libraries of AutoGluon uses GPU for training?

### ISSUE THREAD

**Issue by dclong** [awslabs/autogluon#262]
I have AutoGluon (both CPU and GPU version) installed and tried to train models on Tabular data. There doesn't seems to be much difference in terms of training time between the CPU and GPU version. I monitored the GPU usage when I trained models using the GPU version of AutoGluon and there was no GPU usage almost all the time. I'm curious which underlying libraries of AutoGluon train models using GPU?

**Comment by zhanghang1989** [comment]
GPU training is only enabled for image / text applications, but not for tabular yet.

**Comment by dclong** [comment]
@zhanghang1989 Thank you! Is there any plan to enable GPU for tabular data?

**Comment by zhanghang1989** [comment]
@jwmueller @Innixma

**Comment by Innixma** [comment]
Yes we have plans to add GPU usage for Tabular. We are currently focused on optimizing CPU and ensuring stability. I expect GPU support to be added in the next 2-3 months, but potentially sooner if enough users express a desire for this feature in Tabular.

**Comment by Innixma** [comment]
I have created a master issue for this: #263

**Comment by dclong** [comment]
@Innixma Thank you very much!
