### ISSUE TITLE
GPU Support in Tabular

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#263]
Support GPU usage in Tabular.

Models that could benefit from GPU:
- [Deep Neural Network](https://github.com/awslabs/autogluon/blob/master/autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py)
- [LightGBM](https://github.com/awslabs/autogluon/blob/master/autogluon/utils/tabular/ml/models/lgb/lgb_model.py)
- [CatBoost](https://github.com/awslabs/autogluon/blob/master/autogluon/utils/tabular/ml/models/catboost/catboost_model.py)

If anyone wishes to contribute to this, please update the Model class of any of the above models to accept a new parameter in AG_args_fit: 'use_gpu', which is a boolean. Then alter the code to properly execute training with GPU when 'use_gpu'==True.

Related Issues:
#262

**Comment by jwmueller** [comment]
FYI the neural network does use GPU, but does not support multi-GPU training.   If you're interested in adding GPU support for LightGBM/Catboost, have a look at the NeuralNet UI to see how GPU usage is specified:

https://github.com/awslabs/autogluon/blob/master/autogluon/utils/tabular/ml/models/tabular_nn/tabular_nn_model.py#L196

**Comment by jwmueller** [comment]
GPU is now supported for these 3 models, so closing to avoid confusion.
