### ISSUE TITLE
evaluate function issue of the Image Classification - Quick Start tutorial

### ISSUE THREAD

**Issue by yceugenelai** [awslabs/autogluon#265]
the evaluate result seems incorrect.

Top-1 test acc: **nan**

I have tried on my pc. it shows similar messages as the tutorial and return the wrong evaluate result too

"UserWarning: Ignoring data/test/BabyPants of type . Only support .jpg, .jpeg, .png"

is it a bug of getting class names or listing the images? or is there changes about dataset and/or evaluate function?
Thank you

**Comment by zhanghang1989** [comment]
Thanks for reporting. It is a bug recently introduced. We will fix it.

**Comment by zhanghang1989** [comment]
```
built_in_tasks = {
    'mrpc': MRPCTask,
    'qqp': QQPTask,
    'qnli': QNLITask,
    'rte': RTETask,
    'sts-b': STSBTask,
    'cola': CoLATask,
    'mnli': MNLITask,
    'wnli': WNLITask,
    'sst': SSTTask,
    'toysst': ToySSTTask,
}
```
