### ISSUE TITLE
Improve Tabular Hyperparameter Tuning Stability

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#266]
Master Issue for Tabular hyperparameter tuning improvement tracking.

If you are a user experiencing issues, we recommend to use **auto_stack=True**, **hyperparameter_tune=False** for best stable performance.

Currently hyperparameter tuning suffers from various issues, generally due to multithreading.

Related Issues:
#245 
#231 
#219 
#139 
#329

**Comment by razmikmelikbekyan** [comment]
Hi, 

I am facing the following issue when running hyperparameters tuning. 
When there are  errors in all individual trial threads `autogluon.utils.tabular.ml.models.abstract.model_trial.model_trial` in `autogluon/scheduler/fifo.py:223` the main process is not finishing. I do not know exactly if someone else faced similar issues or not that is why I decided to add it as a comment. 
For reproducing it you can run the following: 
```
import autogluon as ag
from autogluon.task import TabularPrediction as task

hp_tune = True
cat_options = {
    'num_leaves': ag.space.Int(lower=26, upper=66, default=36),
}

hyperparameters = {
    'CAT': cat_options
}

time_limits = 2 * 60
num_trials = 2
search_strategy = 'skopt'
output_directory = 'AutogluonModels/agModels-predictTitanic-tuning'
data = task.Dataset(file_path='AutogluonModels/titanic/train.csv')
label_column = 'Survived'
id_columns = ['PassengerId']

predictor = task.fit(
    train_data=data,
    holdout_frac=0.3,
    label=label_column,
    output_directory=output_directory,
    time_limits=time_limits,
    num_trials=num_trials,
    hyperparameter_tune=hp_tune,
    hyperparameters=hyperparameters,
    search_strategy=search_strategy,
    auto_stack=False,
    stack_ensemble_levels=0
)

print(predictor.leaderboard(silent=True))
```

**Comment by razmikmelikbekyan** [comment]
Basically I want to ask also, if someone is working on this issue on general and from where it is possible to find more detailed documentation about distributed resource management of AutoGluon to be able to solve this.

**Comment by Innixma** [comment]
@razmikmelikbekyan According to https://catboost.ai/docs/concepts/python-reference_parameters-list.html, CatBoost num_leaves parameter is not valid on CPU.

The part about the main job not finishing is an issue however, it should simply fail on CatBoost and return.

HPO is the one part of the Tabular code I am not familiar with because it is part of the core AutoGluon code used in the other parts of AutoGluon such as image classification and text classification. HPO is the only part of Tabular that is directly connected to the other tasks.

I am currently focused on other aspects of Tabular such as Feature Selection, so if you would like to attempt to resolve the HPO issues, it would be greatly appreciated! @zhanghang1989 wrote the core HPO code, so he would be the best to know where to find the relevant documentation.

**Comment by razmikmelikbekyan** [comment]
Hi @Innixma ,

Thanks for response.
So the part about the main job not finishing is an issue however and I noticed similar behaviour in some other cases. 

I would like to help fixing these issues, so I will try to get familiarised with the HPO code and start working on that. Meanwhile @zhanghang1989 it would be nice if you give me a small direction, where I can see the code flow (threads / processes) when running HPO.

**Comment by Innixma** [comment]
#920 should resolve all issues with HPO stability.
