### ISSUE TITLE
Type checking should be performed by using `isinstance`.  

### ISSUE THREAD

**Issue by melikbekyanrazmik** [awslabs/autogluon#271]
https://github.com/awslabs/autogluon/blob/8bfe6b0da8915020eeb9895fd18d7688c0d604c1/autogluon/task/tabular_prediction/tabular_prediction.py#L243

**Comment by melikbekyanrazmik** [comment]
references: 
https://docs.python.org/3/library/functions.html#isinstance
https://stackoverflow.com/questions/152580/whats-the-canonical-way-to-check-for-type-in-python

**Comment by zhanghang1989** [comment]
Agree. Could you create a PR for that?
``if isinstance(train_data, str):``

**Comment by Innixma** [comment]
Thanks for your contribution!
