### ISSUE TITLE
Does not cover the case when the list is empty.

### ISSUE THREAD

**Issue by razmikmelikbekyan** [awslabs/autogluon#277]
https://github.com/awslabs/autogluon/blob/fef4da4c5e6b8c1d0c7a453f45403c14d7244d7e/autogluon/utils/tabular/features/abstract_feature_generator.py#L378

**Comment by Innixma** [comment]
Hello, thanks for creating an issue!

This part of the code is never called by the DefaultLearner in AutoGluon and thus we haven't noticed this defect, but upon looking into it this does seem to be a situation where incorrect behavior would occur.

I have created #278 to address this.

Best,
Nick

**Comment by Innixma** [comment]
Merged fix: #278
