### ISSUE TITLE
The results of the training were garbled

### ISSUE THREAD

**Issue by yllgl** [awslabs/autogluon#283]
![image](https://user-images.githubusercontent.com/23625282/74242940-c2721900-4d19-11ea-86a4-83806a976996.png)
here is my code.
![image](https://user-images.githubusercontent.com/23625282/74242990-d87fd980-4d19-11ea-991c-eb5173a613ea.png)
I find that this garbled code occured after I set the "searcher" parameter. Howerver, after I remove the "searcher" parameter, it‘s back to normal.

**Comment by zhanghang1989** [comment]
SkOpt searcher has some logging, but seems not readable:
https://github.com/awslabs/autogluon/blob/master/autogluon/searcher/skopt_searcher.py#L170-L172

**Comment by Innixma** [comment]
This logging has been fixed in latest version, it is now readable.
