### ISSUE TITLE
Why this repeated call of _cleaning_tasks ?

### ISSUE THREAD

**Issue by mseeger** [awslabs/autogluon#293]
https://github.com/awslabs/autogluon/blob/9a214c5e97363447c321e4e307d8faf0c861dd65/autogluon/scheduler/scheduler.py#L185

I am wondering why _cleaning_tasks is called 2x here, at the start and at the end. Is this required?

**Comment by mseeger** [comment]
I am currently looking through most code in scheduler and searcher, and I can flag things I do not get as issues. Tell me if I should not do that right now ...

**Comment by zhanghang1989** [comment]
Thanks for pointing out. Yes, this is a little redundant.  We can only call `cleaning_task()` once at the end of `join_jobs()`
