### ISSUE TITLE
Could not find a version that satisfies the requirement autogluon

### ISSUE THREAD

**Issue by edwinforedwin** [awslabs/autogluon#305]
My PC has python version 3.7.5
But when I running the command for installing AutoGluon by AWS, the terminal says

'Could not find a version that satisfies the requirement autogluon (from versions: )
No matching distribution found for autogluon'

**Comment by Innixma** [comment]
Can you elaborate?

What is the exact command you entered, and can you provide a 'pip freeze' terminal output?

Also, what is your system information: OS, etc.

Can you try:

```
pip install mxnet
pip install autogluon
```

**Comment by edwinforedwin** [comment]
It's now solved
I got an error while updating my python version and OS bit crashed
So I reinstalled OS and updated python 
Now I can use autogluon easily
