### ISSUE TITLE
RLSearcher cannot be used with existing schedulers

### ISSUE THREAD

**Issue by mseeger** [awslabs/autogluon#317]
https://github.com/awslabs/autogluon/blob/72153b8f373ecadec8aaf359f9ae3ee3099f21e1/autogluon/searcher/rl_controller.py#L34

__init__ has argument kwspaces, of type List[Space], while all other searchers, and BaseSearcher, use CS.ConfigurationSpace. I wonder why the Space abstraction is needed, ConfigSpace should do all of that. And __init__ does not call BaseSearcher.__init__.

This means you cannot support searcher = 'lr' in searcher_factory, which is called in the constructor of FIFOScheduler. I am wondering how RLSearcher can be used (OK, it can be passed  as object in searcher, but that is inconvenient).

In any case, this should be fixed. I'd recommend using ConfigSpace also in RLSearcher.

**Comment by mseeger** [comment]
Or otherwise remove 'rl' as valid argument for search_strategy in tabular_prediction, because currently this does not work out.

**Comment by zhanghang1989** [comment]
Yes. Currently, RLSearcher has to work with RLScheduler https://github.com/awslabs/autogluon/blob/master/autogluon/scheduler/rl_scheduler.py

We may not expose RLSearcher in the searcher factory.

**Comment by mseeger** [comment]
OK, maybe let me ask this differently:
train_fn has train_fn.cs of type CS.ConfigurationSpace, and then it also seems to have train_fn.kwspaces, which is List[Space].

In RLScheduler, train_fn.kwspaces is used, but then FIFOScheduler.__init__ is called, where train_fn.cs is used.

I am just wondering why we cannot use train_fn.cs in RLSearcher, this would solve the issue. Is there anything in Space that we cannot have in CS.ConfigurationSpace.

Note one thing: In the Amper HPO project, they implemented something similar to your List[Space], but when we compared this to the ConfigSpace implementation, the latter is much faster. Sometimes, this can matter. So, even though this is an external dependence, I actually really like the usage of ConfigSpace from Freiburg.

**Comment by mseeger** [comment]
Related to #320

**Comment by mseeger** [comment]
I see now why List[Space] is needed, because these makes the evaluation function decorators easy to do, and using ConfigSpace there would not be easy.

Still, it would be great if we could use ConfigSpace internally in the searchers (as default), because of the speed advantages. It also offers some pretty advanced stuff (like relationships between parameters).

**Comment by zhanghang1989** [comment]
Thanks @mseeger !

The RL Searcher was not carefully implemented, which can be rewritten using ConfigSpace to construction the LSTM controller. 
Currently, we still need RLScheduler, because the searcher update is quite different. We need a large refactor to make RL with FIFO naturally.

**Comment by jwmueller** [comment]
Thanks Matthias (and for your fix on the 'hyperband' option), I'll just remove the 'rl' option from tabular documentation.
