### ISSUE TITLE
Removing ConfigSpace

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#320]
ConfigSpace seems to have several limitations and is not being updated regularly nor are issues being responded to: https://github.com/automl/ConfigSpace

Is there a reason we absolutely need this package?
What would be the work required to match ConfigSpace's functionality?
Why does ConfigSpace require cython?

Related Issues:

#230

**Comment by mseeger** [comment]
Uh wait: This also relates to my objections about RLSearcher.

I've looked into this. The reason to use ConfigSpace is that it is very fast, and sometimes this does matter. I've seen HPO experiments in the Amper team, where literally most of the time was spent converting HP configurations into vectors or back.

The reason why ConfigSpace requires cython is to make it fast.

Note it comes from some very good people in Freiburg. Are you sure it is not maintained? It may simply be good as it is, and so not see more changes.

In return, I was actually asking why we need Space and List[Space] in RLSearcher and RLScheduler, while ConfigSpace is used everywhere else.

We have Aaron Klein from Freiburg in our team now, I could ask him, but I think he already mentioned to me that ConfigSpace is a very decent piece of code, and has been designed to be very fast.

**Comment by mseeger** [comment]
Let me expand. In HPO experiments, when running get_config, people often start evaluating the surrogate model for a large number of randomly chosen (or by Sobol sequence) configs, and then run a local search from the best points found this way. In such situations, I observed that all the local optimization and Gaussian process computations can be faster than the initial evaluations, and the reason was as I said above.

**Comment by Innixma** [comment]
Ok, it seems we have strong reasons to keep ConfigSpace. This was mostly a question from my end as to what benefits it gives, as I believe a few other members are unaware of its benefits.

Also, one of our users posted a detailed GitHub issue to ConfigSpace which hasn't been responded to for over a month: https://github.com/automl/ConfigSpace/issues/141 , which was where my concern stemmed from regarding support.

Given we have strong reasons for keeping ConfigSpace, I'll resolve the issue. Thanks!
