### ISSUE TITLE
MXboard tuple reporting issue

### ISSUE THREAD

**Issue by cgraywang** [awslabs/autogluon#35]
For MXboard, when passing a tuple as the reporting result https://github.com/awslabs/autogluon/blob/7795b9c956c24ff85904700482aa96e3eafea38e/autogluon/scheduler/fifo.py#L241, we would have an error, where in the simple plot is seems to be fine.

**Comment by Innixma** [comment]
What is the status of this? Should we mark as resolved?

**Comment by zhanghang1989** [comment]
The reported `reward_attr` should be numerical value, because we want to compare the value. We may need to mention it somewhere in the doc.
