### ISSUE TITLE
Spiky GPU utilization when training image classification tasks

### ISSUE THREAD

**Issue by shashankprasanna** [awslabs/autogluon#356]
When running shipping samples for image classification directory - cats/dogs, plant seedlings, aerial cactus etc. I notice very spiky GPU utilization behavior. 

Repro: Follow the steps to download the kaggle datasets and run benchmark.py with suggested options on this page:
https://github.com/awslabs/autogluon/tree/master/examples/image_classification

Open a separate terminal window and run:
`watch -n0.1 nvidia-smi
`

You should see GPU-utilization oscillate between 0% - 70%/80%
This is consistency reproducible with all demos.

Versions:
I've tried AutoGluon with both:
mxnet-cu100 and mxnet-cu102
nvcc --version is 10
nvidia-smi
Driver Version: 440.33.01    CUDA Version: 10.2

Is this expected behavior? why is the utilization not at a sustained level as we see with MXNet/TensorFlow/PyTorch training?

**Comment by jwmueller** [comment]
I doubt this explains your issue, but FYI we do expect GPU utilization to drop between training trials.  AutoGluon will train many networks under different hyperparameter configurations, and there is a brief gap in between training runs where GPU may not be utilized.  However, I assume your GPU utilization is constantly oscillating all the time, not just between training runs (so this is not the explanation for your issue)?

**Comment by shashankprasanna** [comment]
I observe this behavior during a single training run, and it appears to happen during an epoch. Something’s not right and I don’t know how to debug/diagnose.

**Comment by aptsunny** [comment]
@shashankprasanna  Thanks for the feedback. In my point of view, the GPU utilization does fluctuate spiky within this range [0%, 90%] in the tasks included in the example, even during a single training run. Generally speaking, the GPU computing amount of the same computing task is fixed. The high GPU utilization during the training process means that the actual running time is less. and about GPU resources utilization we will continue to pay attention to it. Maybe there's something about the issue I don't figure out.

**Comment by Innixma** [comment]
@aptsunny Are you saying that you expect spikes in GPU utilization and that is not a problem? If we expect spikes, my question would be why? If we don't, can you try to reproduce this GPU spike behavior and detail what part of the code causes it? Perhaps performance improvements could be gained if the utilization did not spike?
