### ISSUE TITLE
Are resnet18 and resnet50 the only architectures tested for image classification?

### ISSUE THREAD

**Issue by drjah** [awslabs/autogluon#359]
I used autogluon to train an image classifier.
It was easy to do, but when I ran 
    fit_summary = classifier.fit_summary(verbosity=1)
the result includes: 
    net.choice', Categorical['ResNet50_v1b', 'ResNet18_v1b']

In prior tests I ran using mxnet and gluon (not autogluon), using vgg19, I got better accuracy  for my classification task (identifying the vertebra I found with object detection) than I did using resnet 50. Is it possible to get autogluon to test more than just resnet 18 and resnet 50?

Thanks

**Comment by zhanghang1989** [comment]
All Gluon-CV models are built-in https://gluon-cv.mxnet.io/model_zoo/classification.html
For example you can use `net='VGG19_bn'`

**Comment by drjah** [comment]
Thank you for the response. I will try to run autogluon specifying more
models to try.

**Comment by drjah** [comment]
This worked great for image classification with 
import autogluon as ag
nets=ag.space.Categorical('SE_Net_154', 'SE_ResNext101_32x4d') 
# choose models from https://gluon-cv.mxnet.io/model_zoo/classification.html
# then include net=nets in the task.fit command

Thanks!
