### ISSUE TITLE
RecordIO format does not worl with image classification?

### ISSUE THREAD

**Issue by drjah** [awslabs/autogluon#364]
While a RecordIO format dataset can be loaded without error using:

    import autogluon as ag
    dataset = ag.task.image_classification.RecordDataset('file.rec')

the fit command fails with the message:

.....autogluon/task/image_classification/dataset.py", line 206, in num_classes
    raise NotImplementedError

Is there a trick to getting this to work? 
The recordio format file I am using works fine in other code using 
    from mxnet.io import ImageRecordIter
    train_data = ImageRecordIter(.....)

Thanks

**Comment by zhanghang1989** [comment]
Could you try the following command?
```
from autogluon import ImageClassification as task
dataset = task.Dataset('file.rec')
classifier = task.fit(dataset, epochs=30)
```

**Comment by drjah** [comment]
Thanks for the response.
I tried this but got the same error from dataset.py about num_classes not
implemented
The rec file was created using im2rec.py
