### ISSUE TITLE
ImageClassification example crashes with out of memory error

### ISSUE THREAD

**Issue by doccosmos** [awslabs/autogluon#368]
I'm trying the ImageClassification example on a Linux box:

>uname -a
Linux rico 3.10.0-327.36.1.el7.x86_64 #1 SMP Wed Aug 17 03:02:37 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

running Python 3.7 (Anaconda distro) with CUDA 10.1 and the appropriate autogluon package.  The TabularClassification example runs absolutely fine but the ImageClassification crashes:

>>> classifier = task.fit(dataset,
...                       epochs=5,
...                       ngpus_per_trial=1,
...                       verbose=False)
scheduler: FIFOScheduler(
DistributedResourceManager{
(Remote: Remote REMOTE_ID: 0,
	<Remote: 'inproc://131.215.198.227/25300/1' processes=1 threads=32, memory=270.19 GB>, Resource: NodeResourceManager(32 CPUs, 2 GPUs))
})

Starting Experiments
Num of Finished Tasks is 0
Num of Pending Tasks is 2
100%|█████████████████████████████████████████████| 2/2 [00:00<00:00,  4.89it/s]
terminate called after throwing an instance of 'dmlc::Error'
  what():  [11:39:03] /home/ubuntu/mxnet-distro/mxnet-build/3rdparty/mshadow/mshadow/./stream_gpu-inl.h:198: Check failed: e == cudaSuccess: CUDA: out of memory
Stack trace:
  [bt] (0) /data/mjg/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x6b8b5b) [0x7fb20c8f0b5b]
  [bt] (1) /data/mjg/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37accff) [0x7fb20f9e4cff]
  [bt] (2) /data/mjg/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37c7f07) [0x7fb20f9fff07]
  [bt] (3) /data/mjg/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37c8136) [0x7fb20fa00136]
  [bt] (4) /data/mjg/anaconda3/lib/python3.7/site-packages/mxnet/libmxnet.so(+0x37c3114) [0x7fb20f9fb114]
  [bt] (5) /data/mjg/anaconda3/lib/python3.7/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6(+0xb8678) [0x7fb29dcff678]
  [bt] (6) /lib64/libpthread.so.0(+0x7dc5) [0x7fb2aca02dc5]
  [bt] (7) /lib64/libc.so.6(clone+0x6d) [0x7fb2ac72fced]

**Comment by zhanghang1989** [comment]
can you reduce the batch size?

**Comment by doccosmos** [comment]
I'm just following the example notebook so am surprised it crashes.

**Comment by aptsunny** [comment]
Hi, @doccosmos thank you for your feedback. Would you provide more details, like your operating system, hardware configuration (CPU/GPU/memory/disk, etc), data you used?
