### ISSUE TITLE
Google Colab : Unable to install autogluon

### ISSUE THREAD

**Issue by oke-aditya** [awslabs/autogluon#372]
Hey team.
I tired installing autogluon on google colab. But it seems to give me an error.
Does a simple pip install not work ?
There is import error 
`ImportError: cannot import name 'isStringType'
`

![image](https://user-images.githubusercontent.com/47158509/77228814-e09c2600-6baf-11ea-86c7-63d7039d0e6d.png)

**Comment by oke-aditya** [comment]
- Is this issue linked to #171 ?

**Comment by Innixma** [comment]
Please see #163 for the solution, I believe it should solve your problem. Unfortunately Colab uses an old version of Tornado and needs a bit of extra code to get working with AutoGluon. Resolving for now, please let me know if you have any issues!

**Comment by oke-aditya** [comment]
- It isn't solving the issue. I just tried as you said. It is still giving me error.

![image](https://user-images.githubusercontent.com/47158509/77248728-ac813d80-6c61-11ea-894a-e64000a66160.png)

**Comment by oke-aditya** [comment]
Link to Colab Notebook: 

[https://colab.research.google.com/drive/1ULOytrRHcw4GLl0qWgGnxUpr9zVQVYlr](https://colab.research.google.com/drive/1ULOytrRHcw4GLl0qWgGnxUpr9zVQVYlr)
i used the above notebook. It is not working

**Comment by Innixma** [comment]
Seems that for 0.0.6 doing the ipykernel upgrade at the start doesn't work, but it does if you put it at the end of the installs.

I have updated the notebook and the instructions in #163. Do note that you have to manually restart the Colal runtime prior to importing autogluon (There is a cell that mentions this)

Notebook:
https://colab.research.google.com/drive/1ULOytrRHcw4GLl0qWgGnxUpr9zVQVYlr

Thanks for pointing this out! Let me know if this works.

**Comment by oke-aditya** [comment]
- Works like charm. No issues now. This alternative works.

**Comment by lfleon9b** [comment]
The following version works: 

https://colab.research.google.com/drive/1Z0F2FOowLWrJ-gYx72fiWLIpmEVMk4Bo#scrollTo=XtuOeo_ZzLMq

see full article in : (from https://towardsdatascience.com/getting-started-with-automl-and-aws-autogluon-6bc7ed7aef95) 

greetings!

**Comment by Kishansinh94** [comment]
Searching for answer? refere this :

https://github.com/awslabs/autogluon/issues/163#issuecomment-573388784

It worked for me 👍 
Don't forget to restart manually.
