### ISSUE TITLE
How is train_fn.cs.get_default_configuration() being set?

### ISSUE THREAD

**Issue by mseeger** [awslabs/autogluon#380]
This is a question about the code.
The first config which is evaluated, is train_fn.cs.get_default_configuration().

I am wondering how this config is set if the user does not set it as part of the @ag.args definition? And moreover, can the user set it (and how)?

Some quick digging in the code (core/decorator.py, core/space.py) did not produce something obvious. Is this logic in AutoGluon, or in ConfigSpace?

**Comment by zhanghang1989** [comment]
User can setup the default value when creating the search spaces, for example:
```
real_space = autogluon.space.Real(0.0, 3.0, default=2.5)
```
If the user doesn't setup the fault value, ConfigSpace will automatically suggest defaults, which is usually the average between upper and lower values.

**Comment by mseeger** [comment]
Thanks!
