### ISSUE TITLE
How can I deploy my model on Heroku?

### ISSUE THREAD

**Issue by bitcoinvsalts** [awslabs/autogluon#406]
Is there a node js package to deploy my model on heroku easily? 

what is the best practice to deploy an autogluon model into an api for prediction?

**Comment by Innixma** [comment]
Thanks for submitting an issue! I am not personally familiar with heroku or NodeJS, but perhaps @zhanghang1989 or @jwmueller will have more context to answer. We do have fairly comprehensive AWS SageMaker API support that will be available in the next month or so.

**Comment by jwmueller** [comment]
Sorry I'm also not familiar with heroku, nor aware of any efforts to provide a NodeJS autogluon API.  If you can use Sagemaker instead, here are some resources for deploying AutoGluon there:

AutoGluon for tabular data on Sagemaker: 
https://github.com/yoheigon/amazon-sagemaker-examples/blob/master/advanced_functionality/autogluon-tabular/AutoGluon_Tabular_SageMaker.ipynb

AutoGluon for image data on Sagemaker: 
https://github.com/zhanghang1989/AutoGluon-Docker/blob/master/image_classification_sagemaker.ipynb
