### ISSUE TITLE
add model export onnx format

### ISSUE THREAD

**Issue by dsp6414** [awslabs/autogluon#414]
how can i export nn model to   tf/pytorch/onnx format

**Comment by Innixma** [comment]
@zhanghang1989 could you link the appropriate person to answer this question?

**Comment by dsp6414** [comment]
thanks.


 
---Original---

**Comment by zhreshold** [comment]
@dsp6414 Not sure what model you are refering to, but for gluon models, you can checkout this tutorial to export to onnx: https://mxnet.apache.org/api/python/docs/tutorials/deploy/export/onnx.html

**Comment by dsp6414** [comment]
thanks.I have finished the model transform test.


 
---Original---

**Comment by Innixma** [comment]
Please re-open if you still have questions, thanks!
