### ISSUE TITLE
Why the trials are 2 even I have modified to 32?

### ISSUE THREAD

**Issue by precision2intelligence** [awslabs/autogluon#415]
The scheduler I set is as following:
```Python
myscheduler = ag.scheduler.FIFOScheduler(ag_train_CIFAR,
                                         resource={'num_cpus': 8, 'num_gpus': 4},
                                         num_trials=32,
                                         time_attr='epoch',
                                         reward_attr="accuracy")
```
However, I only found 2 groups of hyperparameters after training, even the Pengding Tasks are 32.

>  Starting Experiments
Num of Finished Tasks is 0
Num of Pending Tasks is 32
  0%|                                                                                                                                                     | 0/32 [00:00<?, ?it/s]lr: 0.0007071068, wd: 0.0002236068
> 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [1:19:10<00:00, 95.00s/it]
Finished Task with config: {'lr': 0.0007071068, 'wd': 0.0002236068} and reward: 60.09██████████████████████████████████████████████████████████| 50/50 [1:19:10<00:00, 98.00s/it]
  6%|████████▍                                                                                                                             | 2/32 [1:19:20<19:50:02, 2380.07s/it]

> Finished Task with config: {'lr': 0.0008149314425575752, 'wd': 0.00020035385682209573} and reward: 60.34
The Best Configuration and Accuracy are: {'lr': 0.0008149314425575752, 'wd': 0.00020035385682209573}, 60.34
The delay time for ag HPO is: 9607.928075313568 s

**Comment by Jerryzcn** [comment]
Can you post your search space?

**Comment by precision2intelligence** [comment]
```python
@ag.args(
    lr=ag.space.Real(0.0005, 0.001, log=True),
    wd=ag.space.Real(1e-4, 5e-4, log=True),
    net=Net(),
    epochs=50,
)
```

**Comment by chongruo** [comment]
Did you set the value of time_limits? Maybe the running time of your job exceeds the limits?

**Comment by precision2intelligence** [comment]
I suppose not. I use the default set. “time_out=None”. 
```Python
def __init__(self, train_fn, args=None, resource=None,
                 searcher=None, search_options=None,
                 checkpoint='./exp/checkpoint.ag',
                 resume=False, num_trials=None,
                 time_out=None, max_reward=1.0, time_attr='epoch',
                 reward_attr='accuracy',
                 visualizer='none', dist_ip_addrs=None):
```

**Comment by Innixma** [comment]
It appears that your score was 60.34, but your max_reward setting was `1.0`, meaning that HPO stopped early due to achieving over the max reward.
