### ISSUE TITLE
RuntimeError: Feature 'TVM_OP' is unknown, known features are: ['CUDA', 'CUDNN'........

### ISSUE THREAD

**Issue by zzdgit** [awslabs/autogluon#418]
I was able to execute successfully last week and the environment didn't change, but I suddenly reported an error today

The error information is as follows:
```
Traceback (most recent call last):
  File "example_advanced_tabular.py", line 6, in <module>
    import autogluon as ag
  File "/home/xxx/miniconda3/envs/mxnet-1.4/lib/python3.6/site-packages/autogluon/__init__.py", line 6, in <module>
    from .utils.try_import import *
  File "/home/xxx/miniconda3/envs/mxnet-1.4/lib/python3.6/site-packages/autogluon/utils/__init__.py", line 5, in <module>
    from .dataset import *
  File "/home/xxx/miniconda3/envs/mxnet-1.4/lib/python3.6/site-packages/autogluon/utils/dataset.py", line 3, in <module>
    import mxnet as mx
  File "/home/xxx/miniconda3/envs/mxnet-1.4/lib/python3.6/site-packages/mxnet/__init__.py", line 90, in <module>
    from . import tvmop
  File "/home/xxx/miniconda3/envs/mxnet-1.4/lib/python3.6/site-packages/mxnet/tvmop.py", line 22, in <module>
    if Features().is_enabled("TVM_OP"):
  File "/home/xxx/miniconda3/envs/mxnet-1.4/lib/python3.6/site-packages/mxnet/runtime.py", line 93, in is_enabled
    feature_name, list(self.keys())))
RuntimeError: Feature 'TVM_OP' is unknown, known features are: ['CUDA', 'CUDNN', 'NCCL', 'CUDA_RTC', 'TENSORRT', 'CPU_SSE', 'CPU_SSE2', 'CPU_SSE3', 'CPU_SSE4_1', 'CPU_SSE4_2', 'CPU_SSE4A', 'CPU_AVX', 'CPU_AVX2', 'OPENMP', 'SSE', 'F16C', 'JEMALLOC', 'BLAS_OPEN', 'BLAS_ATLAS', 'BLAS_MKL', 'BLAS_APPLE', 'LAPACK', 'MKLDNN', 'OPENCV', 'CAFFE', 'PROFILER', 'DIST_KVSTORE', 'CXX14', 'INT64_TENSOR_SIZE', 'SIGNAL_HANDLER', 'DEBUG']
```

 operating environment
```
python 3.6
mxnet-cu90
cuda 9.0
```

**Comment by Innixma** [comment]
Thanks for the issue! Very strange assuming the environment did not change. @zhreshold perhaps you might know why, as the error is coming from mxnet.

One thing I do notice is that mxnet 1.4 is quite old, so perhaps upgrading to mxnet 1.5/1.6 will solve your issue.

**Comment by zzdgit** [comment]
I tried version 1.6 of mxnet，but still reported an error。Then I switched to a server and it was fine。
I wonder what dependencies need to be installed to support TVM_OP。
thanks,

**Comment by zhreshold** [comment]
@zzdgit I think you might have a corrputed mxnet installation. Try clean up the mxnet in pip site-package and reinstall again.

**Comment by hanyunfan** [comment]
I see the same error when I running mlperf:resnet-50 with RTX GPUs, V100s cards are just fine.

**Comment by zzdgit** [comment]
@zhreshold，Thank you very much.
 After creating several virtual environments using anconda, I removed the others, reinstalled mxnet and autogluon, and the problem was gone.I'm confused that using conda create-n XXX python==3.6 should result in an environment that is isolated from each other.

**Comment by Innixma** [comment]
I remember experiencing strange issues with conda environments in the past, although I don't think I've seen them interact across environments before. venv has never caused issues for me however.

**Comment by Innixma** [comment]
@hanyunfan If the solution mentioned here did not work for you, please feel free to create a new issue highlighting your situation.
