### ISSUE TITLE
How to use  Image augmentation for image classification

### ISSUE THREAD

**Issue by dsp6414** [awslabs/autogluon#423]
I still don't know how to use autogluon for sample augmentation, can anyone help me?

**Comment by dsp6414** [comment]
dataset.py [code] 

 if train:
            transform = transforms.Compose(
                [
                    transforms.RandomResizedCrop(input_size),
                    transforms.RandomFlipLeftRight(),
                    transforms.RandomColorJitter(
                        brightness=jitter_param,
                        contrast=jitter_param,
                        saturation=jitter_param
                    ),
                    transforms.RandomLighting(0.1),
                    transforms.ToTensor(),
                    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
                ]
            )

How can I provide my own augmented function？

**Comment by zhreshold** [comment]
@dsp6414  Yes you can define your own augmentation list.

For instance:
```python
@ag.args(
  use_random_crop=ag.Bool(),
  use_random_flip=ag.Bool(),
  jitter_param=ag.Real(0.1, 0.3),
)
def train_fn(args, reporter=None):
  ...
  if train:
    transform_list = []
    if args.use_random_crop:
      transform_list.append(...)
    
```
