### ISSUE TITLE
Use RLScheduler as search_strategy

### ISSUE THREAD

**Issue by amirsani** [awslabs/autogluon#426]
What's the best way to use RLScehduler as the task.fit search strategy?

**Comment by Innixma** [comment]
If you are experiencing issues with RLScheduler, please see #421 and its resolving PR #427. Consider using the latest mainline AutoGluon to get access to this fix now. Note that RLScheduler is not supported in Tabular at present.

**Comment by amirsani** [comment]
Thanks Nick
