### ISSUE TITLE
[distributed] Improper shutdown of remote service

### ISSUE THREAD

**Issue by tlienart** [awslabs/autogluon#433]
cc: @zhanghang1989 @mseeger 

I'm still investigating a standard error that occurs on most runs with SageMaker:

```
Traceback (most recent call last):
  File "/usr/local/bin/dockerd-entrypoint.py", line 20, in <module>
    subprocess.check_call(shlex.split(' '.join(sys.argv[1:])))
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['train']' died with <Signals.SIGTERM: 15>.
```

After some investigation it looks like:

1. the SIGTERM is launched from `Service.shutdown` as per

https://github.com/awslabs/autogluon/blob/04866e5a976c471df1c9272b9be15132f986ead9/autogluon/scheduler/remote/remote.py#L52-L53

This is not good. 

The clean termination procedure is the `atexit` call 

https://github.com/awslabs/autogluon/blob/04866e5a976c471df1c9272b9be15132f986ead9/autogluon/scheduler/remote/remote.py#L165

that calls `_close_global_remote_services` which does not call `Service.shutdown`, this is OK. However it is **only** called upon clean termination, not upon a SIGTERM as stated in the docs https://docs.python.org/3.6/library/atexit.html#module-atexit

So this `os.killpg` does not seem to be the right tool for the job.

### Possible workaround

I think here the process should be killed using `proc.kill` (https://docs.python.org/3/library/subprocess.html#subprocess.Popen.kill) 

I'll try and experiment with this and report (with a PR if things go well) but it'd be great to have someone who's more familiar with Dask to have a think about this and get this fixed reasonably soon.

**Comment by tlienart** [comment]
So `self.proc.kill` does not seem to be sufficient, I still get

```
Traceback (most recent call last):
  File "/usr/local/bin/dockerd-entrypoint.py", line 20, in <module>
    subprocess.check_call(shlex.split(' '.join(sys.argv[1:])))
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
```

on one of the workers, curiously the main worker (scheduler) finishes fine.

**Comment by Innixma** [comment]
Adding @zhreshold who may have some context. Also pinging @zhanghang1989 in case he has comments to add.

**Comment by Innixma** [comment]
@tlienart It may be beneficial for you to add a minimal reproducible example of the error so we can work towards identifying why the particular example fails. Ideally it could be added as a unit-test in your PR (if such a thing is do-able, uncertain given this is related to distributed).

**Comment by tlienart** [comment]
I don’t think that’s doable publicly at this point. But I’m willing to communicate internally with someone who would want to dig into this + experiment with possible ways  out of the issue & report.

**Comment by zhreshold** [comment]
@tlienart I think for a non-python exception, you can use `signal`(https://docs.python.org/3/library/signal.html#example)  module to catch and handle the shutdown gracefully.

**Comment by tlienart** [comment]
I’ll look into it, thanks!

**Comment by tlienart** [comment]
ok no that's almost certainly not the right way to do it as it's not for distributed set ups as far as I'm aware. 

I think to go forward with this we need advice from someone who has experience with Dask distributed.

**Comment by Innixma** [comment]
Closing this, please re-open if this issue still exists.
