### ISSUE TITLE
[Feature Request] Add eval_set to training

### ISSUE THREAD

**Issue by Ishitori** [awslabs/autogluon#450]
I have 2 datasets: one training dataset, which comes from one place, and another, much smaller, evaluation dataset. I want to instruct autogluon to use my evaluation dataset for the estimating performance of the model instead of taking a chunk from training dataset. Basically, it is a functionality similar to XGBoost: https://xgboost.readthedocs.io/en/latest/python/python_api.html#xgboost.XGBRFRegressor.fit

**Comment by Innixma** [comment]
Hi Ishitori,

Thanks for submitting an issue!

Have you tried `tuning_data`? I believe it satisfies your requirements.

`task.fit(train_data=train_data, tuning_data=validation_data, ...)`

Alternatively, you can get the scores on your hold-out set by:

`predictor.leaderboard(holdout_data)`

Let me know if this is what you are looking for.

Best,
Nick

**Comment by Ishitori** [comment]
Yes, that would work. Thanks, Nick.
