### ISSUE TITLE
AutoGluon 0.0.7 pip install does not work: No module named 'autogluon.version'

### ISSUE THREAD

**Issue by hmingkwan** [awslabs/autogluon#456]
After pip install mxnet autogluon
I got this error msg: No module named 'autogluon.version'

**Comment by Innixma** [comment]
@jwmueller Can you take a look at this and see if there are any issues with the 0.0.7 pypi?

**Comment by Innixma** [comment]
Thanks for notifying! I reproduced the error on a fresh linux machine. Looking into this now, I suspect it was due to how the PyPi was created.

**Comment by Innixma** [comment]
This is a major defect. Do not install autogluon 0.0.7, as it will fail to import. For the time being, use pip install autogluon==0.0.6 while we work to resolve the issue.

**Comment by Innixma** [comment]
autogluon 0.0.7 has been yanked from PyPi, we will release 0.0.8 shortly as a hotfix.

**Comment by Innixma** [comment]
#457 has been merged and we have released AutoGluon 0.0.8 which addresses the issue. Please use AutoGluon 0.0.8 and avoid using AutoGluon 0.0.7

Best,
Nick
