### ISSUE TITLE
Reporter returns empty dict to scheduler _run_reporter

### ISSUE THREAD

**Issue by mseeger** [awslabs/autogluon#466]
We use HyperbandScheduler, and we run into the problem that reporter.fetch() in HyperbandScheduler._run_reporter returns an empty dict(). Looking at DistStatusReporter.fetch:

        try:
            kwargs = self._queue.get()
        except CommClosedError:
            return {}
        return kwargs

What is confusing. In Communicator (also reporter.py), exceptions are caught and sent back with 'traceback'. Why is this not done for CommClosedError?

How should we react to this? My first guess is to just skip such reports in _run_reporter, but would this be OK? It comes down to this: Does CommClosedError mean the task is gone, or could it return further results later on, but not the current one?

**Comment by Innixma** [comment]
Closing due to staleness, please re-open if the issue still exists.
