### ISSUE TITLE
ERROR    ExecuteUserScriptError: Command "/usr/local/bin/python3.6 train.py --label y"

### ISSUE THREAD

**Issue by unifydinsights** [awslabs/autogluon#471]
Has anyone run into this. Running the current tabular gluon out of box  I get to the end of the training job and fail at this point where it cannot execute the hyperparameters.  I am using the proper Version conda_mxnet_p36 as requested in Jupyter Lab.

Traceback (most recent call last):
  File "train.py", line 20, in <module>
    import autogluon as ag
  File "package/autogluon/__init__.py", line 6, in <module>
    from .utils.try_import import *
  File "package/autogluon/utils/__init__.py", line 9, in <module>
    from .learning_rate import *
  File "package/autogluon/utils/learning_rate.py", line 1, in <module>
    from gluoncv.utils import LRSequential, LRScheduler
  File "package/gluoncv/__init__.py", line 8, in <module>
    from . import data
  File "package/gluoncv/data/__init__.py", line 4, in <module>
    from . import transforms
  File "package/gluoncv/data/transforms/__init__.py", line 6, in <module>
    from . import experimental
  File "package/gluoncv/data/transforms/experimental/__init__.py", line 2, in <module>
    from . import bbox
  File "package/gluoncv/data/transforms/experimental/bbox.py", line 6, in <module>
    from ....utils import bbox_iou
  File "package/gluoncv/utils/__init__.py", line 6, in <module>
    from . import viz
  File "package/gluoncv/utils/viz/__init__.py", line 7, in <module>
    from .mask import expand_mask, plot_mask, cv_merge_two_images
  File "package/gluoncv/utils/viz/mask.py", line 7, in <module>
    from ...data.transforms.mask import fill
  File "package/gluoncv/data/transforms/mask.py", line 5, in <module>
    from PIL import Image
  File "package/PIL/Image.py", line 93, in <module>
    from . import _imaging as core
**ImportError: cannot import name '_imaging'**
2020-05-16 13:56:37,482 sagemaker-containers ERROR    ExecuteUserScriptError:
Command "/usr/local/bin/python3.6 train.py --label y"
Traceback (most recent call last):
  File "/usr/local/bin/dockerd-entrypoint.py", line 20, in <module>
    subprocess.check_call(shlex.split(' '.join(sys.argv[1:])))
  File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['train']' returned non-zero exit status 1.

here's the traceback

---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    494         self.jobs.append(self.latest_training_job)
    495         if wait:
--> 496             self.latest_training_job.wait(logs=logs)
    497 
    498     def _compilation_job_name(self):

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
   1106         # If logs are requested, call logs_for_jobs.
   1107         if logs != "None":
-> 1108             self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   1109         else:
   1110             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll, log_type)
   3042 
   3043         if wait:
-> 3044             self._check_job_status(job_name, description, "TrainingJobStatus")
   3045             if dot:
   3046                 print()

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   2636                 ),
   2637                 allowed_statuses=["Completed", "Stopped"],
-> 2638                 actual_status=status,
   2639             )
   2640 

UnexpectedStatusException: Error for Training job autogluon-sagemaker-training-2020-05-16-13-52-38-992: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "/usr/local/bin/python3.6 train.py --label y"

**Comment by Innixma** [comment]
Thanks for submitting an issue! Was AutoGluon able to successfully train the models prior to this error? What do you mean by 'it cannot execute the hyperparameters'?

@zhreshold Appears to be a failed import coming from gluoncv, perhaps you might know why this occurred?

**Comment by unifydinsights** [comment]
So I pulled the autogluon jupyter notebook into a sagemaker jupyter
notebook and ran it with no changes.  I tried about four times but
everytime it failed at the training model.  see attached.  I am seeing more
references to the hyperparameters json here.
[image: image.png]

following this we have the environment variables.

[image: image.png]

following this we have a failed import of imaging

[image: image.png]

after this we have the same text that I copied in the first message.

**Comment by zhreshold** [comment]
@unifydinsights Can you print the version of PIL package in sagemaker? I think it's due to a incompatible PIL version issue

**Comment by unifydinsights** [comment]
PIL 7.0.0 in sagemaker jupyter

**Comment by unifydinsights** [comment]
[image: image.png]
now i see this so it does look like an upgrade is needed.  any idea?

**Comment by zhreshold** [comment]
@unifydinsights Per this thread https://stackoverflow.com/questions/25340698/importerror-cannot-import-name-imaging, the solution is to install Pillow `pip install -U Pillow`

**Comment by nickyongzhang** [comment]
Same error here. Just copy the notebook in SM notebook instance and did nothing change.

I tried both `pip install -U Pillow` in jupyter and Docker file and still sees this error.

**Comment by Innixma** [comment]
Closing for now, please re-open if the issue still exists.
