### ISSUE TITLE
Cannot use all GPUs in AutoGluon==0.0.8

### ISSUE THREAD

**Issue by Spark001** [awslabs/autogluon#477]
Like [previous issue](https://github.com/awslabs/autogluon/issues/239#issuecomment-576459539), I set `resource={'num_cpus': 4, 'num_gpus': 2}` in FIFO scheduler, but the GPU usually cannot be all used. 

There are 8 GPUs on my machine, by all rights, there should be 4 tasks working at one time. Therefore I found sometimes only 1 or 2 or 3 tasks working at one time.
My platform & environment is as follow: 
 `Ubuntu 16.04+cuda10.1+mxnet1.5.1+gluoncv0.5.0+autogluon0.0.8`

By the way, I didn't encounter this problem when I use autogluon==0.0.6.

**Comment by Innixma** [comment]
Thanks for creating an issue!

@zhreshold Could you take a look at this?

**Comment by zhreshold** [comment]
@Spark001 Do you have the output `python3 -c "import mxnet; print(mxnet.util.get_gpu_count())"` to be 8 in your build?
And also do you think the number of parallel tasks is bound by `num_cpus` by any chance?

**Comment by Spark001** [comment]
Thanks for your reply. 
Actually I use the gpu and cpu resource on the cloud. I applied 8 GPUs, 32 CPUs and 256G memory, I think they are enough.

**Comment by zhreshold** [comment]
@Spark001 Thanks for the info, the idea of checking the `gpu_count` is to ensure that autogluon can find as many gpu as the phisically availabel GPUs on your instance.

**Comment by Spark001** [comment]
@zhreshold I run `python3 -c "import mxnet; print(mxnet.util.get_gpu_count())"` and confirmed 8 GPUs available.

Furthermore, I found the GPU utility ratio was like a square wave. GPU first works 2 hours, then sleep for about 2 hours repeatedly (2 hours is the time one task costs approximately).

Under my experimental setting, it may appear `out of memory` error, so I suspect that 
thread not terminated when `out of memory` and the resources were not released in time.

**Comment by zhreshold** [comment]
@Spark001 Yes, your guess is very likely straight to the point. It might due to a dead task on GPU that recource manager failed to revoke and clean.

@zhanghang1989 Any straight forward way to kill a task when it's not responsive for certain time?

**Comment by zhanghang1989** [comment]
> @Spark001 Yes, your guess is very likely straight to the point. It might due to a dead task on GPU that recource manager failed to revoke and clean.
> 
> @zhanghang1989 Any straight forward way to kill a task when it's not responsive for certain time?

The `time_out` feature was not considered in the original design. We can do it, but it may lead to misuse and cause troubles for long-training job.
