### ISSUE TITLE
mx.metric moved to gluon.metric in latest MXNet master

### ISSUE THREAD

**Issue by jwmueller** [awslabs/autogluon#482]
This will break autogluon once the official version of MXNet updates to reflect this change.

https://github.com/apache/incubator-mxnet/issues/18386

I'm not sure what the best procedure is to handle this, to cap the MXNet version for now? try-import both of mx.metric & gluon.metric?

**Comment by szha** [comment]
similar to gluoncv, I'd suggest pinning autogluon to mxnet 1.x, gluonnlp and gluoncv to 0.x, until the mx2 migration is done.

**Comment by mseeger** [comment]
+1. In general, I think it is wise to work hard to make AutoGluon as independent from MXNet as possible.

**Comment by cristobal140** [comment]
Hi, I have the same problem, I'm new to this and I don't know how to solve the problem.

could someone help me please?
