### ISSUE TITLE
Classification or detection keeps on running on colab

### ISSUE THREAD

**Issue by ps-coder** [awslabs/autogluon#487]
I'm following as mentioned in #163. Any [classification](https://autogluon.mxnet.io/tutorials/image_classification/beginner.html) or [detection task](https://autogluon.mxnet.io/tutorials/object_detection/beginner.html) keeps on running with no output after the resnet50 or mobilenet model is downloaded. On interrupt, I'm getting following stack trace:

KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-1-f01ebc8d6a82> in <module>()
     10                       epochs=5,
     11                       ngpus_per_trial=1,
---> 12                       verbose=False)

5 frames
/usr/local/lib/python3.6/dist-packages/autogluon/task/image_classification/image_classification.py in fit(dataset, net, optimizer, loss, split_ratio, batch_size, input_size, epochs, final_fit_epochs, ensemble, metric, nthreads_per_trial, ngpus_per_trial, hybridize, search_strategy, plot_results, verbose, search_options, time_limits, resume, output_directory, visualizer, num_trials, dist_ip_addrs, grace_period, auto_search, lr_config, tricks)
    292             )
    293 
--> 294         results = BaseTask.run_fit(train_image_classification, search_strategy, scheduler_options)
    295         args = sample_config(train_image_classification.args, results['best_config'])
    296 

/usr/local/lib/python3.6/dist-packages/autogluon/task/base/base_task.py in run_fit(cls, train_fn, search_strategy, scheduler_options)
     46         scheduler = scheduler_cls(train_fn, **scheduler_options)
     47         print('scheduler:', scheduler)
---> 48         scheduler.run()
     49         scheduler.join_jobs()
     50         # gather the best configuration

/usr/local/lib/python3.6/dist-packages/autogluon/scheduler/fifo.py in run(self, **kwargs)
    221                     (self.max_reward and self.get_best_reward() >= self.max_reward):
    222                 break
--> 223             self.schedule_next()
    224 
    225     def save(self, checkpoint=None):

/usr/local/lib/python3.6/dist-packages/autogluon/scheduler/fifo.py in schedule_next(self)
    262             extra_kwargs['new_config'] = False
    263         task = self._create_new_task(config, resources=resources)
--> 264         self.add_job(task, **extra_kwargs)
    265 
    266     def run_with_config(self, config):

/usr/local/lib/python3.6/dist-packages/autogluon/scheduler/fifo.py in add_job(self, task, **kwargs)
    324                 self.training_history_callback is not None:
    325             self._add_checkpointing_to_job(job)
--> 326         with self.LOCK:
    327             self.scheduled_tasks.append(task_dict)
    328 

/usr/lib/python3.6/multiprocessing/synchronize.py in __enter__(self)
     93 
     94     def __enter__(self):
---> 95         return self._semlock.__enter__()
     96 
     97     def __exit__(self, *args):

Looks like the threads are getting into a deadlock. How to resolve?

**Comment by Innixma** [comment]
Closing due to staleness. Many major updates to AG have occurred since this issue was created, so the issue may have been resolved.
