### ISSUE TITLE
Is there a way to suppress distributed.worker - WARNING - Memory use is high ..

### ISSUE THREAD

**Issue by ouwyukha** [awslabs/autogluon#493]
Is there a way to suppress this warning or even solve this?

> distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 12.09 GB -- Worker memory limit: 17.13 GB

I'm using Jupyter Notebook on WSL Ubuntu 18.04 and just installed latest version of autogluon by pip. At first i thought it's one time warning after i tried to load 5.6GB csv file. But when i tried to run print('test'), the warning is flooding again.

Here's my code:
```
import autogluon as ag
from autogluon import TabularPrediction as task
train_data = task.Dataset(file_path='train_data.csv')
print('test')
```

I tried:
warnings.filterwarnings("ignore")  : warning still show up eagerly
load smaller dataset : warning doesn't show up

Currently using 
```
import logging
logging.disable(50)
```
what's the worst thing can it be?

**Comment by Innixma** [comment]
This should be fixed in the recently released 0.0.10 version, thanks for reporting!
