### ISSUE TITLE
Could HyperbandScheduler obtain max_t from its train_fn?

### ISSUE THREAD

**Issue by mseeger** [awslabs/autogluon#498]
More of a question than an issue, looking for your ideas.
With HyperbandScheduler, we have time_attr, and we have associated max_t, grace_period, which are used to create the rung levels.

Now, it is usually the case that max_t is hard-coded into train_fn, right? If this is NN training, it knows its maximum number of epochs. Is there a way we could obtain max_t from train_fn, which would not be a burden for somebody writing a new train_fn?

I am asking because right now, max_t just defaults to 50, and users will usually not set it. This kind of works if your real max_t in train_fn is smaller, but if it is larger, you are in for a surprise, as HB will not go beyond this. Or at least the scheduler code assumes it does not.

**Comment by Innixma** [comment]
If I understand correctly, you want a unified variable that corresponds to the epochs/iterations/etc. of a particular model when running hyperband for it?

**Comment by zhanghang1989** [comment]
That's very good point. This was not considered during the initial design.

We can pass it through `task.args`, for example `task.args['max_t']=self.max_t` . We can add it at:
https://github.com/awslabs/autogluon/blob/master/autogluon/scheduler/hyperband.py#L280-L281

Then user can read it in the `train_fn`, `max_t=args.max_t`

**Comment by mseeger** [comment]
Yes. The thing is how to do it such that it does not put a burden on the user?

Of course, it is also a burden to have to pass max_t to HyperbandScheduler.

And the risk of not doing it is obvious.

@zhanghang1989 Your suggestion does not solve it. What we want is that the user does not have to specify max_t for HyperbandScheduler anymore, but it is taken from train_fn.

Maybe we could do something like this:
- Have max_t=None in HyperbandScheduler, instead of max_t=50 (which is dangerous)
- Then, if max_t remains None, we check whether train_fn somehow specifies it (I'd not exactly
   know how), and if so, take it from there. And if nothing is found, throw an exception
- Change all tutorials and docs to always add this info to train_fn, at least if HB scheduling is
   considered.

**Comment by zhanghang1989** [comment]
Thanks @mseeger  I see your point now.

It is hard to get it from the `train_fn` unless we ask the user to specify something like `max_t` (fixed name) in the `args`. Then we are able to read it.

**Comment by Innixma** [comment]
For Tabular this is do-able, as the Model class implementations contains this information, which can be fed to hyperband when optimizing the particular model. This is not a solve for the other tasks unless they adopt Tabular's AbstractModel class however. With that said, it is likely that they will in a future version of AG, this work is already in-progress for NLP.

**Comment by mseeger** [comment]
For all or most of our NN training examples, we have train_fn.args.epochs. But this is not a hard requirement, it just seems something folks tend to do.

Here is a proposal:
- Make the default in HyperbandScheduler (for max_t) = None
- If max_t is None, check whether train_fn.args contains a field epochs. If so, use the value for max_t, and also display some message "max_t = train_fn.args.epochs = ***"
- If nothing is found there, raise an assertion exception

Does that sound good? We could also check for other things in train_fn.args. As long as we display what we do?

Of course, if the user specifies max_t when creating HyperbandScheduler, this takes precedence.

I could do this, if somebody tell me a few details:
- How can I check for fields in args? It does not seem to be a dict ...

**Comment by Innixma** [comment]
@zhreshold Can you coordinate with @mseeger to get this working for image? I think we can perform the integration later on for Tabular, as it involves updating AbstractModel.

**Comment by zhreshold** [comment]
> Yes. The thing is how to do it such that it does not put a burden on the user?
> 
> Of course, it is also a burden to have to pass max_t to HyperbandScheduler.
> 
> And the risk of not doing it is obvious.
> 
> @zhanghang1989 Your suggestion does not solve it. What we want is that the user does not have to specify max_t for HyperbandScheduler anymore, but it is taken from train_fn.
> 
> Maybe we could do something like this:
> 
> * Have max_t=None in HyperbandScheduler, instead of max_t=50 (which is dangerous)
> * Then, if max_t remains None, we check whether train_fn somehow specifies it (I'd not exactly
>   know how), and if so, take it from there. And if nothing is found, throw an exception
> * Change all tutorials and docs to always add this info to train_fn, at least if HB scheduling is
>   considered.

It's probably still introducing some extra burden to user defined `train_fn` since the behavior of HyperBand and FIFO is diverging, some `train_fn` which run perfectly using FIFO won't stand in HyberBandScheduler. 

@mseeger  So two questions here:
- Is it dangerous to set a large `max_t` default value like `500`?
- If not, can HyberBandScheduler become smarter enough to detect possible values for `max_t`, such as `epochs` in `args`?

I am mentioning this because it's easier for native tasks to obey these rules but it's way harder to force user to understand what's the extra limitation of Hyperband scheduler.

**Comment by mseeger** [comment]
@zhreshold 
- Large value for max_t: I would have to look at the code in more detail. It certainly would be less
   of an issue than if max_t is too small
- Smarter HB scheduler: This is what I'd suggest

In terms of smarter HB, we could try this:
- If max_t is not None, use it. Then, the user knows what (s)he wants
- If max_t is None, try to infer it from train_fn.args. Look for epochs. If that is not present, look
   for max_t
- If nothing is found in train_fn.args, I'd fail with a clear message. I'd prefer this over doing things
   like set max_t to a huge number

**Comment by mseeger** [comment]
And we'd be clear in the documentation, say for HyperbandScheduler, that it is wise to use either epochs or max_t in args when writing train_fn.

Another thing: Say that HyperbandScheduler gets a max_t value (not None), AND train_fn.args contains epochs or max_t, and these are different. Then, we should write a warning message to the log, but still continue with using max_t passed to the scheduler.

This altogether sounds like a good solution to me.

**Comment by mseeger** [comment]
@zhreshold I can take a stab at this one.
Still, if you could tell me how I can cleanly test whether args has args.epochs or args.max_t, this would be helpful. I am not so firm on Python.

**Comment by mseeger** [comment]
Closing this, superseded by #507
