### ISSUE TITLE
Autogluon for linear models

### ISSUE THREAD

**Issue by priyanga24** [awslabs/autogluon#499]
Hi, 
I used the code below with the aws dataset which has binary class label. So it is logistic regression that must take action.
/*
from autogluon.utils.tabular.ml.trainer.auto_trainer import AutoTrainer
from autogluon.utils.tabular.ml.models.lr.lr_model import LinearModel
import autogluon as ag
import matplotlib.pyplot as plt
from autogluon import TabularPrediction as task
class LinearRegrssionTrainer(AutoTrainer):
    def get_models(self, hyperparameters={}, hyperparameter_tune=True):
        models = [
             LinearModel(
                 path=self.path, name='lr', problem_type=self.problem_type, objective_func=self.objective_func,
                 hyperparameters={'penalty': 'L2'},
             )
        ]
        return models
train_data2 = task.Dataset(file_path='https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
label_column = 'class'
predictor = task.fit(train_data=train_data2, label=label_column,
                     trainer_type = LinearRegrssionTrainer)
test_data2 = task.Dataset(file_path='https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')
y_test2 = test_data2[label_column]  # values to predict
test_data_nolab2 = test_data2.drop(labels=[label_column],axis=1) # delete label column
y_pred2 = predictor.predict(test_data_nolab2)

print("Predictions:  ", y_pred2)
print("actual", y_test2)
perf = predictor.evaluate_predictions(y_true=y_test2, y_pred=y_pred2, auxiliary_metrics=True)
*/
But I got this error:

TypeError                                 Traceback (most recent call last)
<ipython-input-11-af547269a3a7> in <module>
     16 label_column = 'class'
     17 predictor = task.fit(train_data=train_data2, label=label_column,
---> 18                      trainer_type = LinearRegrssionTrainer)
     19 test_data2 = task.Dataset(file_path='https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')
     20 y_test2 = test_data2[label_column]  # values to predict

/usr/local/lib/python3.6/dist-packages/autogluon/task/tabular_prediction/presets_configs.py in _call(**kwargs)
      7         @functools.wraps(f)
      8         def _call(**kwargs):
----> 9             return f(**g(**kwargs))
     10         return _call
     11     return _unpack_inner

/usr/local/lib/python3.6/dist-packages/autogluon/task/tabular_prediction/tabular_prediction.py in fit(train_data, label, tuning_data, time_limits, output_directory, presets, problem_type, eval_metric, stopping_metric, auto_stack, hyperparameter_tune, feature_prune, holdout_frac, num_bagging_folds, num_bagging_sets, stack_ensemble_levels, hyperparameters, num_trials, scheduler_options, search_strategy, search_options, nthreads_per_trial, ngpus_per_trial, dist_ip_addrs, visualizer, verbosity, **kwargs)
    579                     hyperparameter_tune=hyperparameter_tune, feature_prune=feature_prune,
    580                     holdout_frac=holdout_frac, num_bagging_folds=num_bagging_folds, num_bagging_sets=num_bagging_sets, stack_ensemble_levels=stack_ensemble_levels,
--> 581                     hyperparameters=hyperparameters, time_limit=time_limits_orig, save_data=cache_data, save_bagged_folds=save_bagged_folds, verbosity=verbosity)
    582 
    583         predictor = TabularPredictor(learner=learner)

/usr/local/lib/python3.6/dist-packages/autogluon/utils/tabular/ml/learner/default_learner.py in fit(self, X, X_test, scheduler_options, hyperparameter_tune, feature_prune, holdout_frac, num_bagging_folds, num_bagging_sets, stack_ensemble_levels, hyperparameters, time_limit, save_data, save_bagged_folds, verbosity)
    101         self.save()
    102         trainer.train(X, y, X_test, y_test, hyperparameter_tune=hyperparameter_tune, feature_prune=feature_prune, holdout_frac=holdout_frac,
--> 103                       hyperparameters=hyperparameters)
    104         self.save_trainer(trainer=trainer)
    105         time_end = time.time()

/usr/local/lib/python3.6/dist-packages/autogluon/utils/tabular/ml/trainer/auto_trainer.py in train(self, X_train, y_train, X_test, y_test, hyperparameter_tune, feature_prune, holdout_frac, hyperparameters)
     19             hyperparameters = {}
     20         self.hyperparameters = self._process_hyperparameters(hyperparameters=hyperparameters)
---> 21         models = self.get_models(self.hyperparameters, hyperparameter_tune=hyperparameter_tune, level=0)
     22         if self.bagged_mode:
     23             if (y_test is not None) and (X_test is not None):

TypeError: get_models() got an unexpected keyword argument 'level'

**Note: Previously my code it was working fine. The code gave good results with logistic regression. After you made some fixes to autogluon code yesterday, my code is showing me this error. Please help me to rectify and please give an example code for linear models. Thanks.**

**Comment by Innixma** [comment]
Thanks for submitting an issue!

Changing your get_models function fixed the issue:

```
class LinearRegrssionTrainer(AutoTrainer):
    def get_models(self, hyperparameters=None, **kwargs):
        models = [
            LinearModel(path=self.path, name='lr', problem_type=self.problem_type, objective_func=self.objective_func,hyperparameters={'penalty': 'L2'},)
        ]
        return models

```

In 0.0.10, the kwargs option was added to get_models to allow for improved extensibility and customization. You can solve the issue by specifying the **kwargs parameter.

Note that you can also get identical functionality in 0.0.10 without this custom class (Recommended):

```
predictor = task.fit(
        train_data=train_data2, label=label_column,
        hyperparameters={'LR': {'penalty': 'L2', '_ag_args': {'name': 'lr'}}}
)
```

Finally, if you want to get better accuracy with your LR model, try the following to use 100% of the training data for training the model instead of using a train/val split:

```
predictor = task.fit(
        train_data=train_data2, label=label_column,
        hyperparameters={'LR': {'penalty': 'L2', '_ag_args': {'name': 'lr'}}},
        refit_full=True, set_best_to_refit_full=True
)
```

Best,
Nick

**Comment by priyanga24** [comment]
Thank you so much!
