### ISSUE TITLE
Import error caused by removed private scikit-learn function

### ISSUE THREAD

**Issue by artemmavrin** [awslabs/autogluon#509]
Import error using autogluon 0.0.10 and scikit-learn 0.23.1:

```python
import autogluon
```

Error: `ImportError: cannot import name '_argmax'`, caused by

https://github.com/awslabs/autogluon/blob/566a00c552c1ecde8d8e8b433500aa0b46fdfc6b/autogluon/utils/tabular/ml/models/tabular_nn/categorical_encoders.py#L13

`_argmax` was removed from `sklearn.utils.fixes` in https://github.com/scikit-learn/scikit-learn/commit/75d3f29e724c9a2db7bcb5afb2d7e8c08ddbd80b.

**Comment by Innixma** [comment]
We do cap the sklearn version for other reasons related to skopt being incompatible with sklearn 0.23, although this will help us upgrade in future, thanks for the PR!
