### ISSUE TITLE
Time Limit Question

### ISSUE THREAD

**Issue by impulsecorp** [awslabs/autogluon#515]
Using tabular data, when I run it like:
predictor = task.fit(train_data=train_data, label=label_column, output_directory=dir, hyperparameter_tune=True, feature_prune=True, auto_stack=False, search_strategy='random')

it sets a time out of 77.14 for HPO for each algorithm. And then it only performs 1%-2% of the 1000 pending tasks (optimizations, I assume) due to hitting this time limit. Why is that? I did not set an overall time limit, so I would like it to run as long as needed, to be as accurate as possible.

This is what it shows after the 77 seconds have passed:
Num of Pending Tasks is 1000
Time out (secs) is 77.14285714285714
2%
21/1000 [1:41:54<79:10:49, 291.16s/it]

If I instead change it to have bagging sets and trials like this:
predictor = task.fit(train_data=train_data, label=label_column, output_directory=dir, hyperparameter_tune=True, feature_prune=True, auto_stack=False, search_strategy='random', num_bagging_sets=10, num_trials=100)

it has less tasks but a much much longer time out time: 
Starting Experiments
Num of Finished Tasks is 0
Num of Pending Tasks is 100
Time out (secs) is 900000.0

**Comment by Innixma** [comment]
To avoid having users run out of memory and other bad things, if you specify hyperparameter_tune=True without setting num_trials or time_limits, time_limits defaults to 10 minutes. If you want to do many trials, try setting time_limits=3600*24 to have it train for 24 hours.
