### ISSUE TITLE
Tabular metrics print negative values

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#524]
Fix metric printouts in Tabular showing negative values for metrics such as RMSE, MSE, log_loss, etc.

Areas where they are shown negative:
- logging statements after training
- leaderboard
- summary graphics

**Comment by arunmk** [comment]
@Innixma I observed the log_loss eval_metric as negative from the inner function itself (`best_model_score_val` from the `AutoTrainer.get_info` function). So it is not merely a printing artifact. Do you know if the values are accurate but only negative?

**Comment by Innixma** [comment]
@arunmk Yes, they are accurate in absolute value, but flipped since AutoGluon works under the assumption that higher = better for all metrics. This simplifies various logic in the codebase such as when sorting models best to worst, choosing the best model, HPO, etc.

**Comment by arunmk** [comment]
@Innixma ok, I will just invert the values where minima are used for now in our use cases. Thanks for the clarification!

**Comment by Innixma** [comment]
Labelling this as won't fix. I think it's better to keep them as negative to have consistency across the system and to simplify how sorting operates with respect to metric scores.

**Comment by zuliani99** [comment]
@Innixma So does this mean that if I have a negative RMSE I have to turn it into a positive value?

**Comment by Innixma** [comment]
@zuliani99 It's a negative RMSE score to clarify. RMSE = -RMSE score, so yes if you want to get the RMSE value, flip the RMSE score you get from AG. If you are linking AG into a larger system, consider calculating the score outside of AG by getting its predictions and feeding it into your own evaluation metric, this will avoid any confusion regarding AG's internal scoring representation.
