### ISSUE TITLE
Catbost hpo

### ISSUE THREAD

**Issue by priyanga24** [awslabs/autogluon#525]
Hi,
can you give an example of how to specify HPO searchspace for Catboost? Thanks

**Comment by priyanga24** [comment]
Solved it myself. sorry, Thank you.

**Comment by MSaber9** [comment]
ctb_reg_params = {
    'learning_rate':     hp.choice('learning_rate',     np.arange(0.05, 0.31, 0.05)),
    'max_depth':         hp.choice('max_depth',         np.arange(5, 16, 1, dtype=int)),
    'colsample_bylevel': hp.choice('colsample_bylevel', np.arange(0.3, 0.8, 0.1)),
    'n_estimators':      100,
    'eval_metric':       'RMSE',
}
