### ISSUE TITLE
time_limits not respected for object detection

### ISSUE THREAD

**Issue by Sam7791** [awslabs/autogluon#526]
Hello,
I set time_limits to 60*10 seconds (10 minutes) with 3 epoch.
The three epochs finished but the fit is still running more than one hour after end of last epoch training:
`time_limits = 60*10  # 5 hours
epochs = 3
detector = task.fit(dataset_train,
                    epochs=epochs,
                    net='resnet50_v1b',
                    batch_size=4,
                    meta_arch='faster_rcnn',
                    ngpus_per_trial=2,
                    SyncBN=True,
                    lr=ag.Categorical(0.02, 0.01, 0.005, 0.002, 2e-4, 5e-4),
                    time_limits=time_limits)`
the dataset is the motorbike datasets provided.
I get quickly the following results for the last epoch:
[Epoch 2] Training cost: 139.507, RPN_Conf=0.002,RPN_SmoothL1=0.012,RCNN_CrossEntropy=0.035,RCNN_SmoothL1=0.092
[Epoch 2] Validation: motorbike=0.8803156791528884 mAP=0.8803156791528884

Thank you in advance

**Comment by Innixma** [comment]
It is expected that this is now fixed in pre-release and upcoming v0.1 due to overhauls in the code.
