### ISSUE TITLE
Combine tabular and image tasks?

### ISSUE THREAD

**Issue by ifeherva** [awslabs/autogluon#538]
I have a problem best fit for tabular but one column points to images. Is it possible with AutoGluon to combine both tasks, so image and tabular input for each row? If yes, how?

**Comment by jwmueller** [comment]
Offering this as a built-in task is on our roadmap, but probably won't be ready for a while.
For now, you can use `ImageClassification.fit()` on just the images, and `TabularPrediciton.fit()` on the tabular input (on a GPU machine). At inference time you can just take a weighted average of the image-classifier's predicted probabilities and the tabular-predictor's predicted probabilities (assigning a weight to image-classifier that maximizes accuracy over held-out validation data).

**Comment by Innixma** [comment]
#1041 implements Tabular + Image functionality.
