### ISSUE TITLE
Function on AutoGluon that returns a confusion matrix corresponding to the predict

### ISSUE THREAD

**Issue by calebeaires** [awslabs/autogluon#544]
I have done some tests with this lib. Is is fast and accurate. I was wondering how to call some function from evaluate objects that returns a **confusion matrix corresponding to the  predict** while using the processo of TabularPrediction

**Comment by Innixma** [comment]
This is not currently implemented, but I think would be a great addition. Contributions are welcome!

**Comment by alan-aipe** [comment]
@Innixma : May I take this task up? I would like to start contributing to this project and this seems like a good first issue as you have rightfully pointed out.

**Comment by Innixma** [comment]
@alan-aipe : Certainly! I've sent you an email with some tips on getting started.

**Comment by alan-aipe** [comment]
Seems that I did not receive the email yet. Can you forward it to alanaipe@outlook.com?

**Comment by alan-aipe** [comment]
Thanks for the mail. I will start working on this :)

**Comment by alan-aipe** [comment]
@Innixma : Can you have a look at the PR. It seems the CI failed during BUILD_DOC phase because of `ImportError: cannot import name '_psutil_linux' from 'psutil' (/var/lib/jenkins/miniconda3/envs/autogluon_docs/lib/python3.7/site-packages/psutil/__init__.py)` . Let me know if this was caused because of my code as I am not able to figure this out.

**Comment by Innixma** [comment]
@alan-aipe Sorry for the confusion, this started happening 2 days ago due to a psutil update (I believe), I will be debugging it to try to fix the CI. Once the fix is merged I'll update this thread and you can rebase your PR onto the fix to get CI to pass.

**Comment by jwmueller** [comment]
Added in:  https://github.com/awslabs/autogluon/pull/571
