### ISSUE TITLE
Neural Architecture search

### ISSUE THREAD

**Issue by priyanga24** [awslabs/autogluon#553]
Hello, is it possible to implement NAS in autogluon? if yes, can you please provide an example or syntax to build a CNN for image dataset using NAS?

**Comment by jwmueller** [comment]
Yes there is an implementation available for you to use for vision tasks.  See our provided tutorial here:
https://autogluon.mxnet.io/tutorials/nas/index.html

**Comment by priyanga24** [comment]
thanks, under what environmental constrains did this work? I mean the the amount of memory, speed, number of GPU's? 
I have a free tier AWS Sagemaker account with which I have 4 GB RAM and 2 virtual CPU's.

**Comment by priyanga24** [comment]
Also may I know how to define our own threshold for classification problems ? thanks!

**Comment by jwmueller** [comment]
If you read the ProxylessNAS paper closely, they also consider an additional non-gradient-based NAS which is basically ENAS.  The basic cell being searched here is convolutional and is precisely defined under "AutoGluon ENAS Unit":
https://autogluon.mxnet.io/tutorials/nas/enas_proxylessnas.html#autogluon-enas-unit

With your limited compute power, I would avoid NAS if I were you.  CNNs in general require extensive compute (ideally at least 1 GPU), and NAS is even more compute-intensive than standard CNN-training (1 GPU could work but would probably take a long time to get a good model, something like 8 GPUs will be much more reasonable). 

I recommend you first try this instead for your data (again ideally on a GPU machine):  https://autogluon.mxnet.io/tutorials/image_classification/beginner.html

To adjust the classification-threshold, you can just use the `classifier.predict_proba()` method to get predicted probabilities and apply your own threshold yourself. 

By the way if you have time, we would greatly appreciate it if you want to add the ability to select a threshold inside `Classifier.predict()`!

**Comment by priyanga24** [comment]
Thanks, thanks a lot!
