### ISSUE TITLE
Save and Load Individual Models

### ISSUE THREAD

**Issue by misterm10** [awslabs/autogluon#586]
How do I load an individual model?

When i use x.delete_models(models_to_keep='ExtraTreesClassifierEntr_STACKER_l1', dry_run=False) 

It keeps many models not just this model?

When I load the pickle file it appears to the same result for every model on the validation data.

Please could someone advise?

Thanks in advance.

**Comment by Innixma** [comment]
`ExtraTreesClassifierEntr_STACKER_l1` is a Level 1 stack ensemble. That means for it to produce predictions it requires input from Level 0 models. These are the models which are present after the delete models call. It is the minimal valid set of models required for your desired model to function.

**Comment by utopianpallu** [comment]
@Innixma 
Hii I want to load individual models that are generated in models directory and get their metrics.But when i do task.load() , it is loading learner.pkl file always , that is the best model.
How to load model.pkl file from each model that is generated using task.load()?

**Comment by utopianpallu** [comment]
@Innixma For every individual model that i am loading am getting same metric values.
I used this to load:
model = predictor._trainer.load_model('ExtraTreesClassifierEntr')
But when i tried predicting , I am getting errors.

**Comment by Innixma** [comment]
@utopianpallu You can use predictor.info() to get a lot of model-specific information. Alternatively, you can use non-public API's to get access to the models:

```
your_model_object = predictor._trainer().load_model('your_models_name')
```

Due note that it isn't recommended that you use the model object outside of the predictor context, as the model depends on a variety of functionality outside of its context to properly generate predictions on new data.

**Comment by utopianpallu** [comment]
> @utopianpallu You can use predictor.info() to get a lot of model-specific information. Alternatively, you can use non-public API's to get access to the models:
> 
> ```
> your_model_object = predictor._trainer.load_model('your_models_name')
> ```
> 
> Due note that it isn't recommended that you use the model object outside of the predictor context, as the model depends on a variety of functionality outside of its context to properly generate predictions on new data.
@Innixma I tried using this, I am confused as the accuracy are not coming same , in predictor.fit_summary() the accuracy for Light GBM is 0.86 and when i tried loading that model , the accuracy is 0.82.
![Screenshot 2020-08-04 at 11 09 19 AM](https://user-images.githubusercontent.com/48690720/89257346-9a69cf80-d643-11ea-9a70-a919bb762bf9.png)

![Screenshot 2020-08-04 at 11 09 07 AM](https://user-images.githubusercontent.com/48690720/89257142-3f37dd00-d643-11ea-8992-65f497d7fe00.png)

Please clarify. Thanks !
