### ISSUE TITLE
Tabular: Add XGBoost Model

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#589]
Add XGBoost model to increase model diversity in AutoGluon-Tabular.

**Comment by Dipanks** [comment]
HI @Innixma 
Can I work on this?

**Comment by Innixma** [comment]
> HI @Innixma
> Can I work on this?

Sure! Please reference the existing LightGBM and CatBoost implementations when making your model class, and reference [example_custom_model_tabular.py ](https://github.com/awslabs/autogluon/blob/master/examples/tabular/example_custom_model_tabular.py) for an example of adding a custom model to AutoGluon.

**Comment by Innixma** [comment]
@Dipanks Do you have an update on this? If not I may consider taking up the task.

**Comment by sackoh** [comment]
Hi, @Innixma   can I join this work?

**Comment by Innixma** [comment]
@sackoh Hi David, feel free to take up this task and reference the existing LightGBM and Catboost implementations to aid in your code. Do note that I will plan to take up this task in a couple weeks if a contribution has not been submitted, as it is high priority, so please consider the timeline in which you plan to work on this, as submitting a PR within the next 1-2 weeks would be highly preferred.

**Comment by sackoh** [comment]
@Innixma Ok, I consider this in my priority.

**Comment by sackoh** [comment]
@Innixma  Hi, Nick! 
I have spent a couple of days to review the code structure of tabular task.
I started to work on this task in my forked repo.
Hope to finish within coming next 1-2 weeks. 🤗

**Comment by Innixma** [comment]
Awesome, thanks for the update!

**Comment by sackoh** [comment]
@Innixma Hi, Nick. I have cretaed #691 to add XGBoost model.

**Comment by Innixma** [comment]
Great, I'll take a look!

**Comment by Innixma** [comment]
XGBoost model has now been merged in. Thanks @sackoh for the contribution!
