### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by priyanga24** [awslabs/autogluon#593]
Hello team,

I have a tabular dataset which is of size 2GB and when I try to use this dataset to implement an ensemble model(binary classification problem), autogluon gives memory error. I am running the experiment on my workstation with 16GB RAM. Is there anyway I can run the full dataset to create ensemble? thanks

**Comment by Innixma** [comment]
Hello,

In order to help you will need to provide more information. Specifically logs of the run. Also, 16GB of RAM is quite small for handling a 2GB dataset. Consider upgrading to 32GB.
