### ISSUE TITLE
tabular fit cannot take positional argument 

### ISSUE THREAD

**Issue by mli** [awslabs/autogluon#594]
The following code doesn't work

```python
model = task.fit(train, ...)
```

```
TypeError: _call() takes 0 positional arguments but 1 was given
```

if read from source code, it seems this usage should be fine

```python
    def fit(train_data,
            label,
            tuning_data=None,
```

on the other hand, it's ok to call `model.predict(val)`. can we find a way to resolve this inconsistency?

**Comment by Innixma** [comment]
This has been fixed on mainline, but is not yet available in a release: #576
