### ISSUE TITLE
NativeImageFolderDataset vs ImageFolderDataset

### ISSUE THREAD

**Issue by jwmueller** [awslabs/autogluon#603]
Should `NativeImageFolderDataset` be a subclass of `ImageFolderDataset`?
Currently `NativeImageFolderDataset` lacks many of the attributes of `ImageFolderDataset`, such as:
`class_to_idx`, and is not even documented here: 
 https://autogluon.mxnet.io/api/autogluon.task.html#autogluon.task.ImageClassification.Dataset

Also the exact same code may arbitrarily return either `ImageFolderDataset` or `NativeImageFolderDataset` (based on `_is_osx` variable which is determined by Mac vs Linux), so these two should really look identical to users no?

https://github.com/awslabs/autogluon/blob/c7ec8d9461491e1eff65c84d66d19979161ec970/autogluon/task/image_classification/dataset.py#L146

https://github.com/awslabs/autogluon/blob/c7ec8d9461491e1eff65c84d66d19979161ec970/autogluon/task/image_classification/dataset.py#L177

For example, you can run the following on Mac vs on Ubuntu and get either ImageFolderDataset or NativeImageFolderDataset:

```
import autogluon as ag
from autogluon import ImageClassification as task

filename = ag.download('https://autogluon.s3.amazonaws.com/datasets/shopee-iet.zip')
data_folder = ag.unzip(filename)

train_data = task.Dataset('data/train')
train_loaded = train_data.init()
print(train_loaded) 
train_loaded.class_to_idx  # wont work if NativeImageFolderDataset, only if ImageFolderDataset
```

**Comment by Innixma** [comment]
This is likely resolved as of 0.1 / 0.2.
