### ISSUE TITLE
print parameter issue -- related to S3

### ISSUE THREAD

**Issue by cfaaa4460** [awslabs/autogluon#606]
I’m trying to save autogluon model to S3 and print the parameters. Below is my code for V0.0.12. Could you help? Thanks a lot!
 
from autogluon import TabularPrediction as task
 
hyp ={'CAT': {}} 
predictor = task.fit(train_data=combined, label='model_flag',problem_type='binary',eval_metric='log_loss',
                     hyperparameters = hyp,output_directory = 's3://bucket1/model_output1/') 
 
print('The best configuration is:')
print(predictor.results['best_config'])
 
I got some error (part of the error) like this below.

The best configuration is:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-38-f9d2c7a59c8b> in <module>
      1 print('The best configuration is:')
----> 2 print(predictor.results['best_config'])
 
AttributeError: 'TabularPredictor' object has no attribute 'results'
 

FileNotFoundError: [Errno 2] No such file or directory: 's3://bucket1/model_output1/SummaryOfModels.html'

**Comment by jwmueller** [comment]
For TabularPrediction, the usage is a bit different than for other tasks.  Can you try this instead?
```
predictor = task.fit(...)
results = predictor.fit_summary()
print(results)
```

You can then extract the appropriate key you want from the `results` object.

**Comment by Innixma** [comment]
@jwmueller We do need to change all instances of file save/load to be compatible with S3, likely by using a generic wrapper save/load function for generic files like we do already with load_pd/save_pd and load_pkl/save_pkl. 

We need to create load_file/save_file. I believe this impacts HPO and some of the post-fit methods such as fit_summary().

**Comment by Innixma** [comment]
Due to the increasing complexity of support s3 for all models, we no longer support training with s3 path for artifacts directly. Instead, train with local path and clone artifacts from local to s3 after training is complete.

**Comment by inigohidalgo** [comment]
For what it's worth, for anybody looking to persist model results on cloud storage, using fsspec for these operations is probably the best solution:

training
```python
predictor = TimeSeriesPredictor(path="test-model")
...
predictor.fit(...)

from adlfs import AzureBlobFileSystem # for s3 use s3fs, google cloud use gcsfs

cloud_fs = AzureBlobFileSystem(....)
cloud_fs.put("test-model/", "remote/storage/path/")
```

inference
```python
import tempfile
model_tmp_dir = tempfile.TemporaryDirectory()
cloud_fs.get("remote/storage/path/", model_tmp_dir.name, recursive=True)
predictor_from_blob = TimeSeriesPredictor.load(model_tmp_dir.name)
```
