### ISSUE TITLE
Bug on Tabular Feature Generation

### ISSUE THREAD

**Issue by EternalConfession** [awslabs/autogluon#611]
The code in Feature Generator

[https://github.com/awslabs/autogluon/blob/b96e678c350dfc31bb4a3a2bb9e86621d0711bfd/autogluon/utils/tabular/features/abstract_feature_generator.py#L344](url)

defines:

```python
max_desired_bins = min(ideal_cats, max_bins)
min_desired_bins = min(ideal_cats, max_bins)
```

It means that the number of bins will always be ideal cats which is 10.

Or did you initially want to make the feature generator this way?

**Comment by Innixma** [comment]
Great comment! This isn't necessarily a bug but more that the iterative approach to determining optimal bins was fast enough that it was better to early stop through `max_iterations` than through non-ideal bin counts. I am currently refactoring feature generation, and this threshold could be one of the hyperparameters/parameters to the binning generator. To understand if max/min desired bins are ever useful to be different than ideal/max_bins, we would probably want to add tests to the function.

**Comment by EternalConfession** [comment]
So why don't you use

```python
if len(interval) != idea_count:
       pass
```
The current implementation will always make the number of bins to 10. 

It also seems that the fit_transform function didn't really run when I use the tabular predictor. It will feed the raw input to the learner.

**Comment by Innixma** [comment]
Yes, that logic would be equivalent in the current implementation, but I plan to parameterize the min and max values.

Regarding the fit_transform, it is called within learner. Learner has a feature generator object within it that it calls to prepare the data before sending it to Trainer. Trainer trains all of the models using the data provided by Learner.
