### ISSUE TITLE
Tabular: output_directory overwrite issue

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#614]
If two predictors are trained within the same second, they can overwrite each-other's output. This can be fixed by adding a check to see if the directory already exists, and then adding an _N to make a new unique directory (but only if the directory was not specified by user prior). N would be a number >=1, which would be checked repeatedly until a number that results in a unique directory is chosen.

Note that race conditions might still occur in this setup if they are extremely close in start time. A lock could potentially be added on the directory creation process to ensure this does not happen.

Contributions are welcome!

**Comment by songqiang** [comment]
I can take care of this. Seems a simple one.

**Comment by Innixma** [comment]
Awesome, sounds good!

**Comment by Innixma** [comment]
Resolved by #614, thanks Qiang for the very helpful contribution!
