### ISSUE TITLE
Tabular: Multi-label support

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#615]
Enable the following functionality:

```
label_column = ['label1','label2','label3','label4']

predictor = task.fit(train_data=train_data, label=label_column)
```

Contributions are welcome! We suggest that contributors start by enabling multi-label support in individual models by checking the incoming dimensions of the y_train and y_val arguments in the [Model classes](https://github.com/awslabs/autogluon/tree/master/autogluon/utils/tabular/ml/models). This change should be accompanied by a unit test which constructs and trains a multi-label dataset using the model. See this [example](https://github.com/awslabs/autogluon/blob/master/examples/tabular/example_custom_model_tabular.py) for guidance. 

Once several models support this functionality, a contribution can be made to enable the passing of multi-label y throughout the Learner and Trainer logic.

Related issues: #228

**Comment by schinto** [comment]
Multi-output support as discussed in the [article](https://arxiv.org/pdf/1904.03943.pdf) would be great, too.

**Comment by Innixma** [comment]
Basic multi-label support has been added as a tutorial in #953, which is available in pre-release documentation: https://auto.gluon.ai/dev/tutorials/tabular_prediction/tabular-multilabel.html
