### ISSUE TITLE
resume training

### ISSUE THREAD

**Issue by priyanga24** [awslabs/autogluon#616]
Hello team,
https://arxiv.org/pdf/2003.06505.pdf in page number 2, it says "All  intermediate  results  are  saved  on  disk. If  a  call was canceled,  we can invoke fit() with the argument continue training=True to resume training."
But this parameter is not available with the fit() function in tabular prediction? How to resume training of a saved unfinished model? thanks

**Comment by Innixma** [comment]
Please see #475
