### ISSUE TITLE
multiprocessing.fork breaks PyTorch autograd

### ISSUE THREAD

**Issue by samuelstanton** [awslabs/autogluon#619]
Python version: 3.6.5
AutoGluon version: 0.0.11
PyTorch version: 1.5.1

I'm using an Autogluon HyperbandScheduler to do neural architecture search. I'm running into trouble executing jobs on a multi-node cluster due to this error thrown during a backwards call. 

```
RuntimeError: Unable to handle autograd's threading in combination with fork-based multiprocessing. 
See https://github.com/pytorch/pytorch/wiki/Autograd-and-Fork.
```

Reading the linked issue, it seems like PyTorch supports the use of `multiprocessing.spawn` but not `multiprocessing.fork`. Does `fork` support some feature that `spawn` does not? Is there a known workaround?

--

**Comment by Innixma** [comment]
@zhreshold Could you take a look?

**Comment by samuelstanton** [comment]
I'm working on a minimal example to reproduce the issue. My use case is something like this

```
import multiprocessing as mp
import torch
import autogluon as ag
import yaml
import hydra
import os
import time


@ag.args(x0=ag.space.Categorical('a', 'b', 'c', 'd', 'e'),
         x1=ag.space.Categorical('a', 'b', 'c', 'd', 'e'),
         x2=ag.space.Categorical('a', 'b', 'c', 'd', 'e'),
         epochs=32)
def train_fn(args, reporter, **kwargs):
    x = torch.rand(1)
    x = x.cuda() if torch.cuda.is_available() else x
    x.requires_grad = True
    optimizer = torch.optim.SGD([x], lr=1e-2)
    for i in range(args.epochs):
        loss = x ** 2
        loss.backward()
        optimizer.step()
        print(f"--- iteration: {i+1}, x: {x.item():.4f} ---")
        time.sleep(2.)
        reporter(epoch=i+1, objective=-loss.item())


@hydra.main(config_path='../hydra/main.yaml')
def min_example(cfg):
    num_cpus = mp.cpu_count()
    num_gpus = torch.cuda.device_count()
    host_file = os.path.join(hydra.utils.get_original_cwd(), 'hosts.yaml')
    with open(host_file, 'r') as f:
        dist_ip_addrs = yaml.full_load(f)

    scheduler = ag.scheduler.HyperbandScheduler(
        train_fn,
        resource=dict(num_cpus=num_cpus, num_gpus=num_gpus),
        search_options=dict(first_is_default=False),
        dist_ip_addrs=dist_ip_addrs,
        searcher='random',
        grace_period=1,
        reduction_factor=2,
        num_trials=32,
        time_attr='epoch',
        reward_attr='objective',
        type='promotion',
    )
    scheduler.run()
    scheduler.join_jobs()


if __name__ == '__main__':
    min_example()
```

Strangely enough, this example works fine, but when I replace my dummy `train_fn` with actual model training code, the error I mentioned gets thrown. As far as I can tell, it seems to work fine when the `train_fn` call happens on a worker, and fail when the `train_fn` call happens on the main node.

**Comment by zhreshold** [comment]
I guess it's related to https://github.com/awslabs/autogluon/issues/602

**Comment by samuelstanton** [comment]
Thanks for the tip! In my case, I was saving and loading model checkpoints from S3 inside my `train_fn` to halt/resume training. Doing the checkpoint saving/loading on CPU appears to have resolved my issue.
