### ISSUE TITLE
Possible bug due to hybridization of the supernet in ENAS

### ISSUE THREAD

**Issue by Tobias314** [awslabs/autogluon#622]
In the enas implementation of autogluon there exists a supernet which represents the whole search space. This supernet corresponds with the [ENAS paper](https://arxiv.org/abs/1802.03268) where it is described as a DAG and all the possible architectures are sub-graphs of this supernet. If I understand it correctly in the autogluon implementation of enas this is implemented using the `ENAS_Unit` class. Here an `ENAS_Unit` represents several nodes of the same kind in the supergraph. To sample an architecture from the search space for each `ENAS_Unit` one of the possible alternatives is chosen. This is done in the [`hybrid_forward()`](https://github.com/awslabs/autogluon/blob/fefd83f390b22cbc3f486901793e44c909c93d04/autogluon/contrib/enas/enas.py#L373) method of an `ENAS_Unit`. Each `ENAS_Unit` stores all possible alternatives in a `module_list`, then the enas controller sets an index for each `ENAS_Unit` to specify which alternative to use and then during the forward pass for each `ENAS_unit` the alternative corresponding to the index is chosen from the module list.
This makes quite sense however when using an instance of such an supernet for enas training the supernet is hybridized by the `ENAS_Scheduler` by calling [`self.supernet.hybridize()`](https://github.com/awslabs/autogluon/blob/fefd83f390b22cbc3f486901793e44c909c93d04/autogluon/contrib/enas/enas_scheduler.py#L80) in the `initialize_miscs` function. From what I understand, hybridizing in MXNet is done by performing one forward pass, "recording" the operations, and building a computational graph which is then used afterwards so that no further calls to `hybrid_forward()` are necessary. But that would mean that the selection of the right alternatives for each `ENAS_Unit` is only done once at the beginning when the computational graph is built. Afterwards the computational graph is fixed and training the controller which chooses different alternatives for the `ENAS_Units` would have no effect. So in fact we would only train the initial sampled architecture from the beginning till the end and the enas controller would sample different architectures but those are never trained.

What supports my assumption is that I get different results when running enas and commenting out the line [`self.supernet.hybridize()`](https://github.com/awslabs/autogluon/blob/fefd83f390b22cbc3f486901793e44c909c93d04/autogluon/contrib/enas/enas_scheduler.py#L80) in the initilization of the `ENAS_Scheduler`. In theory that shouldn't make any difference other than running a bit slower. In my case however I get a completely different result.

Did I just understand something wrong and the sampling works like expected or is there a bug in the autogluon enas module?

**Comment by Innixma** [comment]
Thanks for making a detailed issue on the topic!

@zhreshold Could you take a look?

**Comment by zhreshold** [comment]
@Tobias314 Your understanding is correct about the hybridization, however, ENAS training is a dynamic process so the recording needs to be done anytime the structure gets updated, i.e., the `supernet.hybridization` during initialization will freeze the recorded graph and cause troubles. TLDR, do not use hybridization during training, but inference. In the latter case you can benefit from it.

**Comment by Tobias314** [comment]
Thanks for the quick response.
 So will it then be fixed in the next Autogluon release? I mean the [`self.supernet.hybridize()`](https://github.com/awslabs/autogluon/blob/fefd83f390b22cbc3f486901793e44c909c93d04/autogluon/contrib/enas/enas_scheduler.py#L80) call is in the ENAS_Scheduler code of Autogluon so when you just use ENAS like e.g. shown in the Autogluon ENAS tutorial, currently you will get wrong results, right?

**Comment by zhreshold** [comment]
@Tobias314 I didn't find anything related to hybridization in the ENAS tutorial. Do you mean autogluon should explicitly disable the hybridization during training to avoid the potential misuse?

**Comment by Tobias314** [comment]
@zhreshold No, I am talking about the fact that the autogluon ENAS implementation does this hybridization internally and if that really is a bug then it should be fixed. Because otherwise the autogluon ENAS is incorrect.

So I am talking about [line 80](https://github.com/awslabs/autogluon/blob/df18ef328672aab3b80a543dde73543de0d68a16/autogluon/contrib/enas/enas_scheduler.py#L80) of autogluon/contrib/enas/enas_scheduler.py in the current master. If you agree, that this hybridization is indeed an issue for the ENAS algorithm, I would just suggest to remove that line.
