### ISSUE TITLE
Autogluon image classification quick start hangs 

### ISSUE THREAD

**Issue by quantum-fusion** [awslabs/autogluon#623]
I executed the image Classification example from your AutoGluon Image Classification quick Start (https://autogluon.mxnet.io/tutorials/image_classification/beginner.html), and the imageClassification.py file is here: (https://www.dropbox.com/s/9lfiw7kgixs4jc2/imageClassification.py?dl=0)

I found that the program when executed has hung, and shows the number of pending tasks as 2, but they never execute.

I am running on MACOS with Python3.  

See transcripts 
----
python imageClassification.py 
Downloading shopee-iet.zip from https://autogluon.s3.amazonaws.com/datasets/shopee-iet.zip...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40895/40895 [00:10<00:00, 3820.21KB/s]
Auto suggesting network net for dataset AutoGluonObject
scheduler_options: Key 'training_history_callback_delta_secs': Imputing default value 60
scheduler_options: Key 'delay_get_config': Imputing default value True

scheduler: FIFOScheduler(
DistributedResourceManager{
(Remote: Remote REMOTE_ID: 0, 
	<Remote: 'inproc://10.11.12.74/59170/1' processes=1 threads=16, memory=34.36 GB>, Resource: NodeResourceManager(16 CPUs, 0 GPUs))
})

Starting Experiments
Num of Finished Tasks is 0
Num of Pending Tasks is 2
  0%|                                                                                                                                                                           | 0/2 [00:00<?, ?it/s]Auto suggesting network net for dataset AutoGluonObject
scheduler_options: Key 'training_history_callback_delta_secs': Imputing default value 60
scheduler_options: Key 'delay_get_config': Imputing default value True

scheduler: FIFOScheduler(
DistributedResourceManager{
(Remote: Remote REMOTE_ID: 0, 
	<Remote: 'inproc://10.11.12.74/59215/1' processes=1 threads=16, memory=34.36 GB>, Resource: NodeResourceManager(16 CPUs, 0 GPUs))
})

Starting Experiments
Num of Finished Tasks is 0
Num of Pending Tasks is 2
  0%|                                                                                                                                                                           | 0/2 [00:00<?, ?it/s]^CTraceback (most recent call last):
  File "imageClassification.py", line 15, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    classifier = task.fit(dataset,
  File "/Users/hottelet/venv/lib/python3.8/site-packages/autogluon/task/image_classification/image_classification.py", line 311, in fit
    results = BaseTask.run_fit(
  File "/Users/hottelet/venv/lib/python3.8/site-packages/autogluon/task/base/base_task.py", line 58, in run_fit
    scheduler.run()
  File "/Users/hottelet/venv/lib/python3.8/site-packages/autogluon/scheduler/fifo.py", line 259, in run
    self.schedule_next()
  File "/Users/hottelet/venv/lib/python3.8/site-packages/autogluon/scheduler/fifo.py", line 284, in schedule_next
    FIFOScheduler.resource_manager._request(resources)
  File "/Users/hottelet/venv/lib/python3.8/site-packages/autogluon/scheduler/resource/dist_manager.py", line 73, in _request
    request_semaphore.acquire()
KeyboardInterrupt
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/hottelet/autoGluon/imageClassification.py", line 15, in <module>
    classifier = task.fit(dataset,
  File "/Users/hottelet/venv/lib/python3.8/site-packages/autogluon/task/image_classification/image_classification.py", line 311, in fit
    results = BaseTask.run_fit(
  File "/Users/hottelet/venv/lib/python3.8/site-packages/autogluon/task/base/base_task.py", line 58, in run_fit
    scheduler.run()
  File "/Users/hottelet/venv/lib/python3.8/site-packages/autogluon/scheduler/fifo.py", line 259, in run
    self.schedule_next()
  File "/Users/hottelet/venv/lib/python3.8/site-packages/autogluon/scheduler/fifo.py", line 300, in schedule_next
    self.add_job(task, **extra_kwargs)
  File "/Users/hottelet/venv/lib/python3.8/site-packages/autogluon/scheduler/fifo.py", line 362, in add_job
    with self.LOCK:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()

pip list
Package                  Version             Location
------------------------ ------------------- ----------------------------------
absl-py                  0.9.0
appnope                  0.1.0
astunparse               1.6.3
attrs                    19.3.0
autogluon                0.0.12
backcall                 0.2.0
bcrypt                   3.2.0
beautifulsoup4           4.9.1
boto3                    1.14.44
botocore                 1.17.44
Bottleneck               1.3.2
cachetools               4.1.1
catboost                 0.23.2
certifi                  2020.6.20
cffi                     1.14.2
chardet                  3.0.4
click                    7.1.2
cloudpickle              1.5.0
ConfigSpace              0.4.10
cryptography             3.0
cycler                   0.10.0
Cython                   0.29.21
dask                     2.23.0
decorator                4.4.2
distributed              2.23.0
docutils                 0.15.2
enum-compat              0.0.3
fastprogress             0.2.3
flake8                   3.8.3
future                   0.18.2
gast                     0.3.3
glob2                    0.7
gluoncv                  0.8.0
google-api-core          1.22.0
google-api-python-client 1.10.0
google-auth              1.19.2
google-auth-httplib2     0.0.4
google-auth-oauthlib     0.4.1
google-pasta             0.2.0
googleapis-common-protos 1.52.0
graphviz                 0.8.4
grpcio                   1.30.0
h5py                     2.10.0
HeapDict                 1.0.1
httplib2                 0.18.1
idna                     2.10
imageio                  2.9.0
iniconfig                1.0.1
ipykernel                5.3.4
ipython                  7.16.1
ipython-genutils         0.2.0
jedi                     0.17.2
jmespath                 0.10.0
joblib                   0.16.0
jupyter-client           6.1.6
jupyter-core             4.6.3
Keras                    2.4.3
Keras-Preprocessing      1.1.2
kiwisolver               1.2.0
liac-arff                2.4.0
lightgbm                 2.3.1
Markdown                 3.2.2
matplotlib               3.2.1
mccabe                   0.6.1
model-archiver           1.0.3
more-itertools           8.4.0
msgpack                  1.0.0
multi-model-server       1.1.2
munch                    2.5.0
mxnet-mkl                1.7.0b20200315
networkx                 2.4
numpy                    1.18.2
nvidia-ml-py3            7.352.0
oauth2client             4.1.3
oauthlib                 3.1.0
onnx                     1.7.0
opencv-contrib-python    4.3.0.36
openml                   0.10.2
opt-einsum               3.2.1
packaging                20.4
pandas                   0.25.3
paramiko                 2.7.1
parso                    0.7.0
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   6.2.1
pip                      20.2.2
plotly                   4.9.0
pluggy                   0.13.1
portalocker              2.0.0
pretrainedmodels         0.7.4
prompt-toolkit           3.0.5
protobuf                 3.12.2
psutil                   5.7.2
ptyprocess               0.6.0
py                       1.9.0
py4j                     0.10.9
pyaml                    20.4.0
pyasn1                   0.4.8
pyasn1-modules           0.2.8
pycodestyle              2.6.0
pycparser                2.20
pyflakes                 2.2.0
Pygments                 2.6.1
PyNaCl                   1.4.0
pyparsing                2.4.7
pyspark                  3.0.0
pytest                   6.0.1
python-dateutil          2.8.1
pytz                     2020.1
PyWavelets               1.1.1
PyYAML                   5.3.1
pyzmq                    19.0.1
requests                 2.24.0
requests-oauthlib        1.3.0
retrying                 1.3.3
rsa                      4.6
s3transfer               0.3.3
scikit-image             0.16.2
scikit-learn             0.22.2.post1
scikit-optimize          0.7.4
scipy                    1.4.1
seaborn                  0.10.1
setuptools               41.2.0
six                      1.15.0
sklearn                  0.0
sortedcontainers         2.2.2
soupsieve                2.0.1
tb-nightly               2.3.0a20200722
tblib                    1.7.0
tensorboard              2.2.2
tensorboard-plugin-wit   1.7.0
tensorflow               2.2.0
tensorflow-estimator     2.2.0
tensorflow-hub           0.8.0
tensorflow-serving-api   2.2.0
termcolor                1.1.0
tf-estimator-nightly     2.4.0.dev2020072301
tf-nightly               2.4.0.dev20200723
Theano                   1.0.4
threadpoolctl            2.1.0
toml                     0.10.1
toolz                    0.10.0
torch                    1.6.0
torch-model-archiver     0.2.0
torchserve               0.2.0
torchvision              0.7.0
tornado                  6.0.4
tqdm                     4.44.1
traitlets                4.3.3
typing                   3.7.4.3
typing-extensions        3.7.4.2
uritemplate              3.0.1
urllib3                  1.25.9
watermark                2.0.2               /Users/hottelet/venv/src/watermark
wcwidth                  0.2.5
Werkzeug                 1.0.1
wheel                    0.34.2
wrapt                    1.12.1
xmltodict                0.12.0
zict                     2.0.0

**Comment by Innixma** [comment]
Thanks for submitting an issue!

I believe that the likely cause is #139, as mxnet has some issues running on MacOS in HPO mode. Could you try using Linux?

@zhreshold Feel free to add to this if you have additional insight.

**Comment by Innixma** [comment]
Closing due to staleness. We don't support GPU training on MacOS at present.
