### ISSUE TITLE
Problem in Importing AutoGluon Package

### ISSUE THREAD

**Issue by Renesis88** [awslabs/autogluon#633]
Hi. I was using AutoGluon about a year back there were no issues. Only recently I keep having this Import Error. I didn't change the code. Was there some updates that affected this ?

**pip install --upgrade mxnet
pip install autogluon

import autogluon as ag
from autogluon import TabularPrediction as task**

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-cdb16434639b> in <module>
----> 1 import autogluon as ag
      2 from autogluon import TabularPrediction as task
      3 import pandas as pd
      4 import numpy
      5 import csv

/opt/conda/lib/python3.7/site-packages/autogluon/__init__.py in <module>
     23 from .utils import *
     24 from .core import *
---> 25 from .task import *

/opt/conda/lib/python3.7/site-packages/autogluon/task/__init__.py in <module>
      3 
      4 from .base import BaseTask
----> 5 from .image_classification import ImageClassification
      6 from .object_detection import ObjectDetection, Detector
      7 from .text_classification import TextClassification

/opt/conda/lib/python3.7/site-packages/autogluon/task/image_classification/__init__.py in <module>
----> 1 from .image_classification import *
      2 from .nets import get_built_in_network
      3 from .dataset import *
      4 from .classifier import Classifier

/opt/conda/lib/python3.7/site-packages/autogluon/task/image_classification/image_classification.py in <module>
      4 import mxnet as mx
      5 
----> 6 from .classifier import Classifier
      7 from .dataset import get_dataset
      8 from .nets import *

/opt/conda/lib/python3.7/site-packages/autogluon/task/image_classification/classifier.py in <module>
     11 from mxnet.gluon.data.vision import transforms
     12 
---> 13 from .metrics import get_metric_instance
     14 from .nets import get_network
     15 from .utils import *

/opt/conda/lib/python3.7/site-packages/autogluon/task/image_classification/metrics.py in <module>
      1 import mxnet
----> 2 import gluoncv
      3 
      4 #from ...metric import autogluon_metrics, Metric
      5 

/opt/conda/lib/python3.7/site-packages/gluoncv/__init__.py in <module>
      6 __version__ = '0.7.0'
      7 
----> 8 from . import data
      9 from . import model_zoo
     10 from . import nn

/opt/conda/lib/python3.7/site-packages/gluoncv/data/__init__.py in <module>
     10 from .mscoco.detection import COCODetectionDALI
     11 from .mscoco.instance import COCOInstance
---> 12 from .mscoco.segmentation import COCOSegmentation
     13 from .mscoco.keypoints import COCOKeyPoints
     14 from .cityscapes import CitySegmentation

/opt/conda/lib/python3.7/site-packages/gluoncv/data/mscoco/segmentation.py in <module>
      7 
      8 from .utils import try_import_pycocotools
----> 9 from ..segbase import SegmentationDataset
     10 
     11 class COCOSegmentation(SegmentationDataset):

/opt/conda/lib/python3.7/site-packages/gluoncv/data/segbase.py in <module>
      2 import random
      3 import numpy as np
----> 4 from PIL import Image, ImageOps, ImageFilter
      5 import mxnet as mx
      6 from mxnet import cpu

/opt/conda/lib/python3.7/site-packages/PIL/ImageOps.py in <module>
     22 
     23 from . import Image
---> 24 from ._util import isStringType
     25 
     26 #

ImportError: cannot import name 'isStringType' from 'PIL._util' (/opt/conda/lib/python3.7/site-packages/PIL/_util.py)

**Comment by Innixma** [comment]
Thanks for creating an issue!

Could you please create a fresh venv and install mxnet and autogluon in it, and then try to run the example code in the README?

```
# First install package from terminal:  pip install mxnet autogluon

from autogluon import TabularPrediction as task
train_data = task.Dataset(file_path='https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
test_data = task.Dataset(file_path='https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')
predictor = task.fit(train_data=train_data, label='class')
performance = predictor.evaluate(test_data)
```

Please ensure `autogluon==0.0.13` and `mxnet==1.6.0`, and provide OS information and `pip freeze` output if the issue persists.

**Comment by jwmueller** [comment]
@Renesis88 It seems your command only updated MXNet, so you may also need to execute:
`pip install --upgrade autogluon`

**Comment by Renesis88** [comment]
> @Renesis88 It seems your command only updated MXNet, so you may also need to execute:
> `pip install --upgrade autogluon`

Hi jwmueller,

Thanks got this to work in Google Colab after this tweak. However, it does not work in the Kaggle Notebooks. After some research, I discovered it is due to the different versions of SK Learn.
