### ISSUE TITLE
TabularPrediction.fit

### ISSUE THREAD

**Issue by Jie-Yuan** [awslabs/autogluon#641]
File "/home/yuanjie/anaconda3/lib/python3.7/site-packages/autogluon/utils/tabular/ml/models/catboost/catboost_model.py", line 235, in _fit
    init_model=init_model,
TypeError: fit() got an unexpected keyword argument 'init_model'
fit() got an unexpected keyword argument 'init_model'

**Comment by Innixma** [comment]
Can you provide the version of catboost you have installed? Also, please try installing catboost 0.23.2 as that is the intended version of catboost in AG. If you are using an old version of catboost, it will be good to know the version so we can tighten the requirements for AG.
