### ISSUE TITLE
 RuntimeError: The best config {'search_space▁optimization.lr': 5.5e-05} is not found in config history = OrderedDict().

### ISSUE THREAD

**Issue by SamanthaSHan** [awslabs/autogluon#647]
Using SageMaker, tried conda_python3 (and downloaded mxnet as suggested in https://autogluon.mxnet.io/install.html#installation-faq) and conda_mxnet_36, error is reproduced in both kernels.

Just following the text prediction quick start example, but running into following:
```
!pip install --upgrade pip
!pip install --upgrade 'scikit-learn<0.23,>=0.22.0'
!pip install --upgrade mxnet autogluon
```

```
from autogluon import TextPrediction as task
from autogluon.utils.tabular.utils.loaders.load_pd import load
import pandas as pd
import numpy as np
train_data = load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/train.parquet')
dev_data = load('https://autogluon-text.s3-accelerate.amazonaws.com/glue/sst/dev.parquet')
rand_idx = np.random.permutation(np.arange(len(train_data)))[:2000]
train_data = train_data.iloc[rand_idx]
train_data.head(10)

predictor = task.fit(train_data, label='label',
                     time_limits=60,
                     seed=123,
                     output_directory='./ag_sst')
```
(No gpu configuration as my instance does not have gpu)
Running into: `RuntimeError: The best config {'search_space▁optimization.lr': 5.5e-05} is not found in config history = OrderedDict(). This should never happen!` error

Edit: tried on both 0.0.13 and 0.0.14, same error. 
I did check the setup.py and verified that all packages were installed. Not sure if there's a version mismatch?

**Comment by Innixma** [comment]
@sxjscience Could you take a look?

**Comment by sxjscience** [comment]
@SamanthaSHan One possibility is that the speed is too slow because you are not using GPU. Thus, the training loop cannot find a model within 60 seconds. There are two options:

1) Change `time_limits=None`, which will wait until all trials are finished.
2) To have the best user experience of TextPrediction, I recommend to use the SageMaker instance with GPU support, e.g., the p3.2x instance in SageMaker.

**Comment by Innixma** [comment]
> @SamanthaSHan One possibility is that the speed is too slow because you are not using GPU. Thus, the training loop cannot find a model within 60 seconds. There are two options:
> 
> 1. Change `time_limits=None`, which will wait until all trials are finished.
> 2. To have the best user experience of TextPrediction, I recommend to use the SageMaker instance with GPU support, e.g., the p3.2x instance in SageMaker.

Can we make clearer error messages if no models were trained in time?

**Comment by SamanthaSHan** [comment]
@sxjscience 
Thanks for your reply. In the meantime, I did try it in p2.xlarge and p3.2x. Though both had 1 GPU, it didn't work in p2.xlarge vs p3.2x.
Following @Innixma 's comment, I do think that it would be necessary to make the error message clearer.

**Comment by sxjscience** [comment]
@SamanthaSHan Would you try again by launching a SageMaker notebook with “conda_py36” kernel and inside the Jupyter notebook, install the following MXNet?

python3 -m pip install -U --pre "mxnet_cu101>=1.7.0b20200713, <2.0.0" -f https://sxjscience.github.io/KDD2020/

I previously tested the command on SageMaker and it should runs fine.

**Comment by sxjscience** [comment]
I noticed that in your previous installation command, you are doing “ !pip install --upgrade mxnet autogluon” Basically, you may try to remove “pip install --upgrade mxnet” and install MXNet with the previous command. Also, you should make sure that you are using the conda_py36 kernel instead of the conda_mxnet_py36 kernel.

**Comment by SamanthaSHan** [comment]
@sxjscience Apologies if my previous comment was not clear. It did work on p3.2x using the initial installation command.

I am now training my own custom data, but running into the same error. Can TextPrediction take symbols? (i.e @!# etc)? That is the only difference between the example data.

**Comment by sxjscience** [comment]
@SamanthaSHan It can take symbols. Basically, you will have to use a larger `time_limits` if you are working on your custom data. You may try to set time_limits to `None` so that it will be trained into convergence.

```python
predictor = task.fit(train_data, label='label',
                     time_limits=None,
                     seed=123,
                     output_directory='./ag_sst')

```

**Comment by SamanthaSHan** [comment]
@sxjscience 
Got it to work without symbols. I did previously try with and without symbols by applying`re.sub(r'[^\w]',' ', str(text))`
```
predictor = task.fit(train_data, label='label',
                     time_limits=None,
                     ngpus_per_trial=1,
                     seed=123,
                     output_directory='./<outpit>')
```

Pertaining to the initial issue that I've created, the error thrown was `RuntimeError: The best config {'search_space▁optimization.lr': 5.5e-05} is not found in config history = OrderedDict(). This should never happen!` when there were symbols in the text, as well as timeout error mentioned above -- I do want to point out that the error message should be more specific :)

**Comment by sxjscience** [comment]
@SamanthaSHan Yeah, thanks for your suggestion! We will improve our error message and the way to deal with the time limits. Stay tuned :) For now, just open issues in case you met any problems and we are always happy to help!

**Comment by SamanthaSHan** [comment]
@sxjscience Thank you.
It may also be good to find any limitations with the use of symbols. I haven't delved deeper into what symbols are in my custom dataset (I assume ASCII characters are ok while utf-8 ones may not be?). I'd like to contribute should time permit!

**Comment by sxjscience** [comment]
@SamanthaSHan The TextPrediction task should work even if your data contain symbols or any UTF-8 characters. Are you seeing errors when you are have symbols in the data?

**Comment by SamanthaSHan** [comment]
@sxjscience Yes, correct. I'm seeing the same error as above, relating to the RuntimeError

**Comment by sxjscience** [comment]
@SamanthaSHan Thanks for reporting this. This is definitely a bug and we should solve it. Would you know if it's possible for us to connect so that I can may debug the issue? I think it's related to certain non-unicode characters, e.g., emojis like '😁' in the dataset.

**Comment by Innixma** [comment]
> @sxjscience Thank you.
> It may also be good to find any limitations with the use of symbols. I haven't delved deeper into what symbols are in my custom dataset (I assume ASCII characters are ok while utf-8 ones may not be?). I'd like to contribute should time permit!

Great to hear that you are interested in contributing! If you can send me an email at neerick@amazon.com, I can invite you to our collaborator slack channel.

**Comment by ganeshmg** [comment]
I am facing the same issue , even though i did try after removing the symbols. I am try to execute this in colab. Code given below for reference.

!pip install mxnet
!pip install autogluon
import autogluon as ag
import pandas as pd
from autogluon import TextPrediction as task
import regex as re

train=pd.read_csv("Train.csv") #Have attached the file as Train.txt since csv was not supported.
trn = train.copy()

def split_it(x):
    return re.sub(r'[^\w][^\x00-\x7F][^A-Za-z0-9]',' ',x)
	
trn['Product_Description']=trn['Product_Description'].apply(split_it)
trn.head()

predictor = task.fit(train_data=trn,eval_metric='log_loss',time_limits=None, seed=123,ngpus_per_trial=1,label='Sentiment',output_directory='ps-example-out/')
[Train.txt](https://github.com/awslabs/autogluon/files/5177715/Train.txt)

**Comment by sxjscience** [comment]
Thanks for reporting. Let me take a look tomorrow.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sxjscience** [comment]
@ganeshmg Sorry that I do not have access to the laptop and will investigate tomorrow. Meanwhile, would you try to specify the “feature_column” in ‘.fit()’ and try to include only the “Product_Description”, and “ Product_Type”? Basically, the “Text_ID” is an ID Column and the text prediction task cannot deal with the ID column currently.

**Comment by ganeshmg** [comment]
@sxjscience  I tried with only the Product_Description and Product_Type as features for the .fit(), but i still i receive the same error. I even tried converting the Product_Type to categorical (string) even though it has numerical values, just in case if it wasn't expecting any numerical columns, but still the same error persists.

**Comment by sxjscience** [comment]
For me, It seems that you are not installing MXNet with GPU support. Would you try again with pip install mxnet_cu101 or pip install mxnet_cu102?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ganeshmg** [comment]
I tried pip install with both mxnet_cu101 and mxnet_cu102, but still the same error in both the cases. Are there any predefined steps or order that needs to be taken care for installing autogluon,mxnet,mxnet_cu101,mxnet_cu102?

After pip install the only things that i import are the ones mentioned below.

import autogluon as ag
from autogluon import TextPrediction as task

Is there anything that i am missing?

**Comment by sxjscience** [comment]
@ganeshmg I just tried locally in a g4dn.4xlarge instance and there is no such issue.

```python
import autogluon as ag
from autogluon import TextPrediction as task
import pandas as pd
df = pd.read_csv('Train.txt')
predictor = task.fit(df, feature_columns='Product_Description', label='Sentiment', verbosity=3)
predictor.evaluate(df, metrics='acc')
```

It gives
```
OrderedDict([('acc', 0.7124450031426776)])
```

Are you seeing this issue when using the Google Colab? Also, would you try to train with `verbosity=3` and paste the error message here so I can help debug?

**Comment by ganeshmg** [comment]
Yes, I am using Google Colab. Attached are the log files of the fit() executed with "verbosity=3" with one and two features. If i execute only with 'Product_Description' it succeeds and fails if i add 'Product_Type'. Is there a way where i can include 'Product_Type' as well in training?
[Error_Log_2_Features.txt](https://github.com/awslabs/autogluon/files/5177975/Error_Log_2_Features.txt)
[LogFile_1_Feature.txt](https://github.com/awslabs/autogluon/files/5177976/LogFile_1_Feature.txt)

**Comment by sxjscience** [comment]
@ganeshmg @SamanthaSHan Thanks so much for trying out AutoGluon! The error message is improved in https://github.com/awslabs/autogluon/pull/651. Also, I fixed the bug found by @ganeshmg. In order to try out this fix, you may use:

```bash
pip uninstall autogluon
pip install git+https://github.com/sxjscience/autogluon.git@fix_bug
```

**Comment by ganeshmg** [comment]
@sxjscience I tried the fit() with both 'Product_Description' and 'Product_Type' as feature_columns and find attached the log file.  
The fit() function succeeded, however under the Train/Tuning dataset section in the log file, i do not see any mention on 'Product_Type'. Not sure whether this means that 'Product_Type' was not considered for training?
[Error_Log.txt](https://github.com/awslabs/autogluon/files/5181723/Error_Log.txt)

**Comment by sxjscience** [comment]
I've verified that `Product_Type` is used, if it is not used, the validation loss can only reach 70%. It can get 88% if `Product_Type` is used together with the text feature.

However, the previous fix introduced another problem that the specified `feature_columns` will be ignored so I created another fix in https://github.com/awslabs/autogluon/pull/653.

To try it out, use the following command:

```bash
pip uninstall autogluon
pip install git+https://github.com/sxjscience/autogluon.git@fix_text_bug2
```

```python
from autogluon import TextPrediction as task
import pandas as pd
df = pd.read_csv('Train.txt')
predictor = task.fit(df, feature_columns=['Product_Description', 'Product_Type'], label='Sentiment', verbosity=3)
predictor.evaluate(df, metrics='acc')
```

**Comment by ganeshmg** [comment]
@sxjscience The fit() function succeeded and under the Train/Tuning dataset section in the log file, i could now see the 'Product_Type' being mentioned. Find attached the log for reference.
[Error_Log_1.txt](https://github.com/awslabs/autogluon/files/5182538/Error_Log_1.txt)

**Comment by sxjscience** [comment]
@ganeshmg Really appreciate your help! Would you provide the details about where did you find the "Train.txt" and which task it is tackling?

**Comment by ganeshmg** [comment]
@sxjscience Thanks for the example script. Will give it a try.
The dataset shared was of a hackathon conducted by Machinehack. Hope it helps.

**Comment by sxjscience** [comment]
@ganeshmg I will mark it as resolved now. Feel free to reopen!
