### ISSUE TITLE
resuming training

### ISSUE THREAD

**Issue by redhood95** [awslabs/autogluon#663]
How do i resume training for text classification?

**Comment by Innixma** [comment]
Can you clarify if you mean TextPrediction or TextClassification? TextClassification is a deprecated task and TextPrediction should be used instead (as of 0.0.13).

**Comment by redhood95** [comment]
I mean TextPrediction.

**Comment by Innixma** [comment]
@sxjscience Could you answer?

**Comment by sxjscience** [comment]
@redhood95 There are two scenarios for resuming a trained model: 1) After you have accidentally killed the job, we may resume the training. 2) We load a trained model and continue the training process with a new sets of hparams, or on a new dataset. Which one is your use case? For now, we cannot resume training but I can add the functionality.

**Comment by redhood95** [comment]
i need to resume training on previous weights for the same dataset, please let me know if its possible. and the two scenarios @sxjscience mentioned how can i resume training when i killed it accidentally.

**Comment by redhood95** [comment]
hey, if it's okay can I work on adding this feature, for all tasks that are present currently?

**Comment by sxjscience** [comment]
@redhood95 We are more than welcome for any contributions to AutoGluon. Adding the second functionality (load a trained model and call `.fit()` again) in TextPrediction is not very difficult. We will need to extend the loaded predictor https://github.com/awslabs/autogluon/blob/54d174913a20ba93a37847af722241022a690664/autogluon/task/text_prediction/models/basic_v1.py#L537-L538 to support `.fit()`. Actually, you may try to join our slack channel to discuss more.  Also ping @Innixma  .

**Comment by redhood95** [comment]
@sxjscience  where can I join the slack channel?

**Comment by sxjscience** [comment]
Would you try out this link? [AutoGluon Slack Invitation](https://join.slack.com/t/autogluon/shared_invite/zt-gx5s8jhw-lg5oGy0Yz3hvfekztiib5g)

**Comment by sxjscience** [comment]
@redhood95 I removed the previous slack invitation. For those who are willing to obtain the slack invitation, just send emails to me or other developers in AutoGluon.

**Comment by sxjscience** [comment]
@zhiqiangdon Would you answer this?

@redhood95 We have upgraded the TextPredictor to support huggingface backbones. The new implementation is based on pytorch-lightning.

Compared with the TextPredictor in AutoGluon 0.3, the TextPredictor in AutoGluon 0.4 has 72.22% win-rate in the multimodal text-tabular benchmark. If we use the “high_quality” preset, the win-rate increased to 77.8% thanks to the microsoft/deberta-v3-base backbone.
In addition, the new version has ~2.88x speedup in training and ~1.40x speedup in inference. With g4dn.12x instance, the model can further achieve 2.26x speedup with 4 GPUs.

**Comment by zhiqiangdon** [comment]
@redhood95 Please check our new implementation here: 

https://github.com/awslabs/autogluon/blob/master/text/src/autogluon/text/automm/predictor.py#L917-L950

Now we can support the two scenarios: 1. resuming from the last saved checkpoint; 2. continuing training on new data by loading the best checkpoint.

**Comment by Innixma** [comment]
Closing as resolved in v0.4.0 release. v0.4.0 is planned for release ~end of Feb.
