### ISSUE TITLE
Can't train object detect with custom dataset 

### ISSUE THREAD

**Issue by solua100** [awslabs/autogluon#698]
Hi,

I try use custm dataset for object detection but it usually crash, sometime it can run. I do almost same with tutorial.
`import autogluon as ag
from autogluon import ObjectDetection as task
import os

root = './train_data'
data_root = os.path.join(root,'number_dataset')
#dataset_train = task.Dataset(data_root, classes=('zero','one','two','three','four','five','six','seven','eight','nine',))
time_limits = 5*60*60  # 5 hours
epochs = 30
detector = task.fit(dataset_train,
                    epochs=epochs,
                    lr=ag.Categorical(5e-4, 1e-4),
                    ngpus_per_trial=1,
                    time_limits=time_limits)

savefile = 'number_model.pkl'
detector.save(savefile)`

crash log:
>>> create dataset(VOC format) 
scheduler_options: Key 'training_history_callback_delta_secs': Imputing default value 60
scheduler_options: Key 'delay_get_config': Imputing default value True

scheduler: FIFOScheduler(
DistributedResourceManager{
(Remote: Remote REMOTE_ID: 0, 
	<Remote: 'inproc://192.168.1.204/23407/1' processes=1 threads=24, memory=50.60 GB>, Resource: NodeResourceManager(24 CPUs, 1 GPUs))
})

Starting Experiments
Num of Finished Tasks is 0
Time out (secs) is 18000
{'meta_arch': 'yolo3', 'dataset': <autogluon.task.object_detection.dataset.voc.CustomVOCDetection object at 0x7f9ca3ebf588>, 'net': 'mobilenet1.0', 'lr': 0.0005, 'loss': SoftmaxCrossEntropyLoss(batch_axis=0, w=None), 'num_gpus': 1, 'batch_size': 16, 'split_ratio': 0.8, 'epochs': 30, 'num_workers': 12, 'hybridize': True, 'verbose': False, 'final_fit': False, 'seed': 223, 'data_shape': 416, 'start_epoch': 0, 'transfer': 'coco', 'lr_mode': 'step', 'lr_decay': 0.1, 'lr_decay_period': 0, 'lr_decay_epoch': '160,180', 'warmup_lr': 0.0, 'warmup_epochs': 2, 'warmup_iters': 1000, 'warmup_factor': 0.3333333333333333, 'momentum': 0.9, 'wd': 0.0005, 'log_interval': 100, 'save_prefix': 'yolo3_mobilenet1.0_custom', 'save_interval': 10, 'val_interval': 1, 'num_samples': -1, 'no_random_shape': False, 'no_wd': False, 'mixup': False, 'no_mixup_epochs': 20, 'label_smooth': False, 'resume': '', 'syncbn': False, 'reuse_pred_weights': True, 'task_id': 0}
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/wee/.local/lib/python3.6/site-packages/gluoncv/data/dataloader.py", line 154, in _worker_fn
    batch = batchify_fn([t_dataset[i] for i in samples])
  File "/home/wee/.local/lib/python3.6/site-packages/gluoncv/data/dataloader.py", line 154, in <listcomp>
    batch = batchify_fn([t_dataset[i] for i in samples])
  File "/home/wee/build/mxnet/python/mxnet/gluon/data/dataset.py", line 219, in __getitem__
    return self._fn(*item)
  File "/home/wee/.local/lib/python3.6/site-packages/gluoncv/data/transforms/presets/yolo.py", line 174, in __call__
    bbox = tbbox.resize(bbox, (w, h), (self._width, self._height))
  File "/home/wee/.local/lib/python3.6/site-packages/gluoncv/data/transforms/bbox.py", line 132, in resize
    bbox[:, 1] = y_scale * bbox[:, 1]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
"""

My dataset in VOC format.
Thanks

**Comment by Innixma** [comment]
@zhreshold is this resolved now?

**Comment by zhreshold** [comment]
@solua100 the dataset is fixed, however, task is deprecated in current version, you may refer to https://auto.gluon.ai/stable/tutorials/object_detection/beginner.html for the new tutorials to train a detector
