### ISSUE TITLE
Autogluon Object detection task not getting trained on cpu.

### ISSUE THREAD

**Issue by utopianpallu** [awslabs/autogluon#699]
Hey @Innixma , I used cpu for training but it is giving error, 
**ValueError: Cannot reset context for Parameter 'mobilenet0_conv0_weight' because it has not been initialized.**

But whenever i am using gpu it gives me correct results.

**Comment by Innixma** [comment]
@zhreshold could you take a look?

**Comment by Innixma** [comment]
Actually, I believe a PR already exists to fix this, and should be merged sometime soon: #697
