### ISSUE TITLE
Object detection not giving results for mobilenet0.25 as a base network.

### ISSUE THREAD

**Issue by utopianpallu** [awslabs/autogluon#700]
@zheng-da @chongruo 
Hii , i tried using mobilenet 0.25 as a base network for yolo3 using:

detector = task.fit(dataset_train,net=ag.Categorical('mobilenet1.0','mobilenet0.25'),
                    lr=ag.Categorical(5e-4, 1e-4),
                    loss=mxnet.gluon.loss.SoftmaxCrossEntropyLoss(),
                    split_ratio=0.8,
                    batch_size=16,
                    num_trials=2,
                    epochs=epochs,
                    ngpus_per_trial=1,
                    time_limits=time_limits)

It is giving error:
ValueError: Pretrained model for yolo3_mobilenet0.25_coco is not available.
But this model is available at [**https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/model_zoo.py**]

and also am getting same errors while using faster_rcnn as a meta_arch in place of yolo3.

**Comment by Innixma** [comment]
@zhreshold Could you take a look?

**Comment by Innixma** [comment]
Closing due to staleness. It may be the case that the model is now available. Please re-open if the issue persists.
