### ISSUE TITLE
TypeError when using 'XT' hyperparameters

### ISSUE THREAD

**Issue by KleinXin** [awslabs/autogluon#703]
I am trying to train data which has 9-dim feature vectors. The format of data is shown below

![image](https://user-images.githubusercontent.com/13084622/95838088-f2bffa80-0d73-11eb-9ec2-e8ce2668b913.png)

The data works fine when I use 'CAT'/'RF'/'GBM'/'KNN' as hyperparameter. However, when I set it as 'XT', it reports a typeerror that is shown below

`Loaded data from: ../Dataset/data_20200927_800w/train_800w.csv | Columns = 10 / 10 | Rows = 6843114 -> 6843114
Beginning AutoGluon training ...
AutoGluon will save models to ./res/20201013_Default_20200927_800w_XT/
AutoGluon Version:  0.0.13
Train Data Rows:    6843114
Train Data Columns: 10
Preprocessing data ...
Here are the 2 unique label values in your data:  [0, 1]
AutoGluon infers your prediction problem is: binary  (because only two unique label-values observed).
If this is wrong, please specify `problem_type` argument in fit() instead (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])

Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Train Data Class Count: 2
Feature Generator processed 6843114 data points with 9 features
Original Features (raw dtypes):
	float64 features: 9
Original Features (inferred dtypes):
	float features: 9
Generated Features (special dtypes):
Processed Features (raw dtypes):
	float features: 9
Processed Features:
	float features: 9
	Data preprocessing and feature engineering runtime = 8.93s ...
AutoGluon will gauge predictive performance using evaluation metric: roc_auc
This metric expects predicted probabilities rather than predicted class labels, so you'll need to use predict_proba() instead of predict()
To change this, specify the eval_metric argument of fit()
AutoGluon will early stop models using evaluation metric: log_loss
Fitting model: ExtraTreesClassifierGini_STACKER_l0 ...
	Warning: Model is expected to require 149.58% of available memory...
	Not enough memory to train ExtraTreesClassifierGini_STACKER_l0... Skipping this model.
Fitting model: ExtraTreesClassifierEntr_STACKER_l0 ...
	Warning: Model is expected to require 142.44% of available memory...
	Not enough memory to train ExtraTreesClassifierEntr_STACKER_l0... Skipping this model.
No base models to train on, skipping weighted ensemble...
No base models to train on, skipping stack level...
No base models to train on, skipping weighted ensemble...
Summary of label_column: 
 count    6.843114e+06
mean     5.214231e-01
std      4.995409e-01
min      0.000000e+00
25%      0.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.000000e+00
Name: y, dtype: float64
Traceback (most recent call last):
  File "TabularPred.py", line 58, in <module>
    num_bagging_folds=10)
  File "/opt/bitnami/python/lib/python3.6/site-packages/autogluon/task/tabular_prediction/presets_configs.py", line 10, in _call
    return f(*gargs, **gkwargs)
  File "/opt/bitnami/python/lib/python3.6/site-packages/autogluon/task/tabular_prediction/tabular_prediction.py", line 600, in fit
    hyperparameters=hyperparameters, ag_args_fit=ag_args_fit, excluded_model_types=excluded_model_types, time_limit=time_limits_orig, save_data=cache_data, save_bagged_folds=save_bagged_folds, verbosity=verbosity)
  File "/opt/bitnami/python/lib/python3.6/site-packages/autogluon/utils/tabular/ml/learner/abstract_learner.py", line 91, in fit
    return self._fit(X=X, X_val=X_val, **kwargs)
  File "/opt/bitnami/python/lib/python3.6/site-packages/autogluon/utils/tabular/ml/learner/default_learner.py", line 103, in _fit
    hyperparameters=hyperparameters, ag_args_fit=ag_args_fit, excluded_model_types=excluded_model_types)
  File "/opt/bitnami/python/lib/python3.6/site-packages/autogluon/utils/tabular/ml/trainer/auto_trainer.py", line 33, in train
    self.train_multi_and_ensemble(X_train, y_train, X_val, y_val, models, hyperparameter_tune=hyperparameter_tune, feature_prune=feature_prune)
  File "/opt/bitnami/python/lib/python3.6/site-packages/autogluon/utils/tabular/ml/trainer/abstract_trainer.py", line 505, in train_multi_and_ensemble
    self.train_multi_levels(X_train, y_train, X_val, y_val, models=models, hyperparameter_tune=hyperparameter_tune, feature_prune=feature_prune, level_start=0, level_end=self.stack_ensemble_levels)
  File "/opt/bitnami/python/lib/python3.6/site-packages/autogluon/utils/tabular/ml/trainer/abstract_trainer.py", line 522, in train_multi_levels
    self.stack_new_level(X=X_train, y=y_train, X_val=X_val, y_val=y_val, level=level, time_limit_core=time_limit_core, time_limit_aux=time_limit_aux)
  File "/opt/bitnami/python/lib/python3.6/site-packages/autogluon/utils/tabular/ml/trainer/abstract_trainer.py", line 532, in stack_new_level
    return core_models + aux_models
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'`

**My code is** 

`custom_hyperparameters = {'XT': [{'criterion': 'gini', 'AG_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, \
                                     {'criterion': 'entropy', 'AG_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, \
                                     {'criterion': 'mse', 'AG_args': {'name_suffix': 'MSE', 'problem_types': ['regression']}}]}

    predictor = task.fit(train_data=train_data, \
                         label=label_column, \
                         output_directory=args.save, \
                         hyperparameters=custom_hyperparameters, \
                         presets='best_quality', \
                         eval_metric='roc_auc')`

**Any help is appreciated！**

**Comment by jwmueller** [comment]
The reason you are encountering this error is highlighted in these lines of the output log:
```
Warning: Model is expected to require 149.58% of available memory...
Not enough memory to train ExtraTreesClassifierGini_STACKER_l0... Skipping this model.
```

AutoGluon has decided there is not enough memory on your machine to train the ExtraTrees model, and since it's the only model you've said to train, AutoGluon cannot produce a `predictor` object. Is there a particular reason you need to use the ExtraTrees model? These are typically not the most accurate models anyway for most datasets.

If you really need an ExtraTrees model, you can try:
1) use a machine with more available memory, and make sure there aren't other processes running when you fit autogluon
2) following these other tips:
https://autogluon.mxnet.io/tutorials/tabular_prediction/tabular-indepth.html#if-you-encounter-memory-issues

**Comment by KleinXin** [comment]
> The reason you are encountering this error is highlighted in these lines of the output log:
> 
> ```
> Warning: Model is expected to require 149.58% of available memory...
> Not enough memory to train ExtraTreesClassifierGini_STACKER_l0... Skipping this model.
> ```
> 
> AutoGluon has decided there is not enough memory on your machine to train the ExtraTrees model, and since it's the only model you've said to train, AutoGluon cannot produce a `predictor` object. Is there a particular reason you need to use the ExtraTrees model? These are typically not the most accurate models anyway for most datasets.
> 
> If you really need an ExtraTrees model, you can try:
> 
> 1. use a machine with more available memory, and make sure there aren't other processes running when you fit autogluon
> 2. following these other tips:
>    https://autogluon.mxnet.io/tutorials/tabular_prediction/tabular-indepth.html#if-you-encounter-memory-issues

thx！In fact, I am just testing different options of AutoGluon on the dataset to compare the accuracy.
