### ISSUE TITLE
Issue with deserializing model

### ISSUE THREAD

**Issue by jojo19893** [awslabs/autogluon#704]
the following workflow persisting a model with: 
`model.save('/tmp/model')` 
the model contains text and numerical attributes the resulting metadata.json looks as follows:
```
{
   "label":{
      "type":"categorical",
      "attrs":{
         "categories":[
            0,
            1
         ],
         "allow_missing":false
      }
   },
   "title":{
      "type":"text",
      "attrs":{
         
      }
   },
   "token_ratio":{
      "type":"numerical",
      "attrs":{
     "shape":[
            
         ]
         
      }
   },
   "length_ratio":{
      "type":"numerical",
      "attrs":{
         "shape":[
            
         ]
      }
   },
   "duplicate_tokens":{
      "type":"numerical",
      "attrs":{
         "shape":[
            
         ]
      }
   }
}
```
when loading the folder with `model=task.load(folder)` it works.
however if you call `model.predict(df)` on a DF that works on the trained model in memory the following error occurs:
`AssertionError: Shape mismatch!. Expected shape=[], shape in the dataset is ()`
the error happens because the `class NumericalColumnProperty(ColumnProperty):` has as a shape a `[]` instead of a `()`
this is due to the fact that the shape is wrong deserialized.
Idea would be to override it in the init: 
```
   def __init__(self, shape: Optional[Tuple] = None):
        """

        Parameters
        ----------
        shape
            The shape of the numerical values
        """
        super().__init__()
        if shape==[]
           shape=()
       self._shape = shape
```

**Comment by sxjscience** [comment]
Thanks for reporting this. A quick fix will be to change the following
https://github.com/awslabs/autogluon/blob/3a688299ee8ac6d05db05faf6ce918ab3c8453ff/text/src/autogluon/text/text_prediction/column_property.py#L240-L242

to 

```
assert tuple(self._shape) == tuple(inferred_shape)
```

**Comment by sxjscience** [comment]
Solved via https://github.com/awslabs/autogluon/pull/708
