### ISSUE TITLE
How to get the return values in train_fn?

### ISSUE THREAD

**Issue by moyiliyi** [awslabs/autogluon#707]
When the train_fn has return values, how to access them?
E.g. in a sample case here, is there a way to get the 'msg' value in each search trial?

```python
def train_mnist(args, reporter):
    def train(epoch):
        #train code here
    def test(epoch):
        #test code here
        reporter(epoch=epoch+1, accuracy=acc)
    for epoch in tqdm(range(0, epochs)):
        train(epoch)
        test(epoch)
    msg = 'Training Completed.'
    return msg

@ag.args(
    lr = ag.space.Real(0.01, 0.2, log=True),
    wd = ag.space.Real(1e-4, 5e-4, log=True)
)
def ag_train_mnist(args, reporter):
    return train_mnist(args, reporter)

myscheduler = ag.scheduler.FIFOScheduler(
    ag_train_mnist,
    resource={'num_cpus': 4, 'num_gpus': 1},
    num_trials=2,
    time_attr='epoch',
    reward_attr='accuracy')

myscheduler.run()
myscheduler.join_jobs()
```

**Comment by mseeger** [comment]
You need to use the reporter.

Your example will not work, you need to have something like

reporter(epoch=..., accuracy=...)

in ag_train_mnist. And you can return other things via reporter, which your scheduler can then access. Careful:
- reporter has to return accuracy (name as in reward_attr) always
- reporter has to return epoch (name as in time_attr) for multi-fidelity schedulers (e.g., Hyperband)
- epoch must be integers starting from 1
- accuracy must be "larger is better" kind

I'd advise you to study the examples, in particular:
https://autogluon.mxnet.io/tutorials/torch/hpo.html

**Comment by moyiliyi** [comment]
> You need to use the reporter.
> 
> Your example will not work, you need to have something like
> 
> reporter(epoch=..., accuracy=...)
> 
> in ag_train_mnist. And you can return other things via reporter, which your scheduler can then access. Careful:
> 
> * reporter has to return accuracy (name as in reward_attr) always
> * reporter has to return epoch (name as in time_attr) for multi-fidelity schedulers (e.g., Hyperband)
> * epoch must be integers starting from 1
> * accuracy must be "larger is better" kind
> 
> I'd advise you to study the examples, in particular:
> https://autogluon.mxnet.io/tutorials/torch/hpo.html

Thanks. Actually my example has a reporter in the test function (line 6). My question is that I need to return some extra information outside the training/test iteration, is that possible?

**Comment by mseeger** [comment]
Ah sorry I missed that.
As I said, you can return other information via the reporter.

But the signal that evaluation has finished, is created automatically, you do not have to do that.

We are routinely returning other information, for example the time per epoch. If you look into the scheduler code, some will also store what you return via reporter into training_history.

The only way to return information is via the reporter.

**Comment by moyiliyi** [comment]
> Ah sorry I missed that.
> As I said, you can return other information via the reporter.
> 
> But the signal that evaluation has finished, is created automatically, you do not have to do that.
> 
> We are routinely returning other information, for example the time per epoch. If you look into the scheduler code, some will also store what you return via reporter into training_history.
> 
> The only way to return information is via the reporter.

Thanks!
