### ISSUE TITLE
Tiny bug related to text prediction

### ISSUE THREAD

**Issue by ZheyuYe** [awslabs/autogluon#709]
https://github.com/awslabs/autogluon/blob/28f5df3a9366b2224bebd7f4a3a81307662378eb/autogluon/task/text_prediction/modules/basic_prediction.py#L248-L249

This action only occurs if `len(field_proj_features)` is equal to 1. Adding some proper test cases that cover basic layers used for prediction would be great.

@sxjscience

**Comment by sxjscience** [comment]
Thanks for reporting this. I find that we can safely remove the `len(field_proj_features)` branch. Because when the number of inputs is 1, `stack` + `mean`, and `concatenate` just becomes identity.

**Comment by ZheyuYe** [comment]
> Thanks for reporting this. I find that we can safely remove the `len(field_proj_features)` branch. Because when the number of inputs is 1, `stack` + `mean`, and `concatenate` just becomes identity.

This is also a good solution

**Comment by Innixma** [comment]
@sxjscience is this fixed at this point?

**Comment by sxjscience** [comment]
Yeah, it has been fixed.
