### ISSUE TITLE
[Feature Request] Add official Docker support

### ISSUE THREAD

**Issue by sxjscience** [awslabs/autogluon#710]
Docker can provide a virtual environment for the users to try out AutoGluon. The new version of GluonNLP has recently added the docker support (See https://github.com/dmlc/gluon-nlp/tree/master/tools/docker for more details).

For AutoGluon, once added, the usage can be like the follows:

```bash
# For CPU Version
docker pull gluonai/autogluon:cpu-latest
docker run --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 --shm-size=2g gluonai/autogluon:cpu-latest
```

It will then open a [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) environment with pre-installed plugins like Tensorboard.

Here, I've included the current gluonnlp docker as an example and have attached the screenshot:

```bash
# For CPU Version
docker pull gluonai/gluon-nlp:cpu-latest
docker run --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 --shm-size=2g gluonai/gluon-nlp:cpu-latest
```

<img width="1055" alt="Screen Shot 2020-10-15 at 10 17 11 AM" src="https://user-images.githubusercontent.com/5178350/96164279-d9cc5c00-0ecf-11eb-9a56-ec9ef922df21.png">

Having an official docker also helps AutoGluon benchmark the performance and integrate with other tools like [SageMaker custom container](https://docs.aws.amazon.com/sagemaker/latest/dg/docker-containers.html).

@awslabs/autogluon-maintainer

**Comment by zhanghang1989** [comment]
FYI https://github.com/zhanghang1989/AutoGluon-Docker

**Comment by gradientsky** [comment]
We released official [Training](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#autogluon-training-containers) and [Inference](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#autogluon-inference-containers) Deep Learning Containers. The containers will be updated once 0.4 will be released. See [examples](https://github.com/aws/amazon-sagemaker-examples/tree/master/advanced_functionality/autogluon-tabular-containers) how to use AutoGluon in SageMaker using containers.
