### ISSUE TITLE
Autogluon Import Error: cannot import name 'IPV6_ADDRZ_RE' 

### ISSUE THREAD

**Issue by ShehzadaAlam** [awslabs/autogluon#716]
Hi, 

**Issue Description:** Until yesterday I was able to import autogluon, but now if I try to import I get an error stating, cannot import name 'IPV6_ADDRZ_RE'.

**Environment/ OS:** I am using google colab and below are the details.
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Steps to Reproduce:**
**Step1:** Open a new notebook on google colab.

**Step2:** Install the autogluon. 
!pip install --upgrade "mxnet_cu101<2.0.0"
!pip install autogluon

**Step3:** Restart the environment.
![restart the envionment](https://user-images.githubusercontent.com/50400399/96555652-aaee2580-12d5-11eb-9add-1f14cf6682f5.PNG)

**Step4:** You'll get the error below.
![error while importing](https://user-images.githubusercontent.com/50400399/96555532-87c37600-12d5-11eb-8084-34b99097e52d.PNG)

**Comment by Innixma** [comment]
Thanks for the info!

Seems like botocore or urllib released a new version today which causes the issue. Downgrading the versions of those packages would be your best bet.

Could you try following this: https://github.com/boto/botocore/issues/2187#issuecomment-712819351
