### ISSUE TITLE
Logistic Regression Question

### ISSUE THREAD

**Issue by impulsecorp** [awslabs/autogluon#717]
For tabular data, how can I use logistic regression at https://github.com/awslabs/autogluon/tree/master/tabular/src/autogluon/tabular/utils/ml/models/lr  for binary prediction (Titanic dataset, for example)? 

It does not seem to be included in the 'best_quality' preset, and when I try to include it manually it does not work, like:
predictor = task.fit(train_data=train_data, label=label_column, output_directory=dir, hyperparameter_tune=False, feature_prune=True, auto_stack=True, search_strategy='random', time_limits=3600*.3, hyperparameters={
               'GBM': {'num_boost_round': 100},
               'CAT': {'iterations': 1000},
               'LR': {},
                }, num_bagging_folds=10, num_bagging_sets=3, num_trials=3, keep_only_best=True, save_space=True)

**Comment by Innixma** [comment]
Can you please provide the complete output logs of your run including the error? I just tested and it works for me.

**Comment by impulsecorp** [comment]
I am sorry, I see now, it was something else I did that was causing it not to work. It works for me now.
