### ISSUE TITLE
Adding A Custom Model Question

### ISSUE THREAD

**Issue by impulsecorp** [awslabs/autogluon#718]
I see your example at https://github.com/awslabs/autogluon/blob/master/examples/tabular/example_custom_model_tabular.py
for how to add a custom model , but how would I actually make that example work, like the custom GBM model is already working?

For example, it works right now to fit it like:
'custom': ['GBM'] 
but it doesn't work if I use
'custom': ['CustomNaiveBayes'] 

Would I need to add the code to your tabular models section at  https://github.com/awslabs/autogluon/tree/master/tabular/src/autogluon/tabular/utils/ml/models ? If so, how?

Also, related to that, you seem to have the code for the FastAI NN working, but when I use fit (binary prediction - Titanic dataset), if I replace
'NN': {},
with
'FASTAI': {},
it does not work.  How do I use FASTAI?

**Comment by Innixma** [comment]
'custom' is not something users can specify their own models in yet, and it is unfortunately a bit misleading, as `'custom': ['GBM']` is not related to `'GBM': {}`. The [code](https://github.com/awslabs/autogluon/blob/master/tabular/src/autogluon/tabular/utils/ml/trainer/model_presets/presets_custom.py) for 'custom' only accepts 'GBM'. Instead, use:

```custom_hyperparameters = {NaiveBayesModel: {}}```

**Note: The following is based on mainline file locations, not on those found in `pip install autogluon`**:

'NaiveBayesModel' as a string would have to be added to https://github.com/awslabs/autogluon/blob/master/tabular/src/autogluon/tabular/utils/ml/trainer/model_presets/presets.py#L54

Then the following would work:
```custom_hyperparameters = {'NaiveBayesModel': {}}```

'FASTAI' requires Torch and FastAI to be installed, which are not yet provided by default in AutoGluon. Try the following:
```
pip install --upgrade torch
pip install fastai<2.0
```

A good example of adding a complex model is currently in progress with XGBoost, which you can reference: #691
