### ISSUE TITLE
Consider rewording frontpage of website + readme

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#722]
Currently the website and readme opens with stating that AutoGluon is a deep learning library, which has caused confusion with users who want to use primarily classical algorithms thinking that AutoGluon is not a good fit.

**Comment by mseeger** [comment]
I'd also think that AutoGluon is broader than that. And soon the core does not even depend on any DL framework. The fact that AG is framework-agnostic, is a big plus over others I think.

**Comment by jwmueller** [comment]
@Innixma  Names still don't seem to be fully standardized between readme and docs. 

I vote we use the name: "AutoGluon: AutoML for Text, Image, and Tabular Data"
because "Tabular" sounds weird unless next to "Data" and "Toolkit" may be an unnecessary extra word

**Comment by Innixma** [comment]
> @Innixma Names still don't seem to be fully standardized between readme and docs.
> 
> I vote we use the name: "AutoGluon: AutoML for Text, Image, and Tabular Data"
> because "Tabular" sounds weird unless next to "Data" and "Toolkit" may be an unnecessary extra word

I'm fine with this (and I agree toolkit is unnecessary). Feel free to send a PR with the changes and fix and inconsistencies.
