### ISSUE TITLE
assert num_tries <= self.MAX_TRIES

### ISSUE THREAD

**Issue by montardon** [awslabs/autogluon#730]
I'm training a default model on a custom dataset.
detector = task.fit(dataset_train,
                    epochs=epochs,
                    lr=ag.Categorical(5e-4, 1e-4, 5e-5),
                    ngpus_per_trial=1,
                    time_limits=time_limits,
                    batch_size=8
                    )
After a while (three times 30 epochs) , I get an error in searcher.py, line 349   
assert num_tries <= self.MAX_RETRIES, \
AssertionError: Cannot find new config in BaseSearcher, even after 100 trials

I can not figure out why this is happening. Is it necessary to stop ?

**Comment by Innixma** [comment]
Assuming this is vision, but please clarify if it is text. @zhreshold could you take a look?

**Comment by montardon** [comment]
Yes. It is vision. I'm training an object detection model on a custom dataset.

**Comment by mseeger** [comment]
This is an easy one. Your whole search space only has 3 configs, and so once RandomSearcher has sampled all of them, there are none left.
You should use a larger search space, or less trials.

**Comment by mseeger** [comment]
I am also not sure whether ag.Categorical should not have string objects? I recommend to use ag.Real() for searching for a learning rate, and use log transform.

**Comment by mseeger** [comment]
We currently do not have the means to check the size of a finite search space, so this is hard to catch in a better way.

**Comment by montardon** [comment]
Thank you.
Using ag.Real() instead of ag.Categorical() in lr ( lr=ag.Real(5e-4, 2e-4)) leads to the folowing error :
  File "ConfigSpace/hyperparameters.pyx", line 408, in ConfigSpace.hyperparameters.UniformFloatHyperparameter.__init__
ValueError: Upper bound 0.000500 must be larger than lower bound 0.000200 for hyperparameter lr

It looks like upper bound 0.000500 is larger than lower bound 0.000200, unless you are using unusual order for sorting.

**Comment by montardon** [comment]
I guess the message is wrong. Reordering parameters did it.

**Comment by Innixma** [comment]
@zhreshold Could you re-order the message so it is correct?

**Comment by mseeger** [comment]
This message comes from Configspace, we do not control that, unless we submit a patch to them.

**Comment by Innixma** [comment]
oh, I see. If others complain about it we might consider, but for now it is likely a niche issue.
