### ISSUE TITLE
CI Failure: tests/unittests/test_bayesopt_searcher.py ..Cancelling nested steps due to timeout

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#734]
tests/unittests/test_bayesopt_searcher.py ..Cancelling nested steps due to timeout

Test times out after 3 hours in Bayesopt. Logs: 
https://ci.mxnet.io/blue/organizations/jenkins/autogluon/detail/PR-691/7/pipeline
https://ci.mxnet.io/blue/organizations/jenkins/autogluon/detail/PR-731/1/pipeline

This occurs non-deterministically, sometimes it does not hang.

@mseeger Could you take a look?

**Comment by mseeger** [comment]
Are you sure this is due to this particular test?
The CI was failing for my due to timeout as well a few times, but at a different point.

This test should be very short running. I'd suggest to deactivate it for now, and then see whether CI time-outs are not anyway happening.

**Comment by Innixma** [comment]
Looks like another version of this test already exists in 'extra' which is disabled due to causing CI failures in the past. Given the similarity between it and the new test, I expect that the test is indeed the cause.

Previous test_bayesopt_searcher file:
https://github.com/awslabs/autogluon/blob/master/extra/tests/unittests/test_bayesopt_searcher.py

**Comment by mseeger** [comment]
The test in extra should be removed altogether, I did not realize it was still there.
But the test is core is using artificial train_fn, and it should work.

If it does not, this could be due to the dead-locking problems we seem to have.

**Comment by Innixma** [comment]
Feel free to remove it in your PR, I have merged the disabling of the core version, so you can rebase your PR with it to incorporate the change.
