### ISSUE TITLE
HPO defaults for the different tasks

### ISSUE THREAD

**Issue by mseeger** [awslabs/autogluon#743]
Hello,

with 'bayesopt' now independent of MXNet, and PR #735, I recommend that more powerful HPO methods (bayesopt, bayesopt_hyperband) are being explored for the vision and text tasks. The current default there is random search, which can be improved upon by a factor by hyperband, and bayesopt_hyperband is again often better than hyperband by a factor of 2.

Of course, this needs some exploration, but given this looks good, I'd challenge the "random search" default for all these tasks.

**Comment by Innixma** [comment]
@sxjscience @zhreshold are we using bayesopt by default in nlp and vision as of v0.2?

**Comment by sxjscience** [comment]
Not for NLP, text is using local + random by default: https://github.com/awslabs/autogluon/blob/699e74d5c0ad7eab1544c64a5f5f1c53dff5f0dd/text/src/autogluon/text/text_prediction/presets.py#L46-L48
