### ISSUE TITLE
Object Detection Images directory layout

### ISSUE THREAD

**Issue by montardon** [awslabs/autogluon#757]
Hi,

I'm trying to run Object Detection on a custom images dataset.
I tried to mimics Tiny bike example.

What is the expected images directory layout ?

For Tiny bike example, the root directory is like :
Annotations\*.xml
ImageSet\Main\trainval.txt
ImageSet\Main\test.txt
JPEGImages\*.jpg

Do you support PNG files ?
I'm using PNG images. I converted them to JPG using mogrify.

**Comment by Innixma** [comment]
@zhreshold Could you take a look?

**Comment by zhreshold** [comment]
@montardon 

The structure is

```
├── Annotations
├── ImageSets
│   ├── Main
│   │   ├── test.txt
│   │   └── trainval.txt
│   └── Segmentation
│       ├── test.txt
│       └── trainval.txt
├── JPEGImages
```

as for now, only `.jpg` files are supported in such voc format. In upcoming https://github.com/awslabs/autogluon/pull/733, the major image extensions will be supported.
