### ISSUE TITLE
ModuleNotFoundError: No module named 'autogluon.tabular'

### ISSUE THREAD

**Issue by arianacai1997** [awslabs/autogluon#760]
In the
from autogluon.tabular import TabularPrediction as task
I got the error:
ModuleNotFoundError: No module named 'autogluon.tabular'

While it works once I change it into 
from autogluon import TabularPrediction as task

**Comment by dai-ichiro** [comment]
Now there are two versions, dev and stable.
[https://auto.gluon.ai/dev/versions.html](https://auto.gluon.ai/dev/versions.html)

In the dev version
`from autogluon.tabular import TabularPrediction as task`

In the stable version
`from autogluon import TabularPrediction as task`

**Comment by Innixma** [comment]
As @dai-ichiro said, dev currently has a separate API from stable as dev is working towards v0.1 release.

For stable:
```
pip install autogluon
```

For dev:

```
pip install --pre autogluon
```

Generally it is recommended to use stable unless you are contributing to AutoGluon.

The github readme is based on the dev version, so it is recommended to refer to the website for tutorials: https://auto.gluon.ai/
