### ISSUE TITLE
Training and Predicting using a single model type

### ISSUE THREAD

**Issue by seekingdeep** [awslabs/autogluon#769]
Hi there,

1. i want to train an **`LightGBMClassifier`** model type only, so i included:
`excluded_model_types=['NN', 'RF', 'XT', 'KNN', 'CAT', 'LR', 'custom']`
- The issue is that training includes **`LightGBMClassifierXT`** and **`weighted_ensemble`**, How to disable them also?

2. For prediction, is there a way to set only the individual model type that i want to use.
Because when i am trying to predict, it requires `learner.pkl` to be present, and also requires all the models trained to be present.

**Comment by seekingdeep** [comment]
@Innixma @jwmueller @zhanghang1989

**Comment by jwmueller** [comment]
Answered here: https://github.com/jwmueller/KDD20-tutorial/issues/9

**Comment by Innixma** [comment]
You can get rid of any other models by using `predictor.delete_models(models_to_keep=['your_model_name'], dry_run=False)` after training.

You can train just a LightGBM (+ weighted ensemble which can be deleted after) via `task,fit(..., hyperparameters={'GBM': {}})`
