### ISSUE TITLE
Deep Clustering of Tabular Data

### ISSUE THREAD

**Issue by seekingdeep** [awslabs/autogluon#781]
How can i train a model to learn how to cluster rows/ nodes into groups.

i have a table inwhich each row is contains a node and it's features.
i want to teach a model how to cluster and create groups of the nodes.

Note that this is not similar to classification.

**Comment by Innixma** [comment]
This is called unsupervised learning, which can be done most commonly by models such as nearest-neighbors algorithms. AutoGluon does not actively support this functionality at present, as it is focused on the supervised learning domain.

**Comment by seekingdeep** [comment]
nearest neighbor might not be suitable for high dimensional data.

**Comment by seekingdeep** [comment]
@Innixma

**Comment by Innixma** [comment]
You said that this is not classification, but what you are describing is a multiclass classification problem, with the cluster name/number as the label. Have you tried simply passing the data into AutoGluon Tabular .fit?

**Comment by seekingdeep** [comment]
i should try testing and reply back, stay tuned

**Comment by seekingdeep** [comment]
hi,
when treating this task as a multi-class classification problem, it seems that the accuracy needs improvement.
My guess is that, for example: "a node that is present in cluster 1 in a certain map, might be in cluster 5 in another map".

Thus, you might consider "deep clustering" as basically a **`Context-Aware`** classification.
@Innixma what do you suggest
