### ISSUE TITLE
ObjectDetection fails with faster_rcnn: unexpected keyword argument 'num_devices'

### ISSUE THREAD

**Issue by la-cruche** [awslabs/autogluon#784]
Hi,

I'm running the public AutoGluon ObjectDetection [Quick Start](https://auto.gluon.ai/tutorials/object_detection/beginner.html) replacing `yolo3` by `faster_rcnn`. My fit is the below:

```python
detector = task.fit(dataset_train,
                    meta_arch='faster_rcnn',
                    net='resnet50_v1b',
                    num_trials=1,
                    epochs=epochs,
                    lr=ag.Categorical(5e-4, 1e-4),
                    ngpus_per_trial=1,
                    time_limits=time_limits)
```

it fails for with the following error (bottom of stack trace only):

```
packages/gluoncv/model_zoo/rcnn/rcnn.py", line 79, in __init__
    super(RCNN, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_devices'
```

[From this page](https://github.com/awslabs/autogluon/blob/master/vision/src/autogluon/vision/object_detection/pipeline.py), this seems to be related to `args.syncbn` being `True` resulting in a `num_devices` argument used in gluoncv model zoo's get_model, and faster_rcnn not supporting that argument. However, I didn't manage to disable syncbn in `task.fit()` ; `syncbn=False` returns the same error. Thoughts? How to make faster_rcnn work?

**Comment by la-cruche** [comment]
@zhreshold :)

**Comment by zhreshold** [comment]
@la-cruche hey, faster rcnn is not included in the existing object detection task. the latest changes that brings faster rcnn is not merged, see #733

**Comment by la-cruche** [comment]
but the [docstring says](https://github.com/awslabs/autogluon/blob/master/vision/src/autogluon/vision/object_detection/object_detection.py) it's supported no? _("Meta architecture of the model. Currently support YoloV3 (Default) and FasterRCNN. YoloV3 is faster, while FasterRCNN is more accurate.")_ Is there a previous AutoGluon version that supported it? Or an ETA for a future version to support it?

**Comment by Innixma** [comment]
#733 has been merged, so marking this as resolved. If the issue still exists in pre-release / upcoming v0.1 release, please re-open.
