### ISSUE TITLE
multiprocessing.context.TimeoutError in docker with gpu/cuda

### ISSUE THREAD

**Issue by claudiuvintila** [awslabs/autogluon#806]
I tried running the object detection example code on Azure Container Instances with GPU and get multiprocessing TimeoutError. Any ideas why?

----------------------------------------------------------------------------
import autogluon.core as ag
from autogluon.vision import ObjectDetection as task

import os

root = './'
filename_zip = ag.download('https://autogluon.s3.amazonaws.com/datasets/tiny_motorbike.zip',
                        path=root)
filename = ag.unzip(filename_zip, root=root)
data_root = os.path.join(root, filename)
dataset_train = task.Dataset(data_root, classes=('motorbike',))

time_limits = 5*60*60  # 5 hours
epochs = 30
detector = task.fit(dataset_train,
                    num_trials=2,
                    epochs=epochs,
                    lr=ag.Categorical(5e-4, 1e-4),
                    ngpus_per_trial=1,
                    time_limits=time_limits)

----------------------------------------------------------------------------

scheduler: FIFOScheduler(
DistributedResourceManager{
(Remote: Remote REMOTE_ID: 0,
        <Remote: 'inproc://10.244.183.4/2561/1' processes=1 threads=6, memory=16.00 GB>, Resource: NodeResourceManager(6 CPUs, 1 GPUs))
})

 50%|███████████████████████████████████████████████████████████████████████                                                                       | 1/2 [00:00<00:00,  1.96it/s]INFO:root:{'meta_arch': 'yolo3', 'dataset': <autogluon.vision.object_detection.dataset.voc.CustomVOCDetection object at 0x7f72302daed0>, 'net': 'mobilenet1.0', 'lr': 0.0005, 'loss': SoftmaxCrossEntropyLoss(batch_axis=0, w=None), 'num_gpus': 1, 'batch_size': 16, 'split_ratio': 0.8, 'epochs': 30, 'num_workers': 6, 'hybridize': True, 'verbose': False, 'final_fit': False, 'seed': 223, 'data_shape': 416, 'start_epoch': 0, 'transfer': 'coco', 'lr_mode': 'step', 'lr_decay': 0.1, 'lr_decay_period': 0, 'lr_decay_epoch': '160,180', 'warmup_lr': 0.0, 'warmup_epochs': 2, 'warmup_iters': 1000, 'warmup_factor': 0.3333333333333333, 'momentum': 0.9, 'wd': 0.0005, 'log_interval': 100, 'save_prefix': 'yolo3_mobilenet1.0_custom', 'save_interval': 10, 'val_interval': 1, 'num_samples': -1, 'no_random_shape': False, 'no_wd': False, 'mixup': False, 'no_mixup_epochs': 20, 'label_smooth': False, 'resume': '', 'syncbn': False, 'reuse_pred_weights': True, 'task_id': 0}
Worker timed out after 120 seconds. This might be caused by

            - Slow transform. Please increase timeout to allow slower data loading in each worker.
            - Insufficient shared_memory if `timeout` is large enough.
            Please consider reduce `num_workers` or increase shared_memory in system.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/autogluon/core/utils/custom_process.py", line 16, in run
    mp.Process.run(self)
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/autogluon/core/scheduler/scheduler.py", line 157, in _worker
    ret = fn(**args)
  File "/usr/local/lib/python3.7/dist-packages/autogluon/core/decorator.py", line 60, in __call__
    output = self.f(args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/autogluon/core/decorator.py", line 143, in wrapper_call
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/autogluon/vision/object_detection/pipeline.py", line 369, in train_object_detection
    train(net, train_data, val_data, eval_metric, ctx, args, reporter, args.final_fit)
  File "/usr/local/lib/python3.7/dist-packages/autogluon/vision/object_detection/pipeline.py", line 226, in train
    for i, batch in enumerate(train_data):
  File "/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataloader.py", line 484, in __next__
    batch = pickle.loads(ret.get(self._timeout))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 653, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [02:13<00:00, 66.76s/it]
INFO:root:{'meta_arch': 'yolo3', 'dataset': <autogluon.vision.object_detection.dataset.voc.CustomVOCDetection object at 0x7f723039b9d0>, 'net': 'mobilenet1.0', 'lr': 0.0001, 'loss': SoftmaxCrossEntropyLoss(batch_axis=0, w=None), 'num_gpus': 1, 'batch_size': 16, 'split_ratio': 0.8, 'epochs': 30, 'num_workers': 6, 'hybridize': True, 'verbose': False, 'final_fit': False, 'seed': 223, 'data_shape': 416, 'start_epoch': 0, 'transfer': 'coco', 'lr_mode': 'step', 'lr_decay': 0.1, 'lr_decay_period': 0, 'lr_decay_epoch': '160,180', 'warmup_lr': 0.0, 'warmup_epochs': 2, 'warmup_iters': 1000, 'warmup_factor': 0.3333333333333333, 'momentum': 0.9, 'wd': 0.0005, 'log_interval': 100, 'save_prefix': 'yolo3_mobilenet1.0_custom', 'save_interval': 10, 'val_interval': 1, 'num_samples': -1, 'no_random_shape': False, 'no_wd': False, 'mixup': False, 'no_mixup_epochs': 20, 'label_smooth': False, 'resume': '', 'syncbn': False, 'reuse_pred_weights': True, 'task_id': 1}

Worker timed out after 120 seconds. This might be caused by

            - Slow transform. Please increase timeout to allow slower data loading in each worker.
            - Insufficient shared_memory if `timeout` is large enough.
            Please consider reduce `num_workers` or increase shared_memory in system.

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/autogluon/core/utils/custom_process.py", line 16, in run
    mp.Process.run(self)
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/autogluon/core/scheduler/scheduler.py", line 157, in _worker
    ret = fn(**args)
  File "/usr/local/lib/python3.7/dist-packages/autogluon/core/decorator.py", line 60, in __call__
    output = self.f(args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/autogluon/core/decorator.py", line 143, in wrapper_call
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/autogluon/vision/object_detection/pipeline.py", line 369, in train_object_detection
    train(net, train_data, val_data, eval_metric, ctx, args, reporter, args.final_fit)
  File "/usr/local/lib/python3.7/dist-packages/autogluon/vision/object_detection/pipeline.py", line 226, in train
    for i, batch in enumerate(train_data):
  File "/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataloader.py", line 484, in __next__
    batch = pickle.loads(ret.get(self._timeout))
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 653, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

INFO:root:{'meta_arch': 'yolo3', 'dataset': <autogluon.vision.object_detection.dataset.voc.CustomVOCDetection object at 0x7f71f6acd850>, 'net': 'mobilenet1.0', 'lr': 0.0005, 'loss': SoftmaxCrossEntropyLoss(batch_axis=0, w=None), 'num_gpus': 1, 'batch_size': 16, 'split_ratio': 0.8, 'epochs': 30, 'num_workers': 6, 'hybridize': True, 'verbose': False, 'final_fit': True, 'seed': 223, 'data_shape': 416, 'start_epoch': 0, 'transfer': 'coco', 'lr_mode': 'step', 'lr_decay': 0.1, 'lr_decay_period': 0, 'lr_decay_epoch': '160,180', 'warmup_lr': 0.0, 'warmup_epochs': 2, 'warmup_iters': 1000, 'warmup_factor': 0.3333333333333333, 'momentum': 0.9, 'wd': 0.0005, 'log_interval': 100, 'save_prefix': 'yolo3_mobilenet1.0_custom', 'save_interval': 10, 'val_interval': 1, 'num_samples': -1, 'no_random_shape': False, 'no_wd': False, 'mixup': False, 'no_mixup_epochs': 20, 'label_smooth': False, 'resume': '', 'syncbn': False, 'reuse_pred_weights': True, 'task_id': 2}
Worker timed out after 120 seconds. This might be caused by

            - Slow transform. Please increase timeout to allow slower data loading in each worker.
            - Insufficient shared_memory if `timeout` is large enough.
            Please consider reduce `num_workers` or increase shared_memory in system.

No valid results obtained with best config, the result may not be useful...
Traceback (most recent call last):
  File "yolo2.py", line 20, in <module>
    time_limits=time_limits)
  File "/usr/local/lib/python3.7/dist-packages/autogluon/vision/object_detection/object_detection.py", line 302, in fit
    update_params(model, results.pop('model_params'))
KeyError: 'model_params'

[Dockerfile.txt](https://github.com/awslabs/autogluon/files/5625797/Dockerfile.txt)

**Comment by Innixma** [comment]
@zhreshold Perhaps this is related to the HPO instability issue that has recently been addressed?

**Comment by RuojiWang** [comment]
**i met this problem a few days ago when i was training custom data with object detection of autogluon. but i use pycharm and anaconda not docker. i spent half a day trying out the following method, which works for me:**

1) use smaller num_workers in fit method, which the default value is 32, you can try 4, 8 or 16 until you never met this problem.
2) run your code in terminal. do not run your code in pycharm, sometimes it may cause threading issues.

**steps above should solve multiprocessing timeout error.
but i met some memory problems which can be solved by the following steps:**

3) use smaller batch_size,  which the default value is 16, you can try 2, 4 or 8.
4) try not to use other software or services during training, which may cause slow dataloader processing and lead to other problems.

**Comment by Innixma** [comment]
@RuojiWang Thanks for the info, it appears that this is primarily a GPU memory issue then.

**Comment by claudiuvintila** [comment]
> **i met this problem a few days ago when i was training custom data with object detection of autogluon. but i use pycharm and anaconda not docker. i spent half a day trying out the following method, which works for me:**
> 
> 1. use smaller num_workers in fit method, which the default value is 32, you can try 4, 8 or 16 until you never met this problem.
> 2. run your code in terminal. do not run your code in pycharm, sometimes it may cause threading issues.
> 
> **steps above should solve multiprocessing timeout error. but i met some memory problems which can be solved by the following steps:**
> 
> 1. use smaller batch_size,  which the default value is 16, you can try 2, 4 or 8.
> 2. try not to use other software or services during training, which may cause slow dataloader processing and lead to other problems.
> 
> **there is a solution for docker, may this help~ [apache/incubator-mxnet#18224](https://github.com/apache/incubator-mxnet/issues/18224)**

Thank you!
