### ISSUE TITLE
No module named "fastai.core"

### ISSUE THREAD

**Issue by sxjscience** [awslabs/autogluon#809]
I'm meeting this error message:

```
  File "/home/ubuntu/autogluon/tabular/src/autogluon/tabular/trainer/model_presets/presets_distill.py", line 5, in <module>
    from .presets import get_preset_models, get_preset_models_softclass
  File "/home/ubuntu/autogluon/tabular/src/autogluon/tabular/trainer/model_presets/presets.py", line 13, in <module>
    from ...models.fastainn.tabular_nn_fastai import NNFastAiTabularModel
  File "/home/ubuntu/autogluon/tabular/src/autogluon/tabular/models/fastainn/tabular_nn_fastai.py", line 12, in <module>
    from fastai.core import defaults
ModuleNotFoundError: No module named 'fastai.core'
```

It might be due to some upgrade of the fastai package.

**Comment by sxjscience** [comment]
I just realized it's due to some incorrect cherry-picking.

**Comment by Monk5088** [comment]
> I just realized it's due to some incorrect cherry-picking.
HEY can you tell how you solved this issue , I'm experiencing same issue while using on kaggle.
`
from fastai.vision import *

from fastai.core import *
import json
from collections import defaultdict
import pdb
import numpy as np`

ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_38/2985014308.py in <module>
      1 from fastai.vision import *
      2 
----> 3 from fastai.core import *
      4 import json
      5 from collections import defaultdict

ModuleNotFoundError: No module named 'fastai.core'

**Comment by univanxx** [comment]
For me changing fastai version to 1.0.61 helped:

`pip install fastai==1.0.61`
