### ISSUE TITLE
Reasoning behind the standard reward function in ENAS

### ISSUE THREAD

**Issue by konstantinjdobler** [awslabs/autogluon#812]
Hey! Is there documentation on why the recommended reward function (https://auto.gluon.ai/tutorials/nas/enas_proxylessnas.html#autogluon-enas-unit, `reward_fn = lambda metric, net: metric * ((net.avg_latency / net.latency) ** 0.1)` ) is structured that way? 

Is the latency used to incentivize fast models instead of accurate ones? If so why, why is `(net.avg_latency / net.latency)` used instead of just subtracting the latency from the reward (adjust by tradeoff parameter)? I am hoping to understand the ENAS implementation of AutoGluon better, but I was not able to find documentation on this. Thanks for your work on this project!

**Comment by Innixma** [comment]
@zhreshold Would you be able to answer this?

**Comment by zhreshold** [comment]
@konstantinjdobler If we take into consideration that `metric`(can be accuracy or else) and `net.latency` are unknown before search, you will notice that subtracting is substantially error prone. By doing `(net.avg_latency / net.latency) ** K` where K is a factor to control the weight of network latency, then you ensure that the `reward_fn` will never be negative. It's not specifically mentioned in the ENAS paper(and I believe for a real dataset you still need a different reward function other than this example), but a lot more details can be found in the paper: https://arxiv.org/pdf/1802.03268.pdf
