### ISSUE TITLE
ModuleNotFoundError: No module named 'autogluon.vision'

### ISSUE THREAD

**Issue by RuojiWang** [awslabs/autogluon#815]
**i use ubuntu 18.04 and Pycharm**

**in my anaconda environment, i use the following code to install autogluon：**

python3 -m pip install --upgrade "mxnet<2.0.0"
python3 -m pip install autogluon

**when i running the following code, which is the example code of object detection of autogluon:**
import autogluon.core as ag
from autogluon.vision import ObjectDetection as task

root = './'
filename_zip = ag.download('https://autogluon.s3.amazonaws.com/datasets/tiny_motorbike.zip', path=root)
filename = ag.unzip(filename_zip, root=root)

import osacti
#data_root = os.path.join(root, filename)
data_root = "./tiny_motorbike"
dataset_train = task.Dataset(data_root, classes=('motorbike',))

time_limits = 5*60*60  # 5 hours
epochs = 30
detector = task.fit(dataset_train,
                    num_trials=2,
                    epochs=epochs,
                    lr=ag.Categorical(5e-4, 1e-4),
                    ngpus_per_trial=1,
                    time_limits=time_limits)

dataset_test = task.Dataset(data_root, index_file_name='test', classes=('motorbike',))

test_map = detector.evaluate(dataset_test)
print("mAP on test dataset: {}".format(test_map[1][1]))

image = '000467.jpg'
image_path = os.path.join(data_root, 'JPEGImages', image)

ind, prob, loc = detector.predict(image_path)

savefile = 'model.pkl'
detector.save(savefile)

from autogluon.vision import Detector
new_detector = Detector.load(savefile)

**i get the following error:**

/home/jingyu/anaconda3/envs/autogluon/bin/python /media/sf_Workspace/YOLOv4/autogluon1.py
Traceback (most recent call last):
  File "/media/sf_Workspace/YOLOv4/autogluon1.py", line 2, in <module>
    from autogluon.vision import ObjectDetection as task
ModuleNotFoundError: No module named 'autogluon.vision'

Process finished with exit code 1

**i have try solution like: https://github.com/awslabs/autogluon/issues/811, or install autogluon from code, but none of them work.**

**i just confused and wondering how to figure it out, thanks a lot~**

**Comment by Innixma** [comment]
You are using the stable release of AutoGluon, meaning you should refer to this version of the documentation: https://auto.gluon.ai/stable/tutorials/object_detection/beginner.html

However, you were looking at the pre-release documentation of AutoGluon which is not compatible with the stable release: https://auto.gluon.ai/dev/tutorials/object_detection/beginner.html

In order to use the pre-release, you must install from a fresh venv with these instructions: https://auto.gluon.ai/dev/install.html

**Comment by RuojiWang** [comment]
now, i am running the code, i didn't notice the stable quick start
thanks a lot.
