### ISSUE TITLE
object detection example code can not work 【Cannot reset context for Parameter 'mobilenet0_conv0_weight' because it has not been initialized.】

### ISSUE THREAD

**Issue by RuojiWang** [awslabs/autogluon#823]
**i use ubuntu 18.04 and pycahrm, my autogluon verison is  0.0.15 and my autogluon-contrib-nlp is 0.0.1b20201009**

**when i am running the example code of object detection(i only change variable like time_limits、 epoch to make program run faster) as following:**

```
import autogluon as ag
from autogluon import ObjectDetection as task

root = './'
filename_zip = ag.download('https://autogluon.s3.amazonaws.com/datasets/tiny_motorbike.zip', path=root)
filename = ag.unzip(filename_zip, root=root)

import os
data_root = os.path.join(root, filename)
#data_root = './tiny_motorbike/'
dataset_train = task.Dataset(data_root, classes=('motorbike',))

#time_limits = 5*60*60  # 5 hours
time_limits = 1*60  # 1 minute
#epochs = 30
epochs = 1
detector = task.fit(dataset_train,
                    num_trials=2,
                    epochs=epochs,
                    lr=ag.Categorical(5e-4, 1e-4),
                    ngpus_per_trial=1,
                    time_limits=time_limits)
print("done1.")

dataset_test = task.Dataset(data_root, index_file_name='test', classes=('motorbike',))

test_map = detector.evaluate(dataset_test)
print("mAP on test dataset: {}".format(test_map[1][1]))

image = '000467.jpg'
image_path = os.path.join(data_root, 'JPEGImages', image)

ind, prob, loc = detector.predict(image_path)

savefile = 'model.pkl'
detector.save(savefile)

from autogluon import Detector
new_detector = Detector.load(savefile)
print("done2.")

**the console output as following:**

/home/jingyu/anaconda3/envs/autogluon/bin/python /home/jingyu/pycharm-community-2020.2.2/plugins/python-ce/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 35003 --file 

/media/sf_Workspace/YOLOv4/autogluon1.py
pydev debugger: process 5324 is connecting

Connected to pydev debugger (build 202.7319.64)
Backend TkAgg is interactive backend. Turning interactive mode on.
>>> create dataset(VOC format) 
The number of requested GPUs is greater than the number of available GPUs.
distributed.diskutils - ERROR - Failed to remove '/media/sf_Workspace/YOLOv4/dask-worker-space/worker-leuqeiko/storage' (failed in <built-in function rmdir>): [Errno 26] Text file busy: 'storage'
distributed.diskutils - ERROR - Failed to remove '/media/sf_Workspace/YOLOv4/dask-worker-space/worker-leuqeiko' (failed in <built-in function rmdir>): [Errno 26] Text file busy: '/media/sf_Workspace/YOLOv4/dask-worker-space/worker-

leuqeiko'
scheduler_options: Key 'training_history_callback_delta_secs': Imputing default value 60
scheduler_options: Key 'delay_get_config': Imputing default value True

Starting Experiments
Num of Finished Tasks is 0
Num of Pending Tasks is 2
  0%|          | 0/2 [00:00<?, ?it/s]Time out (secs) is 60
scheduler: FIFOScheduler(
DistributedResourceManager{
(Remote: Remote REMOTE_ID: 0, 
	<Remote: 'inproc://10.0.2.15/5324/1' processes=1 threads=4, memory=11.64 GB>, Resource: NodeResourceManager(4 CPUs, 0 GPUs))
})

 50%|█████     | 1/2 [00:00<00:00,  3.84it/s]{'meta_arch': 'yolo3', 'dataset': <autogluon.task.object_detection.dataset.voc.CustomVOCDetection object at 0x7f72eb7cbc88>, 'net': 'mobilenet1.0', 'lr': 0.0005, 'loss': 

SoftmaxCrossEntropyLoss(batch_axis=0, w=None), 'num_gpus': 0, 'batch_size': 16, 'split_ratio': 0.8, 'epochs': 1, 'num_workers': 4, 'hybridize': True, 'verbose': False, 'final_fit': False, 'seed': 223, 'data_shape': 416, 'start_epoch': 0, 

'transfer': 'coco', 'lr_mode': 'step', 'lr_decay': 0.1, 'lr_decay_period': 0, 'lr_decay_epoch': '160,180', 'warmup_lr': 0.0, 'warmup_epochs': 2, 'warmup_iters': 1000, 'warmup_factor': 0.3333333333333333, 'momentum': 0.9, 'wd': 0.0005, 

'log_interval': 100, 'save_prefix': 'yolo3_mobilenet1.0_custom', 'save_interval': 10, 'val_interval': 1, 'num_samples': -1, 'no_random_shape': False, 'no_wd': False, 'mixup': False, 'no_mixup_epochs': 20, 'label_smooth': False, 'resume': 

'', 'syncbn': False, 'reuse_pred_weights': True, 'task_id': 0}
[Epoch 0] Training cost: 105.759, ObjLoss=3393.193,BoxCenterLoss=4.119,BoxScaleLoss=3.263,ClassLoss=1.067
[Epoch 0] Validation: motorbike=0.0013434841021047917 mAP=0.0013434841021047917
100%|██████████| 2/2 [02:08<00:00, 64.21s/it]
{'meta_arch': 'yolo3', 'dataset': <autogluon.task.object_detection.dataset.voc.CustomVOCDetection object at 0x7f72eaa1a668>, 'net': 'mobilenet1.0', 'lr': 0.0001, 'loss': SoftmaxCrossEntropyLoss(batch_axis=0, w=None), 'num_gpus': 0, 

'batch_size': 16, 'split_ratio': 0.8, 'epochs': 1, 'num_workers': 4, 'hybridize': True, 'verbose': False, 'final_fit': False, 'seed': 223, 'data_shape': 416, 'start_epoch': 0, 'transfer': 'coco', 'lr_mode': 'step', 'lr_decay': 0.1, 

'lr_decay_period': 0, 'lr_decay_epoch': '160,180', 'warmup_lr': 0.0, 'warmup_epochs': 2, 'warmup_iters': 1000, 'warmup_factor': 0.3333333333333333, 'momentum': 0.9, 'wd': 0.0005, 'log_interval': 100, 'save_prefix': 

'yolo3_mobilenet1.0_custom', 'save_interval': 10, 'val_interval': 1, 'num_samples': -1, 'no_random_shape': False, 'no_wd': False, 'mixup': False, 'no_mixup_epochs': 20, 'label_smooth': False, 'resume': '', 'syncbn': False, 

'reuse_pred_weights': True, 'task_id': 1}
[Epoch 0] Training cost: 105.234, ObjLoss=5483.593,BoxCenterLoss=4.103,BoxScaleLoss=3.401,ClassLoss=1.097
[Epoch 0] Validation: motorbike=4.3166709833376505e-05 mAP=4.3166709833376505e-05
{'meta_arch': 'yolo3', 'dataset': <autogluon.task.object_detection.dataset.voc.CustomVOCDetection object at 0x7f728f72c438>, 'net': 'mobilenet1.0', 'lr': 0.0005, 'loss': SoftmaxCrossEntropyLoss(batch_axis=0, w=None), 'num_gpus': 0, 

'batch_size': 16, 'split_ratio': 0.8, 'epochs': 1, 'num_workers': 4, 'hybridize': True, 'verbose': False, 'final_fit': True, 'seed': 223, 'data_shape': 416, 'start_epoch': 0, 'transfer': 'coco', 'lr_mode': 'step', 'lr_decay': 0.1, 

'lr_decay_period': 0, 'lr_decay_epoch': '160,180', 'warmup_lr': 0.0, 'warmup_epochs': 2, 'warmup_iters': 1000, 'warmup_factor': 0.3333333333333333, 'momentum': 0.9, 'wd': 0.0005, 'log_interval': 100, 'save_prefix': 

'yolo3_mobilenet1.0_custom', 'save_interval': 10, 'val_interval': 1, 'num_samples': -1, 'no_random_shape': False, 'no_wd': False, 'mixup': False, 'no_mixup_epochs': 20, 'label_smooth': False, 'resume': '', 'syncbn': False, 

'reuse_pred_weights': True, 'task_id': 2}
[Epoch 0] Training cost: 109.500, ObjLoss=2585.343,BoxCenterLoss=3.803,BoxScaleLoss=3.022,ClassLoss=1.016

finish model fitting
The best config: {'lr▁choice': 0, 'net▁choice': 0}
done1.
>>> create dataset(VOC format) 
Traceback (most recent call last):
  File "/home/jingyu/pycharm-community-2020.2.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jingyu/pycharm-community-2020.2.2/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/media/sf_Workspace/YOLOv4/autogluon1.py", line 28, in <module>
    test_map = detector.evaluate(dataset_test)
  File "/home/jingyu/anaconda3/envs/autogluon/lib/python3.6/site-packages/autogluon/task/object_detection/detector.py", line 44, in evaluate
    net.collect_params().reset_ctx(ctx)
  File "/home/jingyu/anaconda3/envs/autogluon/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 929, in reset_ctx
    i.reset_ctx(ctx)
  File "/home/jingyu/anaconda3/envs/autogluon/lib/python3.6/site-packages/mxnet/gluon/parameter.py", line 493, in reset_ctx
    "has not been initialized."%self.name)
ValueError: Cannot reset context for Parameter 'mobilenet0_conv0_weight' because it has not been initialized.
python-BaseException
distributed.diskutils - ERROR - Failed to remove '/media/sf_Workspace/YOLOv4/dask-worker-space/worker-_cqczjt5/storage' (failed in <built-in function rmdir>): [Errno 26] Text file busy: 'storage'
distributed.diskutils - ERROR - Failed to remove '/media/sf_Workspace/YOLOv4/dask-worker-space/worker-_cqczjt5' (failed in <built-in function rmdir>): [Errno 26] Text file busy: '/media/sf_Workspace/YOLOv4/dask-worker-space/worker-_cqczjt5'

Process finished with exit code 1
```

**i google it but have no idea how to modify the code, so i come here for help. 
i guess the problem is: Cannot reset context for Parameter 'mobilenet0_conv0_weight' because it has not been initialized.**

**anyway thanks in advance.**

**Comment by Innixma** [comment]
Thanks for reporting the issue!

We can confirm that this tutorial runs reliably on our CI build machines as it is executed on our [CI builds](https://ci.gluon.ai/blue/organizations/jenkins/autogluon/detail/0.0.15/2/pipeline) to [build the documentation](https://auto.gluon.ai/0.0.15/tutorials/object_detection/beginner.html), so if you are still having issues running it, it may be specific to your machine configuration.

ObjectDetection has been overhauled in mainline (v0.0.15 is >2 months old compared to mainline), so I'd recommend you try [installing autogluon from a fresh venv using the pre-release version](https://auto.gluon.ai/dev/install.html) and [following the dev tutorial](https://auto.gluon.ai/dev/tutorials/object_detection/beginner.html).

If you are still having issues, I'd recommend providing info on OS, GPU, CUDA, etc. as well as MXNet version (should be a GPU MXNet version).

**Comment by MatheCore** [comment]
With the following code :
``
``
``
``
``
``
``
``

**Comment by MatheCore** [comment]
With the following code: 
`import os`
`root = './'`
`filename_zip = ag.download('https://philschmid-datasets.s3.eu-central-1.amazonaws.com/tiny_fruit.zip',
                        path=root)`
`# unzip data`
`filename = ag.unzip(filename_zip, root=root)`

`# create Dataset`
`data_root = os.path.join(root, filename)`
`# train dataset`
`dataset_train = task.Dataset(data_root, classes=('banana','apple','orange'),format='voc')`
`# test dataset`
`dataset_test = task.Dataset(data_root, index_file_name='test', classes=('banana','apple','orange'),format='voc')`

`from autogluon import ObjectDetection as task`

`epochs = 20`
`detector = task.fit(dataset_train,
                    num_trials=3,
                    epochs=epochs,
                    lr=ag.Categorical(5e-4, 1e-4, 3e-4),
                                        ngpus_per_trial=1,time_limits=60*20)`

I could make training for the data, it needs about 9 hours to finish even the time_limits is just 20 minutes... but the probelm is: when i try to evaluate the performance with: 
`test_map = detector.evaluate(dataset_test)`

`print(f"The mAP on the test dataset is {test_map[1][1]}")`

or predict an image like: 
`image = 'mixed_10.jpg'`

`image_path = os.path.join(data_root, 'JPEGImages', image)`

`ind, prob, loc = detector.predict(image_path)`

i get the same error 

> ValueError: Cannot reset context for Parameter 'mobilenet0_conv0_weight' because it has not been initialized.

I did the suggested solutions but it did not work. I am working on colab but i am not using the GPU because when i do it just make more problems.

**Comment by RuojiWang** [comment]
> Thanks for reporting the issue!
> 
> Firstly, please try running the tutorial with the indicated time limits and epochs (or at least close to). 1 minute is likely not enough time to produce a model, which would explain the errors. Note that tasks other than Tabular do not have as thorough failsafes regarding this behavior yet, so always try to increase the time limit / epochs in these situations as a sanity check. Furthermore, please attempt running the code from terminal instead of python debugger, as debugger / PyCharm could introduce issues regarding multi-threading. If running for the full 5 hours still does not work, please continue reading.
> 
> We can confirm that this tutorial runs reliably on our CI build machines as it is executed on our [CI builds](https://ci.gluon.ai/blue/organizations/jenkins/autogluon/detail/0.0.15/2/pipeline) to [build the documentation](https://auto.gluon.ai/0.0.15/tutorials/object_detection/beginner.html), so if you are still having issues running it, it may be specific to your machine configuration.
> 
> ObjectDetection has been overhauled in mainline (v0.0.15 is >2 months old compared to mainline), so I'd recommend you try [installing autogluon from a fresh venv using the pre-release version](https://auto.gluon.ai/dev/install.html) and [following the dev tutorial](https://auto.gluon.ai/dev/tutorials/object_detection/beginner.html).
> 
> If you are still having issues, I'd recommend providing info on OS, GPU, CUDA, etc. as well as MXNet version (should be a GPU MXNet version).

**i guess i met the problem because of using VM Oracle VirtualBox(which is a kind of virtual machine) on my windows7(ubuntu18.04 without GPU, cause virtual machine can not share GPU with my windows).

when i use dual system windows7&ubuntu18.04, i never met this problem, now i can use the object detection example code. and the code and work in pycharm environment, maybe i should use terminal more instead of pycharm to avoid some strange errors.

it takes me some time to download files like yolo3_mobilenet1.0_coco-66dbbae6.zip, until i get VPN......**

**Comment by Innixma** [comment]
@MatheCore I suspect that trying to infer with these models without a GPU will not work. I don't believe our developers intended object detection models to be trained and inferred with CPU, and I would highly recommend that you leverage a GPU as these models are very large.

@zhreshold Do you think it would make sense for us to have Colab notebook tutorials for image classification and object detection for v0.1 release? Also, perhaps some of the errors described here could provide more helpful messages to users? At present it seems rather cryptic.
