### ISSUE TITLE
Cant install Autogluon on Kaggle

### ISSUE THREAD

**Issue by elvinaqa** [awslabs/autogluon#827]
Error
```ImportError: cannot import name 'isStringType' from 'PIL._util' (/opt/conda/lib/python3.7/site-packages/PIL/_util.py)```

**Comment by Innixma** [comment]
Can you try to follow the logic of the working Kaggle Kernel linked [here](https://github.com/awslabs/autogluon/issues/818#issuecomment-745429026)?

**Comment by Innixma** [comment]
Closing as we have confirmed AutoGluon pre-release can be installed on Kaggle via pip.
