### ISSUE TITLE
Continuous search space like ag.space.Real not supported by RLScheduler?

### ISSUE THREAD

**Issue by Droneree** [awslabs/autogluon#830]
Mxnet version: 1.7.0
autogluon version: 0.0.13

I tried a piece of example code from [Autogluon official website](https://auto.gluon.ai/api/autogluon.core.scheduler.html#rlscheduler).

```python
import numpy as np
import autogluon.core as ag

@ag.args(
lr=ag.space.Real(1e-3, 1e-2, log=True),
wd=ag.space.Real(1e-3, 1e-2))
def train_fn(args, reporter):
print('lr: {}, wd: {}'.format(args.lr, args.wd))
for e in range(10):
dummy_accuracy = 1 - np.power(1.8, -np.random.uniform(e, 2*e))
reporter(epoch=e+1, accuracy=dummy_accuracy, lr=args.lr, wd=args.wd)

scheduler = ag.scheduler.RLScheduler(train_fn,
resource={'num_cpus': 2, 'num_gpus': 0},
num_trials=20,
reward_attr='accuracy',
time_attr='epoch')
scheduler.run()
scheduler.join_jobs()
scheduler.get_training_curves(plot=True)
```

An error was raised:

```python
scheduler_options: Key 'resume': Imputing default value False
scheduler_options: Key 'checkpoint': Imputing default value ./exp/checkpoint.ag
scheduler_options: Key 'controller_lr': Imputing default value 0.001
scheduler_options: Key 'ema_baseline_decay': Imputing default value 0.95
scheduler_options: Key 'controller_resource': Imputing default value {'num_cpus': 0, 'num_gpus': 0}
scheduler_options: Key 'controller_batch_size': Imputing default value 1
scheduler_options: Key 'sync': Imputing default value True

Traceback (most recent call last):
  File "test2222.py", line 17, in <module>
    time_attr='epoch')
  File "/home/lllei/anaconda3/envs/tf/lib/python3.7/site-packages/autogluon/scheduler/rl_scheduler.py", line 118, in __init__
    train_fn.kwspaces, reward_attribute=kwargs['reward_attr'])
  File "/home/lllei/anaconda3/envs/tf/lib/python3.7/site-packages/autogluon/searcher/rl_controller.py", line 41, in __init__
    self.controller = LSTMController(kwspaces, ctx=ctx, **kwargs)
  File "/home/lllei/anaconda3/envs/tf/lib/python3.7/site-packages/autogluon/searcher/rl_controller.py", line 133, in __init__
    assert isinstance(space, Categorical)
AssertionError

```

It seems that only **Categorical** search space is supported for **RLSchduler**. I replaced RLScheduler with **FIFOScheduler**, it turned out to be fine. Also when my search space is **Categorical** rather than **Real**, it works well. Is this a bug? Or Real search space is just not supported by RLScheduler? Thanks for any help.

**Comment by jwmueller** [comment]
As you said, the RLScheduler only supports Categorical search spaces at the moment. Real search spaces would require a different policy network that can parameterize continuous distributions, whereas the current policy network only parameterizes discrete distributions.

**Comment by Droneree** [comment]
> As you said, the RLScheduler only supports Categorical search spaces at the moment. Real search spaces would require a different policy network that can parameterize continuous distributions, whereas the current policy network only parameterizes discrete distributions.

Thanks for @jwmueller 's answer. I think my problem has been solved.
