### ISSUE TITLE
Is there a way to use pretrained bert model to do text classify with autogluon.task.TextPrediction?

### ISSUE THREAD

**Issue by Gpwner** [awslabs/autogluon#846]
When I  refer to the  autogluon.task.TextPrediction API , I found the 'fit' method return a model which is
`A BertForTextPredictionBasic object that can be used for making predictions on new data.`
So,Is there a way to use pretrained bert model to do text classification with autogluon.task.TextPrediction?

**Comment by Gpwner** [comment]
What I  mean is using customized pretraining model.Any help?

**Comment by Innixma** [comment]
We use pre-trained BERT by default and fine-tune it on the provided data. @sxjscience could you elaborate on what our support for custom pre-training models are?

**Comment by sxjscience** [comment]
@Gpwner Thanks for the question! Currently it's not directly supported. And you will need to tweak the code to convert your pretrained weights to a format understandable by GluonNLP (https://github.com/sxjscience/autogluon-contrib-nlp/blob/master/src/autogluon_contrib_nlp/models/electra.py). I'm currently

1) Add the support of Huggingface pretrained models so you can use your own pretrained model if it's in the format of Huggingface/Transformers

Later on, I'll do the following:

2) Switch to the official GluonNLP: https://github.com/dmlc/gluon-nlp/tree/master, in which we offer the pretraining scripts that have been optimized: https://github.com/dmlc/gluon-nlp/tree/master/scripts/pretraining

You will see some upgrade on the huggingface / pytorch support soon and just stay tuned.

**Comment by Gpwner** [comment]
Is it possible to use tensorflow model which is pretrain by Google official BERT code?

**Comment by Gpwner** [comment]
Any way This is a great job.Looking forward to your upgrade！

**Comment by sxjscience** [comment]
> Is it possible to use tensorflow model which is pretrain by Google official BERT code?

Yes, the plan is to ask people to use the conversion tool in Huggingface (https://huggingface.co/transformers/converting_tensorflow_models.html) / GluonNLP (https://github.com/dmlc/gluon-nlp/tree/master/scripts/conversion_toolkits) to convert the  TF checkpoints. This will offer a path for using TF models.

**Comment by wlongxiang** [comment]
> Add the support of Huggingface pretrained models so you can use your own pretrained model if it's in the format of Huggingface/Transformers

Looking forward to this!

**Comment by cgnorthcutt** [comment]
> You will see some upgrade on the huggingface / pytorch support soon and just stay tuned.

@sxjscience - I'm still tuned in. Any updates on when this will be released?

**Comment by sxjscience** [comment]
@cgnorthcutt It will be released this year.

**Comment by cgnorthcutt** [comment]
@sxjscience so glad to hear! If you plan on publishing benchmarks, let us know. We might be able to help (MIT, ChipBrain AI Research, CleanLab AI).

**Comment by clechristophe** [comment]
@sxjscience Any news ? How can we use custom Huggingface/Spacy models on AutoGluon ? It will be great to use Autogluon on different languages !

**Comment by Innixma** [comment]
@clechristophe The release is planned for Late Jan 2022 in AutoGluon v0.4

In v0.4 you will be able to specify custom HuggingFace models.

**Comment by sxjscience** [comment]
We have upgraded the TextPredictor to support huggingface backbones.

Compared with the TextPredictor in AutoGluon 0.3, the TextPredictor in AutoGluon 0.4 has 72.22% win-rate in the multimodal text-tabular benchmark. If we use the “high_quality” preset, the win-rate increased to 77.8% thanks to the microsoft/deberta-v3-base backbone.
In addition, the new version has ~2.88x speedup in training and ~1.40x speedup in inference. With g4dn.12x instance, the model can further achieve 2.26x speedup with 4 GPUs.

Feel free to reopen the issue if problem persists.
