### ISSUE TITLE
Stuck in task.fit() for image classification

### ISSUE THREAD

**Issue by stacy0416** [awslabs/autogluon#853]
I used autogluon to train an image classifier.
But when I trained a classifier with nets='resnest101', there will be a situation where the GPU utilization has been reset to zero, the CPU/memory usage has slowly increased, and the process has not finished.

`classifier = ag.ImageClassification.fit(dataset,
                      net='resnest101',
                      input_size=224,
                      batch_size=64,
                      epochs=300,
                      num_trials=2,
                      time_limits=None,
                      split_ratio=0.8,
                      ngpus_per_trial=2
                     )`

Thanks

**Comment by zhreshold** [comment]
Do you notice the GPU memory hit the maximum before it freeze? And how long have you been waiting for the process to finish?

**Comment by stacy0416** [comment]
Do you notice the GPU memory hit the maximum before it freeze? Yes
How long have you been waiting for the process to finish? Haven't finished for a long time.

**Comment by zhreshold** [comment]
@stacy0416 batch_size 64 is probably not feasible for your setup, you may reduce it in order to allow the model to fit in the gpu memory.
