### ISSUE TITLE
AutoGluon Text training error due to data passing

### ISSUE THREAD

**Issue by sflender** [awslabs/autogluon#866]
When training AutoGluon Text (nightly) with a large file (2M rows), I get an error 

**distributed.core - ERROR - 2497537887 exceeds max_bin_len(2147483647)**

Xingjian: " I’m suspecting this line: https://github.com/awslabs/autogluon/blob/ae5dd91e8892c6c8edd87e42442b8007fc9d60c5/text/src/autogluon/text/text_prediction/models/basic_v1.py#L[…]11, in which we are passing the train_data. This may potentially be large. "

**Comment by sxjscience** [comment]
@sflender Would I know if the fix works or not?

**Comment by sflender** [comment]
the fix worked, the model is training. thanks!
