### ISSUE TITLE
Autogluon Dev Tutorial for Tabular + Text Model 5 multimodal embedding not used

### ISSUE THREAD

**Issue by mikiwz** [awslabs/autogluon#868]
https://auto.gluon.ai/dev/tutorials/tabular_prediction/tabular-multimodal-text-others.html#model-5-multimodal-embedding-tabularpredictor

In Model 5, it seems that the multimodal embedding is not used and the original train_df fed into the TextPrediction is the input to the TabularPrediction, and thus there is no performance improvement observed.

**Comment by Innixma** [comment]
Thanks for the report! This has been fixed as the tutorial has been reworked: https://auto.gluon.ai/dev/tutorials/tabular_prediction/tabular-multimodal-text-others.html#
