### ISSUE TITLE
AG Text multi-GPU inference

### ISSUE THREAD

**Issue by sflender** [awslabs/autogluon#872]
Hey AG team, when running inference with the AG Text Neural Network in the nightly build, I only see one GPU is being used (of the 8 on a p2-8xlarge instance). Training on the other hand works fine on the 8 GPUs. Can we implement support for multi-GPU parallelized inference?

**Comment by sxjscience** [comment]
@sflender Feel free to report here if it has fixed your issue.

**Comment by sxjscience** [comment]
@sflender Just a check. Has the issue been resolved?

**Comment by sflender** [comment]
Indeed, thanks.
