### ISSUE TITLE
Segmentation fault on import

### ISSUE THREAD

**Issue by briandesilva** [awslabs/autogluon#875]
### Issue
I am getting a segmentation fault when running the following import statement 
```python
from autogluon.tabular import TabularPrediction
```
and segmentation fault: 11 when running
```python
from autogluon.text import TextPrediction
```

I am using a recent branch of autogluon, installed in a clean virtual environment: autogluon version 0.0.16b20210120

### Environment
```bash
conda create -n autogluon-dev python=3.7
conda activate autogluon-dev
python3 -m pip install --upgrade "mxnet_cu100<2.0.0"
python3 -m pip install --pre autogluon
```

I have also tried installing by cloning autogluon from github, replacing the last line with
```bash
git clone https://github.com/awslabs/autogluon.git
cd autogluon
bash full_install.sh
```

Platform: Linux/UNIX
(ec2) Instance type: p2.8xlarge
AMI: Deep Learning AMI (Amazon Linux 2) Version 36.0

`python3 --version`: Python 3.7.9
`nvcc --version`: Cuda compilation tools, release 10.0, V10.0.130
`pip freeze`:
```bash
attrs==20.3.0
autocfg==0.0.6
autogluon==0.0.16b20210120
autogluon-contrib-nlp==0.0.1b20210112
autogluon.core==0.0.16b20210120
autogluon.extra==0.0.16b20210120
autogluon.mxnet==0.0.16b20210120
autogluon.tabular==0.0.16b20210120
autogluon.text==0.0.16b20210120
autogluon.vision==0.0.16b20210120
autograd==1.3
bcrypt==3.2.0
beautifulsoup4==4.9.3
blis==0.7.4
bokeh==2.2.0.dev4
boto3==1.16.57
botocore==1.19.57
Bottleneck==1.3.2
catalogue==1.0.0
catboost==0.24.4
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
click==8.0.0a1
cloudpickle==1.6.0
ConfigSpace==0.4.16
contextvars==2.4
cryptography==3.3.1
cycler==0.10.0
cymem==2.0.5
Cython==3.0a6
d8==0.0.2
dask==2021.1.0
decorator==4.4.2
decord==0.4.2
dill==0.3.3
distributed==2021.1.0
fastai==1.0.61
fastprogress==1.0.0
flake8==3.8.4
future==0.18.2
gluoncv==0.10.0b20210120
graphviz==0.8.4
HeapDict==1.0.1
idna==2.10
immutables==0.14
importlib-metadata==3.4.0
iniconfig==1.1.1
Jinja2==3.0.0a1
jmespath==0.10.0
joblib==1.0.0
kaggle==1.5.10
kiwisolver==1.3.1
liac-arff==2.5.0
lightgbm==3.1.1
MarkupSafe==2.0.0a1
matplotlib==3.3.3
mccabe==0.6.1
msgpack==1.0.2
murmurhash==1.0.5
mxnet-cu100==1.7.0
networkx==2.5
numexpr==2.7.2
numpy==1.19.5
nvidia-ml-py3==7.352.0
opencv-python==4.5.1.48
openml==0.11.0
packaging==20.8
pandas==1.2.1
paramiko==2.7.2
Pillow==6.2.1
plac==1.1.3
plotly==4.14.3
pluggy==1.0.0.dev0
portalocker==2.0.0
preshed==3.0.5
protobuf==3.14.0
psutil==5.7.0
py==1.10.0
pyaml==20.4.0
pyarrow==1.0.0
pycodestyle==2.6.0
pycparser==2.20
pyflakes==2.2.0
PyNaCl==1.4.0
pyparsing==3.0.0b2
pytest==6.2.1
python-dateutil==2.8.1
python-slugify==4.0.1
pytz==2020.5
PyYAML==5.4
regex==2020.11.13
requests==2.25.1
retrying==1.3.3
s3transfer==0.3.4
sacrebleu==1.4.14
sacremoses==0.0.43
scikit-learn==0.23.2
scikit-optimize==0.8.1
scipy==1.4.1
sentencepiece==0.1.95
six==1.15.0
sortedcontainers==2.3.0
soupsieve==2.1
spacy==2.3.5
srsly==1.0.5
tblib==1.7.0
tensorboardX==2.1
text-unidecode==1.3
thinc==7.4.5
threadpoolctl==2.1.0
tokenizers==0.9.4
toml==0.10.2
toolz==0.11.1
torch==1.7.1
torchvision==0.8.2
tornado==6.1
tqdm==4.56.0
typing-extensions==3.7.4.3
urllib3==1.26.2
wasabi==0.8.0
xgboost==1.2.1
xmltodict==0.12.0
yacs==0.1.8
zict==2.0.0
zipp==3.4.0
```

**Comment by dai-ichiro** [comment]
I got the same error.
I solved it by changing python version from 3.7 to 3.6.

Hope this helps.

**Comment by briandesilva** [comment]
Switching to Python 3.6 worked for me too.

```python
conda create -n autogluon-dev python=3.6
conda activate autogluon-dev
python3 -m pip install --upgrade "mxnet_cu100<2.0.0"
python3 -m pip install --pre autogluon
```

**Comment by briandesilva** [comment]
Minor issue: the nightly build [documentation](https://auto.gluon.ai/dev/api/autogluon.task.html?highlight=auto_ml_pipeline) shows `AutoMLPipelineFeatureGenerator` residing at `autogluon.utils.tabular.features.generators.auto_ml_pipeline.AutoMLPipelineFeatureGenerator`, but it appears to now be at `autogluon.tabular.features.generators.auto_ml_pipeline.AutoMLPipelineFeatureGenerator`.

**Comment by Innixma** [comment]
> I got the same error.
> I solved it by changing python version from 3.7 to 3.6.
> 
> Hope this helps.

Were you also using cuda? I suspect this might be related to cuda versions, and `cu100` is fairly old.

**Comment by dai-ichiro** [comment]
> Were you also using cuda? I suspect this might be related to cuda versions, and cu100 is fairly old.

Yes, I'm using cuda toolkit 10.2.

**Comment by Innixma** [comment]
Just a guess, but it might be related to the use of Amazon Linux, since all our tests are on Ubuntu, and therefore we haven't tested Amazon Linux. I'll plan to have someone look into this prior to our next release. If anyone is able to figure out the cause or has additional info, please feel free to share it here.

**Comment by dai-ichiro** [comment]
My environment was:
```
Ubuntu 18.04 LTS
NVIDIA GTX 1080
CUDA toolkit 10.2
python 3.7.5
```
I got this error.

**Comment by sflender** [comment]
I also encountered Segmentation fault: 11 once when running .fit() with AG Text on a p3dn.24xlarge with Ubuntu. Rebooting the instance solved the problem for me - might be an issue with the instance itself.

**Comment by Innixma** [comment]
I expect some of the issue is related to ConfigSpace, which we have recently stabilized in pre-release. I am marking this resolved for now, but please re-open if issues persist in latest pre-release and v0.1+
