### ISSUE TITLE
how to change anchor box  size in autogluon object detection

### ISSUE THREAD

**Issue by RuojiWang** [awslabs/autogluon#884]
i am using object detection of autogluon for my own custom data(to find coins in picutres), the detector can show me the target through the anchor box, but i want to know how to change the size of anchor box, to make box fit the target.

**Comment by zhreshold** [comment]
Take ssd object detector as an example, you may plugin the anchor sizes and ratios such as:

```python
detector = ObjectDetector().fit(train, val, 
    hyperparameters={'estimator': 'ssd', 'transfer': None, 
    'ssd': {
        'sizes': (30, 60, 111, 162, 213, 264, 315), 
        'ratios': tuple([[1, 2, 0.5]] + [[1, 2, 0.5, 3, 1.0/3]] * 3 + [[1, 2, 0.5]] * 2)})
```

Note that if you change these settings, the custom model can no longer benefit from the pre-trained COCO models therefore the results may be worse than the default ones.
