### ISSUE TITLE
How to limit CPU usage?

### ISSUE THREAD

**Issue by EternalConfession** [awslabs/autogluon#904]
The **TabularPrediction.task.fit()** will occupy all the CPU cores, even though I set **nthread_per_trial = 1** and **"NUMEXPR_MAX_THREADS" = 8**. The CPU usage will rocket to ~9000%.

How can I limit the CPU usage.

**Comment by Innixma** [comment]
This is a good callout, as currently most models do not respect limiting the resources. I will plan to address this in the upcoming v0.1 release or as a follow-up, as we already have added limit control for GPUs.

**Comment by EternalConfession** [comment]
For those who meet the same issue, currently, I use **taskset** to limit the resources.

taskset -c 0-32 python xxx.py

**Comment by yinweisu** [comment]
Hi,

You can do something like this:
`predictor = TabularPredictor(...).fit(..., ag_fit_args={'num_cpus': NUM_CORES_YOU_WANT})`

This is also added to our doc's FAQ section with https://github.com/awslabs/autogluon/pull/1482
