### ISSUE TITLE
Customize learning_rate in autogluon classification .fit()

### ISSUE THREAD

**Issue by mhup115** [awslabs/autogluon#916]
I'm a student working on an autogluon project and can't get the learning rate modified. I have an oscillating HPO chart and figured that was a good place to start. 

![sagemaker v2 train](https://user-images.githubusercontent.com/78876421/107563036-701a4100-6b95-11eb-8379-d04c6c06bf88.png)

Here's my code:

```
import autogluon.core as ag
from autogluon import ImageClassification as task
from mxnet import optimizer as optim

dataset = task.Dataset('data/train')

@ag.obj(
        learning_rate=ag.space.Real(0.1111, 0.22222),
        momentum=ag.space.Real(0.86, 0.99),
        wd=ag.space.Real(1e-5, 1e-3, log=True)
        )        
class NAG(optim.NAG):
    pass
optimizer = NAG()

time_limit = 10*60
num_epochs = 30

classifier = task.fit(dataset, optimizer=optimizer, time_limits=time_limit, epochs=num_epochs, verbose=4)
```

**Comment by mhup115** [comment]
The random learning rate values were from my debugging, should have mentioned that I originally used the code as its given in the documentation: learning_rate=ag.space.Real(1e-4, 1e-2, log=True)

**Comment by Innixma** [comment]
Could you provide logs? It is very hard to debug without logs.

Additionally, could you try pre-release? v0.0.15 is 5 months old now, and we have overhauled ImageClassification.

Pre-release installation instructions and documentation:

https://auto.gluon.ai/dev/install.html
https://auto.gluon.ai/dev/tutorials/image_prediction/beginner.html#sec-imgquick

**Comment by mhup115** [comment]
Sorry, here are the logs. I'll try downloading the pre-release next.
--
scheduler_options: Key 'training_history_callback_delta_secs': Imputing default value 60
scheduler_options: Key 'delay_get_config': Imputing default value True

Starting Experiments
Num of Finished Tasks is 0
Time out (secs) is 600

scheduler: FIFOScheduler(
DistributedResourceManager{
(Remote: Remote REMOTE_ID: 0, 
	<Remote: 'inproc://172.16.22.158/9036/1' processes=1 threads=16, memory=66.01 GB>, Resource: NodeResourceManager(16 CPUs, 0 GPUs))
})

/home/ec2-user/anaconda3/envs/mxnet_latest_p37/lib/python3.7/site-packages/mxnet/gluon/data/vision/datasets.py:318: UserWarning: Ignoring data/train/s/.ipynb_checkpoints of type . Only support .jpg, .jpeg, .png
  filename, ext, ', '.join(self._exts)))
/home/ec2-user/anaconda3/envs/mxnet_latest_p37/lib/python3.7/site-packages/mxnet/gluon/data/vision/datasets.py:318: UserWarning: Ignoring data/train/s_f/.ipynb_checkpoints of type . Only support .jpg, .jpeg, .png
  filename, ext, ', '.join(self._exts)))
{'dataset': <autogluon.task.image_classification.dataset.NativeImageFolderDataset object at 0x7fc38a411850>, 'net': 'ResNet50_v1b', 'optimizer': <__main__.NAG object at 0x7fc35c3a91d0>, 'loss': SoftmaxCrossEntropyLoss(batch_axis=0, w=None), 'metric': 'accuracy', 'num_gpus': 0, 'split_ratio': 0.8, 'batch_size': 64, 'input_size': 224, 'epochs': 30, 'final_fit_epochs': 30, 'verbose': 4, 'num_workers': 16, 'hybridize': True, 'final_fit': False, 'tricks': Dict{'last_gamma': False, 'use_pretrained': True, 'use_se': False, 'mixup': False, 'mixup_alpha': 0.2, 'mixup_off_epoch': 0, 'label_smoothing': False, 'no_wd': False, 'teacher_name': None, 'temperature': 20.0, 'hard_weight': 0.5, 'batch_norm': False, 'use_gn': False}, 'lr_config': Dict{'lr_mode': 'cosine', 'lr_decay': 0.1, 'lr_decay_period': 0, 'lr_decay_epoch': '40,80', 'warmup_lr': 0.0, 'warmup_epochs': 0}, 'task_id': 2}

**Comment by mhup115** [comment]
I just tried updating to the pre-release, it says i'm running the latest version and to restart the kernel.

When following these [docs](https://auto.gluon.ai/stable/tutorials/image_classification/hpo.html) on customizing the search space, the logs produced don't reflect any of these changes. Pretty stumped unfortunately

**Comment by Innixma** [comment]
You probably aren't using the pre-release then. I'd recommend creating a fresh venv without autogluon installed, and then following thee pre-release install instructions.

**Comment by mhup115** [comment]
Thanks, that eventually got it resolved. However now I'm hitting a another wall with the fit function returning -1 values for train_acc and valid_acc:

`
import autogluon.core as ag
from autogluon.vision import ImagePredictor
train_dataset, _, test_dataset = ImagePredictor.Dataset.from_folders("data")
predictor = ImagePredictor()
predictor.fit(train_dataset)`


> WARNING:gluoncv.auto.tasks.image_classification:The number of requested GPUs is greater than the number of available GPUs.Reduce the number to 4
INFO:gluoncv.auto.tasks.image_classification:Randomly split train_data into train[201]/validation[29] splits.
INFO:gluoncv.auto.tasks.image_classification:Starting fit without HPO
INFO:ImageClassificationEstimator:modified configs: {
INFO:ImageClassificationEstimator:root.valid.batch_size 128 != 16
INFO:ImageClassificationEstimator:root.valid.num_workers 4 != 32
INFO:ImageClassificationEstimator:root.img_cls.model   resnet50_v1 != resnet50_v1b
INFO:ImageClassificationEstimator:root.gpus            (0,) != (0, 1, 2, 3)
INFO:ImageClassificationEstimator:root.train.rec_train ~/.mxnet/datasets/imagenet/rec/train.rec != auto
INFO:ImageClassificationEstimator:root.train.rec_train_idx ~/.mxnet/datasets/imagenet/rec/train.idx != auto
INFO:ImageClassificationEstimator:root.train.num_training_samples 1281167 != -1
INFO:ImageClassificationEstimator:root.train.epochs    10 != 15
INFO:ImageClassificationEstimator:root.train.data_dir  ~/.mxnet/datasets/imagenet != auto
INFO:ImageClassificationEstimator:root.train.lr        0.1 != 0.01
INFO:ImageClassificationEstimator:root.train.rec_val   ~/.mxnet/datasets/imagenet/rec/val.rec != auto
INFO:ImageClassificationEstimator:root.train.num_workers 4 != 32
INFO:ImageClassificationEstimator:root.train.batch_size 128 != 16
INFO:ImageClassificationEstimator:root.train.rec_val_idx ~/.mxnet/datasets/imagenet/rec/val.idx != auto
INFO:ImageClassificationEstimator:}
INFO:ImageClassificationEstimator:Saved config to /home/ec2-user/SageMaker/imageclassificationestimator-02-12-2021/config.yaml
INFO:gluoncv.auto.tasks.image_classification:>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> finish model fitting
INFO:gluoncv.auto.tasks.image_classification:total runtime is 0.27 s
INFO:gluoncv.auto.tasks.image_classification:{ 'best_config': { 'batch_size': 16,
                   'dist_ip_addrs': None,
                   'epochs': 15,
                   'estimator': <class 'gluoncv.auto.estimators.image_classification.image_classification.ImageClassificationEstimator'>,
                   'gpus': [0, 1, 2, 3],
                   'log_dir': '/home/ec2-user/SageMaker',
                   'lr': 0.01,
                   'model': 'resnet50_v1b',
                   'ngpus_per_trial': 8,
                   'nthreads_per_trial': 128,
                   'num_trials': 1,
                   'num_workers': 32,
                   'search_strategy': 'random',
                   'seed': 597,
                   'time_limits': 2147483647},
  'total_time': 0.26659536361694336,
  'train_acc': -1,
  'valid_acc': -1}



> RuntimeError                              Traceback (most recent call last)
> <ipython-input-10-e676d1ef4e8f> in <module>
>      11 
>      12 
> ---> 13 predictor.fit(train_dataset)
>      14 
>      15 
> 
> ~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/autogluon/vision/configs/presets_configs.py in _call(*args, **kwargs)
>      11         def _call(*args, **kwargs):
>      12             gargs, gkwargs = set_presets(preset_name, *args, **kwargs)
> ---> 13             return f(*gargs, **gkwargs)
>      14         return _call
>      15     return _unpack_inner
> 
> ~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/autogluon/vision/predictor/predictor.py in fit(self, train_data, tuning_data, time_limit, presets, hyperparameters, **kwargs)
>     313         with warnings.catch_warnings(record=True) as w:
>     314             warnings.simplefilter("always")
> --> 315             self._classifier = task.fit(train_data, tuning_data, 1 - holdout_frac, random_state)
>     316         self._classifier._logger.setLevel(log_level)
>     317         self._classifier._logger.propagate = True
> 
> ~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/auto/tasks/image_classification.py in fit(self, train_data, val_data, train_size, random_state)
>     306         model_checkpoint = results.get('model_checkpoint', None)
>     307         if model_checkpoint is None:
> --> 308             raise RuntimeError(f'Unexpected error happened during fit: {pprint.pformat(results, indent=2)}')
>     309         estimator = pickle.loads(results['model_checkpoint'])
>     310         return estimator
> 
> RuntimeError: Unexpected error happened during fit: { 'args': "{'img_cls': {'model': 'resnet50_v1b', 'use_pretrained': True, "
>           "'use_gn': False, 'batch_norm': False, 'use_se': False, "
>           "'last_gamma': False}, 'train': {'pretrained_base': True, "
>           "'batch_size': 16, 'epochs': 15, 'lr': 0.01, 'lr_decay': 0.1, "
>           "'lr_decay_period': 0, 'lr_decay_epoch': '40, 60', 'lr_mode': "
>           "'step', 'warmup_lr': 0.0, 'warmup_epochs': 0, "
>           "'num_training_samples': -1, 'num_workers': 32, 'wd': 0.0001, "
>           "'momentum': 0.9, 'teacher': None, 'hard_weight': 0.5, 'dtype': "
>           "'float32', 'input_size': 224, 'crop_ratio': 0.875, 'use_rec': "
>           "False, 'rec_train': 'auto', 'rec_train_idx': 'auto', 'rec_val': "
>           "'auto', 'rec_val_idx': 'auto', 'data_dir': 'auto', 'mixup': False, "
>           "'no_wd': False, 'label_smoothing': False, 'temperature': 20, "
>           "'resume_epoch': 0, 'mixup_alpha': 0.2, 'mixup_off_epoch': 0, "
>           "'log_interval': 50, 'mode': '', 'start_epoch': 0, "
>           "'transfer_lr_mult': 0.01, 'output_lr_mult': 0.1}, 'valid': "
>           "{'batch_size': 16, 'num_workers': 32}, 'gpus': [0, 1, 2, 3]}",
>   'time': 0.26659536361694336,
>   'traceback': 'Traceback (most recent call last):\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/auto/tasks/image_classification.py", '
>                'line 89, in _train_image_classification\n'
>                '    result = estimator.fit(train_data=train_data, '
>                'val_data=val_data)\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/auto/estimators/base_estimator.py", '
>                'line 140, in fit\n'
>                '    self._init_network()\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/auto/estimators/image_classification/image_classification.py", '
>                'line 262, in _init_network\n'
>                '    self.net = get_model(model_name, **kwargs)\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/model_zoo/model_zoo.py", '
>                'line 409, in get_model\n'
>                '    net = _models[name](**kwargs)\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/model_zoo/resnetv1b.py", '
>                'line 367, in resnet50_v1b\n'
>                '    tag=pretrained, root=root), ctx=ctx)\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/gluon/block.py", '
>                'line 556, in load_parameters\n'
>                '    params[name]._load_init(loaded[name], ctx, '
>                'cast_dtype=cast_dtype, dtype_source=dtype_source)\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/gluon/parameter.py", '
>                'line 316, in _load_init\n'
>                '    self._init_impl(data, ctx)\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/gluon/parameter.py", '
>                'line 365, in _init_impl\n'
>                '    self._data = [data.copyto(ctx) for ctx in self._ctx_list]\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/gluon/parameter.py", '
>                'line 365, in <listcomp>\n'
>                '    self._data = [data.copyto(ctx) for ctx in self._ctx_list]\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", '
>                'line 2666, in copyto\n'
>                '    return _internal._copyto(self, out=hret)\n'
>                '  File "<string>", line 27, in _copyto\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/_ctypes/ndarray.py", '
>                'line 91, in _imperative_invoke\n'
>                '    ctypes.byref(out_stypes)))\n'
>                '  File '
>                '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/base.py", '
>                'line 246, in check_call\n'
>                '    raise get_last_ffi_error()\n'
>                'mxnet.base.MXNetError: Traceback (most recent call last):\n'
>                '  File "src/ndarray/ndarray.cc", line 1298\n'
>                'MXNetError: GPU is not enabled\n',
>   'train_acc': -1,
>   'valid_acc': -1}

**Comment by mhup115** [comment]
Hi following up on this. If its relevant info, the graph output after the model training in the checkpoint folder is blank:
![ag](https://user-images.githubusercontent.com/78876421/107998592-52384c00-6f9a-11eb-91ff-20419512738e.png)
