### ISSUE TITLE
Image Classification error: returning -1 'train_acc' and 'valid_acc' values 

### ISSUE THREAD

**Issue by mhup115** [awslabs/autogluon#945]
The model completes the epochs, however when its finished training I get this error showing -1 values for training accuracy and validation accuracy. The HPO graph produced is blank.

CODE: 

`pip install --upgrade "mxnet<2.0.0"`
`pip install --pre autogluon`
`pip install autogluon.vision`
`pip install autogluon.core`
`import autogluon.core as ag`
`from autogluon.vision import ImagePredictor`
`train_dataset, _, test_dataset = ImagePredictor.Dataset.from_folders("data")`
`predictor = ImagePredictor()`
`predictor.fit(train_dataset)`

OUTPUT:

```

INFO:root:`time_limit=auto` set to `time_limit=7200`.
WARNING:gluoncv.auto.tasks.image_classification:The number of requested GPUs is greater than the number of available GPUs.Reduce the number to 4
INFO:gluoncv.auto.tasks.image_classification:Randomly split train_data into train[214]/validation[16] splits.
INFO:gluoncv.auto.tasks.image_classification:Starting fit without HPO
INFO:ImageClassificationEstimator:modified configs(<old> != <new>): {
INFO:ImageClassificationEstimator:root.valid.batch_size 128 != 16
INFO:ImageClassificationEstimator:root.valid.num_workers 4 != 32
INFO:ImageClassificationEstimator:root.img_cls.model   resnet50_v1 != resnet50_v1b
INFO:ImageClassificationEstimator:root.gpus            (0,) != (0, 1, 2, 3)
INFO:ImageClassificationEstimator:root.train.num_workers 4 != 32
INFO:ImageClassificationEstimator:root.train.lr        0.1 != 0.01
INFO:ImageClassificationEstimator:root.train.batch_size 128 != 16
INFO:ImageClassificationEstimator:root.train.epochs    10 != 15
INFO:ImageClassificationEstimator:root.train.rec_val   ~/.mxnet/datasets/imagenet/rec/val.rec != auto
INFO:ImageClassificationEstimator:root.train.data_dir  ~/.mxnet/datasets/imagenet != auto
INFO:ImageClassificationEstimator:root.train.rec_train ~/.mxnet/datasets/imagenet/rec/train.rec != auto
INFO:ImageClassificationEstimator:root.train.num_training_samples 1281167 != -1
INFO:ImageClassificationEstimator:root.train.rec_val_idx ~/.mxnet/datasets/imagenet/rec/val.idx != auto
INFO:ImageClassificationEstimator:root.train.rec_train_idx ~/.mxnet/datasets/imagenet/rec/train.idx != auto
INFO:ImageClassificationEstimator:}
INFO:ImageClassificationEstimator:Saved config to /home/ec2-user/SageMaker/010a04d9/.trial_0/config.yaml
INFO:gluoncv.auto.tasks.image_classification:Finished, total runtime is 0.26 s
INFO:gluoncv.auto.tasks.image_classification:{ 'best_config': { 'batch_size': 16,
                   'dist_ip_addrs': None,
                   'epochs': 15,
                   'estimator': <class 'gluoncv.auto.estimators.image_classification.image_classification.ImageClassificationEstimator'>,
                   'final_fit': False,
                   'gpus': [0, 1, 2, 3],
                   'log_dir': '/home/ec2-user/SageMaker/010a04d9',
                   'lr': 0.01,
                   'model': 'resnet50_v1b',
                   'ngpus_per_trial': 8,
                   'nthreads_per_trial': 128,
                   'num_trials': 1,
                   'num_workers': 32,
                   'search_strategy': 'random',
                   'seed': 101,
                   'time_limits': 7200,
                   'wall_clock_tick': 1613743719.5959685},
  'total_time': 0.25241589546203613,
  'train_acc': -1,
  'valid_acc': -1}

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-8-b3d3a1c497d1> in <module>
      6 
      7 
----> 8 predictor.fit(train_dataset)

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/autogluon/vision/configs/presets_configs.py in _call(*args, **kwargs)
     13         def _call(*args, **kwargs):
     14             gargs, gkwargs = set_presets(preset_name, *args, **kwargs)
---> 15             return f(*gargs, **gkwargs)
     16         return _call
     17     return _unpack_inner

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/autogluon/vision/predictor/predictor.py in fit(self, train_data, tuning_data, time_limit, presets, hyperparameters, **kwargs)
    315         with warnings.catch_warnings(record=True) as w:
    316             warnings.simplefilter("always")
--> 317             self._classifier = task.fit(train_data, tuning_data, 1 - holdout_frac, random_state)
    318         self._classifier._logger.setLevel(log_level)
    319         self._classifier._logger.propagate = True

~/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/auto/tasks/image_classification.py in fit(self, train_data, val_data, train_size, random_state, time_limit)
    380             if results.get('traceback', '') == 'timeout':
    381                 raise TimeoutError(f'Unable to fit a usable model given `time_limit={time_limit}`')
--> 382             raise RuntimeError(f'Unexpected error happened during fit: {pprint.pformat(results, indent=2)}')
    383         estimator = pickle.loads(results['model_checkpoint'])
    384         return estimator

RuntimeError: Unexpected error happened during fit: { 'args': "{'img_cls': {'model': 'resnet50_v1b', 'use_pretrained': True, "
          "'use_gn': False, 'batch_norm': False, 'use_se': False, "
          "'last_gamma': False}, 'train': {'pretrained_base': True, "
          "'batch_size': 16, 'epochs': 15, 'lr': 0.01, 'lr_decay': 0.1, "
          "'lr_decay_period': 0, 'lr_decay_epoch': '40, 60', 'lr_mode': "
          "'step', 'warmup_lr': 0.0, 'warmup_epochs': 0, "
          "'num_training_samples': -1, 'num_workers': 32, 'wd': 0.0001, "
          "'momentum': 0.9, 'teacher': None, 'hard_weight': 0.5, 'dtype': "
          "'float32', 'input_size': 224, 'crop_ratio': 0.875, 'use_rec': "
          "False, 'rec_train': 'auto', 'rec_train_idx': 'auto', 'rec_val': "
          "'auto', 'rec_val_idx': 'auto', 'data_dir': 'auto', 'mixup': False, "
          "'no_wd': False, 'label_smoothing': False, 'temperature': 20, "
          "'resume_epoch': 0, 'mixup_alpha': 0.2, 'mixup_off_epoch': 0, "
          "'log_interval': 50, 'mode': '', 'start_epoch': 0, "
          "'transfer_lr_mult': 0.01, 'output_lr_mult': 0.1}, 'valid': "
          "{'batch_size': 16, 'num_workers': 32}, 'gpus': [0, 1, 2, 3]}",
  'time': 0.25241589546203613,
  'traceback': 'Traceback (most recent call last):\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/auto/tasks/image_classification.py", '
               'line 134, in _train_image_classification\n'
               '    result = estimator.fit(train_data=train_data, '
               'val_data=val_data, time_limit=wall_clock_tick-tic)\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/auto/estimators/base_estimator.py", '
               'line 150, in fit\n'
               '    self._init_network()\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/auto/estimators/image_classification/image_classification.py", '
               'line 284, in _init_network\n'
               '    self.net = get_model(model_name, **kwargs)\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/model_zoo/model_zoo.py", '
               'line 409, in get_model\n'
               '    net = _models[name](**kwargs)\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/gluoncv/model_zoo/resnetv1b.py", '
               'line 367, in resnet50_v1b\n'
               '    tag=pretrained, root=root), ctx=ctx)\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/gluon/block.py", '
               'line 556, in load_parameters\n'
               '    params[name]._load_init(loaded[name], ctx, '
               'cast_dtype=cast_dtype, dtype_source=dtype_source)\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/gluon/parameter.py", '
               'line 316, in _load_init\n'
               '    self._init_impl(data, ctx)\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/gluon/parameter.py", '
               'line 365, in _init_impl\n'
               '    self._data = [data.copyto(ctx) for ctx in self._ctx_list]\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/gluon/parameter.py", '
               'line 365, in <listcomp>\n'
               '    self._data = [data.copyto(ctx) for ctx in self._ctx_list]\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", '
               'line 2666, in copyto\n'
               '    return _internal._copyto(self, out=hret)\n'
               '  File "<string>", line 27, in _copyto\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/_ctypes/ndarray.py", '
               'line 91, in _imperative_invoke\n'
               '    ctypes.byref(out_stypes)))\n'
               '  File '
               '"/home/ec2-user/anaconda3/envs/amazonei_tensorflow_p36/lib/python3.6/site-packages/mxnet/base.py", '
               'line 246, in check_call\n'
               '    raise get_last_ffi_error()\n'
               'mxnet.base.MXNetError: Traceback (most recent call last):\n'
               '  File "src/ndarray/ndarray.cc", line 1298\n'
               'MXNetError: GPU is not enabled\n',
  'train_acc': -1,
  'valid_acc': -1}

```

**Comment by Innixma** [comment]
Most import thing I notice, is that you aren't using GPU.

This is mentioned at the end of the logs: `'MXNetError: GPU is not enabled\n',`

```
python3 -m pip install --upgrade "mxnet<2.0.0"
python3 -m pip install --pre autogluon
```

Is not correct for GPU usage. Instead it should be:

```
# Here we assume CUDA 10.1 is installed.  You should change the number
# according to your own CUDA version (e.g. mxnet_cu100 for CUDA 10.0).
python3 -m pip install --upgrade "mxnet_cu101<2.0.0"
python3 -m pip install --pre autogluon
```

Refer to dev install instructions, CPU/GPU is part of the installation:
https://auto.gluon.ai/dev/install.html

@zhreshold Can we add an automatic exception raising when GPU MXNet is not installed (or a highly visible warning message)? This shouldn't be something that is easily missed by users.

**Comment by zhreshold** [comment]
@mhup115 I also noticed that you are running in tensorflow kernels, you may want to create a new conda environment or try the mxnet* kernels.

**Comment by zhreshold** [comment]
closed with #946

**Comment by talhaanwarch** [comment]
This error start rising again, if i restart colab notebook and run it again, each time I have to factory reset it
RuntimeError: Unexpected error happened during fit: { 'args': "{'img_cls': {'model': 'resnet50_v1b', 'use_pretrained': True, "
          "'use_gn': False, 'batch_norm': False, 'use_se': False, "
          "'last_gamma': False}, 'train': {'pretrained_base': True, "
          "'batch_size': 16, 'epochs': 15, 'lr': 0.01, 'lr_decay': 0.1, "
          "'lr_decay_period': 0, 'lr_decay_epoch': '40, 60', 'lr_mode': "
          "'step', 'warmup_lr': 0.0, 'warmup_epochs': 0, "
          "'num_training_samples': -1, 'num_workers': 2, 'wd': 0.0001, "
          "'momentum': 0.9, 'teacher': None, 'hard_weight': 0.5, 'dtype': "
          "'float32', 'input_size': 224, 'crop_ratio': 0.875, 'use_rec': "
          "False, 'rec_train': 'auto', 'rec_train_idx': 'auto', 'rec_val': "
          "'auto', 'rec_val_idx': 'auto', 'data_dir': 'auto', 'mixup': False, "
          "'no_wd': False, 'label_smoothing': False, 'temperature': 20, "
          "'resume_epoch': 0, 'mixup_alpha': 0.2, 'mixup_off_epoch': 0, "
          "'log_interval': 50, 'mode': '', 'start_epoch': 0, "
          "'transfer_lr_mult': 0.01, 'output_lr_mult': 0.1, "
          "'early_stop_patience': 10, 'early_stop_min_delta': 0.001, "
          "'early_stop_baseline': -inf, 'early_stop_max_value': inf}, 'valid': "
          "{'batch_size': 16, 'num_workers': 2}, 'gpus': [0]}",
  'time': 7.050602436065674,
  'traceback': 'multiprocessing.pool.RemoteTraceback: \n'
               '"""\n'
               'Traceback (most recent call last):\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", '
               'line 2898, in get_loc\n'
               '    return self._engine.get_loc(casted_key)\n'
               '  File "pandas/_libs/index.pyx", line 70, in '
               'pandas._libs.index.IndexEngine.get_loc\n'
               '  File "pandas/_libs/index.pyx", line 101, in '
               'pandas._libs.index.IndexEngine.get_loc\n'
               '  File "pandas/_libs/hashtable_class_helper.pxi", line 1032, '
               'in pandas._libs.hashtable.Int64HashTable.get_item\n'
               '  File "pandas/_libs/hashtable_class_helper.pxi", line 1039, '
               'in pandas._libs.hashtable.Int64HashTable.get_item\n'
               'KeyError: 541\n'
               '\n'
               'The above exception was the direct cause of the following '
               'exception:\n'
               '\n'
               'Traceback (most recent call last):\n'
               '  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, '
               'in worker\n'
               '    result = (True, func(*args, **kwds))\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataloader.py", '
               'line 429, in _worker_fn\n'
               '    batch = batchify_fn([_worker_dataset[i] for i in '
               'samples])\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataloader.py", '
               'line 429, in <listcomp>\n'
               '    batch = batchify_fn([_worker_dataset[i] for i in '
               'samples])\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataset.py", '
               'line 217, in __getitem__\n'
               '    item = self._data[idx]\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/gluoncv/auto/data/dataset.py", '
               'line 372, in __getitem__\n'
               "    im_path = self._dataset['image'][idx]\n"
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", '
               'line 882, in __getitem__\n'
               '    return self._get_value(key)\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", '
               'line 990, in _get_value\n'
               '    loc = self.index.get_loc(label)\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", '
               'line 2900, in get_loc\n'
               '    raise KeyError(key) from err\n'
               'KeyError: 541\n'
               '"""\n'
               '\n'
               'The above exception was the direct cause of the following '
               'exception:\n'
               '\n'
               'Traceback (most recent call last):\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/gluoncv/auto/tasks/image_classification.py", '
               'line 138, in _train_image_classification\n'
               '    result = estimator.fit(train_data=train_data, '
               'val_data=val_data, time_limit=wall_clock_tick-tic)\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/gluoncv/auto/estimators/base_estimator.py", '
               'line 175, in fit\n'
               '    ret = self._fit(train_data, val_data, '
               'time_limit=time_limit) if not resume else \\\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/gluoncv/auto/estimators/image_classification/image_classification.py", '
               'line 81, in _fit\n'
               '    return self._resume_fit(train_data, val_data, '
               'time_limit=time_limit)\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/gluoncv/auto/estimators/image_classification/image_classification.py", '
               'line 110, in _resume_fit\n'
               '    return self._train_loop(train_loader, val_loader, '
               'time_limit=time_limit)\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/gluoncv/auto/estimators/image_classification/image_classification.py", '
               'line 163, in _train_loop\n'
               '    for i, batch in enumerate(train_data):\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataloader.py", '
               'line 484, in __next__\n'
               '    batch = pickle.loads(ret.get(self._timeout))\n'
               '  File "/usr/lib/python3.7/multiprocessing/pool.py", line 657, '
               'in get\n'
               '    raise self._value\n'
               '  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, '
               'in worker\n'
               '    result = (True, func(*args, **kwds))\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataloader.py", '
               'line 429, in _worker_fn\n'
               '    batch = batchify_fn([_worker_dataset[i] for i in '
               'samples])\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataloader.py", '
               'line 429, in <listcomp>\n'
               '    batch = batchify_fn([_worker_dataset[i] for i in '
               'samples])\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/mxnet/gluon/data/dataset.py", '
               'line 217, in __getitem__\n'
               '    item = self._data[idx]\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/gluoncv/auto/data/dataset.py", '
               'line 372, in __getitem__\n'
               "    im_path = self._dataset['image'][idx]\n"
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", '
               'line 882, in __getitem__\n'
               '    return self._get_value(key)\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", '
               'line 990, in _get_value\n'
               '    loc = self.index.get_loc(label)\n'
               '  File '
               '"/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", '
               'line 2900, in get_loc\n'
               '    raise KeyError(key) from err\n'
               'KeyError: 541\n',
  'train_acc': -1,
  'valid_acc': -1}

**Comment by talhaanwarch** [comment]
@Innixma  this issue arises when I split data after shuffling using some external library or using even .iloc function and feed it to the predictor without resetting the index.
