### ISSUE TITLE
Align predict_proba argument defaults across Tabular and Text

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#976]
Align `predict_proba` argument defaults across Tabular and Text for binary classification.

Option 1: `as_multiclass=False`:
- Return the positive_class pred_proba as a single column (pandas Series).
- User refers to `predictor.positive_class` to identify which class the probabilities belong to.
- This is what TabularPredictor/TabularPrediction has traditionally done.

Option 2: `as_multiclass=True`:
- Return both negative and positive class pred_probas as 2 columns (pandas DataFrame).
- User can refer to pandas DataFrame column names to identify which class the probabilities belong to.

Some info:
- LightGBM uses Option 1
- sklearn uses Option 2
- XGBoost uses Option 2
- CatBoost uses Option 2

**Comment by Innixma** [comment]
@jwmueller @gradientsky @sxjscience Please feel free to weigh in.

**Comment by Innixma** [comment]
It should be noted that this will be something we cannot change after v0.1 release, as it is heavily API breaking.

**Comment by sxjscience** [comment]
I will vote for option 2. Option 1 will make the return type and shape  be inconsistent. It can be either pandas.Series or pandas.DataFrame for option 1. In addition, it will also be difficult for users to process the data output by predict_proba because they will need to check whether they are dealing with a binary classification problem or multiclass classification problem.

**Comment by jwmueller** [comment]
I agree option 2 is a bit more unified, and currently option 1 is not as user-friendly since it was less clear which class the probabilities were for. My only concern is changing Tabular to option 2 might introduce many bugs and take some time?

**Comment by Innixma** [comment]
#979 has been merged and implements Option 2. Thanks for the feedback, I agree that it is the most user-friendly and least confusing option.
