### ISSUE TITLE
RF/XT lower priority for regression problems.

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#987]
RF/XT can be slow in regression due to performing many splits, consider lowering model priority.

**Comment by sxjscience** [comment]
In fact, should we consider to remove RF/XT given that we have already had three other tree models? (LightGBM, CatBoost, XGBoost).

**Comment by sxjscience** [comment]
Also, may be we can consider to only keep one between FastAI model v.s. MXNet-based NN.

**Comment by Innixma** [comment]
Priority for RF/XT has been lowered since v0.2
