### ISSUE TITLE
Fix TextPredictorModel during refit_full

### ISSUE THREAD

**Issue by Innixma** [awslabs/autogluon#991]
Calling refit_full on a TextPredictorModel can take overly long since it doesn't use the epochs trained by the original model. This should be fixed for users to use good and high quality presets for faster inference compared to best_quality.

**Comment by sxjscience** [comment]
In fact, I added one test case in https://github.com/awslabs/autogluon/blob/7af68d6d80ff7dfe6e03f9555e85491cdfde9c7a/tabular/tests/unittests/models/test_text_prediction_v1_model.py#L8-L10. May need to investigate what causes the failure.

**Comment by Innixma** [comment]
I looked into code user mentioned failure in, error was actually caused by #994, so the issue isn't TextPredictor. Still, it will be good eventually to handle refit_full correctly to respect time_limit and ensure refit_full version isn't significantly different from non-refit_full version in terms of accuracy.
